unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Used for debugging, logging exceptions, errors &amp; API requests/response.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Stores the class name</description>
    <label>Class Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Stores the log level</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>FATAL</fullName>
                <label>EXCEPTION</label>
            </value>
            <value>
                <fullName>INFO</fullName>
                <label>API INFO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Log_Date__c.field-meta.xml
<CustomField>
    <fullName>Log_Date__c</fullName>
    <description>The date when the entry was logged.</description>
    <label>Log Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Stores the exception message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Stores the method name</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Stores the exception type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System.DmlException</fullName>
            </value>
            <value>
                <fullName>System.QueryException</fullName>
            </value>
            <value>
                <fullName>System.NullPointerException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LogSelectorTest.cls
/*
* @Author: Apoorv (NeuraFlash)
* @CreatedDate: June'01, 2020
*/
@isTest(isParallel=false)
private class LogSelectorTest {

    private enum LogLevel {FATAL, ERROR, INFO, DEBUG}

    @testSetup
    static void testDataSteup(){
        List<Log__c> logList  = new List<Log__c>();
        for(Integer i=0; i<150; i++){
            Log__c newLog = new Log__c();
            newLog.Level__c = String.valueof(LogLevel.FATAL);
            newLog.Log_Date__c = System.now();
            newLog.Type__c = 'System.NullPointerException';
            newLog.Message__c = 'null input to JSON parser';
            newLog.Class_Name__c = 'TestClassName';
            newLog.Method_Name__c = 'testMethod';
            logList.add(newLog);
        }
        insert logList;
    }

    @IsTest
    static void testGetLogs(){
        String queryfilters = '{"loglevel":"Fatal","fromlogDate":"'+System.now()+'","tologDate":"'+System.now()+'","classname":"TestClassName","type":"System.NullPointerException"}';
        Test.startTest();
            LogSelector.DataTableResponse dtResponse = LogSelector.getLogs(queryfilters, null);
        Test.stopTest();
        System.assertEquals(true, dtResponse.dataTableRecords.size()>0,'FATAL');
    }

    @IsTest
    static void testLogArchivalBatch(){
        String cronExpression = '0 0 0 06 12 ? *';
        Test.startTest();
            System.schedule('ScheduledApexTest', cronExpression, new LogArchivalBatchScheduler());
        Test.stopTest();
        System.assertEquals(true, [SELECT Id FROM Log__c].size()>0, 'FATAL');
    }
}