unpackaged/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Used for debugging, logging exceptions, errors &amp; API requests/response.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event to create Log records.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Log_Setting__mdt/Log_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used for configuring log settings.</description>
    <label>Log Setting</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Log_Setting__mdt/fields/Logging_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Logging_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls creation of log records. Creates log records if set true.</description>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/LogPublisher.cls
/*
* @Author: Apoorv (NeuraFlash)
* @CreatedDate: May'10, 2020
* @Description: Publishes the Log_Event__e platform events, which further creates 
*               Log__c record in the system.
* @TestClass: LoggerTest
*/ 

public with sharing class LogPublisher {

    public static void publishLogs(List<Log_Event__e> logEventList){
        try{
            Log_Setting__mdt logSetting = [SELECT Logging_Enabled__c	 
                                                FROM Log_Setting__mdt 
                                                    WHERE DeveloperName = 'Log_Setting'];
                                                    
            if(logSetting != null && logSetting.Logging_Enabled__c){
                List<Database.SaveResult> results = EventBus.publish(logEventList);
                for (Database.SaveResult sr : results) {
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug(LoggingLevel.ERROR, 'LogPublisher > publishLog: '+err.getMessage());
                        }
                    }       
                }
            }
         } catch(Exception ex){
            System.debug(LoggingLevel.ERROR, 'LogPublisher > publishLog: '+ex.getMessage());
        }
    }    
}