unpackaged/main/default/objects/CallDetail__c/CallDetail__c.object-meta.xml
<CustomObject>
    <label>CallDetail</label>
    <nameField>
        <label>CallDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CallDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CallDetail__c/fields/CallDirection__c.field-meta.xml
<CustomField>
    <fullName>CallDirection__c</fullName>
    <description>CallDirection</description>
    <label>CallDirection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CallDetail__c/fields/CallDurationInSeconds__c.field-meta.xml
<CustomField>
    <fullName>CallDurationInSeconds__c</fullName>
    <description>CallDurationInSeconds</description>
    <label>CallDurationInSeconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CallDetail__c/fields/CallEndTime__c.field-meta.xml
<CustomField>
    <fullName>CallEndTime__c</fullName>
    <description>CallEndTime</description>
    <label>CallEndTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CallDetail__c/fields/CallStartTime__c.field-meta.xml
<CustomField>
    <fullName>CallStartTime__c</fullName>
    <description>CallStartTime</description>
    <label>CallStartTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/CallDetail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>CallDetails</relationshipLabel>
    <relationshipName>CallDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/CallDetail__c/fields/NumberDialed__c.field-meta.xml
<CustomField>
    <fullName>NumberDialed__c</fullName>
    <description>Number dialed</description>
    <label>NumberDialed</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CallDirection__c.field-meta.xml
<CustomField>
    <fullName>CallDirection__c</fullName>
    <description>Call Direction</description>
    <label>CallDirection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CallDurationInSeconds__c.field-meta.xml
<CustomField>
    <fullName>CallDurationInSeconds__c</fullName>
    <description>Call duration in seconds</description>
    <label>CallDurationInSeconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CallEndTime__c.field-meta.xml
<CustomField>
    <fullName>CallEndTime__c</fullName>
    <label>CallEndTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CallStartTime__c.field-meta.xml
<CustomField>
    <fullName>CallStartTime__c</fullName>
    <description>Call start time</description>
    <label>CallStartTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CalvinKlein.us</fullName>
                <label>Online - CalvinKlein.com</label>
            </value>
            <value>
                <fullName>Calvin Klein Retail</fullName>
                <label>Calvin Klein Store</label>
            </value>
            <value>
                <fullName>Tommy.com</fullName>
                <label>Online - Tommy.com</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger Retail</fullName>
                <label>Tommy Hilfiger Store</label>
            </value>
            <value>
                <fullName>SpeedoUSA.com</fullName>
                <label>Online - speedo.com</label>
            </value>
            <value>
                <fullName>VanHeusen.com</fullName>
                <label>Online - vanheusen.com</label>
            </value>
            <value>
                <fullName>Izod.com</fullName>
                <label>Online - Izod.com</label>
            </value>
            <value>
                <fullName>styleBureau.com</fullName>
                <label>Online - styleBureau.com</label>
            </value>
            <value>
                <fullName>trueandco.com</fullName>
                <label>Online -True&amp;co.com</label>
            </value>
            <value>
                <fullName>CalvinKlein.ca</fullName>
                <label>Online-CalvinKlein Canada</label>
            </value>
            <value>
                <fullName>Speedo.com</fullName>
            </value>
            <value>
                <fullName>Warner.com</fullName>
                <label>Online-Warner&#39;s</label>
            </value>
            <value>
                <fullName>Van Heusen | IZOD Company Store</fullName>
            </value>
            <value>
                <fullName>Amazon.com</fullName>
            </value>
            <value>
                <fullName>Nordstrom</fullName>
            </value>
            <value>
                <fullName>Other Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Call Notes/Comments</description>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/NumberDialed__c.field-meta.xml
<CustomField>
    <fullName>NumberDialed__c</fullName>
    <description>Number Dialed</description>
    <label>NumberDialed</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SkillName__c.field-meta.xml
<CustomField>
    <fullName>SkillName__c</fullName>
    <label>SkillName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_CallDetailsTriggerHelper.cls
public class NF_CallDetailsTriggerHelper{
    public static void handleAfterInsert(List<CallDetail__c> newCallDetails){
        Log.push('CallDetailsTriggerHandler->entered clearCallDetailsOnCase method');
        List<Id> caseIds = new List<Id>();
        for (CallDetail__c callDetail : newCallDetails){
            caseIds.add(callDetail.case__c);//capture parent case id's
        }
        Log.push('Parent case ids found ' + caseIds);
        List<Case> parentCases = [select id, CallDirection__c, CallDurationInSeconds__c, CallEndTime__c, CallStartTime__c, Comments__c, SkillName__c, NumberDialed__c, Channel__c
                                  from Case
                                  where id in:caseIds];

        for (Case parentCase : parentCases){
             //clear call details
            parentCase.CallDirection__c = null;
            parentCase.CallDurationInSeconds__c = null;
            parentCase.CallEndTime__c = null;
            parentCase.CallStartTime__c = null;
            parentCase.Comments__c = null;
            parentCase.SkillName__c = null;
            parentCase.NumberDialed__c = null;
        }
        //update parent cases after call details cleared
        Logger.logDebug();
        update parentCases;
    }

}