unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/A1_TrackerAPI_tokens__mdt.object-meta.xml
<CustomObject>
    <description>To store the access tokens returned by Tracker API auth call, along with the access keys generated within SFSC</description>
    <label>A1 TrackerAPI tokens</label>
    <pluralLabel>A1 TrackerAPI tokens</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/access_key__c.field-meta.xml
<CustomField>
    <fullName>access_key__c</fullName>
    <label>access key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <label>access token</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>ApplicationID__c</fullName>
    <label>ApplicationID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/AppName__c.field-meta.xml
<CustomField>
    <fullName>AppName__c</fullName>
    <defaultValue>&quot;DWTracker&quot;</defaultValue>
    <label>AppName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/key_expires_at__c.field-meta.xml
<CustomField>
    <fullName>key_expires_at__c</fullName>
    <label>key expires at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/token_expires_at__c.field-meta.xml
<CustomField>
    <fullName>token_expires_at__c</fullName>
    <label>token expires at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/token_expires_in__c.field-meta.xml
<CustomField>
    <fullName>token_expires_in__c</fullName>
    <label>token expires in</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/A1_bcryptkey.cls
/******************************************************************************
 * Deployed only for testing to UAT
* @Description: API to POST the bCrypt Accesskey
* @Author	  : PVH
* @Date		  : 30:11.2022
******************************************************************************/ 
@RestResource(urlMapping='/get/AcquiaAccessKey')
global class A1_bcryptkey {
    
    global class ActiveBcrypt {
        public String brandId;
        public String applicationID;
        public String accesskey;
        public datetime keyExpireAt;
    }
    
    global class SubResponse {
        public String Code;
        public String Message;
        public List<ActiveBcrypt> ActiveBcrypt;
    }
    
    @httpGet
    global static void doFetch(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String, String> paramsMap = RestContext.request.params;
        String appName = paramsMap.get('appName');
        String applicationID = paramsMap.get('applicationID');
        String brandId = paramsMap.get('brandId');
        datetime currentDateTime= system.now();
        
        if (string.IsBlank(brandId) || string.IsBlank(appName)) {
            SubResponse objres=new SubResponse();
            res.statusCode = 400;            
            objres.code='INVALID_QUERY'; 
            objres.message='Missing required parameters BrandId or AppName';
            res.responseBody = Blob.valueOf(JSON.serialize(objres));
            return;
        }
       if(brandId=='1' || brandId=='2'){
            List<A1_TrackerAPI_tokens__mdt> Activebcryptkey = Database.query('Select BrandId__c,ApplicationID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,token_expires_at__c,token_expires_in__c from A1_TrackerAPI_tokens__mdt where BrandId__c=:brandId AND AppName__c=:appName');
           // List<A1_TrackerAPI_tokens__mdt> Activebcryptkey = Database.query('Select BrandId__c,TenantID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,Source_System__c,token_expires_at__c,token_expires_in__c	,TokenID__c from A1_TrackerAPI_tokens__mdt where BrandId__c=:brandId AND AppName__c=:appName AND key_expires_at__c>=:currentDateTime');
            SubResponse successres = new SubResponse();
            system.debug('Activebcryptkey>>>'+Activebcryptkey);
            if(!Activebcryptkey.isEmpty()){
                res.statusCode = 200;
                successres.message='Success';
                successres.code='Ok';
                successres.ActiveBcrypt=bCryptKeyResponse(Activebcryptkey);
                res.responseBody = Blob.valueOf(JSON.serialize(successres));
                return;
            }else{
                res.statusCode = 200;            
                successres.message='No Active bCryptKeys'; 
                res.responseBody = Blob.valueOf(JSON.serialize(successres));
                return;
            }             
       }else{
            SubResponse objres=new SubResponse();
            res.statusCode = 400;            
            objres.code='INVALID_BRANDID'; 
            objres.message='Invalid BrandId';
            res.responseBody = Blob.valueOf(JSON.serialize(objres));
            return;
        } 
    }
    //Wrapper class to collect bCrypt keys response
    public static List<ActiveBcrypt> bCryptKeyResponse(List<A1_TrackerAPI_tokens__mdt> lstBcryptKeys){
        List<ActiveBcrypt> lstActKeys=new List<ActiveBcrypt>();
        ActiveBcrypt objActKeys;
        for(A1_TrackerAPI_tokens__mdt objRew:lstBcryptKeys){
            objActKeys=new ActiveBcrypt();
            objActKeys.brandId=objRew.BrandId__c;
            objActKeys.applicationID=objRew.ApplicationID__c;
            objActKeys.accesskey=objRew.access_key__c;
            objActKeys.keyExpireAt=objRew.key_expires_at__c;
           
            lstActKeys.add(objActKeys);
            
        }
        return lstActKeys;
    }
    
}