unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/A1_TrackerAPI_tokens__mdt.object-meta.xml
<CustomObject>
    <description>To store the access tokens returned by Tracker API auth call, along with the access keys generated within SFSC</description>
    <label>A1 TrackerAPI tokens</label>
    <pluralLabel>A1 TrackerAPI tokens</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/access_key__c.field-meta.xml
<CustomField>
    <fullName>access_key__c</fullName>
    <label>access key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/access_token__c.field-meta.xml
<CustomField>
    <fullName>access_token__c</fullName>
    <label>access token</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/ApplicationID__c.field-meta.xml
<CustomField>
    <fullName>ApplicationID__c</fullName>
    <label>ApplicationID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/AppName__c.field-meta.xml
<CustomField>
    <fullName>AppName__c</fullName>
    <defaultValue>&quot;DWTracker&quot;</defaultValue>
    <label>AppName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/key_expires_at__c.field-meta.xml
<CustomField>
    <fullName>key_expires_at__c</fullName>
    <label>key expires at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/token_expires_at__c.field-meta.xml
<CustomField>
    <fullName>token_expires_at__c</fullName>
    <label>token expires at</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_tokens__mdt/fields/token_expires_in__c.field-meta.xml
<CustomField>
    <fullName>token_expires_in__c</fullName>
    <label>token expires in</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/A1_bcryptkeyTest.cls
/******************************************************************************
* @Description: Test class for A1_bcryptkey
* @Author	  : PVH
* @Date		  : 30:11.2022
******************************************************************************/ 
@isTest
public class A1_bcryptkeyTest {
    
  public static testmethod void testdoFetch(){
        test.startTest();
        string appName='DWTracker';
        string BrandId='1';
        List<A1_TrackerAPI_tokens__mdt> bcryptToken =[Select BrandId__c,ApplicationID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,token_expires_at__c,token_expires_in__c	from A1_TrackerAPI_tokens__mdt where BrandId__c='1' AND AppName__c='DWTracker'];
        RestResponse res = new RestResponse();
        string url='DWTracker';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('appName','DWTracker');
        RestContext.request.params.put('brandId', '1');
        RestContext.response= res;
        A1_bcryptkey.doFetch();
        test.stopTest();
    }
  
    public static testmethod void testdoFetch1(){
        test.startTest();
        string appName='DWTracker';
        string BrandId='2';
        List<A1_TrackerAPI_tokens__mdt> bcryptToken =[Select BrandId__c,ApplicationID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,token_expires_at__c,token_expires_in__c from A1_TrackerAPI_tokens__mdt where BrandId__c='1' AND AppName__c='DWTracker'];
        RestResponse res = new RestResponse();
        string url='DWTracker';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('appName','DWTracker');
        RestContext.request.params.put('brandId', '2');
        RestContext.response= res;
        A1_bcryptkey.doFetch();
        test.stopTest();
    }
     public static testmethod void testdoFetch2(){
        test.startTest();
        string appName='DWTracker';
        string BrandId='5';
        List<A1_TrackerAPI_tokens__mdt> bcryptToken =[Select BrandId__c,ApplicationID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,token_expires_at__c,token_expires_in__c from A1_TrackerAPI_tokens__mdt where BrandId__c='1' AND AppName__c='DWTracker'];
        RestResponse res = new RestResponse();
        string url='DWTracker';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('appName','DWTracker');
        RestContext.request.params.put('brandId', '5');
        RestContext.response= res;
        A1_bcryptkey.doFetch();
        test.stopTest();
    }
    public static testmethod void testdoFetch3(){
        test.startTest();
        string appName='DWTracker';
        string BrandId='5';
        List<A1_TrackerAPI_tokens__mdt> bcryptToken =[Select BrandId__c,ApplicationID__c,AppName__c,access_key__c,access_token__c,key_expires_at__c,token_expires_at__c,token_expires_in__c from A1_TrackerAPI_tokens__mdt where BrandId__c='1' AND AppName__c='DWTracker'];
        RestResponse res = new RestResponse();
        string url='DWTracker';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('appName','DWTracker');
        //RestContext.request.params.put('brandId', '5');
        RestContext.response= res;
        A1_bcryptkey.doFetch();
        test.stopTest();
    }
}