unpackaged/main/default/objects/Brand_Form_Picklist__mdt/Brand_Form_Picklist__mdt.object-meta.xml
<CustomObject>
    <description>This custom setting is used to store Picklist Values for fields corresponding to each brand. Also this contains Product Category and Sub Category for each Brand.</description>
    <label>Brand Form Picklist</label>
    <pluralLabel>Brand Form Picklists</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Form_Picklist__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Form_Picklist__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to match the Case Source Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Form_Picklist__mdt/fields/Picklist_Values_JSON__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values_JSON__c</fullName>
    <label>Picklist Values JSON</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CalvinKlein.us</fullName>
                <label>Online - CalvinKlein.com</label>
            </value>
            <value>
                <fullName>Calvin Klein Retail</fullName>
                <label>Calvin Klein Store</label>
            </value>
            <value>
                <fullName>Tommy.com</fullName>
                <label>Online - Tommy.com</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger Retail</fullName>
                <label>Tommy Hilfiger Store</label>
            </value>
            <value>
                <fullName>SpeedoUSA.com</fullName>
                <label>Online - speedo.com</label>
            </value>
            <value>
                <fullName>VanHeusen.com</fullName>
                <label>Online - vanheusen.com</label>
            </value>
            <value>
                <fullName>Izod.com</fullName>
                <label>Online - Izod.com</label>
            </value>
            <value>
                <fullName>styleBureau.com</fullName>
                <label>Online - styleBureau.com</label>
            </value>
            <value>
                <fullName>trueandco.com</fullName>
                <label>Online -True&amp;co.com</label>
            </value>
            <value>
                <fullName>CalvinKlein.ca</fullName>
                <label>Online-CalvinKlein Canada</label>
            </value>
            <value>
                <fullName>Speedo.com</fullName>
            </value>
            <value>
                <fullName>Warner.com</fullName>
                <label>Online-Warner&#39;s</label>
            </value>
            <value>
                <fullName>Van Heusen | IZOD Company Store</fullName>
            </value>
            <value>
                <fullName>Amazon.com</fullName>
            </value>
            <value>
                <fullName>Nordstrom</fullName>
            </value>
            <value>
                <fullName>Other Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Is_Existing_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Is_Existing_Purchase__c</fullName>
    <description>This field is created to keep information about the purchase is Existing or Not</description>
    <label>Is Existing Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bikinis &amp; Separates</fullName>
            </value>
            <value>
                <fullName>One Piece Swimsuits</fullName>
            </value>
            <value>
                <fullName>Rash Guards</fullName>
            </value>
            <value>
                <fullName>Swim Bottoms</fullName>
            </value>
            <value>
                <fullName>Tankinis</fullName>
            </value>
            <value>
                <fullName>Triathlon &amp; Wetsuits</fullName>
            </value>
            <value>
                <fullName>Elite Technical Swimsuits</fullName>
            </value>
            <value>
                <fullName>Parkas</fullName>
            </value>
            <value>
                <fullName>Racing &amp; Practice Swimsuits</fullName>
            </value>
            <value>
                <fullName>Team Apparel</fullName>
            </value>
            <value>
                <fullName>Jackets</fullName>
            </value>
            <value>
                <fullName>Joggers</fullName>
            </value>
            <value>
                <fullName>Pants &amp; Leggings</fullName>
            </value>
            <value>
                <fullName>Shorts</fullName>
            </value>
            <value>
                <fullName>Swim Tees</fullName>
            </value>
            <value>
                <fullName>Flip-flop</fullName>
            </value>
            <value>
                <fullName>Water Shoe</fullName>
            </value>
            <value>
                <fullName>Briefs</fullName>
            </value>
            <value>
                <fullName>Jammers</fullName>
            </value>
            <value>
                <fullName>Square Legs</fullName>
            </value>
            <value>
                <fullName>Swim Trunks &amp; Boardshorts</fullName>
            </value>
            <value>
                <fullName>Team Warmups</fullName>
            </value>
            <value>
                <fullName>Tops &amp; Tanks</fullName>
            </value>
            <value>
                <fullName>Begin To Swim</fullName>
            </value>
            <value>
                <fullName>One- Piece Suits</fullName>
            </value>
            <value>
                <fullName>Board shorts</fullName>
            </value>
            <value>
                <fullName>Volleys</fullName>
            </value>
            <value>
                <fullName>Adult Goggles</fullName>
            </value>
            <value>
                <fullName>Elite Goggles</fullName>
            </value>
            <value>
                <fullName>Jr. Goggles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_First_Name__c</fullName>
    <description>Supplied First Name</description>
    <label>Supplied First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tommy_Adaptive__c.field-meta.xml
<CustomField>
    <fullName>Tommy_Adaptive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tommy Adaptive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Success_Message_Setting__mdt/Success_Message_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to configure success message based on specific brand for Brand Forms.
Please provide the custom success message and put &lt;ticketid&gt; where ever you need to keep Ticket Number</description>
    <label>Success Message Setting</label>
    <pluralLabel>Success Message Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Success_Message_Setting__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <description>This field is used to store Name of Brand</description>
    <label>Brand Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Success_Message_Setting__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used to story Case Source Country</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Success_Message_Setting__mdt/fields/Success_Message_f__c.field-meta.xml
<CustomField>
    <fullName>Success_Message_f__c</fullName>
    <label>Success Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Success_Message_Setting__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to store type of form</description>
    <inlineHelpText>Represents either Privacy or Brand Form</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BrandFormApexController.cls
/**
 * @class:       BrandFormApexController
 * @JIRA:        NASSC-25, NASSC-354
 * @description: Controller Class to show picklist values from Custom Metadata to Brand Form and 
 *         create a case in Salesforce after form submission
 */
/**
* @author Magnet360
*
* @date 2019
*
* @description Brand form controller
*
*/
public without sharing class BrandFormApexController {

    /*******************************************************************************************************
    * @description Method to fetch below field Values from Case Custom Metadata - Brand Form Picklist, and show it to Brand Form
    * This method is called at Brand Form Initialization
    * @param brandName Brand name sent from Form
    * @param sourceCountry Either US or CA. Used only for CK Canada
    * @return InitialDataWrapper
    * @example
    */
    @AuraEnabled
    public static InitialDataWrapper getData(String brandName, String sourceCountry) {
        InitialDataWrapper wrapperObject = new InitialDataWrapper();
        Map<Decimal, List<String>> myMap = new Map<Decimal, List<String>>();
        Set<String> setQuestions = new Set<String>();
        //String newSearchText = '%'+brandName+'%';
        //String countrySearchText = '%'+sourceCountry+'%';
        //System.debug('We Got: Brand Name = '+brandName+' and Case Source Country = '+sourceCountry);
        List<Brand_Form_Picklist__mdt> listBrandData = [Select Id,Sequence__c,Brand_Name__c,Question__c,Picklist_Values_JSON__c from Brand_Form_Picklist__mdt where Brand_Name__c = :brandName AND Country__c = :sourceCountry order by Sequence__c ASC];
        System.debug('***Got ' + brandName + ' data = ' + listBrandData);

        for (Brand_Form_Picklist__mdt bData : listBrandData) {

            //System.debug('***Sequence = '+bData.Sequence__c);
            List<String> tempList = bData.Picklist_Values_JSON__c.Split(';');
            myMap.put(bData.Sequence__c.intValue(), tempList);

        }
        //System.debug('***We got Map = '+myMap);
        wrapperObject.listQue0 = myMap.get(0);
        wrapperObject.listQue1 = myMap.get(1);
        wrapperObject.listQue3 = myMap.get(3);
        wrapperObject.listQue4 = myMap.get(4);
        wrapperObject.userId = UserInfo.getUserId();


        //fetching the Success Message based on Brand
        List<Success_Message_Setting__mdt> getMessage = [Select Id,Success_Message_f__c from Success_Message_Setting__mdt Where Type__c = 'B' and Brand_Name__c = :brandName and Country__c = :sourceCountry];

        if (!getMessage.isEmpty()) {
            //System.debug('***Got Configurd Message');
            wrapperObject.successMessage = getMessage[0].Success_Message_f__c;
        } else {
            //System.debug('***No Configurd Message. Default Message is Set');
            wrapperObject.successMessage = 'Your submission has been successfully received and your ticket number is: <ticketid>';
        }

        return wrapperObject;
    }

    /* Method to create Case in Salesforce when Privacy Form is submitted and return:
     * WrapperObject with:
     * CaseNumber and 
     * Success Message (Custom Metadata - Success Message Setting)
     * Regards (Custom Metadata - Success Message Setting)
     */
    /*******************************************************************************************************
    * @description Method to create Case in Salesforce when Privacy Form is submitted and return:
    * WrapperObject with:
    * CaseNumber and
    * Success Message (Custom Metadata - Success Message Setting)
    * Regards (Custom Metadata - Success Message Setting)
    * @param getCaseDetail details of case sent from form
    * @param FirstName first name inputed from page
    * @param FirstName first name inputed from page
    * @return
    * @example
    */
    @AuraEnabled
    public static CaseWrapper createCase(Case getCaseDetail, String firstName, String lastName, String name, String brandName) {
        //System.debug('***inside createCase Method');
        CaseWrapper CaseWrapperObject = new CaseWrapper();


        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();

        //call method to get API name of Brand:
        String getAPINameBrand = getBrandAPIName(brandName);
        //System.debug('***We got BrandAPIName = '+getAPINameBrand);

        //System.debug('***Tommy Adaptive = '+getCaseDetail.Tommy_Adaptive__c);
        // System.debug('***We got Product Sub Category = '+getCaseDetail.Product_Sub_Category__c);

        System.debug('***We got Channel = ' + getCaseDetail.Channel__c);
        string channel=getCaseDetail.Channel__c;
        if(getCaseDetail.Channel__c=='True & Co website'){
            channel='trueandco.com';
        }
        else{
           channel=getCaseDetail.Channel__c; 
        }
        
        //Fetching the assignment rules on case
        AssignmentRule assignRule = new AssignmentRule(); 
        assignRule = [select id from AssignmentRule where SobjectType = 'Case' and Active = true and Name='Case Assignment Rule' limit 1];
        system.debug('assignRule***'+assignRule);
        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmls = new Database.DMLOptions();
        dmls.assignmentRuleHeader.assignmentRuleId= assignRule.id;
        system.debug('dmls***'+dmls);
        
        
        Case newCases = new Case(
                Supplied_First_Name__c = firstName,
                Supplied_Last_Name__c = lastName,
                SuppliedName = name,
                SuppliedEmail = getCaseDetail.SuppliedEmail,
                SuppliedPhone = getCaseDetail.SuppliedPhone,
                Is_Existing_Purchase__c = getCaseDetail.Is_Existing_Purchase__c,
                Channel__c = channel,
                Type = getCaseDetail.Type,
            //    Reason_Code__c=getCaseDetail.Type,
                Description = getCaseDetail.Description,
                Brand__c = brandName,
                Tommy_Adaptive__c = getCaseDetail.Tommy_Adaptive__c,
                Origin = 'Web',
                Order_Number__c = getCaseDetail.Order_Number__c,
                recordTypeId = recordTypeIdSupportCase
        );
        
        //Setting the DMLOption on Case instance
         newCases.setOptions(dmls);
         system.debug('newCases***'+newCases);

        try {
            insert newCases;
        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
       
       Case getCase =new Case(); 
        if(newCases!=Null){
            getCase = [Select Id,caseNumber from Case where Id = :newCases.Id];
             
        }
        //System.debug('***Case Inserted = '+getCase.CaseNumber);
     
            if(getCase!=Null){
                CaseWrapperObject.caseId = getCase.Id;
                CaseWrapperObject.caseNumber = getCase.caseNumber;
            }
        
        return CaseWrapperObject;
        
    }

    public static String getBrandAPIName(String brandNames) {
        Map<String, String> mapBrandLabelValue = new Map<String, String>();
        Schema.sObjectType objTypeCase = Case.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objTypeCase.getDescribe();
        map <String, Schema.SObjectField> typeMap = objDescribe.fields.getMap();
        list <Schema.PicklistEntry> brandValues = typeMap.get('Brand__c').getDescribe().getPickListValues();
        for (Schema.PicklistEntry ent : brandValues) {
            mapBrandLabelValue.put(ent.getLabel(), ent.getValue());
        }
        //System.debug('***We got BrandMap = '+mapBrandLabelValue);
        String brandAPIName = mapBrandLabelValue.get(brandNames);
        return brandAPIName;
    }

    @auraEnabled
    public static String assignFilesToCase(String[] files, Id caseId) {
        system.debug('files@@@ ' + files);

        Set<String> fileIds = new Set<String>(files);

        system.debug('fileIds@@@ '+ fileIds);

        List<ContentDocument> cd = [SELECT Id, ParentId FROM ContentDocument WHERE Id IN :fileIds];

        List<ContentDocumentLink> cdl = new List<ContentDocumentLink>();

        for(ContentDocument cdItem : cd) {
            ContentDocumentLink cDocLink = new ContentDocumentLink();
            cDocLink.ContentDocumentId = cdItem.Id;//Add ContentDocumentId
            cDocLink.LinkedEntityId = caseId;//Add attachment parentId
            cDocLink.ShareType = 'V'; //V - Viewer permission. C - Collaborator permission. I - Inferred permission.
            cdl.add(cDocLink);
        }

        insert cdl;

        system.debug('cdl AFTER: ' + cdl);

        return '';
    }

    /*******************************************************************************************************
    * @description Deprecated method
    * @param sdocumentId
    * @return void
    */
    /*@AuraEnabled
    public static void deleteFiles(string sdocumentId) {
        delete [SELECT Id,Title,FileType from ContentDocument WHERE id = :sdocumentId];
    }*/


    public class InitialDataWrapper {

        @AuraEnabled
        public List<String> listQue0 { get; set; }
        @AuraEnabled
        public List<String> listQue1 { get; set; }
        @AuraEnabled
        public List<String> listQue3 { get; set; }
        @AuraEnabled
        public List<String> listQue4 { get; set; }
        @AuraEnabled
        public String successMessage { get; set; }
        @AuraEnabled
        public String userId { get; set; }
    }

    public class CaseWrapper {
        @AuraEnabled
        public String caseNumber { get; set; }
        @AuraEnabled
        public String caseId { get; set; }

    }

}