unpackaged/main/default/objects/NF_Batch_Control__mdt/NF_Batch_Control__mdt.object-meta.xml
<CustomObject>
    <label>NF Batch Control</label>
    <pluralLabel>NF Batches Control</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Batch_Control__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Determines the batch size to run</description>
    <inlineHelpText>Determines the batch size to run</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SchedulableBatch_PurgeTrackerEvents.cls
/*  Class: SchedulableBatch_PurgeTrackerEvents
 *  Description : Schedulable class to call Batch class Batch_PurgeTrackerEvents.
 */
global class SchedulableBatch_PurgeTrackerEvents implements Schedulable{ 
    global void execute(SchedulableContext ctx){
        NF_Batch_Control__mdt batchMeta =  NF_Batch_Control__mdt.getInstance('SchedulableBatch_PurgeTrackerEvents'); 
        Batch_PurgeTrackerEvents TrackerEvents = new Batch_PurgeTrackerEvents();
        Database.executeBatch(TrackerEvents,Integer.valueOf(batchMeta.Batch_Size__c));
    }
}