unpackaged/main/default/objects/NF_Batch_Control__mdt/NF_Batch_Control__mdt.object-meta.xml
<CustomObject>
    <label>NF Batch Control</label>
    <pluralLabel>NF Batches Control</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Batch_Control__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Determines the batch size to run</description>
    <inlineHelpText>Determines the batch size to run</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/Schedule_Batch_SAPStoreCodeUpdate.cls
global class Schedule_Batch_SAPStoreCodeUpdate implements Schedulable{

   global void execute(SchedulableContext ctx){
        Batch_SAPStoreCodeUpdate sapstoreContact= new Batch_SAPStoreCodeUpdate ();
        NF_Batch_Control__mdt batchMeta =  NF_Batch_Control__mdt.getInstance('Schedule_Batch_SAPStoreCodeUpdate'); 
        Database.executeBatch(sapstoreContact,Integer.valueOf(batchMeta.Batch_Size__c));
        }
}