unpackaged/main/default/objects/NF_Batch_Control__mdt/NF_Batch_Control__mdt.object-meta.xml
<CustomObject>
    <label>NF Batch Control</label>
    <pluralLabel>NF Batches Control</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Batch_Control__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>Determines the batch size to run</description>
    <inlineHelpText>Determines the batch size to run</inlineHelpText>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/LogArchivalBatchScheduler.cls
/*
* @Author: Apoorv (NeuraFlash)
* @CreatedDate: June'16, 2020
* @Description: Scheduler class for LogArchivalBatch.
*/
public with sharing class LogArchivalBatchScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        NF_Batch_Control__mdt batchMeta =  NF_Batch_Control__mdt.getInstance('LogArchivalBatchScheduler');
        Database.executeBatch(new LogArchivalBatch(),Integer.valueOf(batchMeta.Batch_Size__c));
    }
}