unpackaged/main/default/objects/Account/fields/AccountEmail__c.field-meta.xml
<CustomField>
    <fullName>AccountEmail__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>AccountEmail</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Brand_Setting__mdt/Brand_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Email__c.field-meta.xml
<CustomField>
    <fullName>Brand_Email__c</fullName>
    <label>Brand Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Phone__c.field-meta.xml
<CustomField>
    <fullName>Brand_Phone__c</fullName>
    <label>Brand Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Covid_URL__c.field-meta.xml
<CustomField>
    <fullName>Covid_URL__c</fullName>
    <label>Covid URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Order_Status_URL__c.field-meta.xml
<CustomField>
    <fullName>Order_Status_URL__c</fullName>
    <label>Order Status URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Product_Questions_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Questions_URL__c</fullName>
    <label>Product Questions URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Promotions_URL__c.field-meta.xml
<CustomField>
    <fullName>Promotions_URL__c</fullName>
    <label>Promotions URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Return_Questions_URL__c.field-meta.xml
<CustomField>
    <fullName>Return_Questions_URL__c</fullName>
    <label>Return Questions URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Shipping_Questions_URL__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Questions_URL__c</fullName>
    <label>Shipping Questions URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/ebotdata__Bot_Chat_Log__c.object-meta.xml
<CustomObject>
    <description>Track each chat log record and any relevant information thru a backend process</description>
    <label>Bot Chat Log</label>
    <nameField>
        <displayFormat>BLG-{00000}</displayFormat>
        <label>Bot Chat Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Chat Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Bot_Session__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Bot_Session__c</fullName>
    <description>Bot Chat Session</description>
    <inlineHelpText>Einstein Bot Chat Session</inlineHelpText>
    <label>Bot Chat Session</label>
    <referenceTo>ebotdata__Bot_Session__c</referenceTo>
    <relationshipLabel>Bot Chat Logs</relationshipLabel>
    <relationshipName>Bot_Chat_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Current_Utterance__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Current_Utterance__c</fullName>
    <label>Current Utterance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Intent_Name__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Intent_Name__c</fullName>
    <description>Intent Name</description>
    <inlineHelpText>Intent Name</inlineHelpText>
    <label>Intent Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Live_Agent_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Agent_Session_Id__c</fullName>
    <description>This maps to the ChatKey column in LiveChatTranscirpt object</description>
    <inlineHelpText>This maps to the ChatKey column in LiveChatTranscirpt object</inlineHelpText>
    <label>Live Agent Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/CarouselContent__c.field-meta.xml
<CustomField>
    <fullName>CarouselContent__c</fullName>
    <label>CarouselContent</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Case__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case</description>
    <inlineHelpText>Case</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Bot Sessions</relationshipLabel>
    <relationshipName>Bot_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Agent_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Agent_Session_Id__c</fullName>
    <description>Live Agent Session Id</description>
    <inlineHelpText>Live Agent Session Id</inlineHelpText>
    <label>Live Agent Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Live Chat Transcript</description>
    <inlineHelpText>Live Chat Transcript</inlineHelpText>
    <label>Live Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Einstein Bot Chat Session</relationshipLabel>
    <relationshipName>Einstein_Bot_Chat_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_Util.cls
/**
 * Created by apoorvrajput on 9/10/20.
 */

public with sharing class NF_Util {

    public static final String ORIGIN = 'Chat';
    public static String TOMMY = 'Tommy Hilfiger';
    public static String CALVIN = 'Calvin Klein';
    public static String IZOD = 'IZOD';
    public static String VAN = 'Van Heusen';
    public static final String RECORD_TYPE = 'Chat Case';

    public static String getLastBusinessIntent(String chatKey){
        String lastBusinessIntent = '';
        try {
            ebotdata__Bot_Session__c botSession = NF_Util.getBotSession(chatKey);
            System.debug('>>NF_Util.getFirstUserInput botSession=' + botSession);

            if (botSession != null) {
                for (ebotdata__Bot_Chat_Log__c chatLog : [
                        SELECT Id, ebotdata__Intent_Name__c
                        FROM ebotdata__Bot_Chat_Log__c
                        WHERE ebotdata__Bot_Session__c = :botSession.Id
                        ORDER BY Name ASC
                        LIMIT 10
                ]) {

                    System.debug('>>NF_Util.getLastBusinessIntent: ebotdata__Intent_Name__c=' + chatLog.ebotdata__Intent_Name__c);
                    if (String.isNotEmpty(chatLog.ebotdata__Intent_Name__c) && chatLog.ebotdata__Intent_Name__c.substring(0, 3) == 'bus') {
                        lastBusinessIntent = chatLog.ebotdata__Intent_Name__c;
                        break;
                    }
                }
            }
        }catch(Exception e){
            System.debug('Exception encountered: ' + e);
        }
        return lastBusinessIntent;
    }

    public static RecordType getRecordType(){
        RecordType[] recordTypes = [
                SELECT Id
                FROM RecordType
                WHERE Name = :RECORD_TYPE
                LIMIT 1
        ];

        return recordTypes.size() > 0 ? recordTypes[0] : null;
    }

    public static Map<String, String> channelMapping = new Map<String, String>{
            TOMMY => 'Online - Tommy.com',
            CALVIN => 'Online - CalvinKlein.com',
            IZOD => 'Online - Izod.com',
            VAN => 'Online - vanheusen.com'
    };

    public static Map<String, String> buttonMapping = new Map<String, String>{
            TOMMY => 'Tommy Prioritized Chat',
            CALVIN => 'Calvin Klein Prioritized Chat',
            IZOD => 'Partner Brands Prioritized Chat',
            VAN => 'Partner Brands Prioritized Chat'
    };

    public static Map<String, String> deploymentMapping = new Map<String, String> {
            TOMMY => 'Tommy Prioritized Chat',
            CALVIN => 'Calvin Klein Prioritized Chat',
            IZOD => 'Partner Brands Prioritized Chat',
            VAN => 'Partner Brands Prioritized Chat'
    };

    public static Map<String, String> queueMapping = new Map<String, String> {
            TOMMY => 'Tommy_Chat_Priority',
            CALVIN => 'Calvin_Klein_Chat_Priority',
            IZOD => 'Partner_Brands_Chat_Priority',
            VAN => 'Partner_Brands_Chat_Priority'
    };

    public static Brand_Setting__mdt getBrandName(String URL){
        System.debug(URL);
        String brandName = '';
        String backup = URL.toUpperCase();
        URL = URL.toUpperCase();
        URL = URL.remove('HTTPS');
        URL = URL.remove('HTTP');
        URL = URL.remove('//');
        URL = URL.substringBefore('/');
        System.debug(URL +', ' +backup);
        // this is a test domain.
        if(URL.contains('NEURAFLASH') || URL.contains('PVHSERVICECLOUD')) {
            URL = backup;
            System.debug('USING backup'+ URL +', ' +URL.contains('CALVIN'));

        }
        if(URL.contains('TH') || URL.contains('TOMMY') || URL.contains('HILFIGER'))
            brandName = 'Tommy_Hilfiger';
        else if(URL.contains('CK') || URL.contains('CALVIN') || URL.contains('KLEIN'))
            brandName = 'Calvin_Klein';
        else if(URL.contains('IZOD') || URL.contains('IZOD') || URL.contains('IZ'))
            brandName = 'Izod';
        else if(URL.contains('VH') || URL.contains('HEUSEN') || URL.contains('VAN'))
            brandName = 'Van_Heusen';

        List<Brand_Setting__mdt> configs = new List<Brand_Setting__mdt>();
        try{
            configs = [SELECT Id, Community_Name__c, Brand_Id__c, Label, Brand_Email__c, Brand_Phone__c, Shipping_Questions_URL__c, Covid_URL__c, Return_Questions_URL__c, Return_URL__c, Product_Questions_URL__c, Promotions_URL__c, Order_Status_URL__c
            FROM Brand_Setting__mdt
            WHERE DeveloperName = :brandName];
        }
        catch(Exception e) {
            System.debug('Exception encountered: ' + e);
        }
        return configs.size() > 0 ? configs[0] : null;
    }

    public static void insertSession(String chatKey, String payload, String brand){
        System.debug('bot session creation started.');
        ebotdata__Bot_Session__c session = new ebotdata__Bot_Session__c();
        session.CarouselContent__c = payload;
        session.ebotdata__Live_Agent_Session_Id__c = chatKey;
        //session.ebotdata__Live_Chat_Transcript__c = chatKey;
        session.Brand__c = brand;
        insert session;
        System.debug('bot session created');
    }

    public static User getPlatformIntegrationUser(){
        User[] users = [SELECT Id, Name FROM User WHERE Name = 'Automated Process' LIMIT 1];
        return users.size() > 0 ? users[0] : null;
    }

    public static String getDomainName(String url) {
        try {

            Url uri = new Url(url);
            String domain = uri.getHost();
            System.debug('Host is: '+ domain);
            return domain.startsWith('www.') ? domain.substring(4) : domain;
        }
        catch (Exception e) {
            System.debug('exception details :'+e.getStackTraceString());
        }
        return '';
    }

    public static List<String> splitFullNameIntoFirstAndLast(String fullName){
        //grab the first name and parse it
        String firstName;
        String lastName;
        List<String> resultList = new List<String>();
        if (!String.isEmpty(fullName)) {
            //tokenize the full name
            List<String> names = fullName.split(' ');
            if (!names.isEmpty()) {
                //set the first name, and a default last name
                firstName = names.remove(0);
                lastName = 'NA';

                if (!names.isEmpty()) {
                    lastName = names[0];
                    names.remove(0);
                    while (!names.isEmpty()) {
                        lastName += ' ' + names[0];
                        names.remove(0);
                    }
                }
            }
        }
        resultList.add(firstName);
        resultList.add(lastName);
        return resultList;
    }

    public static Account getContact(String email) {
        List<Account> contactList = new List<Account>();
        try{
            if(String.isNotBlank(email)) {
                contactList =   [SELECT Id,FirstName__c, LastName__c
                FROM Account
                WHERE AccountEmail__c = :email];
            }
        }
        catch(Exception e) {
            System.debug('Exception encountered: ' + e);
        }
        return contactList.size() > 0 ? contactList[0] : null;
    }

    public static Contact getContact(String email, String accountId, String brand) {
        List<Contact> contactList = new List<Contact>();
        List<Brand_Setting__mdt> configs = new List<Brand_Setting__mdt>();
        System.debug('brand is:'+brand  + 'email is: '+email);

        if(!String.isBlank(brand))
            try{
                configs = [SELECT Brand_Id__c
                FROM Brand_Setting__mdt
                WHERE Label = :brand];
            }catch(Exception e) {
                System.debug('Exception encountered: ' + e);
            }

        try{
            if(String.isNotBlank(email) && configs.size() > 0) {
                contactList =   [SELECT Id,FirstName, LastName
                FROM Contact
                // account creation removal.
                //WHERE Email = :email and AccountId = :accountId and Brand_Id__c = :configs[0].Brand_Id__c];
                WHERE Email = :email and Brand_Id__c = :configs[0].Brand_Id__c];
            }
            else if(String.isNotBlank(email) && configs.size() == 0) {
                contactList =   [SELECT Id, FirstName, LastName
                FROM Contact
                // account creation removal.
                //WHERE Email = :email and AccountId = :accountId];
                WHERE Email = :email ];
            }
            System.debug('Returning contact list: '+contactList);
        }
        catch(Exception e) {
            System.debug('Exception encountered: ' + e);
        }
        return contactList.size() > 0 ? contactList[0] : null;

    }

    public static Case getCaseRelatedToContact(String contactId) {
        List<Case> caseList = new List<Case>();
        try {
            DateTime compareDate = System.now().addHours(-72);
            if (String.isNotBlank(contactId)) {
                caseList = [
                        SELECT ID, CaseNumber, ContactId, CreatedDate, LastModifiedDate
                        FROM Case
                        WHERE ContactId = :contactId
                        AND (status = 'Open' OR status='New')
                        AND LastModifiedDate >= :compareDate
                        ORDER BY LastModifiedDate DESC
                ];
            }
        }
        catch(Exception e) {
            System.debug('Exception encountered: ' + e);
        }
        return caseList.size() > 0 ? caseList[0] : null;
    }

    public static RecordType getRecordType(String recordType){
        RecordType[] recordTypes = [
                SELECT Id
                FROM RecordType
                WHERE Name = :recordType
                LIMIT 1
        ];

        return recordTypes.size() > 0 ? recordTypes[0] : null;
    }

    public static Group getQueue(String developerName){
        Group[] groups = [SELECT Id, DeveloperName
        FROM Group
        WHERE DeveloperName = :developerName
        LIMIT 1];

        return groups.size() > 0 ? groups[0] : null;
    }

    public static String getSubject(String chatKey) {
        String subject = '';

        //review business intents to get the first utterance from the user
        for (ebotdata__Bot_Chat_Log__c chatLog : [
                SELECT ebotdata__Current_Utterance__c
                FROM ebotdata__Bot_Chat_Log__c
                WHERE ebotdata__Live_Agent_Session_Id__c = :chatKey
                ORDER BY CreatedDate ASC
        ]) {
            if (String.isNotBlank(chatLog.ebotdata__Current_Utterance__c)) {
                subject = chatLog.ebotdata__Current_Utterance__c;
                System.debug('NF_CreateCase getCaseSubject: using utterance for subject:' + subject);
                break;
            }
        }

        //if we weren't able to find an utterance from the history
        if (String.isBlank(subject)) {
            //if it's empty here, just default to 'Chatbot Case'
            subject = 'Chatbot Case';
        }
        if(subject.length() > 250)
            return subject.substring(0, 250);
        else 
            return subject;
        
    }

    public static LiveChatTranscript getLiveChatTranscript(String chatKey){
        System.debug('>>NF_Util.getLiveChatTranscript chatKey is ' + chatKey);

        if(String.isEmpty(chatKey)){
            System.debug('>>NF_Util.getLiveChatTranscript Cannot find LiveChatTranscript, chatKey is empty');
            return null;
        }

        List<LiveChatTranscript> listTranscripts = new List<LiveChatTranscript>();
        try {
            listTranscripts = [SELECT Id, CaseId, Status, ContactId, AccountId, Subject__c
            FROM LiveChatTranscript
            WHERE ChatKey = :chatKey];
        }
        catch(Exception e){
            System.debug('Exception encountered: ' + e);
        }

        return listTranscripts.size() > 0 ? listTranscripts[0] : null;
    }

    public static boolean associateTranscriptWithCase(LiveChatTranscript transcript, String caseId, String contactId) {
        System.debug('Associating Transcript with Case: ' + caseId);

        boolean result = false;

        if (transcript != null && String.isNotEmpty(caseId)) {
            transcript.caseId = caseId;
            try {
                //transcript.caseId = caseId;
                Case caseToLink = [SELECT CaseNumber, SourceId, Description, Subject
                FROM Case
                WHERE Id = :caseId
                LIMIT 1];
                System.debug('Associating Case #' + caseToLink.CaseNumber + ' to transcript ' + transcript.id);
                caseToLink.LiveChatTranscripts.add(transcript);
                caseToLink.SourceId = transcript.Id;
                if(String.isNotBlank(contactId)) {
                    transcript.ContactId = contactId;
                }
                System.debug('updating transcript :****'+ transcript);
                transcript.Subject__c = caseToLink.Description;
                update transcript;
                System.debug('updating case :****'+ caseToLink);
                update caseToLink;
                result = true;
            }
            catch (Exception e) {
                //NF_EinsteinBotLogger.populatedLog(e);
                System.debug('Exception encountered while updating transcript: ' + e);
                System.debug('Line: ' + e.getLineNumber());
                System.debug('Trace: ' + e.getStackTraceString());
                return false;
            }
        }

        return result;
    }

    @Future
    public static void associateCaseWithSession(String chatKey, String caseId) {
        System.debug('NF_CreateCase associateCaseWithSession: chatKey=' + chatKey);

        if (String.isNotBlank(chatKey)) {
            ebotdata__Bot_Session__c session = NF_Util.getBotSession(chatKey);
            System.debug('NF_CreateCase associateCaseWithSession: session=' + session);

            if (session != null && String.isNotBlank(caseId)) {
                session.ebotdata__Case__c = caseId;
                System.debug('NF_CreateCase associateCaseWithSession: ebotdata__Case__c=' + session.ebotdata__Case__c);

                update session;
            }
        }
    }

    public static ebotdata__Bot_Session__c getBotSession(String chatKey){
        ebotdata__Bot_Session__c[] botSessions = [SELECT Id, Brand__c
        FROM ebotdata__Bot_Session__c
        WHERE ebotdata__Live_Agent_Session_Id__c = :chatKey
        LIMIT 1];
        return botSessions.size() > 0 ? botSessions[0] : null;
    }

    public static Account createCustomer(String firstName, String lastName, String emailId) {
        try{
            //Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            Account newPersonAccount = new Account(
                    FirstName__c = firstName,
                    LastName__c = lastName,
                    AccountEmail__c = emailId,
                    Name = firstName + ' ' + lastName
                    //RecordTypeId = personAccRecordTypeId
            );
            System.debug('Inserting account'+ newPersonAccount);
            insert newPersonAccount;
            return newPersonAccount;
        }
        catch(Exception e) {
            System.debug('Exception encountered: ' + e);
        }
        return null;

    }

    public static Contact createContact(String firstName, String lastName, String emailId, String brandId) {
        Id contactEmailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Email').getRecordTypeId();
        if(String.isBlank(firstName))
            firstName = 'UNKNOWN';
        if(String.isBlank(lastName))
            lastName = 'UNKNOWN';
        try{
            Contact contact = new Contact(
            FirstName = firstName,
            LastName = lastName,
            Email = emailId,
            Brand_Id__c = brandId,
            RecordTypeId = contactEmailRecordTypeId
            );//Added RecordTypeId for Incident INC0781631 - Duplicate contact created
        System.debug('Inserting contact'+ contact);
        insert contact;
        return contact;
        }
        catch(Exception e) {
        System.debug('Exception encountered: ' + e);
        }
    return null;

}

    public Static String getBrandId(String brand) {
        List<Brand_Setting__mdt> configs = new List<Brand_Setting__mdt>();
        if(!String.isBlank(brand))
            try{
                configs = [SELECT Brand_Id__c
                FROM Brand_Setting__mdt
                WHERE Label = :brand];
            }catch(Exception e) {
                System.debug('Exception encountered: ' + e);
            }
        return configs[0].Brand_Id__c;
    }
}