unpackaged/main/default/objects/Account/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>Controlled By Account - This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountTriggerHandler.cls
/**
* @author Magnet360
* @date 2019
*
* @group Account
* @group-content ../../ApexDocContent/Account.htm
*
* @description Trigger Handler on Accounts.
*/
public without sharing class AccountTriggerHandler implements ITrigger {
    /**
     * bulkBefore
     *
     * This method is called prior to execution of a BEFORE trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkBefore() {
        if(Trigger.isDelete) {
            GenericRecords__c genericAccountRecord = GenericRecords__c.getValues(Constants.AccountGenericRecordSettingName);
            Account genericAccount = [Select Id from Account where Id = :genericAccountRecord.recordId__c];

            List<SObject> recordsToDisassociate = new List<SObject>();
            Set<Id> accountIds = Trigger.oldMap.keySet();

            //Disassociate Cases
            for(Contact con :[Select Id, AccountId from Contact where AccountId in :accountIds]) {
                con.AccountId = genericAccount.Id;
                recordsToDisassociate.add(con);
            }

            //Disassociate Cases
            for(Case c :[Select Id, AccountId from Case where AccountId in :accountIds]) {
                c.AccountId = null;
                recordsToDisassociate.add(c);
            }

            //Reassociate Opportunities
            for(Opportunity o :[Select Id, AccountId from Opportunity where AccountId in :accountIds]) {
                o.AccountId = null;
                recordsToDisassociate.add(o);
            }

            //Disassociate Contracts
            for(Contract ct :[Select Id, AccountId from Contract where AccountId in :accountIds]) {
                ct.AccountId = genericAccount.Id;
                recordsToDisassociate.add(ct);
            }

            update recordsToDisassociate;
        }
    }
    
    /**
     * bulkAfter
     *
     * This method is called prior to execution of an AFTER trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkAfter() {
        if (Trigger.isUpdate) {
            List<String> updatedOWABrandNames = new List<String>();
            Map<String, String> updatedBrandOWAMap = new Map<String, String>();
            for (SObject so : Trigger.New) {
                Account acc = (Account)so;
                Account oldAcc = (Account)Trigger.oldMap.get(acc.Id);
                if (acc.RecordTypeId == Constants.brandRecordTypeId && acc.Brand_Privacy_OWA_Name__c != oldAcc.Brand_Privacy_OWA_Name__c) {
                    String brandPickVal;

                    List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
                    for (Schema.Picklistentry ple: fieldResult) {
                        if(ple.getLabel() == acc.Name) {
                            brandPickVal = ple.getValue();
                        }
                    }
                    if (String.isBlank(brandPickVal)) {
                        System.debug('Brand account without brand picklist value on case' + acc.Name + acc);
                        continue;
                    }
                    updatedBrandOWAMap.put(brandPickVal, acc.Brand_Privacy_OWA_Name__c);
                    updatedOWABrandNames.add(brandPickVal);
                }

            }
            if (updatedOWABrandNames.size() > 0) {
                List<Case> relatedCases = [Select Id, Brand_Privacy_OWA_Name__c, Brand__c From Case Where Type = :Constants.privacyCaseType And Brand__c In :updatedOWABrandNames And Status Not In :Constants.privacyCaseCompletedStatuses];
                if (relatedCases.size() > 0) {
                    for (Case relatedCase : relatedCases) {
                        relatedCase.Brand_Privacy_OWA_Name__c = updatedBrandOWAMap.get(relatedCase.Brand__c);
                    }
                    update relatedCases;
                }
            }

        }
        
    }
    
    /**
     * beforeInsert
     *
     * This method is called iteratively for each record to be inserted during a BEFORE
     * trigger. Never execute any SOQL/SOSL etc in this and other iterative methods.
     */
    public void beforeInsert(SObject obj) {

        
    }
    
    /**
     * beforeUpdate
     *
     * This method is called iteratively for each record to be updated during a BEFORE
     * trigger.
     */
    public void beforeUpdate(SObject oldSo, SObject so) {
        Account acc = (Account)so;
        if (acc.RecordTypeId == Constants.brandRecordTypeId) {
            if (!FeatureManagement.checkPermission(Constants.modifyBrandPermission)){
                acc.addError('You must have the modify Brand Permission enabled to edit or delete brand records. If you believe you need this permission, please contact your system administrator.');
            }
        }
        
    }

    /**
     * beforeDelete
     *
     * This method is called iteratively for each record to be deleted during a BEFORE
     * trigger.
     */
    public void beforeDelete(SObject so) {
        Account acc = (Account)so;
        if (acc.RecordTypeId == Constants.brandRecordTypeId) {
            if (!FeatureManagement.checkPermission(Constants.modifyBrandPermission)){
                acc.addError('You must have the modify Brand Permission enabled to edit or delete brand records. If you believe you need this permission, please contact your system administrator.');
            }
        }
        
    }

    /**
     * afterInsert
     *
     * This method is called iteratively for each record inserted during an AFTER
     * trigger. Always put field validation in the 'After' methods in case another trigger
     * has modified any values. The record is 'read only' by this point.
     */
    public void afterInsert(SObject so) {
        
    }

    /**
     * afterUpdate
     *
     * This method is called iteratively for each record updated during an AFTER
     * trigger.
     */
    public void afterUpdate(SObject oldSo, SObject so) {}

    /**
     * afterDelete
     *
     * This method is called iteratively for each record deleted during an AFTER
     * trigger.
     */
    public void afterDelete(SObject so) {

    }

    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this 
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally() {
        
    }
}