unpackaged/main/default/objects/Account/fields/Brand_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Image_Link__c</fullName>
    <description>Link to the Brand&#39;s Publicly Accessible Image. To be used in email templates</description>
    <label>Brand Image Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Brand_Privacy_Form_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Form_Link__c</fullName>
    <description>Link to the brand&#39;s privacy policy form to submit data access and deletion requests</description>
    <label>Brand Privacy Form Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Privacy_Escalation_Email__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Escalation_Email__c</fullName>
    <description>The email address to use when data owner cases need to be escalated</description>
    <label>Privacy Escalation Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Image_Link__c</fullName>
    <description>Controlled by Brand Account - Link to the Brand&#39;s Publicly Accessible Image. To be used in email templates</description>
    <label>Brand Image Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_Form_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Form_Link__c</fullName>
    <description>Controller by Brand Account - Link to the brand&#39;s privacy policy form to submit data access and deletion requests</description>
    <label>Brand Privacy Form Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>Controlled By Account - This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Escalation_Email__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Escalation_Email__c</fullName>
    <description>Controlled by Account - The email address to use when data owner cases need to be escalated</description>
    <label>Privacy Escalation Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/R2R_Email_UserConfirmation__c.field-meta.xml
<CustomField>
    <fullName>R2R_Email_UserConfirmation__c</fullName>
    <label>Email User Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_1__c</fullName>
    <description>The first additional email to send data owner requests to</description>
    <label>Additional Email 1</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_2__c</fullName>
    <description>The second additional email to send data owner requests to</description>
    <label>Additional Email 2</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_3__c</fullName>
    <description>The third additional email to send data owner requests to</description>
    <label>Additional Email 3</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_4__c</fullName>
    <description>The fourth additional email to send data owner requests to</description>
    <label>Additional Email 4</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/System_Type__c.field-meta.xml
<CustomField>
    <fullName>System_Type__c</fullName>
    <description>The type of system for which the Data Owner is Responsible</description>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>External - Managed By PVH</fullName>
            </value>
            <value>
                <fullName>Supplemental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_CaseTriggerHelperTest.cls
@IsTest
public class NF_CaseTriggerHelperTest {
	@testsetup
    static void makedata(){
        Group gp = new Group();
        gp.Name = 'RTR Request';
        insert gp; 
        
        OrgWideEmailAddress owa = [Select DisplayName From OrgWideEmailAddress Limit 1];
        
        Account brandAccount = new Account();
        brandAccount.Name = 'Calvin Klein';
        brandAccount.RecordTypeId = Constants.brandRecordTypeId;
        brandAccount.Brand_Image_Link__c = 'foo.bar';
        brandAccount.Brand_Privacy_Form_Link__c = 'boo.far';
        brandAccount.Brand_Privacy_OWA_Name__c = owa.DisplayName;
        brandAccount.Privacy_Escalation_Email__c = 'foo@example.com';
        insert brandAccount;

        Contact brandOwner = new Contact();
        brandOwner.accountId = brandAccount.Id;
        brandOwner.RecordTypeId = Constants.dataOwnerContactRecordTypeId;
        brandOwner.firstName = 'foo';
        brandOwner.LastName = 'Bar';
        brandOwner.Email = 'mrfoobar@example.com';
        brandOwner.System_Type__c = Constants.dataOwnerSupplemental;
        brandOwner.Additional_Email_1__c = 'foo@example.com';
        brandOwner.Additional_Email_2__c = 'foo@example.com';
        brandOwner.Additional_Email_3__c = 'foo@example.com';
        brandOwner.Additional_Email_4__c = 'foo@example.com';
        brandOwner.Brand_Id__c='2';
        insert brandOwner;

        Account acc = new Account();
        acc.Name = 'generic Account';
        insert acc;

        Contact con = new Contact();
        con.email = 'foo@example.com';
        con.lastName = 'generic contact';
        con.AccountId = acc.id;
        con.Brand_Id__c='2';
        insert con;

        GenericRecords__c genRec = new GenericRecords__c(
            Name = Constants.privacyContactGenericRecordSettingName,
            recordId__c = con.Id
        );
        insert genRec;
    }
    
    @IsTest
    static void testAfterUpdate(){
		Case cs = new Case();
        cs.Supplied_Last_Name__c = 'TESTING';
        cs.SuppliedEmail = 'test@test.com';
        cs.Origin = 'Phone';
        insert cs;
		cs.Brand__c = '2';
        cs.SuppliedPhone = '9988998899';
        cs.status = 'Resolved';
        cs.Sub_Type__c = 'Rectify My Data';
        cs.R2R_Email_UserConfirmation__c = 'Confirmed';
        update cs;
    }
    
    @IsTest
    static void test234MethodTest(){
     NF_CaseTriggerHelper.test234Method();
     //repeat the same for the rest of classes.
  }  
}