unpackaged/main/default/objects/Account/fields/Brand_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Image_Link__c</fullName>
    <description>Link to the Brand&#39;s Publicly Accessible Image. To be used in email templates</description>
    <label>Brand Image Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Brand_Privacy_Email__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Email__c</fullName>
    <description>Email Address for the Brand&#39;s Privacy Email Communications</description>
    <label>Brand Privacy Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Brand_Privacy_Form_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Form_Link__c</fullName>
    <description>Link to the brand&#39;s privacy policy form to submit data access and deletion requests</description>
    <label>Brand Privacy Form Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Brand_Setting__mdt/Brand_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Outbound_Privacy_Email__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Privacy_Email__c</fullName>
    <label>Outbound Privacy Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Privacy_Email__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Email__c</fullName>
    <label>Privacy Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Additional_Privacy_Request_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Privacy_Request_Information__c</fullName>
    <description>This field will contain additional information to send to the Data Owners to process data owner requests</description>
    <inlineHelpText>This field will contain additional information to send to the Data Owners to process data owner requests</inlineHelpText>
    <label>Additional Privacy Request Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Image_Link__c</fullName>
    <description>Controlled by Brand Account - Link to the Brand&#39;s Publicly Accessible Image. To be used in email templates</description>
    <label>Brand Image Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_Email__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Email__c</fullName>
    <description>Controlled By Account - Email Address for the Brand&#39;s Privacy Email Communications</description>
    <label>Brand Privacy Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_Form_Link__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Form_Link__c</fullName>
    <description>Controller by Brand Account - Link to the brand&#39;s privacy policy form to submit data access and deletion requests</description>
    <label>Brand Privacy Form Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Email_Assignment_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_Assignment_Code__c</fullName>
    <label>Email Assignment Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R</fullName>
                <label>Retail</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Ecomm</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Wholesale</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Internal</label>
            </value>
            <value>
                <fullName>RS</fullName>
                <label>Retail Store</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/emailToAddress__c.field-meta.xml
<CustomField>
    <fullName>emailToAddress__c</fullName>
    <label>emailToAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <description>Used to track the last time a status was changed to open in order to properly assign case to either a zQueue or the originating queue.</description>
    <label>Last Status Change</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Originating_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Originating_Queue_Id__c</fullName>
    <label>Originating Queue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Personal_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Personal_Queue_Id__c</fullName>
    <formula>Owner:User.Personal_Queue_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Personal Queue Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Case_Resolved_Date__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Case_Resolved_Date__c</fullName>
    <description>The date where the case was resolved. After some hours, configured in custom settings, the case will be closed</description>
    <label>Privacy Case Resolved Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Date_Consumer_Last_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Date_Consumer_Last_Contacted__c</fullName>
    <description>The date where the consumer was contacted for additional information. After some hours, configured in custom settings, the case will be closed if the consumer does not respond.</description>
    <label>Privacy Date Consumer Last Contacted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_User_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Privacy_User_Confirmed_Date__c</fullName>
    <description>The date that the user confirmed their privacy request</description>
    <label>Privacy User Confirmed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/R2R_Email_UserConfirmation__c.field-meta.xml
<CustomField>
    <fullName>R2R_Email_UserConfirmation__c</fullName>
    <label>Email User Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_First_Name__c</fullName>
    <description>Supplied First Name</description>
    <label>Supplied First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/VerificationHash__c.field-meta.xml
<CustomField>
    <fullName>VerificationHash__c</fullName>
    <defaultValue>&#39;1234&#39;</defaultValue>
    <description>Used by clickable email responses to validate the authenticity of the response.</description>
    <label>VerificationHash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/ZdPVH.recordType-meta.xml
<RecordType>
    <fullName>ZdPVH</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk PVH</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/ZdTnC.recordType-meta.xml
<RecordType>
    <fullName>ZdTnC</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk True &amp; Co</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Personal_Queue_ID__c.field-meta.xml
<CustomField>
    <fullName>Personal_Queue_ID__c</fullName>
    <label>Personal Queue ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseTriggerHandler.cls
/**
* @author Magnet360
* @date 2019
*
* @group Case
* @group-content ../../ApexDocContent/Case.htm
*
* @description Trigger Handler on Case that performs a variety of actions
* related to CCPA and Support Cases.
*/
public without sharing class CaseTriggerHandler implements ITrigger {
    List<Id> listCaseId = new List<Id>();
    List<Id> listCaseIdDeleteReq = new List<Id>();
    List<Case> caseListForAccCon = new List<Case>();
    List<Contact> contactListForAccCon = new List<Contact>();
    Static String SupportRecordTypeId = Schema.SObjectType.CASE.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
    Map<Id, User> caseOwnersMap = new Map<Id, User>();
    Set<Case> casesToUpload = new Set<Case>();
    public static boolean sentSuccessEmail = false;
    /*******************************************************************************************************
    * @description This method is called prior to execution of a BEFORE trigger. Use this to cache
     * any data required into maps prior execution of the trigger. <p>
    * <p>
    * Privacy and Support cases that are to be sent back to a users Omni Personal Queue are grouped together
    *
    * @return void
    */
    public void  bulkBefore(){
        if(trigger.isUpdate) {
            Set<String> ownerIds = new Set<String>();
            List<Case> casesToSendToOmni = new List<Case>();
            List<Case> newEmailCases = new List<Case>();
            Id unassignedPrivacyQueueId;
            for(sObject updatedRec :Trigger.New) {
                Case c = (Case)updatedRec;
                Case oldCase = (Case)Trigger.oldMap.get(c.Id);

                if(c.Status != oldCase.Status && c.Status == 'Open' && oldCase.Status != 'New') {
                    casesToUpload.add(c);
                    ownerIds.add(c.OwnerId);
                    //system.debug('casesToUpload***'+casesToUpload);
                }
                    
                if (c.Type == Constants.privacyCaseType &&
                        c.Sub_Type__c != Constants.privacyEmailSubType &&
                        (c.Status == Constants.openStatus && oldCase.Status != Constants.openStatus)) {
                    casesToSendToOmni.add(c);
                }
                if (c.Type == Constants.privacyCaseType &&
                        c.Sub_Type__c != Constants.unsubscribeRequestSubType &&
                        (c.Status == Constants.openStatus && oldCase.Status != Constants.openStatus)) {
                    casesToSendToOmni.add(c);
                }
                if (c.Type == Constants.marketingCaseType && c.Sub_Type__c == Constants.unsubscribeRequestSubType && c.Status == Constants.openStatus && oldCase.Status != Constants.openStatus) {
                    casesToSendToOmni.add(c);
                }
                if (c.Origin == 'Email' && !String.isBlank(c.emailToAddress__c) && String.isBlank(oldCase.emailToAddress__c)) {
                    List<Brand_Setting__mdt> brandSetting1 = [Select Brand_Id__c From Brand_Setting__mdt Where Privacy_Email__c = :c.emailToAddress__c];
                    List<Brand_Setting__mdt> brandSetting2 = [Select Brand_Id__c From Brand_Setting__mdt Where Outbound_Privacy_Email__c = :c.emailToAddress__c];
                    if (brandSetting1.size() > 0 || brandSetting2.size() > 0) {
                        Brand_Setting__mdt brandSetting;
                        if (brandSetting1.size() > 0) {
                            brandSetting = brandSetting1[0];
                        } else {
                            brandSetting = brandSetting2[0];
                        }
                        c.Brand__c = brandSetting.Brand_Id__c;
                        c.Type = Constants.privacyCaseType;
                        c.Sub_Type__c = Constants.privacyEmailSubType;
                        c.RecordTypeId = Constants.supportCaseRecordTypeId;
                        PrivacyCaseTriggerHandler.isFirstRun = True;
                    }
                    casesToSendToOmni.add(c);
                    //system.debug('casesToSendToOmni***'+casesToSendToOmni);
                }
            }
            caseOwnersMap = new Map<Id, User> ([Select Id, Personal_Queue_ID__c from User where Id in :ownerIds]);
            if (casesToSendToOmni.size() > 0) {
                // system.debug('casesToSendToOmni***'+casesToSendToOmni);
                PrivacyCaseQueueHandler.sendCasesToOmni(casesToSendToOmni);
            }
        }

        this.updatePrivacyCaseBrandInfo();

        //added to add brand logo to non-privacy cases for email template support
        this.updateCaseBrandImageLink();

    }



    /*******************************************************************************************************
    * @description This method is called prior to execution of an AFTER trigger. Use this to cache
    * any data required into maps prior execution of the trigger. Following Actions take place:<p>
    * <p>
    * After the case has been inserted, Contacts that match either the Email or Phone are queried to be
    * sent to the ContactFuture Methods
    * @return void
    */
    public void bulkAfter(){       
        List<Case> listOfResolvedCases = new List<Case>();
        for(SObject c :Trigger.new) {
            Case newCase = (Case)c;
            if(Trigger.isInsert){
                if(newCase.Origin != 'Phone') {
                    caseListForAccCon.add(newCase);
                }
            } else if(Trigger.isUpdate) {
                if(newCase.Origin == 'Phone' && newCase.ContactId == null & newCase.Supplied_Last_Name__c != null && (newCase.SuppliedEmail != null || newCase.SuppliedPhone != null)) {
                    caseListForAccCon.add(newCase);
                }
            }
        }

        if(caseListForAccCon.size() > 0){


            List<Id> caseId = new List<Id>();
            List<String> EmailList = new List<String>();
            List<String> BrandList = new List<String>();
            List<String> PhoneList = new List<String>();

            for(Case newCase : caseListForAccCon){
                if(newCase.Id !=Null && (newCase.ZdTnCTicketId__c==null && newCase.ZdPVHTicketId__c==null)){
                    caseId.add(newCase.Id);
                    if (newCase.SuppliedEmail != null) {
                        EmailList.add(newCase.SuppliedEmail);
                    }
                    BrandList.add(newCase.Brand__c);
                    if (newCase.SuppliedPhone != null) {
                        PhoneList.add(newCase.SuppliedPhone);
                    }
                }
            }

            contactListForAccCon = [SELECT Id, FirstName, LastName, Email, Brand_Id__c, AccountId, Phone, MobilePhone, HomePhone
            FROM Contact
            WHERE (Email IN :EmailList OR Phone IN :PhoneList) Order BY Brand_Id__c DESC NULLS FIRST, Email DESC NULLS LAST, Phone DESC NULLS LAST, CreatedDate];
        }
    }

    /*******************************************************************************************************
    * @description This method is called iteratively for each record to be inserted during a BEFORE
    * trigger. Never execute any SOQL/SOSL etc in this and other iterative methods.
    *
    * Email to Case origins are split to identify the proper brand for the case
    * Names originated from Emails are formatted so the Contact is preoperly created
    *
    * @return void
    */
    public void  beforeInsert(SObject obj){
        Case cas = (Case)obj;
        system.debug('>>>>>>>cas.Origin'+cas.Origin);
        if(cas.Origin != null && cas.Origin.startsWithIgnoreCase('Email -') && cas.Brand__c == null){
            List<String> e2cRoutings = cas.Origin.split('-');
            cas.Origin = 'Email';
            if(e2cRoutings.size() >= 2){
                cas.Brand__c = e2cRoutings[1].trim();
            }

            if(e2cRoutings.size() == 3){
                cas.Email_Assignment_Code__c = e2cRoutings[2].trim();
            }
            cas.Origin = 'Email';
        }

        //splits email sender name to populate Supplied First Name and Last Name fields on Case, which will help populate the Contact First and Last Name
        if (cas.Origin == 'Email' ) {

            if(cas.SuppliedName != null) {
                List<String> suppliedNameSplitString = cas.SuppliedName.split(' ');

                String newFirstname = '';
                String newLastname = '';
                Integer suppliedNameSplitStringSize = suppliedNameSplitString.size();

                for (Integer i = 0; i < suppliedNameSplitStringSize; i++) {
                    if (suppliedNameSplitStringSize == 1 && i == 0) {
                        newLastname = suppliedNameSplitString[i];
                    } else if (suppliedNameSplitStringSize == 2) {
                        if (i == 0) {
                            newFirstname = suppliedNameSplitString[i];
                        } else if (i == 1) {
                            newLastname = suppliedNameSplitString[i];
                        }
                    } else if (suppliedNameSplitStringSize > 2) {
                        if (i < suppliedNameSplitStringSize - 1) {
                            newFirstname = newFirstname + suppliedNameSplitString[i] + ' ';
                        } else if (i == suppliedNameSplitStringSize - 1) {
                            newLastname = suppliedNameSplitString[i];
                        }
                    }
                }
                cas.Supplied_First_Name__c = newFirstname;
                cas.Supplied_Last_Name__c = newLastname;
            }


        }

        //Added below code to attach the Record type For Email-To-case,when the case is
        //closed and the customer reply to the case then new case gets created
        if(cas.Type == Constants.privacyCaseType) {
            if (cas.Sub_Type__c == Constants.deletionRequestSubType || cas.Sub_Type__c == Constants.accessRequestSubType || cas.Sub_Type__c == Constants.rectifyRequestSubType) {
                cas.RecordTypeId = Constants.privacyRecordTypeId;
                cas.Additional_Privacy_Request_Information__c = 'N/A';
            }
        }
        cas.VerificationHash__c = utilityClass.generateRandomString(16);
        //else  cas.RecordTypeId = SupportRecordTypeId;
    }
    
    
    public void zQueueAssignment(Case c) {
        if(casesToUpload.contains(c) && c.Type != Constants.privacyCaseType) {
            if(caseOwnersMap.containsKey(c.OwnerId)) {
                if(caseOwnersMap.get(c.OwnerId).Personal_Queue_Id__c != null) {
                    c.OwnerId = caseOwnersMap.get(c.OwnerId).Personal_Queue_Id__c;
                }
            }
        }
    }

    /*******************************************************************************************************
    * @description This method is called iteratively for each record to be updated during a BEFORE
    * trigger.<p>
    * <p>
    *
    * @return void
    */
    public void  beforeUpdate(SObject oldSo, SObject so){
        Case c = (Case)so;
        Case oldCase = (Case)oldSo;
        //returns cases to omni queue
        if(c.Status != oldCase.Status && c.Status == 'Open' && oldCase.Status != 'New' && c.Last_Status_Change__c != null){
           if(c.Originating_Queue_Id__c != null) {
                    c.OwnerId = c.Originating_Queue_Id__c;
                } 
        }
        if(c.Type == Constants.privacyCaseType) {
            if (c.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                c.Privacy_Case_Resolved_Date__c = System.now();
                c.VerificationHash__c = utilityClass.generateRandomString(16);
            }
            if(c.Status == Constants.waitingForResponse && oldCase.Status != Constants.waitingForResponse) {
                c.Privacy_Date_Consumer_Last_Contacted__c = System.now();
            }

            // Change the hash on a status change to 'break' old API request links.
            if(c.Privacy_User_Confirmed_Date__c != oldCase.Privacy_User_Confirmed_Date__c &&
                    c.Privacy_User_Confirmed_Date__c != null) {
                c.VerificationHash__c = utilityClass.generateRandomString(16);
            }

        }
    }

   


    /*******************************************************************************************************
    * @description This method is called iteratively for each record to be deleted during a BEFORE
    * trigger. <p>
    * <p>
    *  No actions are currently defined
    * @return void
    */

    public void  beforeDelete(SObject so){

    }

    /*******************************************************************************************************
    * @description This method is called iteratively for each record inserted during an AFTER
    * trigger. Always put field validation in the 'After' methods in case another trigger
    * has modified any values. The record is 'read only' by this point.
    *<p>
    * @return void
    */
    public void  afterInsert(SObject so){
        Case inputCase = (Case)so;
        if(inputCase.Sub_Type__c == Constants.accessRequestSubType && inputCase.ParentId==null)
            listCaseId.add(inputCase.Id);

        if((inputCase.Sub_Type__c == Constants.deletionRequestSubType||inputCase.Sub_Type__c == Constants.rectifyRequestSubType) && inputCase.ParentId==null)
            listCaseIdDeleteReq.add(inputCase.Id);
    }

    /*******************************************************************************************************
    * @description This method is called iteratively for each record deleted during an AFTER
    * trigger.
    *<p>
    * no actions are currently defined
    * @return void
    */
    public void  afterUpdate(SObject oldSo, SObject so){

        List<Case> listOfResolvedCases = new List<Case>();
        List<Case> listOfOnHoldCases = new List<Case>();
        for(SObject c :Trigger.new) {
            Case newCase = (Case)c;
            Case oldCase = (Case)Trigger.oldMap.get(c.Id);
			 if(Trigger.isUpdate) {
                if(sentSuccessEmail == false && newCase.status == 'Resolved' && (newCase.Sub_Type__c == 'Rectify My Data' || newCase.Sub_Type__c == 'Do Not Sell/Share') && newCase.R2R_Email_UserConfirmation__c == 'Confirmed' && newCase.status != oldCase.Status){
                    system.debug('sss');
                    listOfResolvedCases.add(newCase);
                }
                 if((newCase.status == 'On Hold' || newCase.status == 'Resolved') && newCase.status != oldCase.status && (newCase.sub_Type__c == 'Do Not Sell/Share' || newCase.sub_Type__c == 'Rectify My Data')){
                     listOfOnHoldCases.add(newCase);
                 }
            }
        }
		    if(!listOfResolvedCases.isEmpty()){
                sendSuccessEmails(listOfResolvedCases);
            }
        
        if(!listOfOnHoldCases.isEmpty()){
            if(system.isFuture()){
            	changeCaseOwnerQueue(JSON.serialize(listOfOnHoldCases));
            }else{
                changeCaseOwnerQueueFuture(JSON.serialize(listOfOnHoldCases));
            }
        }
    }
    /*******************************************************************************************************
    * @description This method is called iteratively for each record deleted during an AFTER
    * trigger.
    *<p>
    * no actions are currently defined
    * @return void
    */
    public void  afterDelete(SObject so){

    }

    /*******************************************************************************************************
    * @description This method is called once all records have been processed by the trigger. Use this
    * method to accomplish any final operations such as creation or updates of other records.
    *<p>
    * DML updates on Contacts
    * @return void
    */
    public void andFinally(){

        if(!caseListForAccCon.isEmpty() && !System.isFuture()){
            //If Contact Creation is requested in an update, run immediately, not async
            Boolean runInFuture = !Trigger.isUpdate;
            CaseUtility.updateCaseContactdetails(caseListForAccCon, contactListForAccCon, runInFuture);
        }
    }

    /***********************************************************************************************
    * @description Update privacy cases with brand information pulled from accounts.
    * Iterates over Trigger.New
    */
    private void updatePrivacyCaseBrandInfo() {
        try {
            List<Case> privacyCasesNeedingBrandUpdate = new List<Case>();
            for(Sobject sobjCase : Trigger.New) {
                Case cse = (Case)sobjCase;
                if (cse.Type == Constants.privacyCaseType || (
                        cse.Type == Constants.marketingCaseType &&
                                cse.Sub_Type__c == Constants.unsubscribeRequestSubType
                )
                        ) {
                    if (Trigger.isInsert && String.isNotBlank(cse.Brand__c)) {
                        privacyCasesNeedingBrandUpdate.add(cse);
                    } else {
                        Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                        if (cse.Brand__c != oldCase.Brand__c) {
                            privacyCasesNeedingBrandUpdate.add(cse);
                        }
                    }
                }
            }
            if (privacyCasesNeedingBrandUpdate.size() > 0) {
                List<Account> brands = [Select Id, Name, Brand_Image_Link__c, Brand_Privacy_Form_Link__c, Brand_Privacy_Email__c, Brand_Privacy_OWA_Name__c, Privacy_Escalation_Email__c From Account Where RecordTypeID = :Constants.brandRecordTypeId];
                Map<String, Account> brandMap = new Map<String, Account>();
                for (Account brand: brands) {
                    brandMap.put(brand.Name, brand);
                }
                Map<String, String> brandValueMap = new Map<String, String>();
                List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
                for (Schema.Picklistentry ple: fieldResult) {
                    brandValueMap.put(ple.getValue(), ple.getLabel());
                }
                Map<String, String> OwaNameEmailMap = new Map<String, String>();
                List<OrgWideEmailAddress> owaList = [Select Id, DisplayName, Address From OrgWideEmailAddress limit 1000];
                for (OrgWideEmailAddress owa : owaList) {
                    OwaNameEmailMap.put(owa.DisplayName, owa.Address);
                }
                for (Case cse : privacyCasesNeedingBrandUpdate) {
                    String brandName = brandValueMap.get(cse.Brand__c);
                    Account brandRecord = brandMap.get(brandName);
                    cse.Brand_Privacy_Form_Link__c = brandRecord.Brand_Privacy_Form_Link__c;
                    cse.Brand_Image_Link__c = brandRecord.Brand_Image_Link__c;
                    cse.Brand_Privacy_Email__c = brandRecord.Brand_Privacy_Email__c;
                    cse.Brand_Privacy_OWA_Name__c = brandRecord.Brand_Privacy_OWA_Name__c;
                    cse.Privacy_Escalation_Email__c = brandRecord.Privacy_Escalation_Email__c;
                    cse.Default_From_Address__c = OwaNameEmailMap.get(cse.Brand_Privacy_OWA_Name__c);
                }

            }
        } catch(Exception e) {
            System.debug('Exception encountered updating Brand' + e);

        }
    }

    /***********************************************************************************************
* @description Update non-privacy cases with brand logo pulled from accounts.
* Iterates over Trigger.New
*/
    private void updateCaseBrandImageLink() {
        try {
            List<Case> casesNeedingBrandImage = new List<Case>();
           for(Sobject sobjCase : Trigger.New) {
                Case cse = (Case)sobjCase;
                if (cse.Type != Constants.privacyCaseType){
                    if (Trigger.isInsert && String.isNotBlank(cse.Brand__c)) {
                        	casesNeedingBrandImage.add(cse);
                    } else if(cse.id!=null){
                        Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                        if (cse.Brand__c != oldCase.Brand__c) {
                            casesNeedingBrandImage.add(cse);
                        } else if (String.isBlank(cse.Brand_Image_Link__c) && String.isNotBlank(cse.Brand__c)) {
                            casesNeedingBrandImage.add(cse);
                        }
                    }
                }
            }
            if (casesNeedingBrandImage.size() > 0) {
                List<Account> brands = [Select Id, Name, Brand_Image_Link__c, Brand_Privacy_Form_Link__c, Brand_Privacy_Email__c, Brand_Privacy_OWA_Name__c, Privacy_Escalation_Email__c From Account Where RecordTypeID = :Constants.brandRecordTypeId];
                Map<String, Account> brandMap = new Map<String, Account>();
                for (Account brand: brands) {
                    brandMap.put(brand.Name, brand);
                }
                Map<String, String> brandValueMap = new Map<String, String>();
                List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
                for (Schema.Picklistentry ple: fieldResult) {
                    brandValueMap.put(ple.getValue(), ple.getLabel());
                }
                for (Case cse : casesNeedingBrandImage) {
                    String brandName = brandValueMap.get(cse.Brand__c);
                    Account brandRecord = brandMap.get(brandName);
                    cse.Brand_Image_Link__c = brandRecord.Brand_Image_Link__c;
                }

            }
        } catch(Exception e) {
            System.debug('Exception encountered updating Brand' + e);

        }
    }
        /**
* @author       : Juhi Bahrani
* @date       : 07/09/2022
* @description   : This Case trigger update record type on case
*            
*/
    public static void beforeUpdateOnCase(List<Case> newCaseList){
        
        Map<String, Contact> ZdTnCContactMap = new Map<String, Contact>();
        Map<String, Contact> ZdPVHContactMap = new Map<String, Contact>();
        Set<String> setCaseZdTnCUserIds = new Set<String>();
        Set<String> setCaseZdPVHUserIds = new Set<String>();
        Id zdPVHRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdPVH').getRecordTypeId();
        Id zdTnCRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdTnC').getRecordTypeId();

        for(Case newCase : newCaseList) {
           if (newCase.ZdTnCTicketId__c != null ) {
               setCaseZdTnCUserIds.add(newCase.ZdTnCUserId__c) ;
               newCase.RecordTypeId = zdTnCRecordTypeId;
           }
           if (newCase.ZdPVHTicketId__c != null ) {
               setCaseZdPVHUserIds.add(newCase.ZdPVHUserId__c) ;
               newCase.RecordTypeId = zdPVHRecordTypeId;
           }
        }
        
        for (Contact c: [SELECT Id, AccountId, ZdTnCUserId__c, ZdPVHUserId__c
                         FROM Contact
                         WHERE ZdTnCUserId__c IN  :setCaseZdTnCUserIds OR ZdPVHUserId__c IN :setCaseZdPVHUserIds ])
        {
            if(c.ZdTnCUserId__c != null)   ZdTnCContactMap.put(c.ZdTnCUserId__c,c);
            if(c.ZdPVHUserId__c!=null)  ZdPVHContactMap.put(c.ZdPVHUserId__c,c);
        }

        
        for(Case newCase : newCaseList) {
            Contact con;
            if(newCase.ZdTnCUserId__c !=null && ZdTnCContactMap.containsKey(newCase.ZdTnCUserId__c)){
                con = ZdTnCContactMap.get(newCase.ZdTnCUserId__c);
            } else if(newCase.ZdPVHUserId__c !=null && ZdPVHContactMap.containsKey(newCase.ZdPVHUserId__c )!=null){
                con = ZdPVHContactMap.get(newCase.ZdPVHUserId__c);
            }
            if(con != null) {
                newCase.ContactId = con.id;
                newCase.AccountId = con.AccountId;
            }
        }
    }
    
    public static void sendSuccessEmails(List<case> listOfCases){
        
        system.debug(';calling me'+listOfCases);
        Map<String,Brand_Details_Mapping__mdt> mapOfBrandMappings = new Map<String,Brand_Details_Mapping__mdt>();
        
        List<Brand_Details_Mapping__mdt> listOfBrandMappings = [Select Id,Brand_Number__c,Success_Email_Template__c,Brand_Name__c,Email_Template__c,Ordwide_Email__c,Donot_sell_share_success_template__c from Brand_Details_Mapping__mdt];
        for(Brand_Details_Mapping__mdt eachMdt : listOfBrandMappings){
            mapOfBrandMappings.put(eachMdt.Brand_Number__c, eachMdt);
            
        }
        
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        for(Case cs : listOfCases)
        {
            system.debug('mapOfBrandMappings-'+mapOfBrandMappings);
            
            EmailTemplate templateId;
            if(cs.Sub_Type__c == 'Do Not Sell/Share'){
                system.debug('owdListkkk');
                templateId = [Select id from EmailTemplate where name =: mapOfBrandMappings.get(cs.brand__c).Donot_sell_share_success_template__c];
            }else{
                system.debug('owdListkkklll');
                templateId = [Select id from EmailTemplate where name =: mapOfBrandMappings.get(cs.brand__c).Success_Email_Template__c];
            }
            system.debug('temp id'+templateId);
            List<OrgwideEmailAddress> owdList = [Select Id,displayName from OrgwideEmailAddress where 
                                             displayName = :mapOfBrandMappings.get(cs.brand__c).Ordwide_Email__c];
            system.debug('owdList'+owdList);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateID(templateId.Id); 
            mail.setTargetObjectId(cs.contactId);
            mail.setSaveAsActivity(false);
            mail.orgwideemailaddressid = owdList[0].Id;
            mail.setWhatId(cs.Id);
            allmsg.add(mail);
        }
        system.debug('allmsg-'+allmsg);
        Messaging.sendEmail(allmsg,false);
        sentSuccessEmail = true;
    }
    
	@future
    public static void changeCaseOwnerQueueFuture(String casesString){
        changeCaseOwnerQueue(casesString);
    }
    
    
    public static void changeCaseOwnerQueue(String casesString){
        List<case> listOfCases = (List<case>) JSON.deserialize(casesString, List<case>.class);
        List<Group> listOfQueues = [Select Id, Name from group where name in ('Advertising Opt-Out Request','RTR Request')];
        Map<String,group> mapOfQueues = new Map<String,group>();
        for(Group eachGrp : listOfQueues){
            mapOfQueues.put(eachGrp.name, eachGrp);
        }
        for(Case eachCase : listOfCases){
            if(eachCase.Sub_Type__c == 'Do Not Sell/Share'){
                eachCase.OwnerId = mapOfQueues.get('Advertising Opt-Out Request').id;
            }else if(eachCase.Sub_Type__c == 'Rectify My Data'){
                eachCase.OwnerId = mapOfQueues.get('RTR Request').Id;
            }
            
        }
        update listOfCases;
    }

}