unpackaged/main/default/objects/Account/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <description>Set as external Id to get it indexed</description>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/get_accountIdTest.cls
/**
 * Created by venkatpenukonda on 2019-06-17.
 */

@IsTest
private class get_accountIdTest {
    @IsTest
    static void testBehavior() {

        List <Account> accountList = new List<Account>();
        Account a1Account = new Account( Name = 'test account1', Customer_Id__c = 'abc123');
        Account a2Account = new Account( Name = 'test account2', Customer_Id__c = 'abc124');
        Account a3Account = new Account( Name = 'test account2', Customer_Id__c = 'mnp789');

        accountList.add(a1Account);
        accountList.add(a2Account);
        accountList.add(a3Account);

        insert accountList;

        List <Contact> contactList = new List<Contact>();
        Contact c1a2 = new Contact(
                FirstName = 'f1',
                LastName = 'l1',
                Customer_Id__c = 'abc124',
            	Brand_Id__c = '1',
            	Source_System__c ='SFSC'
        );

        Contact c2a1 = new Contact(
                FirstName = 'f2',
                LastName = 'l2',
            	Brand_Id__c = '1',
                Customer_Id__c = 'abc123',
            	Source_System__c ='SFSC'
        );

        Contact c3 = new Contact(
                FirstName = 'f3',
                LastName = 'l3',
            	Brand_Id__c = '1',
                Customer_Id__c = 'xyz1234',
            	Source_System__c ='SFSC'
        );
        contactList.add(c1a2);
        contactList.add(c2a1);
        contactList.add(c3);

        Test.startTest();
            insert contactList;

            Id c1a2AccountId = [select accountId from Contact where id = :c1a2.id].AccountId;
            Id c2a1AccountId = [select accountId from Contact where id = :c2a1.id].AccountId;
            Id c3AccountId = [select accountId from Contact where id = :c3.id].AccountId;

          //  System.assertEquals(c1a2AccountId, a2Account.Id);
            //System.assertEquals(c2a1AccountId, a1Account.Id);
           // System.assertEquals(null, c3AccountId);
        Test.stopTest();



    }
}