unpackaged/main/default/objects/Account/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Code</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Country_ds__c.field-meta.xml
<CustomField>
    <fullName>Country_ds__c</fullName>
    <description>To Capture the country values for CK brand</description>
    <label>Country DS</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CreatedByMethod__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMethod__c</fullName>
    <label>Created By Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <description>Set as external Id to get it indexed</description>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOrigSource__c.field-meta.xml
<CustomField>
    <fullName>EmailOrigSource__c</fullName>
    <label>EmailOrigSource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>U</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Market_ds__c.field-meta.xml
<CustomField>
    <fullName>Market_ds__c</fullName>
    <label>Market DS</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Region_ds__c.field-meta.xml
<CustomField>
    <fullName>Region_ds__c</fullName>
    <label>Region DS</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SelfClaimedGender__c.field-meta.xml
<CustomField>
    <fullName>SelfClaimedGender__c</fullName>
    <label>SelfClaimedGender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>GN</fullName>
            </value>
            <value>
                <fullName>PNTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptInDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptInDate__c</fullName>
    <label>SMS Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/SubscriberDataSources__mdt.object-meta.xml
<CustomObject>
    <label>SubscriberDataSource</label>
    <pluralLabel>SubscriberDataSources</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/DataSource__c.field-meta.xml
<CustomField>
    <fullName>DataSource__c</fullName>
    <label>Data Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Source System</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Welcome Source</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Company_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CA</fullName>
        <label>CA - Calvin Klein Specialty</label>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <label>CC - Calvin Klein Canada</label>
    </customValue>
    <customValue>
        <fullName>CK</fullName>
        <label>CK - Calvin Klein Collection</label>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
        <label>CO - Calvin Klein Company US</label>
    </customValue>
    <customValue>
        <fullName>CX</fullName>
        <label>CX - Calvin Klein Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC - Izod CA</label>
    </customValue>
    <customValue>
        <fullName>IZ</fullName>
        <label>IZ - Izod US</label>
    </customValue>
    <customValue>
        <fullName>OS</fullName>
        <label>OS - Van Heusen US</label>
    </customValue>
    <customValue>
        <fullName>SX</fullName>
        <label>SX - Speedo Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>TC</fullName>
        <label>TC - Tommy Hilfiger Company/Outlets CA</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>TH - Tommy Hilfiger Full Price</label>
    </customValue>
    <customValue>
        <fullName>TI</fullName>
        <label>TI - Tommy Hilfiger Full Price CA</label>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
        <label>TO - Tommy Hilfiger Company/Outlets US</label>
    </customValue>
    <customValue>
        <fullName>TS</fullName>
        <label>TS - Tommy Hilfiger Specialty US</label>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
        <label>TX - Tommy Hilfiger Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>VC</fullName>
        <label>VC - Van Heusen CA</label>
    </customValue>
    <customValue>
        <fullName>VX</fullName>
        <label>VX - Heritage Ecommerce</label>
    </customValue>
    <description>Global Company Code list</description>
    <masterLabel>Company Code</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/InboundSignUp.cls
/**
*Json Request
* Inbound API:{"Count":"1","Subscribes":[{"BrandId":"2","SourceSystem":"wifi", "WelcomeSource":"02","Email":"onbou1@yopmail.com","EmailOptinFlag":"true","LoyaltyOptinFlag":"true","SMSOptIn":"false","FirstName":"Inboundwifi","LastName":"testCKUpdatedAgainAgain","address1":"123 Main Street","address2":"","City":"Albany","State":"NY","ZIP":"14810","MailingCountry":"US","Phonenumber":"5555555555","HomePhone":"2222222222","MobilePhone":"5083330304","BirthMonth":"9","BirthDay":"22","Birthyear":"2000","Gender":"M","Region":"US","Country":"US","Market":"New York","preferredLanguage":"English"}]}}
* RAF Payload:{"Count":"1","Subscribes":[{"BrandId":"1","SourceSystem":"Extole","WelcomeSource":"06","Email":"a1@yopmail.com","EmailOptinFlag":"true","LoyaltyOptinFlag":"true","SMSOptIn":"false","FirstName":"Extole1234", "LastName":"testth","address1":"123 Main Street","address2":"Costco","City":"Albany","State":"NY","ZIP":"14810","MailingCountry":"US","Phonenumber":"5555555555","HomePhone":"2222222222","MobilePhone":"5083330304","BirthMonth":"9","BirthDay":"22","Birthyear":"2000","Gender":"M","Region":"US","Country":"US","Market":"New York","preferredLanguage":"E"}]}
*  https://instance.salesforce.com/services/apexrest/subscribers/SignUps
*  POD1-79,POD1-14
**/

@RestResource(urlMapping='/subscribers/SignUps')
global without sharing class InboundSignUp {
    
    private static Id contactEmailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId(); 
    private static Map<String,String> mapSubbrandParentbrand = new Map<String,String>();    
    private static Map<Id,Contact> accIdsToContact = new Map<Id,Contact>();
    
    global class signupRequest{
        public string count;
        public List<Subscriber> Subscribes;        
    }
    
    global class Subscriber{
        public string brandId;
        public string sourceSystem;
        public string welcomeSource;
        public string email;
        public string emailOptinFlag;
        public string loyaltyOptinFlag;
       // public string smsOptIn;
        public string firstName;
        public string lastName;
     /* public string address1;
        public string address2;
        public string city;
        public string state;
        public string zip;
        public string phonenumber;
        public string homePhone;
        public string mobilePhone;
        public String birthDate;
        public string birthMonth;
        public string birthDay;
        public string birthyear;
        public string gender;*/
        public string Country;
        public string region;
        public string market;
        public string preferredLanguage;
    } 
    
    
    global class signupResponse{
        public List<Subscribes> Subscribes;
        public Integer count;
    }
    
    
    global class Subscribes{
        public Integer StatusCode;
        public String Code;
        public String Message;
        public String ContactId;
        public String LoyaltyId;
		//public String ExistingCustomer;
     }
    
  
    @HttpPost 
    global static signupResponse doSignUp(){
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response; 
        String requestData = req.requestBody.toString();
        List<Contact> insertParentBrandContacts = new List<Contact>();//insert parent brand contact
        List<Contact> insertSubBrandContacts = new List<Contact>();//insert sub brand contact
        Boolean createParent = false;
        List<Contact> searchedParentContactList = new List<Contact>();
        //Converting JSON Payload into Apex class
        signupRequest signupRequestPayload = (signupRequest)JSON.deserialize(requestData,signupRequest.class);
        signupRequest subReq = removeDuplicate(signupRequestPayload);
        Set<String> BrandIds = new Set<String>(); 
        Set<String> EmailAddresses = new Set<String>();
        String sourceSystem;
        List<Contact> brandEmailContacts = new List<Contact>();  
        List<Contact> brandLoyaltyContacts = new List<Contact>();  
        Map<String,Map<String,Contact>> BrandToEmailContactMap = new Map <String,Map<String,Contact>>(); //mapping brand+email to contact
        Map<string,Contact> loyaltyToContactMap = new Map<string,Contact>();
        signupResponse errorResponse = new signupResponse();
        String errorMessage = ' ';
        Boolean existingCont = false;
		Boolean newCont = false;
        List<ID> contactID = new List<ID>();
        List<Subscribes> subsList = new List<Subscribes>();
        List<Subscribes> subsListAll = new List<Subscribes>();
        List<Contact> profileUpdateContacts = new List <Contact>();
        List<Contact> newContacts = new List<Contact>();
        List<SignUpActivity> signUpActivityList = new List<SignUpActivity>(); 
        Boolean isError = false;
        
        for(Subscriber sub : signupRequestPayload.Subscribes) {
           //validating input paramerters which are required
            if(String.isEmpty(sub.brandId) || String.isEmpty(sub.email) || String.isEmpty(sub.sourceSystem) || String.isEmpty(sub.Country)||
               String.isBlank(sub.brandId) || String.isBlank(sub.email) || String.isBlank(sub.sourceSystem) || String.isBlank(sub.Country)){
                   isError = true;
                   break;
               }
            else {//storing brand id and email
                if(String.isNotEmpty(sub.BrandId)) BrandIds.add(sub.BrandId);
                if(String.isNotEmpty(sub.Email)) EmailAddresses.add(sub.Email);
                if(String.isNotEmpty(sub.sourceSystem)) sourceSystem = sub.sourceSystem;
            }
        }
        if (isError) {
            res.statusCode = 400;
            Subscribes sub = new Subscribes();
            sub.StatusCode = 400;
            sub.Code = 'INVALID_QUERY';
            sub.Message = 'FAILURE:Missing BrandId or EmailId or Source System or Country';
            subsList.add(sub);
            errorResponse.subscribes = subsList;
            errorResponse.count = subsList.size();
            return errorResponse;
        } 
        mapSubbrandParentbrand = getSubToParentBrandDetails();//fetching parent brand id linked to sub brand id
        if(!BrandIds.isEmpty() && !EmailAddresses.isEmpty()){
            brandEmailContacts = fetchExistingContact(BrandIds,EmailAddresses);//fetching existing contacts in system based on brand and email address
        }
        system.debug('brandEmailContacts:: '+brandEmailContacts);
        if(!brandEmailContacts.isEmpty()) { 
            existingCont = true;
            for(Contact con : brandEmailContacts){
                Map<String,Contact> emailToContactMap = new Map<String,Contact>();
                if(BrandToEmailContactMap.containsKey(con.Brand_Id__c)){
                    BrandToEmailContactMap.get(con.Brand_Id__c).put(con.Email,con);//assigning brandId to multiple contacts
                } 
                else{
                    emailToContactMap.put(con.Email,con);
                    BrandToEmailContactMap.put(con.Brand_Id__c,emailToContactMap);
                } 
            }
        }
        system.debug('BrandToEmailContactMap:: '+BrandToEmailContactMap);
        Map<String,LoyaltySettings__mdt> mapLoyaltySettings = new Map<String,LoyaltySettings__mdt>();
        mapLoyaltySettings = brandLoyaltySettings(BrandIds);//fetching loyalty settings based on brandId
        system.debug('mapLoyaltySettings:: '+mapLoyaltySettings);

        for(Subscriber sub : subReq.Subscribes) {
            Boolean emailOptedIn = false;
            Contact thisContact;
            if(BrandToEmailContactMap.containsKey(sub.BrandId) && BrandToEmailContactMap.get(sub.BrandId).containsKey(sub.Email.toLowerCase())) {
                thisContact = BrandToEmailContactMap.get(sub.BrandId).get(sub.Email.toLowerCase());//getting contact based on brandId
                if(thisContact != null && sub.sourceSystem !='EXTOLE'){
                    profileUpdateContacts.add(createOrUpdateContact(thisContact,sub,sub.BrandId,false));//updating contact as per payload
                }
            } 
            else if(mapLoyaltySettings.get(sub.BrandId)!=null){   //checking loyalty setting based on brandId                  
                LoyaltySettings__mdt loyaltySettingDetails = mapLoyaltySettings.get(sub.BrandId);
                if(String.isEmpty(loyaltySettingDetails.Parent_Brand__c)){//checking parent brand id empty or not based on loyalty settings 
                    Contact newParentContact = new Contact();   
                    //creating new contact as per payload
                    insertParentBrandContacts.add(createOrUpdateContact(newParentContact,sub,sub.BrandId,false));
                }
                    
            }         
        }
        
        List<contact> allContacts = new List<contact>(); 
        if(!profileUpdateContacts.isEmpty()) {
            //updating existing contact details as per payload
            Database.SaveResult[] srList = Database.update(profileUpdateContacts,false);
            for(Contact c : profileUpdateContacts){
                if(c.id != null) {
                    allContacts.add(c);
                    if(String.isNotBlank(c.AccountId)) {
                        accIdsToContact.put(c.AccountId, c);//storing accountid from contact
                    } 
                }
            }
            //error logs
            ContactUtility.createErrorLogRecords(srList,profileUpdateContacts[0].Latest_Source__c,'');
            
            List<Account> listAccountsToUpdate = getAccountsToUpdate();
            if(!listAccountsToUpdate.isEmpty()){
                Database.SaveResult[] srListAcc = Database.update(listAccountsToUpdate, false);//updating account based on contact linked account
                ContactUtility.createErrorLogRecords(srListAcc,profileUpdateContacts[0].Latest_Source__c,'');
            }
        }
        if(!insertParentBrandContacts.isEmpty()) {
            List<Database.SaveResult> srList = Database.insert(insertParentBrandContacts,false);//creating new contact as per payload
            for(integer i=0; i<insertParentBrandContacts.size(); i++){
                if(insertParentBrandContacts[i].LastName!=null){
                    allContacts.add(insertParentBrandContacts[i]); //adding all parent brand contact
                }
                ContactUtility.createErrorLogRecords(srList,insertParentBrandContacts[0].Latest_Source__c,'');//Error log creation
            }
        }
        signupResponse genRes = new signupResponse();
        
        List<Contact> conList = [Select id,LoyaltyId__c,Latest_Source__c,Brand_Id__c from Contact where id IN:allContacts];
		if(ConList.size()>0){
		newCont = true;
		}
		//contructing response payload
        if(newCont == true && existingCont == false){
        for(Contact con : conList){
            contactID.add(con.Id);
            
            Subscribes sub = new Subscribes();
            sub.StatusCode = 200;
            sub.Code = 'OK';
            sub.Message = 'Success';
            sub.ContactId = con.Id;
            sub.LoyaltyId = con.LoyaltyId__c;
           // sub.ExistingCustomer = String.valueOf(existingCont);
            subsList.add(sub);
            signUpActivityList.add(SignUpActivity.signupActivity(con.Id, con.Latest_Source__c,con.Brand_Id__c));
            
        }
        }
        if(existingCont == true){
            for(contact existCon : brandEmailContacts){
              /*  if(sourceSystem =='EXTOLE'){
                    Subscribes sub = new Subscribes();
                    sub.Code = 'OK';
                    sub.Message = 'Customer Existing in the System, You are not eligible for this program';
                    sub.ContactId = existCon.Id;
                    sub.LoyaltyId = existCon.LoyaltyId__c;
                    sub.ExistingCustomer = String.valueOf(existingCont);
                    subsList.add(sub);
                }else{*/
                    Subscribes sub = new Subscribes();
                	sub.StatusCode = 200;
                    sub.Code = ' OK';
                    sub.Message = 'Success: Customer Data Updated';
                    sub.ContactId = existCon.Id;
                    sub.LoyaltyId = existCon.LoyaltyId__c;
                   // sub.ExistingCustomer = String.valueOf(existingCont);
                    subsList.add(sub);
                    system.debug('subsList>>>>>>>>>>'+subsList);
                    signUpActivityList.add(SignUpActivity.signupActivity(existCon.Id, existCon.Latest_Source__c,existCon.Brand_Id__c));
               // }
            }	
        }
        
        
        //Response status
        genRes.count = subsList.size();
        res.statusCode = 200;
        genRes.subscribes = subsList;
        return genRes;
    }
    
    //Creating or updating contact details based on payload
    private static Contact createOrUpdateContact(Contact newCon,Subscriber sub,String brandId,Boolean createParent) {
        newCon.createdByMethod__c = 'API';
        newCon.RecordTypeId = contactEmailRecordTypeId;
        newCon.Status__c = 'ACTIVE';
        if (String.isNotBlank(brandId)) newCon.Brand_Id__c = brandId;
        if (String.isNotBlank(sub.FirstName)) newCon.FirstName = sub.FirstName; else newCon.FirstName = 'Unknown';
     	if(String.isNotBlank(sub.lastName)){ newCon.LastName = sub.lastName; }
        else if(String.isBlank(sub.lastName) || String.valueOf(sub.lastName) == '') newCon.LastName = 'Unknown';
      /*  if (String.isNotBlank(sub.address1) && String.isNotBlank(sub.address2)){
            newCon.MailingStreet = sub.address1 + '\n' + sub.address2;
        }else if(String.isNotBlank(sub.address1)){
            newCon.MailingStreet = sub.address1;
        }
        newCon.MailingCity = sub.City;
        newCon.MailingState = sub.State;
        newCon.MailingPostalCode = sub.ZIP;
        if (String.isNotBlank(sub.Country)) newCon.MailingCountry = sub.Country;
        newCon.Phone = sub.phonenumber;
        newCon.HomePhone = sub.HomePhone;
        newCon.MobilePhone = sub.MobilePhone;*/
         if (String.isNotBlank(sub.email)) newCon.Email = sub.email;
        newCon.WelcomeSource__c = sub.welcomeSource;
        if(sub.preferredLanguage == 'English'){
            newCon.Language__c = 'E';
        }else if(sub.preferredLanguage == 'French'){
            newCon.Language__c = 'F';  
        }else{
            newCon.Language__c =sub.preferredLanguage;
        }
        //Checking Birth Day, Month and Year from payload
      /*  if(String.isNotEmpty(sub.birthDay) && String.isNotEmpty(sub.birthMonth) && String.isNotEmpty(sub.birthYear) ){
            newCon.Birthdate = Date.newInstance(integer.valueOf(sub.birthYear),integer.valueOf(sub.birthMonth),integer.valueOf(sub.birthDay));
        } //Converting Birth Date from Payload to date format
        else if(String.isNotBlank(sub.BirthDate) && (newCon.Birthdate != UtilityClass.strYYYMMDDtoDate(sub.BirthDate))){
            newCon.Birthdate = UtilityClass.strYYYMMDDtoDate(sub.birthDate);
        }*/
        newCon.Market_ds__c = sub.market; 
        newCon.Region_ds__c = sub.region; 
        newCon.Country_ds__c = sub.Country;
        if(String.isBlank(newCon.Source_System__c)) {
            newCon.Source_System__c = sub.SourceSystem;
        }
        if(String.isNotBlank(sub.SourceSystem)) {
            newCon.Latest_Source__c = sub.SourceSystem;
        }
        String subLoyaltyOptinValue='N';
        if (String.isNotBlank(sub.LoyaltyOptinFlag) && Boolean.valueOf(sub.LoyaltyOptinFlag)) {
            subLoyaltyOptinValue = 'Y';
        }
        if(subLoyaltyOptinValue=='Y') {
            newCon.LoyaltyFlag__c = Boolean.valueOf(sub.LoyaltyOptinFlag); 
            newCon.Loyalty_Optin_Date__c = system.now();
        }
       /* if (String.isNotBlank(sub.smsOptIn) && Boolean.valueOf(sub.smsOptIn)) {
            newCon.SMSOptinStatus__c = 'Y';
            newCon.SMSOptInDate__c = System.now();
            if (String.isNotBlank(sub.MobilePhone)) newCon.SMSNumber__c = sub.MobilePhone;
            if (String.isNotBlank(sub.Country)) newCon.SMSLocale__c = sub.Country;
        }*/
        String subEmailOptinValue='N';
        if(String.isNotBlank(sub.EmailOptinFlag) && Boolean.valueOf(sub.EmailOptinFlag)) {
            subEmailOptinValue= 'Y';
        }
        
        //if(String.isNotBlank(sub.SourceSystem)) 
           // subEmailOptinValue= 'Y';
        if(subEmailOptinValue=='Y') {
            newCon.EmailOptInStatus__c = subEmailOptinValue;
			newCon.EmailOptInDate__c = System.now();
            newCon.HasOptedOutOfEmail = false;            
        } else if(subEmailOptinValue=='N'){
            newCon.EmailOptInStatus__c = 'N';
            newCon.EmailOptOutDate__c=system.now();
            newCon.HasOptedOutOfEmail=true;
        }
        if(string.isEmpty(newCon.Id)){
            if(createParent){
                newCon.EmailOptInStatus__c = 'N';
                newCon.EmailOptOutDate__c=system.now();
                newCon.EmailOptInDate__c=Null;
                newCon.HasOptedOutOfEmail=true;
            }
        }
        if(String.isNotBlank(sub.SourceSystem)){
            String searchBrand = sub.BrandId;
            if(mapSubbrandParentbrand.containsKey(sub.BrandId)){
                searchBrand = mapSubbrandParentbrand.get(sub.BrandId);
            }
            //Matching of Brand Details against SubscriberDataSources object
            List<SubscriberDataSources__mdt> listDataSource = [SELECT Brand__c, SourceSystem__c, 
                                                               WelcomeSource__c,DataSource__c
                                                               FROM SubscriberDataSources__mdt
                                                               WHERE Brand__c=:searchBrand AND
                                                               SourceSystem__c=:sub.SourceSystem];
            
            if (listDataSource.size()>0){
                newCon.EmailOrigSource__c = listDataSource[0].DataSource__c;
                newCon.Source__c = listDataSource[0].DataSource__c;
            }  
        }
        
      //  if(String.isNotBlank(sub.Gender) && (newCon.SelfClaimedGender__c != sub.Gender)) newCon.SelfClaimedGender__c = sub.Gender;
        return newCon;
    }
    
    /*
	* Name : removeDuplicate
	* Description: removing of duplicate data from payload
	*/ 
    public static signupRequest removeDuplicate(signupRequest inputRequest){
        Map<String,Subscriber> mapSubscriber = new Map<String,Subscriber>();
        List<Subscriber> listSubscriber = new List<Subscriber>();
        signupRequest subObject = new signupRequest();
        for(Subscriber inputSub : inputRequest.Subscribes){
            if(String.isNotBlank(inputSub.BrandId) && String.isNotBlank(inputSub.Email)){
                mapSubscriber.put(inputSub.BrandId+(inputSub.Email).toLowercase(),inputSub);
            }
            else if(String.isNotBlank(inputSub.BrandId) && String.isNotBlank(inputSub.email)){
                mapSubscriber.put(inputSub.BrandId+(inputSub.email).toLowercase(),inputSub);
            }
        }
        for(Subscriber subInput : mapSubscriber.values()){
            listSubscriber.add(subInput);
        }
        subObject.Count = String.valueOf(mapSubscriber.size());
        subObject.Subscribes = new List<Subscriber>();
        subObject.Subscribes.addAll(listSubscriber);
        return subObject;
    }
    
    /*
	* Name : getAccountsToUpdate
	* Description : Updating of gender on Account based on SelfClaimedGender
	*/ 
    public static List<Account> getAccountsToUpdate(){
        List<Account> listUpdAccounts = new List<Account>();
        List<Account> listAccounts = [Select Id, Gender__c from Account where Id IN:accIdsToContact.keySet()];
        for(Account acc : listAccounts){
            if(accIdsToContact.containsKey(acc.Id)){
                if(acc.Gender__c != accIdsToContact.get(acc.Id).SelfClaimedGender__c){
                    acc.Gender__c = accIdsToContact.get(acc.Id).SelfClaimedGender__c;
                    listUpdAccounts.add(acc);
                }
            }
        }
        return listUpdAccounts;
    }
    
    /* Name : fetchExistingContact
	* Description : fetching contact details based on brand Id and email address
	*/ 
    public static List<contact> fetchExistingContact(Set<String> brandIdSet,Set<String> emailAddressSet){
        List<Contact> existingContactList = new List<Contact>();
        existingContactList = [SELECT Id,AccountId,FirstName,MiddleName,LastName,MailingStreet,MailingCity, MailingState,MailingPostalCode,Company_Code__c,
                               Brand_Id__c,MailingCountry,Email,Phone,HomePhone,MobilePhone,Birthdate,HomeStore__c,LoyaltyID__c,External_Id__c,Customer_Id__c,
                               StoreOfCapture__c,Source_System__c,Ecomm_Connected__c,LoyaltyFlag__c,EmailOptInDate__c,EmailOptInStatus__c,Loyalty_Optin_Date__c, 
                               PVHCreatedDate__c,PrefCenterInterests__c,Source__c,SelfClaimedGender__c,Latest_Source__c
                               FROM Contact 
                               WHERE Brand_Id__c IN:brandIdSet AND Email IN:emailAddressSet
                               AND RecordTypeId=:contactEmailRecordTypeId order by Ecomm_Connected__c DESC, LastmodifiedDate DESC LIMIT 1];
       
        system.debug('existingContactList::::::::::::: '+existingContactList);
        return existingContactList;
    }
    
    /*
	* Name : getSubToParentBrandDetails
	* Description : matching sub brand to parent brand based on loyalty settings
	*/ 
    
    public static Map<String,String> getSubToParentBrandDetails(){
        Map<String,String> subToParentBrandMap = new Map<String,String>();
        List<LoyaltySettings__mdt> loyaltySettingsList = [SELECT Id,BrandId__c,Parent_Brand__c FROM LoyaltySettings__mdt];
        for(LoyaltySettings__mdt loyaltySettings : loyaltySettingsList){
            if(string.isNotEmpty(loyaltySettings.Parent_Brand__c)){
                subToParentBrandMap.put(loyaltySettings.BrandId__c,loyaltySettings.Parent_Brand__c);
            }
        }
        return subToParentBrandMap;
    }
    
    /*
	* Name : brandLoyaltySettings
	* Description : matching brandId to loyalty settings
	*/ 
    public static Map<String,LoyaltySettings__mdt> brandLoyaltySettings(Set<String> brandIdSet){
        Map<String,LoyaltySettings__mdt> loyaltySettingsMap = new Map<String,LoyaltySettings__mdt>();
        List<LoyaltySettings__mdt> loyaltySettingList = [SELECT Id,BrandId__c,IsLoyaltyApplicable__c,Parent_Brand__c 
                                                         FROM LoyaltySettings__mdt 
                                                         WHERE BrandId__c IN:brandIdSet AND BrandId__c!=''];
        system.debug('loyaltySettingList:: '+loyaltySettingList);
        if(!loyaltySettingList.isEmpty()){
            for(LoyaltySettings__mdt loyaltySettings: loyaltySettingList){
                loyaltySettingsMap.put(loyaltySettings.BrandId__c,loyaltySettings);
            }
        }
        return loyaltySettingsMap;
    }
}