unpackaged/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SMSSubscriberSignUpTest.cls
@isTest
public class SMSSubscriberSignUpTest {

	@testSetup
    static void dataSetup() {
        List<Contact> listTestContacts = new List<Contact>();
        Account accOne = new Account(Name = 'Testing', Gender__c='M');
        insert accOne;
        
        Contact conOne = new Contact(LastName='TestConOne', AccountId=accOne.Id,
                                     Brand_Id__c='1',SMSNumber__c='15555555550',Email='emailone@doamin.com');
        listTestContacts.add(conOne);
        
        Contact conTwo = new Contact(LastName='TestConTwo', AccountId=accOne.Id,
                                     Brand_Id__c='1',Email='emailtwo@doamin.com');
        listTestContacts.add(conTwo);
        
        Contact conThree = new Contact(LastName='TestConThree', AccountId=accOne.Id,
                                     Brand_Id__c='1',SMSNumber__c='15555555552');
        listTestContacts.add(conThree);
        
        Contact conFour = new Contact(LastName='TestConFour', AccountId=accOne.Id,
                                     Brand_Id__c='1',Email='emailfour@doamin.com');
        listTestContacts.add(conFour);
        
        Contact conFive = new Contact(LastName='TestConFive', AccountId=accOne.Id,
                                     Brand_Id__c='1',SMSNumber__c='15555555550',Email='emailfive@doamin.com');
        listTestContacts.add(conFive);
        /*
        Contact conSix = new Contact(LastName='TestConSix', AccountId=accOne.Id,
                                     Brand_Id__c='1',SMSNumber__c='15555555558',Email='emailsix@doamin.com');
       	listTestContacts.add(conSix);
        */
        insert listTestContacts;
        
    }
    
    @isTest
    public static void doSMSSignUp_missingParameters(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = ' ';
		requestObj.emailAddress = 'noemailone@domain.com';
		requestObj.smsNumber = '15555555551';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        System.assertEquals('MISSING_PARAMETERS', responseObj.code);
    }
    
    @isTest
    public static void doSMSSignUp_OptIn_1(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '1';
		requestObj.emailAddress = 'noemailone@domain.com';
		requestObj.smsNumber = '7878787878';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
    }
    
    @isTest
    public static void doSMSSignUp_OptIn_2(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '1';
		requestObj.emailAddress = 'emailtwo@doamin.com';
		requestObj.smsNumber = '7878787878';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
    }
    
    @isTest
    public static void doSMSSignUp_OptIn_3(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '1';
		requestObj.emailAddress = 'emailfive@doamin.com';
		requestObj.smsNumber = '15555555556';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
    }
    
    @isTest
    public static void doSMSSignUp_Re_OptIn_5(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '1';
		requestObj.emailAddress = 'noemailfour@doamin.com';
		requestObj.smsNumber = '15555555552';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
    }
    
    @isTest
    public static void doSMSSignUp_ReOptIn_1_2_3_4_5(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        SMSSubscriberSignUp.SMSRequest requestObj = new SMSSubscriberSignUp.SMSRequest();
        SMSSubscriberSignUp.SMSResponse responseObj = new SMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '1';
		requestObj.emailAddress = 'emailfour@doamin.com';
		requestObj.smsNumber = '15555555552';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/SMSSubscriber/SignUp';
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = SMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
    }
}