unpackaged/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/isEmployee__c.field-meta.xml
<CustomField>
    <fullName>isEmployee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Employee</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CountryOfCapture__c.field-meta.xml
<CustomField>
    <fullName>CountryOfCapture__c</fullName>
    <label>Country of Capture</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/isEmployee__c.field-meta.xml
<CustomField>
    <fullName>isEmployee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Employee</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <description>Captures the Keyword values from where the customer SMS opt In. Ex: TH004, Preference center , ChargeIt</description>
    <label>SMSKeyword</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/PrefCenterInterests__c.field-meta.xml
<CustomField>
    <fullName>PrefCenterInterests__c</fullName>
    <label>Email Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Company Stores</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Tommy.com</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Anchor / Specialty Stores</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mens</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Womens</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Kids (TH)</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Ecom Main Site</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Ecomm - New (TH)</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Loyalty</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retail Store</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>One Time</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Ecom Outlet</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>CK Collection</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>CK International</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kids (HE)</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Fitness</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Performance</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Active Recreation</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Adaptive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SelfClaimedGender__c.field-meta.xml
<CustomField>
    <fullName>SelfClaimedGender__c</fullName>
    <label>SelfClaimedGender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>GN</fullName>
            </value>
            <value>
                <fullName>PNTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMS_Unsubscribe_Reason__c.field-meta.xml
<CustomField>
    <fullName>SMS_Unsubscribe_Reason__c</fullName>
    <description>To capture the SMS unsubscribe reason once the customer opted out from SMS.</description>
    <label>SMS Unsubscribe Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptInDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptInDate__c</fullName>
    <label>SMS Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOutDate__c</fullName>
    <label>SMS Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/preferenceCenterKeyword__c.field-meta.xml
<CustomField>
    <fullName>preferenceCenterKeyword__c</fullName>
    <label>MCpreferenceCenterKeyword</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SubscriberProfileUpdates.cls
/******************************************************************************
* @Description: custom REST API to consume the preference center updates from eComm.
* @Date       : April 15, 2020
* @JIRA       : NASSC-1671
*
******************************************************************************/

@RestResource(urlMapping='/subscriber/profile')
global without sharing class SubscriberProfileUpdates {
    
    global class PCUpdateRequest{
        public String ContactId;
        public String isEmployee;
        public Name Name;
        public String Email;
        public MailingAddress MailingAddress;
        public String BirthDate;
        public String Phone;
        public SMS SMS;
        public String PrefCenterInterests;
        public String HomeStore;
        public String Gender;
        public String SourceSystem;
        
    }
    
    global class Name {
        public String FirstName;
        public String LastName;
    }
    
    global class MailingAddress {
        public String Street;
        public String City;
        public String State;
        public String Country;
        public String PostalCode;
    }
    
    global class SMS {
        public String SMSNumber ;
        public String SMSOptinStatus;
        //public String SMSOptinDate;
        public String Locale; 
    }
    
    global class PCUpdateResponse{
        public String code;
        public String message;
        public String contactId;
    }
    
    
    @HttpPost
    global static PCUpdateResponse doSignUp(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        PCUpdateResponse pcResponse = new PCUpdateResponse();
        Contact foundContact = new Contact();
        Contact foundSMSContact = new Contact();
        Contact brandAndEmailContact = new Contact();
        String requestData = req.requestBody.toString();
        PCUpdateRequest pcRequest = (PCUpdateRequest)json.deserialize(requestData, PCUpdateRequest.class);
        System.debug('** req: '+ pcRequest);
        
        //scenario: if ContactId missing in request parameter
        if(String.isBlank(pcRequest.ContactId)){
            res.statusCode = 400;
            pcResponse.code = 'MISSING_PARAMETERS';
            pcResponse.message = 'Missing: ContactId';
            return pcResponse;
        }
        
        else{
            System.debug('** '+ pcRequest.ContactId);
           // System.debug('** '+ pcRequest.SMS.SMSNumber);
            //System.debug('** '+ pcRequest.Name.FirstName);
            System.debug('** '+ pcRequest.MailingAddress.City);
            foundContact = searchContact(pcRequest.ContactId);
            foundSMSContact = searchSMSContact(pcRequest.SMS.SMSNumber);
          
            
            if(foundContact != null){
                brandAndEmailContact =  SFMCUtility.searchEmailBrandContact(foundContact.Brand_Id__c,pcRequest.Email);
            }
            
            
           
            if(foundContact == null){
                System.debug('***Error: Contact Not Found');
                res.statusCode = 400;
                pcResponse.code = 'INVALID_CONTACTID';
                pcResponse.message = 'No matching contact found';
                return pcResponse;
                
            }
            
            else if(brandAndEmailContact != null && (foundContact.Email != pcRequest.Email) && (foundContact.Id != brandAndEmailContact.Id)){
                System.debug('***Error: Another Contact Exists with Email');            
                res.statusCode = 400;
                pcResponse.code = 'INVALID_EMAIL';
                pcResponse.message = 'Supplied Email address used by another contact';
                return pcResponse;
            }
            
            else if(foundSMSContact != null && (foundContact.Id != foundSMSContact.Id)){
                System.debug('***Error: Another Contact Exists with SMSNumber');            
                res.statusCode = 400;
                pcResponse.code = 'INVALID_SMSNUMBER';
                pcResponse.message = 'SMS Number used by another contact';
                return pcResponse;
                
            }
           
            else if(foundContact != null && pcRequest.SMS.SMSNumber == null){
                
                System.debug(foundContact);
                Contact updatedConWithOutSMS= updateContacWithOutSMSNumber(foundContact,pcRequest);
                System.debug(updatedConWithOutSMS);
                Account updatedAcc = updateAccount(foundContact,pcRequest);
                Savepoint sp;
                try {
                    sp = Database.setSavepoint();
                    update updatedConWithOutSMS;
                    System.debug('***Contact Record Updated without SMS Number');  
                    update updatedAcc;
                    System.debug('***Account Record Updated'); 
                }
                catch (Exception e) {
                    System.debug('An exception occurred while updating Contact' + e.getMessage());
                    res.statusCode = 400;
                    pcResponse.code = 'OTHER_ERROR';
                    pcResponse.message = e.getMessage();
                    Database.RollBack(sp);
                    return pcResponse;
                }
                
                res.statusCode = 200;
                pcResponse.code = 'OK';
                pcResponse.contactId = updatedConWithOutSMS.Id;
                
            }            
            else {
                System.debug(foundContact);
                Contact updatedCon = updateContact(foundContact,pcRequest);
                System.debug(updatedCon);
                Account updatedAcc = updateAccount(foundContact,pcRequest);
                Savepoint sp;
                try {
                    sp = Database.setSavepoint();
                    update updatedCon;
                    System.debug('***Contact Record Updated');  
                    update updatedAcc;
                    System.debug('***Account Record Updated'); 
                }
                catch (Exception e) {
                    System.debug('An exception occurred while updating Contact' + e.getMessage());
                    res.statusCode = 400;
                    pcResponse.code = 'OTHER_ERROR';
                    pcResponse.message = e.getMessage();
                    Database.RollBack(sp);
                    return pcResponse;
                }
                
                res.statusCode = 200;
                pcResponse.code = 'OK';
                pcResponse.contactId = updatedCon.Id;
                pcResponse.message='Success';
                
            } 
            
        }
        return pcResponse;        
    }
    
    public static Contact searchContact(Id contactId){
        List<Contact> conList = [SELECT Id,FirstName,LastName,MailingStreet,MailingCity,MailingState,Brand_Id__c,Email,
                                 MailingCountry, MailingPostalCode, BirthDate, Phone, SMSNumber__c,SMSOptinStatus__c, SMSOptInDate__c,
                                 PrefCenterInterests__c, HomeStore__c,isEmployee__c,AccountId,SMSLocale__c,CountryOfCapture__c,SelfClaimedGender__c,
                                 Latest_Source__c,Source_System__c,Keyword__c 
                                 FROM Contact WHERE Id =: contactId];
        if (conList.size()>0) return conList[0];
        else return null;
        
    }
    
    public static Contact searchSMSContact(String inputSMSNumber){
        List<Contact> conList = [SELECT Id,FirstName,LastName,MailingStreet,MailingCity,MailingState,
                                 MailingCountry, MailingPostalCode, BirthDate, Phone, SMSNumber__c,SMSOptinStatus__c, SMSOptInDate__c,
                                 PrefCenterInterests__c, HomeStore__c,isEmployee__c,SMSLocale__c,CountryOfCapture__c,SelfClaimedGender__c,
                                 Latest_Source__c,Source_System__c,Keyword__c 
                                 FROM Contact 
                                 WHERE SMSNumber__c != null AND SMSNumber__c =: inputSMSNumber];
        
        if (conList.size()>0) return conList[0];
        else return null;
        
    }
    
    public static Contact updateContact(Contact con, PCUpdateRequest pcReq){
        System.debug('***inside updateContact');
        
        if(String.isNotBlank(pcReq.Name.FirstName) && (con.FirstName != pcReq.Name.FirstName)) con.FirstName = pcReq.Name.FirstName;
        if(String.isNotBlank(pcReq.Name.LastName) && (con.LastName != pcReq.Name.LastName)) con.LastName = pcReq.Name.LastName;
        if(String.isNotBlank(pcReq.Email) && (con.Email != pcReq.Email)) con.Email = pcReq.Email;
        if(String.isNotBlank(pcReq.MailingAddress.Street) && (con.MailingStreet != pcReq.MailingAddress.Street)) con.MailingStreet = pcReq.MailingAddress.Street;
        if(String.isNotBlank(pcReq.MailingAddress.City) && (con.MailingCity != pcReq.MailingAddress.City)) con.MailingCity = pcReq.MailingAddress.City;
        if(String.isNotBlank(pcReq.MailingAddress.State) && (con.MailingState != pcReq.MailingAddress.State)) con.MailingState = pcReq.MailingAddress.State;
        if(String.isNotBlank(pcReq.MailingAddress.Country) && (con.MailingCountry != pcReq.MailingAddress.Country)) con.MailingCountry = pcReq.MailingAddress.Country;
        if(String.isNotBlank(pcReq.MailingAddress.PostalCode) && (con.MailingPostalCode != pcReq.MailingAddress.PostalCode)) con.MailingPostalCode = pcReq.MailingAddress.PostalCode;
        if(String.isNotBlank(pcReq.BirthDate) && (con.Birthdate != Date.valueOf(pcReq.BirthDate))) con.Birthdate = Date.valueOf(pcReq.BirthDate);
        if(String.isNotBlank(pcReq.Phone) && (con.Phone != pcReq.Phone)) con.Phone = pcReq.Phone;
        if(String.isNotBlank(pcReq.SourceSystem) && (con.Latest_Source__c != pcReq.SourceSystem))
        {
            con.Latest_Source__c = pcReq.SourceSystem;
        }
        
        
       /*if(String.isBlank(pcReq.SourceSystem)){
             con.Latest_Source__c='eComm';
        }*/
       if(String.isNotBlank(pcReq.isEmployee) && Boolean.valueOf(pcReq.isEmployee) == true && (!pcReq.isEmployee.equals(con.isEmployee__c)))
           con.isEmployee__c = true;
       else if(String.isNotBlank(pcReq.isEmployee) && Boolean.valueOf(pcReq.isEmployee) == false && (!pcReq.isEmployee.equals(con.isEmployee__c)))
           con.isEmployee__c = false;
        //if(String.isNotBlank(pcReq.SourceSystem) && (con.Source_System__c != pcReq.SourceSystem)) con.Source_System__c = pcReq.SourceSystem;
        
     
        
       //Start: Setting SMS Related Fields
        if(String.isNotBlank(pcReq.SMS.SMSNumber) && pcReq.SMS.SMSOptinStatus == 'P' && String.isBlank(con.SMSNumber__c)){
            //brand new sms optin
            System.debug('***First Time Optin');
            con.SMSNumber__c = pcReq.SMS.SMSNumber;
            con.SMSOptinStatus__c = 'P';
            con.SMSOptInDate__c = System.now();
        }
        else if((pcReq.SMS.SMSOptinStatus == 'N') && (con.SMSOptinStatus__c == null || con.SMSOptinStatus__c == 'Y' || con.SMSOptinStatus__c == 'P')){
            // sms optout
            System.debug('***Optout');
            con.SMSOptinStatus__c = 'N';
            con.SMSOptOutDate__c = System.now();
            con.SMS_Unsubscribe_Reason__c='eComm Opt-out';
        }
        else if(String.isNotBlank(pcReq.SMS.SMSNumber) && pcReq.SMS.SMSOptinStatus == 'P' && String.isNotBlank(con.SMSNumber__c) && con.SMSNumber__c == pcReq.SMS.SMSNumber){
           //sms reoptin with same number
            System.debug('***Re-Optin with same number');
            con.SMSOptinStatus__c = 'P';
            con.SMSOptInDate__c = System.now();
        }
        else if(String.isNotBlank(pcReq.SMS.SMSNumber) && pcReq.SMS.SMSOptinStatus == 'P' && String.isNotBlank(con.SMSNumber__c) && con.SMSNumber__c != pcReq.SMS.SMSNumber){
            //sms optin with a different number
            System.debug('***Re-Optin with different number');
            con.SMSNumber__c = pcReq.SMS.SMSNumber;
            con.SMSOptinStatus__c = 'P';
            con.SMSOptInDate__c = System.now();
        }
        //End: Setting SMS Related Field
        
        if(String.isNotBlank(pcReq.SMS.Locale) && (con.SMSLocale__c != pcReq.SMS.Locale)) con.SMSLocale__c = pcReq.SMS.Locale;
        if(string.isNotBlank(pcReq.PrefCenterInterests) && (con.PrefCenterInterests__c != pcReq.PrefCenterInterests)) con.PrefCenterInterests__c = pcReq.PrefCenterInterests;
        if(String.isNotBlank(pcReq.HomeStore) && (con.HomeStore__c != pcReq.HomeStore)) con.HomeStore__c = pcReq.HomeStore;
        if(String.isNotBlank(pcReq.Gender) && (con.SelfClaimedGender__c != pcReq.Gender)) con.SelfClaimedGender__c = pcReq.Gender;
        
        //GCT-1571 TH - SMS Source to Match keyword opt in
           LoyaltySettings__mdt prefernceKey =[select BrandId__c,preferenceCenterKeyword__c from LoyaltySettings__mdt where BrandId__c='1' limit 1];
            if(prefernceKey!=Null){
                con.Keyword__c=prefernceKey.preferenceCenterKeyword__c;
            }
        
        if(String.isBlank(con.CountryOfCapture__c) && String.isNotBlank(pcReq.SMS.Locale)){
            if(pcReq.SMS.Locale.length() == 5) con.CountryOfCapture__c = pcReq.SMS.Locale.right(2).toUpperCase();
        }
        System.debug(con);
        return con;
    }
    /* NACDT-3788 AND BELT-1614 */
    public static Contact updateContacWithOutSMSNumber(Contact con, PCUpdateRequest pcReq){
        system.debug('***inside updateContactWithOutSMSNumber');
        if(String.isNotBlank(pcReq.Name.FirstName) && (con.FirstName != pcReq.Name.FirstName)) con.FirstName = pcReq.Name.FirstName;
        if(String.isNotBlank(pcReq.Name.LastName) && (con.LastName != pcReq.Name.LastName)) con.LastName = pcReq.Name.LastName;
        if(String.isNotBlank(pcReq.Email) && (con.Email != pcReq.Email)) con.Email = pcReq.Email;
        if(String.isNotBlank(pcReq.MailingAddress.Street) && (con.MailingStreet != pcReq.MailingAddress.Street)) con.MailingStreet = pcReq.MailingAddress.Street;
        if(String.isNotBlank(pcReq.MailingAddress.City) && (con.MailingCity != pcReq.MailingAddress.City)) con.MailingCity = pcReq.MailingAddress.City;
        if(String.isNotBlank(pcReq.MailingAddress.State) && (con.MailingState != pcReq.MailingAddress.State)) con.MailingState = pcReq.MailingAddress.State;
        if(String.isNotBlank(pcReq.MailingAddress.Country) && (con.MailingCountry != pcReq.MailingAddress.Country)) con.MailingCountry = pcReq.MailingAddress.Country;
        if(String.isNotBlank(pcReq.MailingAddress.PostalCode) && (con.MailingPostalCode != pcReq.MailingAddress.PostalCode)) con.MailingPostalCode = pcReq.MailingAddress.PostalCode;
        if(String.isNotBlank(pcReq.BirthDate) && (con.Birthdate != Date.valueOf(pcReq.BirthDate))) con.Birthdate = Date.valueOf(pcReq.BirthDate);
        if(String.isNotBlank(pcReq.Phone) && (con.Phone != pcReq.Phone)) con.Phone = pcReq.Phone; 
       
        if(String.isNotBlank(pcReq.SourceSystem) && (con.Latest_Source__c != pcReq.SourceSystem)) con.Latest_Source__c = pcReq.SourceSystem;
       /*  if(String.isNotBlank(pcReq.SourceSystem) && (con.Latest_Source__c != pcReq.SourceSystem))
        {
            con.Latest_Source__c = pcReq.SourceSystem;
        }
       if(String.isBlank(pcReq.SourceSystem)){
             con.Latest_Source__c='eComm';
        }*/
       
       if(String.isNotBlank(pcReq.isEmployee) && Boolean.valueOf(pcReq.isEmployee) == true)
           con.isEmployee__c = true;
       else if(String.isNotBlank(pcReq.isEmployee) && Boolean.valueOf(pcReq.isEmployee) == false)
           con.isEmployee__c = false;
        
        if((pcReq.SMS.SMSOptinStatus == 'N') && (con.SMSOptinStatus__c == null || con.SMSOptinStatus__c == 'Y' || con.SMSOptinStatus__c == 'P')){
            // sms optout
            System.debug('***Optout');
            con.SMSOptinStatus__c = 'N';
            con.SMSOptOutDate__c = System.now();
            con.SMS_Unsubscribe_Reason__c='eComm Opt-out';
        }
       /* NACDT-3828 */
        //End: Setting SMS Related Field
        if(String.isNotBlank(pcReq.SMS.Locale) && (con.SMSLocale__c != pcReq.SMS.Locale)) con.SMSLocale__c = pcReq.SMS.Locale;
        if(String.isNotBlank(pcReq.PrefCenterInterests) && (con.PrefCenterInterests__c != pcReq.PrefCenterInterests)) con.PrefCenterInterests__c = pcReq.PrefCenterInterests;
        if(String.isNotBlank(pcReq.HomeStore) && (con.HomeStore__c != pcReq.HomeStore)) con.HomeStore__c = pcReq.HomeStore;
        if(String.isNotBlank(pcReq.Gender) && (con.SelfClaimedGender__c != pcReq.Gender)) con.SelfClaimedGender__c = pcReq.Gender;
        
        //GCT-1571 TH - SMS Source to Match keyword opt in
        LoyaltySettings__mdt prefernceKey =[select BrandId__c,preferenceCenterKeyword__c from LoyaltySettings__mdt where BrandId__c='1' limit 1];
        if(prefernceKey!=Null){
           con.Keyword__c=prefernceKey.preferenceCenterKeyword__c;
          }
        
        if(String.isBlank(con.CountryOfCapture__c) && String.isNotBlank(pcReq.SMS.Locale)){
            if(pcReq.SMS.Locale.length() == 5) con.CountryOfCapture__c = pcReq.SMS.Locale.right(2).toUpperCase();
        }
        System.debug(con);
        return con;
     }
    
    public static Account updateAccount(Contact con, PCUpdateRequest pcReq){
        System.debug('***inside updateAccount');
        List<Account> listAccount = [Select Id,Gender__c,Name from Account where Id=: con.AccountId];
        if (listAccount.size() > 0){
            if(String.isNotBlank(pcReq.Gender) && (listAccount[0].Gender__c != pcReq.Gender)) listAccount[0].Gender__c = pcReq.Gender;
            if((String.isNotBlank(pcReq.Name.FirstName) && pcReq.Name.FirstName!='Unknown') && (String.isNotBlank(pcReq.Name.LastName) && pcReq.Name.LastName!='Unknown' )){
                listAccount[0].Name=pcReq.Name.FirstName+pcReq.Name.LastName;
            }
        }
        
        return listAccount[0];
    }
    
}