unpackaged/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Female</label>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CKSMSSubscriberSignUpTest.cls
@isTest
public class CKSMSSubscriberSignUpTest {

	@testSetup
    static void dataSetup() {
        List<Contact> listTestContacts = new List<Contact>();
        Account accOne = new Account(Name = 'Testing', Gender__c='M');
        insert accOne;
        
        Contact conOne = new Contact(LastName='TestConOne', AccountId=accOne.Id,
                                     Brand_Id__c='2',SMSNumber__c='15555555550',Email='emailone@doamin.com',SMSOptinStatus__c='Y',SMSLocale__c='en_US');
        listTestContacts.add(conOne);
        
        Contact conTwo = new Contact(LastName='TestConTwo', AccountId=accOne.Id,
                                     Brand_Id__c='2',Email='emailtwo@doamin.com',SMSNumber__c='');
        listTestContacts.add(conTwo);
        
        Contact conThree = new Contact(LastName='TestConThree', AccountId=accOne.Id,
                                     Brand_Id__c='2',SMSNumber__c='15555555552',Email='');
        listTestContacts.add(conThree);
        
        Contact conFour = new Contact(LastName='TestConFour', AccountId=accOne.Id,
                                     Brand_Id__c='2',Email='emailfour@doamin.com',SMSNumber__c='15555555551');
        listTestContacts.add(conFour);
        
        Contact conFive = new Contact(LastName='TestConFive', AccountId=accOne.Id,
                                     Brand_Id__c='2',SMSNumber__c='',Email='');
        listTestContacts.add(conFive);
        Contact conSix = new Contact(LastName='TestConSix', AccountId=accOne.Id,
                                     Brand_Id__c='2',Email='emailsix@doamin.com',SMSNumber__c='15545455550');
        listTestContacts.add(conSix);
        Contact conSeven = new Contact(LastName='TestConSeven', AccountId=accOne.Id,
                                     Brand_Id__c='2',Email='',SMSNumber__c='15545555550');
        listTestContacts.add(conSeven);
        /*
        Contact conSix = new Contact(LastName='TestConSix', AccountId=accOne.Id,
                                     Brand_Id__c='1',SMSNumber__c='15555555558',Email='emailsix@doamin.com');
       	listTestContacts.add(conSix);
        */
        insert listTestContacts;
        
    }
    @isTest
    public static void doSMSSignUp_missingParameters(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = ' ';
		requestObj.emailAddress = 'noemailone@domain.com';
		requestObj.smsNumber = '15555555551';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        System.assertEquals('MISSING_PARAMETERS', responseObj.code);
    }
    @isTest
    public static void doSMSSignUp_missingParameters1(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '2';
		requestObj.emailAddress = '';
		requestObj.smsNumber = '15555555551';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'en_US';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        System.assertEquals('MISSING_PARAMETERS', responseObj.code);
    }
     @isTest
    public static void doSMSSignUp_ExactSMSEmailMatch(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '2';
		requestObj.emailAddress = 'emailone@doamin.com';
		requestObj.smsNumber = '15555555550';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'es_MX';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        
    }
   @isTest
    public static void doSMSSignUp_SMSMatchNoEmailMatch(){
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '2';
		requestObj.emailAddress = 'emailone123@doamin.com';
		requestObj.smsNumber = '15555555550';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'es_MX';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        
    }
    @isTest
    public static void doSMSSignUp_SMSMatchInvalidEmailMatch(){
          List<Contact> updatedlistTestContacts = new List<Contact>();
        Account acctwo = new Account(Name = 'Testing', Gender__c='M');
        insert accTwo;
        
        Contact conEight = new Contact(LastName='TestConEight', AccountId=accTwo.Id,
                                     Brand_Id__c='2',SMSNumber__c='15555555557',Email='',SMSOptinStatus__c='Y');
        updatedlistTestContacts.add(conEight);
        Contact connine= new Contact(LastName='TestConnine', AccountId=accTwo.Id,
                                     Brand_Id__c='2',SMSNumber__c='',Email='emailtest9@doamin.com',SMSOptinStatus__c='Y');
        updatedlistTestContacts.add(connine);
        insert updatedlistTestContacts;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '2';
		requestObj.emailAddress = 'emailtest9@doamin.com';
		requestObj.smsNumber = '15555555557';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'es_MX';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        
    }
    @isTest
    public static void doSMSSignUp_EmailMatch(){
          List<Contact> updatedlistTestContacts = new List<Contact>();
        Account acc3 = new Account(Name = 'Testing', Gender__c='M');
        insert acc3;
        
        Contact con10= new Contact(LastName='TestCon10', AccountId=acc3.Id,
                                     Brand_Id__c='2',SMSNumber__c='15557655557',Email='emailtest10@doamin.com',SMSOptinStatus__c='Y',LoyaltyFlag__c=False);
        updatedlistTestContacts.add(con10);
        insert updatedlistTestContacts;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
    
        RestContext.request = req;
        RestContext.response= res;
        CKSMSSubscriberSignUp.SMSRequest requestObj = new CKSMSSubscriberSignUp.SMSRequest();
        CKSMSSubscriberSignUp.SMSResponse responseObj = new CKSMSSubscriberSignUp.SMSResponse();
        requestObj.brandId = '2';
		requestObj.emailAddress = 'emailtest10@doamin.com';
		requestObj.smsNumber = '15557555557';
		requestObj.loyaltyOptin = true;
		requestObj.storeOfCapture = 'CK801';
        requestObj.locale = 'es_MX';
        //newCon.SMSLocale__c  =smsRequest.locale;
      	String JSONRequest = JSON.serialize(requestObj);  
     	req.requestURI = '/CKSMSSubscriber/SignUp';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSONRequest);
        responseObj = CKSMSSubscriberSignUp.doSMSSignUp();
        System.debug('***Got Response = '+responseObj);
        System.debug('***RES = '+res);
        
    }
    
}