unpackaged/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/Brand_Details_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Brand Details Mapping</label>
    <pluralLabel>Brand Details Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Brand_form_link__c.field-meta.xml
<CustomField>
    <fullName>Brand_form_link__c</fullName>
    <label>Brand form link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Brand_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Number__c</fullName>
    <label>Brand Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Ordwide_Email__c.field-meta.xml
<CustomField>
    <fullName>Ordwide_Email__c</fullName>
    <label>Ordwide Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/PDR_Link__c.field-meta.xml
<CustomField>
    <fullName>PDR_Link__c</fullName>
    <label>PDR Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Perfect_Match_Found__c.field-meta.xml
<CustomField>
    <fullName>Perfect_Match_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether a Perfect Match was found for the privacy request</description>
    <label>Perfect Match Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_User_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Privacy_User_Confirmed_Date__c</fullName>
    <description>The date that the user confirmed their privacy request</description>
    <label>Privacy User Confirmed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/R2R_Email_UserConfirmation__c.field-meta.xml
<CustomField>
    <fullName>R2R_Email_UserConfirmation__c</fullName>
    <label>Email User Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rectified_JSON_Data__c.field-meta.xml
<CustomField>
    <fullName>Rectified_JSON_Data__c</fullName>
    <label>Rectified JSON Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Rejected Request</fullName>
            </value>
            <value>
                <fullName>No Response to follow-up</fullName>
            </value>
            <value>
                <fullName>Data Not Found</fullName>
            </value>
            <value>
                <fullName>User Data Provided</fullName>
            </value>
            <value>
                <fullName>User Data Deleted</fullName>
            </value>
            <value>
                <fullName>User Data Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/VerificationHash__c.field-meta.xml
<CustomField>
    <fullName>VerificationHash__c</fullName>
    <defaultValue>&#39;1234&#39;</defaultValue>
    <description>Used by clickable email responses to validate the authenticity of the response.</description>
    <label>VerificationHash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Advertising_Opt_out__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Opt_out__c</fullName>
    <description>GCT-772 :This field is marked True indicating the customers opt-out in Do Not Sell/Share</description>
    <label>Advertising Opt-out</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Advertising_Opt_out_Date__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Opt_out_Date__c</fullName>
    <description>GCT-772 :This field is marked with Date indicating the customers opt-out in Do Not Sell/Share</description>
    <label>Advertising Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_UserName__c.field-meta.xml
<CustomField>
    <fullName>B2C_UserName__c</fullName>
    <description>... represents the B2C Commerce customer profile username mapped to a given Service Cloud Contact.</description>
    <inlineHelpText>... represents the B2C Commerce customer profile username mapped to a given Service Cloud Contact.</inlineHelpText>
    <label>B2C UserName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_Address_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_Reason_Code__c</fullName>
    <label>Email Address Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Verification Success : Email Update</fullName>
            </value>
            <value>
                <fullName>Verification Success : Unable to Update in SC</fullName>
            </value>
            <value>
                <fullName>Verification Declined : No Email Update</fullName>
            </value>
            <value>
                <fullName>Verification Failure : No Customer&#39;s response</fullName>
            </value>
            <value>
                <fullName>Verfication Success: login email is already in use</fullName>
            </value>
            <value>
                <fullName>Verification Success : R2R update</fullName>
            </value>
            <value>
                <fullName>Verification Declined: No personal data update</fullName>
            </value>
            <value>
                <fullName>Verification Failure: No customer response</fullName>
            </value>
            <value>
                <fullName>Verification Success: Do Not Sell/ Share Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined: No Advertising Opt Out</fullName>
            </value>
            <value>
                <fullName>Tealium Request: Advertise OptIn</fullName>
            </value>
            <value>
                <fullName>Tealium Request: Advertise OptOut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/OptOutShare__c.field-meta.xml
<CustomField>
    <fullName>OptOutShare__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When opt_out_share = 0
 - opt_out_share = N

When opt_out_share = 1
 - opt_out_share =  Y</description>
    <label>OptOutShare</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SelfClaimedGender__c.field-meta.xml
<CustomField>
    <fullName>SelfClaimedGender__c</fullName>
    <label>SelfClaimedGender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>GN</fullName>
            </value>
            <value>
                <fullName>PNTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/Privacy_Intervals__c/Privacy_Intervals__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Intervals to send privacy emails in hours</description>
    <label>Privacy Intervals</label>
</CustomObject>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/MaxAfterConfirm__c.field-meta.xml
<CustomField>
    <fullName>MaxAfterConfirm__c</fullName>
    <description>The maximum number of hours that a privacy case can be open before resolution</description>
    <label>MaxAfterConfirm</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/R2RProcessResponseAPI.cls
/* Description : This class is for Right to Rectify and Do Not Sell/Share Customer Response*/

@RestResource(urlMapping='/public/v1/r2rProcesss/*')
global without sharing class R2RProcessResponseAPI {
    @HttpGet
    global static void restGet() {
        RestRequest req = RestContext.request;
        System.debug('The request params are ' + req.params);
        Account acc= new Account();
        String respMessage = 'Your response was not successfully processed. Please email customer support.';
        RestResponse resp = RestContext.response;
        
        Privacy_Intervals__c pi = Privacy_Intervals__c.getValues('PrivacyIntervalSetting');
        
        DateTime dueDate = system.now() + pi.MaxAfterConfirm__c/24;
		Map<String,String> mapOfBrands = new Map<String,String>();
		Schema.DescribeFieldResult fieldResult = Case.Brand__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			mapOfBrands.put(pickListVal.getValue(),pickListVal.getLabel());
		}     
		
        Map<String,Brand_Details_Mapping__mdt> mapOfBrandMappings = new Map<String,Brand_Details_Mapping__mdt>();
        
        List<Brand_Details_Mapping__mdt> listOfBrandMappings = [Select Id,Brand_Number__c,Brand_Name__c,PDR_Link__c,Email_Template__c,Ordwide_Email__c,Brand_form_link__c from Brand_Details_Mapping__mdt];
        for(Brand_Details_Mapping__mdt eachMdt : listOfBrandMappings){
            mapOfBrandMappings.put(eachMdt.Brand_Number__c, eachMdt);
            
        }
        
        Case cs = [SELECT Id,Rectified_JSON_Data__c,ContactId,R2R_Email_UserConfirmation__c,Privacy_User_Confirmed_Date__c,Sub_Type__c,
                   Resolution_Code__c,Status,VerificationHash__c,accountId,contact.firstName, contact.lastName,contact.Email_Address_Reason_Code__c,createddate,brand__c
                   FROM Case 
                   WHERE Id=:req.params.get('in_caseid')];
        cs.Due_Date__c = dueDate;
        acc.Id = cs.AccountId;
        String htmlBody = '<a href='+ mapOfBrandMappings.get(cs.brand__c).PDR_Link__c +'> Personal Data Request Form</a>';
		Boolean expired=false;
        if((((system.now().getTime())/1000/60/60) - ((cs.createdDate.getTime())/1000/60/60) > 24)||(cs.Status == 'Resolved' && cs.Resolution_Code__c =='No Response')){
            respMessage = 'This link is expired. If you\'d like to submit a new request please fill out a new'+htmlBody+'.';
            expired=true;
        }
        else if (cs.R2R_Email_UserConfirmation__c =='Started'){
          Group rtrQueue = [Select Id, Name from group where name = 'RTR Request' limit 1];
           system.debug('rtrQueue - '+rtrQueue);
           if (req.params.get('in_response') == 'Open' && req.params.get('in_verificationCode') == cs.VerificationHash__c) {
                cs.Privacy_User_Confirmed_Date__c = System.now();
                cs.Resolution_Code__c = 'User Data Provided';
                cs.R2R_Email_UserConfirmation__c = 'Confirmed'; 
                cs.Perfect_Match_Found__c = true;
                cs.Status = 'On Hold';
                if(rtrQueue != null){
                   cs.OwnerId = rtrQueue.Id;
                }
                update cs; 
               
               Contact con = new Contact();
               con.Id = cs.ContactId;
               //added as part of GCT-772
               if(cs.Sub_Type__c == Constants.doNotSellorShare){
                   if(cs.contact.Email_Address_Reason_Code__c == 'Tealium Request: Advertise OptOut'){
                   con.Advertising_Opt_out__c = 'Y';
                   con.Advertising_Opt_out_Date__c = System.Now();
                   con.OptOutShare__c = true;
                   con.Email_Address_Reason_Code__c = 'Tealium Request: Advertise OptOut';
                   }
                   else {
                   con.Advertising_Opt_out__c = 'Y';
                   con.Advertising_Opt_out_Date__c = System.Now();
                   con.OptOutShare__c = true;
                   con.Email_Address_Reason_Code__c = 'Verification Success: Do Not Sell/Share approved';
                       
                   }
                   
               }else{
               
               con.Email_Address_Reason_Code__c = 'Verification Success : R2R update';
                    
               if(string.isNotEmpty(cs.Rectified_JSON_Data__c)){
                    system.debug('cs.Rectified_JSON_Data__c***'+cs.Rectified_JSON_Data__c); 
                     system.debug('con.SelfClaimedGender__c***'+ con.SelfClaimedGender__c); 
                   
                    Map<String,Object> rectifiedJSONDataMap = (Map<String,Object>)JSON.deserializeUntyped(cs.Rectified_JSON_Data__c);
                    if(rectifiedJSONDataMap.get('newEmail')!=null && rectifiedJSONDataMap.get('newEmail') != ''){
                        con.Email = string.valueOf(rectifiedJSONDataMap.get('newEmail'));
                        con.B2C_UserName__c = string.valueOf(rectifiedJSONDataMap.get('newEmail'));
                    }
                    if(rectifiedJSONDataMap.get('newFirstName')!=null && rectifiedJSONDataMap.get('newFirstName') != ''){
                        con.FirstName = string.valueOf(rectifiedJSONDataMap.get('newFirstName'));
                        acc.name = con.FirstName +' '+ cs.contact.lastName;
                        acc.FirstName__c = con.FirstName;
                    }
                    if(rectifiedJSONDataMap.get('newLastName')!=null && rectifiedJSONDataMap.get('newLastName') != ''){
                        con.LastName = string.valueOf(rectifiedJSONDataMap.get('newLastName'));
                        if(acc.name != null && acc.name != ''){
                            acc.name = con.FirstName + ' ' + con.LastName;
                        }else{
                            acc.name = cs.contact.firstName +' '+ con.LastName;                     
                        }
                        acc.LastName__c = con.LastName;
                    }
                    if(rectifiedJSONDataMap.get('newAddress')!=null && rectifiedJSONDataMap.get('newAddress') != ''){
                        con.MailingStreet = string.valueOf(rectifiedJSONDataMap.get('newAddress'));
                    }
                    
                    if(rectifiedJSONDataMap.get('newUnit')!=null && rectifiedJSONDataMap.get('newUnit') != ''){
                        if(con.MailingStreet != null)
                        	con.MailingStreet = con.MailingStreet + ', '+string.valueOf(rectifiedJSONDataMap.get('newUnit'));
                        else
                            con.MailingStreet = string.valueOf(rectifiedJSONDataMap.get('newUnit'));
                    }
                    
                    if(rectifiedJSONDataMap.get('newCountry')!=null && rectifiedJSONDataMap.get('newCountry') != ''){
                        con.MailingCountry = string.valueOf(rectifiedJSONDataMap.get('newCountry'));
                    }
                    if(rectifiedJSONDataMap.get('newCity')!=null && rectifiedJSONDataMap.get('newCity') != ''){
                        con.MailingCity = string.valueOf(rectifiedJSONDataMap.get('newCity'));
                    }
                    if(rectifiedJSONDataMap.get('newState')!=null && rectifiedJSONDataMap.get('newState') != ''){
                        con.MailingState = string.valueOf(rectifiedJSONDataMap.get('newState'));
                    }
                    if(rectifiedJSONDataMap.get('newZipCode')!=null && rectifiedJSONDataMap.get('newZipCode') != ''){
                        con.MailingPostalCode = string.valueOf(rectifiedJSONDataMap.get('newZipCode'));
                    }
                    if(rectifiedJSONDataMap.get('newPhone')!=null && rectifiedJSONDataMap.get('newPhone') != ''){
                        con.Phone = string.valueOf(rectifiedJSONDataMap.get('newPhone'));
                    }
                    if(rectifiedJSONDataMap.get('newGender')!=null && rectifiedJSONDataMap.get('newGender') != ''){
                       // if(string.valueOf(rectifiedJSONDataMap.get('newGender'))!='-- Select Option --'){
                       // JIRA GCT-1848, GCT-6775  
                       if(string.valueOf(rectifiedJSONDataMap.get('newGender'))!='--- Select Option ---'){
                        system.debug('rectifiedJSONDataMap.get(newGender)***'+(string.valueOf(rectifiedJSONDataMap.get('newGender'))));    
                        Map<String,String> mapOfGender = new Map<String,String>();
                            mapOfGender.put('Man','M');
                            mapOfGender.put('Woman','F');
                           //JIRA GCT-7509  
                            mapOfGender.put('Gender Diverse','GN');
                            mapOfGender.put('Prefer not to say','PNTS');
                        con.SelfClaimedGender__c = mapOfGender.get(string.valueOf(rectifiedJSONDataMap.get('newGender')));
                        }
                    } 
                     if(rectifiedJSONDataMap.get('newDate')!=null && rectifiedJSONDataMap.get('newDate') != '' && rectifiedJSONDataMap.get('newDate')!='--- Select Option ---'
                       && rectifiedJSONDataMap.get('newMonth')!=null && rectifiedJSONDataMap.get('newMonth') != '' && rectifiedJSONDataMap.get('newMonth')!='--- Select Option ---'){
                           con.birthdate = Date.newInstance(1900, integer.valueOf(rectifiedJSONDataMap.get('newMonth')), integer.valueOf(rectifiedJSONDataMap.get('newDate')));
                       }
                }
               }
                req.params.put('in_caseid', cs.ContactId);
                req.params.put('updateContact', JSON.serialize(con));
                Flow.Interview.Call_Email_service_when_case_updated flow1 = new Flow.Interview.Call_Email_service_when_case_updated(req.params);
            	flow1.start();
                update acc;
               	System.debug('+++++ createChildDataOwnerCases check');
                System.debug('email address reason code ' + con.Email_Address_Reason_Code__c);
                if(con.Email_Address_Reason_Code__c == 'Verification Success : R2R update' ||con.Email_Address_Reason_Code__c == 'Verification Success: Do Not Sell/Share approved' || con.Email_Address_Reason_Code__c == 'Tealium Request: Advertise OptOut'){//added as part of GCT-772
                System.debug('+++++ inside createChildDataOwnerCases check' + con.Email_Address_Reason_Code__c);
                    ChildPrivacyCaseActionsHandler.createChildDataOwnerCases(cs.Id);
                }
                respMessage = 'Your response was successfully processed. Click here to close the window';
            }
            else if (req.params.get('in_response') == 'Resolved' && req.params.get('in_verificationCode') == cs.VerificationHash__c) {
                system.debug('inside resolved condition>>>>>');
                cs.Privacy_User_Confirmed_Date__c = System.now();
                cs.Resolution_Code__c = 'Rejected Request';
                cs.R2R_Email_UserConfirmation__c = 'Rejected'; 
                cs.Status = 'Resolved';
                if(rtrQueue != null){
                   cs.OwnerId = rtrQueue.Id;
                }
                update cs;
                /*Flow.Interview.Call_Email_service_when_case_updated flow1 = new Flow.Interview.Call_Email_service_when_case_updated(req.params);
            	flow1.start();*/
                
                Contact con = new Contact();
                con.Id = cs.ContactId;
                if(cs.Sub_Type__c == Constants.rectifyRequestSubType){
                    con.Email_Address_Reason_Code__c = 'Verification Declined: No personal data update';
                }else if(cs.Sub_Type__c == Constants.doNotSellorShare){//added as part of GCT-772
                    con.Email_Address_Reason_Code__c = 'Verification Declined: No Advertising Opt Out';
                }
                system.debug('con--'+cs.ContactId);
                req.params.put('in_caseid', cs.ContactId);
                update con;
                update acc;
                
                req.params.put('updateContact', JSON.serialize(con));
                Flow.Interview.Call_Email_service_when_case_updated flow1 = new Flow.Interview.Call_Email_service_when_case_updated(req.params);
            	flow1.start();
                
                respMessage = 'Thank you for your response. Please note that no changes have been made to your account.';
                
            }
        }else{
            respMessage ='We are sorry, but a response was previously recorded in our system.';
        }
        String response;
        if(expired){
            response =  '<html><head><title>PVH Privacy Request Processing</title><script type="text/javascript">' +
            '    function closeCurrentTab(){ ' +
            '		var conf=confirm("Are you sure, you want to close this tab?"); ' +
            '		if(conf==true){ ' +
            '			close(); ' +
            '		} ' +
            '	} ' +
            '</script> ' +
            '</head><body style="text-align: center;">' +
            '<p>' + respMessage +  '</body></html>' ;
        }else{
            response =  '<html><head><title>PVH Privacy Request Processing</title><script type="text/javascript">' +
            '    function closeCurrentTab(){ ' +
            '		var conf=confirm("Are you sure, you want to close this tab?"); ' +
            '		if(conf==true){ ' +
            '			close(); ' +
            '		} ' +
            '	} ' +
            '</script> ' +
            '</head><body style="text-align: center;">' +
            '<p><input type="button" value="' + respMessage + '" onclick="window.close()"' + '</body></html>' ;
        }
        resp.responseBody = Blob.valueOf(response);
        resp.headers.put('Content-Type', 'text/html; charset=utf-8');
    }   
}