unpackaged/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CalvinKlein.us</fullName>
                <label>Online - CalvinKlein.com</label>
            </value>
            <value>
                <fullName>Calvin Klein Retail</fullName>
                <label>Calvin Klein Store</label>
            </value>
            <value>
                <fullName>Tommy.com</fullName>
                <label>Online - Tommy.com</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger Retail</fullName>
                <label>Tommy Hilfiger Store</label>
            </value>
            <value>
                <fullName>SpeedoUSA.com</fullName>
                <label>Online - speedo.com</label>
            </value>
            <value>
                <fullName>VanHeusen.com</fullName>
                <label>Online - vanheusen.com</label>
            </value>
            <value>
                <fullName>Izod.com</fullName>
                <label>Online - Izod.com</label>
            </value>
            <value>
                <fullName>styleBureau.com</fullName>
                <label>Online - styleBureau.com</label>
            </value>
            <value>
                <fullName>trueandco.com</fullName>
                <label>Online -True&amp;co.com</label>
            </value>
            <value>
                <fullName>CalvinKlein.ca</fullName>
                <label>Online-CalvinKlein Canada</label>
            </value>
            <value>
                <fullName>Speedo.com</fullName>
            </value>
            <value>
                <fullName>Warner.com</fullName>
                <label>Online-Warner&#39;s</label>
            </value>
            <value>
                <fullName>Van Heusen | IZOD Company Store</fullName>
            </value>
            <value>
                <fullName>Amazon.com</fullName>
            </value>
            <value>
                <fullName>Nordstrom</fullName>
            </value>
            <value>
                <fullName>Other Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_First_Name__c</fullName>
    <description>Supplied First Name</description>
    <label>Supplied First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Code</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StorePreference__c.field-meta.xml
<CustomField>
    <fullName>StorePreference__c</fullName>
    <description>Preferred store</description>
    <label>Store Preference</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/IsLoyaltyApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsLoyaltyApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this brand is part of Loyalty program or not.</description>
    <label>IsLoyaltyApplicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Company_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CA</fullName>
        <label>CA - Calvin Klein Specialty</label>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <label>CC - Calvin Klein Canada</label>
    </customValue>
    <customValue>
        <fullName>CK</fullName>
        <label>CK - Calvin Klein Collection</label>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
        <label>CO - Calvin Klein Company US</label>
    </customValue>
    <customValue>
        <fullName>CX</fullName>
        <label>CX - Calvin Klein Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC - Izod CA</label>
    </customValue>
    <customValue>
        <fullName>IZ</fullName>
        <label>IZ - Izod US</label>
    </customValue>
    <customValue>
        <fullName>OS</fullName>
        <label>OS - Van Heusen US</label>
    </customValue>
    <customValue>
        <fullName>SX</fullName>
        <label>SX - Speedo Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>TC</fullName>
        <label>TC - Tommy Hilfiger Company/Outlets CA</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>TH - Tommy Hilfiger Full Price</label>
    </customValue>
    <customValue>
        <fullName>TI</fullName>
        <label>TI - Tommy Hilfiger Full Price CA</label>
    </customValue>
    <customValue>
        <fullName>TO</fullName>
        <label>TO - Tommy Hilfiger Company/Outlets US</label>
    </customValue>
    <customValue>
        <fullName>TS</fullName>
        <label>TS - Tommy Hilfiger Specialty US</label>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
        <label>TX - Tommy Hilfiger Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>VC</fullName>
        <label>VC - Van Heusen CA</label>
    </customValue>
    <customValue>
        <fullName>VX</fullName>
        <label>VX - Heritage Ecommerce</label>
    </customValue>
    <description>Global Company Code list</description>
    <masterLabel>Company Code</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactFuture.cls
/**
 * @author Magnet360
 *
 * @date 2019
 *
 * @description Future methods for Contact Creation. Called when cases are created from Web or Email
 *
 */
public without sharing class ContactFuture{
    /*******************************************************************************************************
     * @description Called when a direct contact match is found for a case. Will associate the contact and account to the case.
     * @param caseContactBrandMap - mao of Cases to matched Contact
     * @return void
     * @example
     */
    public static void updateCaseContactAndAccount(Map<Id, Id> caseContactBrandMap){
        updateCaseContactAndAccount(caseContactBrandMap, true);
    }
    

    /*******************************************************************************************************
     * @description Called when a direct contact match is found for a case. Will associate the contact and account to the case.
     * @param caseContactBrandMap - map of Cases to matched Contact
     * @param isFuture - allows contact method to be run immediately instead of future
     * @return void
     * @example
     */
    public static void updateCaseContactAndAccount(Map<Id, Id> caseContactBrandMap, Boolean isFuture){
        if (isFuture){
            updateCaseContactAndAccountFuture(caseContactBrandMap);
        } else{
            runUpdateCaseContactAndAccount(caseContactBrandMap);
        }
    }

    @future
    private static void updateCaseContactAndAccountFuture(Map<Id, Id> caseContactBrandMap){
        runUpdateCaseContactAndAccount(caseContactBrandMap);
    }

    @future
    private static void updatePOSContactFuture(List<Id> recordIds){
       runUpdatePOSContact(recordIds);
    }

    /*******************************************************************************************************
     * @description Called when a direct contact match is found for a case. Will associate the contact and account to the case.
     * @param caseContactBrandMap - mao of Cases to matched Contac
     * @return void
     * @example
     */
    private static void runUpdateCaseContactAndAccount(Map<Id, Id> caseContactBrandMap){

        List<Case> updatedCaseList = new List<Case>();
        Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, CaseNumber, AccountId, ContactId, Brand__c, SuppliedEmail, Supplied_First_Name__c, Supplied_Last_Name__c, SuppliedName, SuppliedPhone, Origin, SourceId, Type
                                                   FROM Case 
                                                   WHERE Id IN:caseContactBrandMap.keySet()]);


        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, FirstName, LastName, Email, Brand_Id__c, AccountId, Phone
                                                            FROM Contact
                                                            WHERE Id IN:caseContactBrandMap.values()]);
        List<Contact> updatedContactList = new List<Contact>();
        for (Id casId : caseContactBrandMap.keySet()){
            Case cas = caseMap.get(casId);
            Contact con = contactMap.get(caseContactBrandMap.get(casId));
            cas.ContactId = con.Id;
            cas.AccountId = con.AccountId;
            if (con.Phone == null && cas.SuppliedPhone != null){
                con.Phone = cas.SuppliedPhone;
            }
            updatedCaseList.add(cas);
            updatedContactList.add(con);
        }

        Log.push('>>>updatedCaseList :' + updatedCaseList);
        update updatedCaseList;
        Log.push('>>>updatedContactList :' + updatedContactList);
        Logger.logDebug();
        update updatedContactList;
    }

    /*******************************************************************************************************
     * @description Called when an account is found, but not a contact. The contact is created, associated to the case and the account.
     * @param caseContactGenericMap - a map of CaseIds to Account Ids
     * @return void
     * @example
     */
    public static void updateCaseAccountAndCreateNewContact(Map<Id, Id> caseContactGenericMap){
        updateCaseAccountAndCreateNewContact(caseContactGenericMap, true);
    }

    /*******************************************************************************************************
     * @description Called when an account is found, but not a contact. The contact is created, associated to the case and the account.
     * @param caseContactGenericMap - a map of CaseIds to Account Ids
     * @param isFuture - allows contact future method to be run immediately instead of future
     * @return void
     * @example
     */
    public static void updateCaseAccountAndCreateNewContact(Map<Id, Id> caseContactGenericMap, Boolean isFuture){
        if (isFuture){
            updateCaseAccountAndCreateNewContactFuture(caseContactGenericMap);
        } else{
            runUpdateCaseAccountAndCreateNewContact(caseContactGenericMap);
        }
    }

    @future
    private static void updateCaseAccountAndCreateNewContactFuture(Map<Id, Id> caseContactGenericMap){
        runUpdateCaseAccountAndCreateNewContact(caseContactGenericMap);
    }

    private static void runUpdateCaseAccountAndCreateNewContact(Map<Id, Id> caseContactGenericMap){
        Log.push('>>caseContactGenericMap :' + caseContactGenericMap);
        List<Case> updatedCaseList = new List<Case>();
        List<Contact> createContactList = new List<Contact>();

        Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, CaseNumber, AccountId, ContactId, Brand__c, SuppliedEmail, SuppliedName, Supplied_First_Name__c, Supplied_Last_Name__c, SuppliedPhone, Origin, SourceId, Type
                                                   FROM Case 
                                                   WHERE Id IN:caseContactGenericMap.keySet()]);


        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, FirstName, LastName, Email, Brand_Id__c, AccountId, Phone
                                                            FROM Contact
                                                            WHERE Id IN:caseContactGenericMap.values()]);

        for (Id casId : caseContactGenericMap.keySet()){
            Log.push('>>>casId :' + casId);
            Case cas = caseMap.get(casId);
            Log.push('>>>cas :' + cas);
            Log.push('>>>caseContactGenericMap.get(casId) :' + caseContactGenericMap.get(casId));
            Contact con = contactMap.get(caseContactGenericMap.get(casId));
            Log.push('>>>con :' + con);
            cas.AccountId = con.AccountId;
            Contact cont = new Contact();
            cont.Email = cas.SuppliedEmail;
            cont.AccountId = con.AccountId;
            cont.Phone = cas.SuppliedPhone;
            cont.Brand_Id__c = cas.Brand__c;
            cont.Source_System__c = 'SFSC';
            Log.push('updateCaseAccountAndCreateNewContact cas.Supplied_First_Name__c: ' + cas.Supplied_First_Name__c);
            Log.push('updateCaseAccountAndCreateNewContact cas.Supplied_Last_Name__c: ' + cas.Supplied_Last_Name__c);
            if (cas.Supplied_First_Name__c != null && cas.Supplied_Last_Name__c != null){
                cont.FirstName = cas.Supplied_First_Name__c;
                cont.LastName = cas.Supplied_Last_Name__c;
            } else if (cas.SuppliedName != Null){
                cont.LastName = cas.SuppliedName;
            } else{
                cont.FirstName = con.FirstName;
                cont.LastName = con.LastName;
            }
            createContactList.add(cont);
        }

        insert createContactList;
        Log.push('>>>createContactList :' + createContactList);

        for (Id casId : caseContactGenericMap.keySet()){
            Log.push('>>>casId :' + casId);
            Case cas = caseMap.get(casId);
            for (Contact con : createContactList){
                Log.push('>>>con :' + con);
                if (cas.SuppliedEmail == con.Email || cas.SuppliedPhone == con.Phone){
                    cas.AccountId = con.AccountId;
                    cas.ContactId = con.Id;
                    updatedCaseList.add(cas);
                }
            }
        }

        update updatedCaseList;
        Logger.logDebug();
    }

    public static void createNewContactAndAccountForCase(Set<Id> caseContactNotFound){
        createNewContactAndAccountForCase(caseContactNotFound, true);
    }

    public static void createNewContactAndAccountForCase(Set<Id> caseContactNotFound, Boolean isFuture){
        if (isFuture){
            createNewContactAndAccountForCaseFuture(caseContactNotFound);
        } else{
            runCreateNewContactAndAccountForCase(caseContactNotFound);
        }
    }

    @future
    public static void createNewContactAndAccountForCaseFuture(Set<Id> caseContactNotFound){
        runCreateNewContactAndAccountForCase(caseContactNotFound);
    }

    /*******************************************************************************************************
     * @description Called when neither an account, nor a contact is found for the case. A new account and contact is created and then associated to the case
     * @param caseContactNotFound - a set of case ids
     * @return void
     * @example
     */
    public static void runCreateNewContactAndAccountForCase(Set<Id> caseContactNotFound){
        Log.push('>>caseContactNotFound :' + caseContactNotFound);
        List<Case> updatedCaseList = new List<Case>();

        Map<Id, Account> caseToAccount = new Map<Id, Account>();
        Map<Id, Contact> caseToContact = new Map<Id, Contact>();

        Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, CaseNumber, AccountId, ContactId, Brand__c, SuppliedEmail, SuppliedName, Supplied_First_Name__c, Supplied_Last_Name__c, SuppliedPhone, Origin, SourceId, Type
                                                   FROM Case 
                                                   WHERE Id IN:caseContactNotFound]);
        for (Id casId : caseContactNotFound){
            Case cas = caseMap.get(casId);
            System.debug('cas'+cas);
			//Create new Account list to insert
            Account acc = new Account();
            System.debug('cas.Supplied_Last_Name__c'+cas.Supplied_Last_Name__c);
            System.debug('cas.SuppliedName'+cas.SuppliedName);
            String accName = (String.isBlank(cas.Supplied_Last_Name__c) ? cas.SuppliedName : cas.Supplied_First_Name__c + ' ' + cas.Supplied_Last_Name__c);
            
            if (accName != Null){
                acc.Name = accName;
                acc.LastName__c = (String.isBlank(cas.Supplied_Last_Name__c) ? cas.SuppliedName : cas.Supplied_Last_Name__c);
            } else{
                acc.Name = SYSTEM.LABEL.Unknown;
                acc.LastName__c = SYSTEM.LABEL.Unknown;
            }
            //acc.FirstName__c = cas.Id;
            caseToAccount.put(cas.Id, acc);
            //createNewAccountList.add(acc);

            //Create new contact list to insert
            Contact cont = new Contact();

            Log.push('createNewContactAndAccountForCase cas.Supplied_First_Name__c: ' + cas.Supplied_First_Name__c);
            Log.push('createNewContactAndAccountForCase cas.Supplied_Last_Name__c: ' + cas.Supplied_Last_Name__c);

            if (cas.Supplied_First_Name__c != null && cas.Supplied_Last_Name__c != null){
                Log.push('first name and last name');
                cont.FirstName = cas.Supplied_First_Name__c;
                cont.LastName = cas.Supplied_Last_Name__c;
            } else if (cas.SuppliedName != Null){
                Log.push('suppliedname not null');
                cont.LastName = cas.SuppliedName;
            } else{
                cont.LastName = SYSTEM.LABEL.Unknown;
            }
            cont.Email = cas.SuppliedEmail;
            cont.Phone = cas.SuppliedPhone;
            cont.Brand_Id__c = cas.Brand__c;
            cont.Source_System__c = SYSTEM.LABEL.SFSC;
            cont.Channel__c = SYSTEM.LABEL.X6;//Per instructions from NASSC-938
            cont.Source__c = SYSTEM.LABEL.Service_Desk;//Per instructions from NASSC-938
            //setting record type due to process builder error for NASSC-841
            cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
            //cont.FirstName = cas.Id;
            caseToContact.put(cas.Id, cont);
            //createNewContactList.add(cont);
        }

        insert caseToAccount.values();
        insert caseToContact.values();

        for (case cas : caseMap.values()){
            if (caseToAccount.containsKey(cas.Id)){
                cas.AccountId = caseToAccount.get(cas.Id).Id;
            }

            if (caseToContact.containsKey(cas.Id)){
                cas.ContactId = caseToContact.get(cas.Id).Id;
            }
            updatedCaseList.add(cas);
        }

        update updatedCaseList;

        for (String caseId : caseToContact.keySet()){
            if (caseToAccount.containsKey(caseId)){
                caseToContact.get(caseId).AccountId = caseToAccount.get(caseId).Id;
            }
        }

        update caseToContact.values();
        Logger.logDebug();
    }

    @future
    public static void processNewPrivacyCases(List<Id> newCaseIds){

        List<Case> cases = [Select Id, SuppliedName, Brand__c, SuppliedEmail, ContactId
                            From Case
                            Where Id In:newCaseIds];
        List<String> caseEmails = new List<String>();
        List<String> brands = new List<String>();
        List<Case> matchedCases = new List<Case>();

        for (Case cse : cases){
            if (String.isNotBlank(cse.SuppliedEmail) && !caseEmails.contains(cse.SuppliedEmail)){
                caseEmails.add(cse.SuppliedEmail.toLowerCase());
            }
            if (String.isNotBlank(cse.Brand__c) && !brands.contains(cse.Brand__c)){
                brands.add(cse.Brand__c);
            }
        }
        Log.push('===emails ' + caseEmails);
        Log.push('===brands ' + brands);
        ///CODE updations FOR  PVH Jira - 2781
        List<Contact> cons = [Select Id, FirstName, LastName, Email, Brand_Id__c
                              From Contact
                              Where Brand_ID__c In:brands AND Email In:caseEmails
                              Order By Brand_ID__c, Email
                              LIMIT 10000];
        for (Contact con : cons){
            String conFullName;
            if (String.isBlank(con.FirstName)){
                conFullName = con.LastName;
            } else{
                conFullName = con.FirstName + con.LastName;
            }
            conFullName = conFullName.replace(' ', '').toLowerCase();
            String conEmail = con.Email.toLowerCase();
            ///CODE updations FOR  PVH Jira - 2781
            for (Case cse : cases){
                if (String.isBlank(cse.ContactId) && cse.Brand__c == con.Brand_Id__c && cse.SuppliedEmail.toLowerCase() == conEmail){
                    Log.push('===matched case ' + cse);
                    Log.push('===matched contact ' + con);
                    cse.ContactId = con.Id;
                    matchedCases.add(cse);
                }
            }
        }
        if (matchedCases.size() > 0){
            Log.push('===updating matched cases ' + matchedCases.size());
            update matchedCases;
        }
        Logger.logDebug();
    }

    @future
    public static void upsertChildContactOnParentupdate(Set<Id> parentContactIdSet){

        Map<Contact, list<Contact>> parentAndSubBrandContactMap = new Map<Contact, List<Contact>>();
        Map<String, Set<String>> parentAndSubBrandMap = new Map<String, Set<String>>();

        List<LoyaltySettings__mdt> LoyaltySettingList = [Select Id, BrandId__c, IsLoyaltyApplicable__c, Parent_Brand__c
                                                         from LoyaltySettings__mdt];
        if (!LoyaltySettingList.isEmpty()){
            for (LoyaltySettings__mdt loyalRecord : LoyaltySettingList){
                if (loyalRecord.Parent_Brand__c != null){
                    if (parentAndSubBrandMap.containsKey(loyalRecord.Parent_Brand__c)){
                        parentAndSubBrandMap.get(loyalRecord.Parent_Brand__c).add(loyalRecord.BrandId__c);
                    } else{
                        Set<String> subBrandIdSet = new Set<String>();
                        subBrandIdSet.add(loyalRecord.BrandId__c);
                        parentAndSubBrandMap.put(loyalRecord.Parent_Brand__c, subBrandIdSet);
                    }
                }
            }
        }
        Log.push('Parent and sub brand map ' + parentAndSubBrandMap);

        List<Contact> parentContactList = [select id, FirstName, MiddleName, LastName, Brand_Id__c, AccountId, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry, EmailOptInStatus__c, EmailOptInDate__c, Email, Phone, HomePhone, OtherPhone, MobilePhone, HomeStore__c, Source_System__c, Source__c, LoyaltyFlag__c, Loyalty_Optin_Date__c, LoyaltyID__c, Company_Code__c, StorePreference__c, StoreOfCapture__c, WelcomeSource__c, Birthdate
                                           from Contact
                                           where Id IN:parentContactIdSet];

        List<Contact> contactListToUpsert = searchContacts(parentContactList, parentAndSubBrandMap);
        if (!contactListToUpsert.isEmpty()){
            upsert contactListToUpsert;
        }
    }

    //This method wil check if subbrands contacts exists-
    //if exists update  StoreOfCapture__c,WelcomeSource__c else create new one
    public static List<Contact> searchContacts(List<Contact> parentContactlist, Map<String, Set<String>> parentAndSubBrandMap){
        Map<Contact, List<Contact>> emailAndContactMap = new Map<Contact, List<Contact>>();
        Set<String> parentEmailIdSet = new Set<String>();
        Set<String> subBrandIdSet = new Set<String>();
        Map<Contact, List<Contact>> parentAndChildContactMap = new Map<Contact, List<Contact>>();
        List<Contact> updateContactList = new List<Contact>();
        Id emailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();

        if (parentContactlist != null){
            for (Contact parentCon : parentContactlist){
                parentEmailIdSet.add(parentCon.Email);
                subBrandIdSet.addAll(parentAndSubBrandMap.get(parentCon.Brand_Id__c));
            }
        }

        List<Contact> searchedContactList = [SELECT Id, FirstName, MiddleName, LastName, Email, Brand_Id__c
                                             FROM Contact
                                             WHERE RecordTypeId = :emailRecordTypeId AND Brand_Id__c IN:subBrandIdSet AND Email = :parentEmailIdSet];

        if (!searchedContactList.isEmpty()){
            for (Contact cnt : searchedContactList){
                for (Contact parentCon : parentContactlist){
                    if (!parentAndChildContactMap.containsKey(parentCon)){
                        List<Contact> subBrandContactList = new List<Contact>();
                        if (parentCon.Email == cnt.Email){
                            subBrandContactList.add(cnt);
                            parentAndChildContactMap.put(parentCon, subBrandContactList);
                        }
                    } else{
                        if (parentCon.Email == cnt.Email){
                            parentAndChildContactMap.get(parentCon).add(cnt);
                        }
                    }
                }
            }
        } else{
            for (Contact parentCon : parentContactlist){
                List<Contact> emptyCnt = new list<Contact>();
                parentAndChildContactMap.put(parentCon, emptyCnt);
            }
        }
        //check if searched contact list is empty
        if (parentAndChildContactMap != null){
            for (Contact con : parentAndChildContactMap.keySet()){
                Set<String> subBrandSet = parentAndSubBrandMap.get(con.Brand_Id__c);
                if (parentAndChildContactMap.get(con) != null){
                    for (Contact childCon : parentAndChildContactMap.get(con)){
                        if (subBrandSet.contains(childCon.Brand_Id__c)){
                            Contact updateCon = new Contact(id = childCon.id); //copy 2 fields from parent contact
                            updateCon.StoreOfCapture__c = con.StoreOfCapture__c;
                            updateCon.WelcomeSource__c = con.WelcomeSource__c;
                            updateCon.EmailOptinStatus__c = con.EmailOptinStatus__c;
                            updateCon.LoyaltyFlag__c = con.LoyaltyFlag__c;
                            updateContactList.add(updateCon);
                            subBrandSet.remove(childCon.Brand_Id__c);
                        }
                    }
                }
                if (subBrandSet != null){
                    //create new contacts if not exists for any subbrands
                    for (String subbrandId : subBrandSet){
                        Contact newCon = con.clone(false, true, false, false);
                        newCon.Brand_Id__c = subbrandId;
                        newCon.Status__c = SYSTEM.LABEL.ACTIVE;
                        updateContactList.add(newCon);
                    }
                }
            }
        }
        Logger.logDebug();
        return updateContactList;
    }

    private static void runUpdatePOSContact(List<Id> recordIds){
        
        
    }

}