unpackaged/main/default/objects/Account/fields/PVHCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>PVHCreatedDate__c</fullName>
    <label>PVHCreatedDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CountryOfCapture__c.field-meta.xml
<CustomField>
    <fullName>CountryOfCapture__c</fullName>
    <label>Country of Capture</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CreatedByMethod__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMethod__c</fullName>
    <label>Created By Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <description>Captures the Keyword values from where the customer SMS opt In. Ex: TH004, Preference center , ChargeIt</description>
    <label>SMSKeyword</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/PVHCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>PVHCreatedDate__c</fullName>
    <label>PVHCreatedDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMS_Unsubscribe_Reason__c.field-meta.xml
<CustomField>
    <fullName>SMS_Unsubscribe_Reason__c</fullName>
    <description>To capture the SMS unsubscribe reason once the customer opted out from SMS.</description>
    <label>SMS Unsubscribe Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptInDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptInDate__c</fullName>
    <label>SMS Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOutDate__c</fullName>
    <label>SMS Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CKSMSSubscriberSignUp.cls
/******************************************************************************
* @Description: CKSMSSubscriberSignUp from SFMC to SFSC
* @Author     : PVH
* @Date       : Sept 2021
* @JIRA       : NACDT-5338
*
******************************************************************************/ 

@RestResource(urlmapping='/CKSMSSubscriber/SignUp')
global without sharing class CKSMSSubscriberSignUp {
       static Id emailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();

      global class SMSRequest {
        public String brandId;
        public String emailAddress;
        public String smsNumber;
        public Boolean loyaltyOptin;
        public String storeOfCapture;
        public String locale;
        
    }     
    
    global class SMSResponse{
        public String code;
        public String message;
        public String ContactId;
        public String LoyaltyId;
        public String countryOfCapture;
        
    }  
    @HttpPost
  global static SMSResponse doSMSSignUp(){
        
        Contact SMSMatchedContact = new Contact();
        Contact emailMatchedContact = new Contact();
        Boolean smsAndEmailExactMatch = false;
 
        List<SignUpActivity> signUpActivityList = new List<SignUpActivity>();

        Contact newContact;
        Contact toBeUpdatedContact;
        Contact existingUpdatedContact;
        
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response; 
        String requestData = request.requestBody.toString();
        System.debug('***got request data = '+requestData);
        
        SMSRequest smsRequest = (SMSRequest)JSON.deserialize(requestData,SMSRequest.class);
        System.debug('***SMS Request = '+smsRequest);
        SMSResponse errorResponse = new SMSResponse();
        SMSResponse successResponse = new SMSResponse();
        Boolean isRequiredParameterMissing = false;
 
        if (String.isBlank(smsRequest.brandId) || 
            String.isBlank(smsRequest.emailAddress) ||
            String.isBlank(smsRequest.smsNumber) ||
            //String.isEmpty(smsRequest.loyaltyOptin) ||    //fix this..
            String.isBlank(smsRequest.storeOfCapture)) {
            isRequiredParameterMissing = true;
        }

        
        if (isRequiredParameterMissing) {
            response.statusCode = 400;
            errorResponse.code = 'MISSING_PARAMETERS';
            errorResponse.Message = 'Missing: one or more of the required parameters missing';
            System.debug('### errorResponse' + errorResponse);
            return errorResponse;
        }
         
       if(!isRequiredParameterMissing){
           //Exact Matched SMSNumber & Email Contact #scenario Option#5
          SMSMatchedContact = SFMCUtility.searchSMSBrandContact(smsRequest.brandId,smsRequest.smsNumber);
          if (SMSMatchedContact!=null && SMSMatchedContact.Email!=null && SMSMatchedContact.Email==smsRequest.emailAddress) smsAndEmailExactMatch = true;
         if(SMSMatchedContact!=Null){
           if(SMSMatchedContact.LoyaltyFlag__c==False){
               SMSMatchedContact.LoyaltyFlag__c=True;
               SMSMatchedContact.Loyalty_Optin_Date__c=System.now();
           }
           if(SMSMatchedContact.SMSLocale__c!=smsRequest.locale){
               SMSMatchedContact.SMSLocale__c=smsRequest.locale;
           }
         }  
          if (smsAndEmailExactMatch){

                response.statusCode = 200;
                errorResponse.code = 'INVALID_SCENARIO';
                errorResponse.Message = 'Exact match on email+SMS Number found -  nothing to update';
                System.debug('### errorResponse' + errorResponse);
                return errorResponse;

            }
           
                     
           if (!smsAndEmailExactMatch) {
                emailMatchedContact = SFMCUtility.searchEmailBrandContact(smsRequest.brandId, smsRequest.emailAddress);
            }
              //no SMSMatch scenarios
           if (SMSMatchedContact==null) {
                   //No EmailMatch scenario optin#1
                if (emailMatchedContact==null){
                   //optin#1 - create new SMS+email Contact, optin.
                    newContact = createNewSMSAndEmailContact(smsRequest);
                    // trigger to assign new/existing account on insert.
                 } else {
                     if (emailMatchedContact.SMSNumber__c==null) {
                        //optin#2 - update email Contact with SMS, SMS Optin
                        emailMatchedContact.SMSNumber__c = smsRequest.smsNumber;
                        emailMatchedContact.SMSOptInDate__c = System.now();
                        if(emailMatchedContact.SMSLocale__c!=smsRequest.locale){
                           emailMatchedContact.SMSLocale__c=smsRequest.locale;
                        }
                         //GCT-1571- Matching of Keyword  
                        if(SMSMatchedContact.Keyword__c!=smsRequest.storeOfCapture){
                          SMSMatchedContact.Keyword__c=smsRequest.storeOfCapture;
                        }
                        if(emailMatchedContact.LoyaltyFlag__c==False){
                           emailMatchedContact.LoyaltyFlag__c=True;
                           emailMatchedContact.Loyalty_Optin_Date__c=System.now();
                        }
                        emailMatchedContact.SMSOptinStatus__c = 'Y';
                        emailMatchedContact.Latest_Source__c = 'SFMC';
                        emailMatchedContact.SMSOptInDate__c = System.now();
                         
                        toBeUpdatedContact = emailMatchedContact;
                        
                    } 
                }
              }
            //optin#3 - No matching SMS #; Matching Email address with different SMS #
           if(emailMatchedContact!=Null){
               
               if(emailMatchedContact.SMSNumber__c!=Null && emailMatchedContact.SMSNumber__c!=smsRequest.smsNumber && SMSMatchedContact==Null){
             
                   newContact = createNewSMSAndEmailContact(smsRequest);
                   if(emailMatchedContact.LoyaltyFlag__c!=True){
                       emailMatchedContact.LoyaltyFlag__c=True;
                       emailMatchedContact.Loyalty_Optin_Date__c = System.now();
                   }
                  
                   if(emailMatchedContact.LoyaltyID__c!=Null){
                       newContact.LoyaltyID__c=emailMatchedContact.LoyaltyID__c;
                       newContact.LoyaltyFlag__c = emailMatchedContact.LoyaltyFlag__c;
                       newContact.Loyalty_Optin_Date__c = emailMatchedContact.Loyalty_Optin_Date__c;
                   } 
                   if(emailMatchedContact.EmailOptInStatus__c!=Null){
                       newContact.EmailOptInStatus__c=emailMatchedContact.EmailOptInStatus__c;
                       if(newContact.EmailOptInStatus__c=='Y'){
                       newContact.EmailOptInDate__c=emailMatchedContact.EmailOptInDate__c;
                       newContact.HasOptedOutOfEmail=False;
                       newContact.EmailOptOutDate__c=Null;
                       }else if(newContact.EmailOptInStatus__c=='N'){
                       newContact.EmailOptOutDate__c=emailMatchedContact.EmailOptOutDate__c;
                       newContact.HasOptedOutOfEmail=True; 
                       }
                   }
                  existingUpdatedContact=emailMatchedContact;
                   if(existingUpdatedContact!=Null){
                       update existingUpdatedContact;
                   }
                   toBeUpdatedContact=newContact;
                   
              }
           }
           //Matching SMS #; No matching Email address Scenorio 4
           if((SMSMatchedContact!=Null && SMSMatchedContact.SMSNumber__c==smsRequest.smsNumber) && (SMSMatchedContact.Email!=Null && SMSMatchedContact.Email!=smsRequest.emailAddress) && emailMatchedContact==Null){
                newContact = createNewSMSAndEmailContact(smsRequest);
                SMSMatchedContact.SMSNumber__c=Null;
               SMSMatchedContact.SMS_Unsubscribe_Reason__c='Change of Email';
                if(SMSMatchedContact.SMSOptinStatus__c=='Y'){
                  SMSMatchedContact.SMSOptinStatus__c='N';
                  SMSMatchedContact.SMSOptOutDate__c = System.now();
             } 
               //Commenting the code for the defect NACDT-5438 on 08/11/2021
             /*  if(SMSMatchedContact.EmailOptInStatus__c!='N'){
                  SMSMatchedContact.EmailOptInStatus__c='N';
                  SMSMatchedContact.EmailOptOutDate__c=System.now();
                  SMSMatchedContact.HasOptedOutOfEmail=True;
               }  */
              if(SMSMatchedContact.SMSLocale__c!=smsRequest.locale){
               SMSMatchedContact.SMSLocale__c=smsRequest.locale;
           }
               //GCT-1571- Matching of Keyword  
              if(SMSMatchedContact.Keyword__c!=smsRequest.storeOfCapture){
                  SMSMatchedContact.Keyword__c=smsRequest.storeOfCapture;
               }
               toBeUpdatedContact=SMSMatchedContact;
                if(toBeUpdatedContact!=Null){
                  update toBeUpdatedContact;
              }
            }

           
          //optin#6 - matching SMS #; Invalid Email address 
                   
          if ((SMSMatchedContact!=null && SMSMatchedContact.Email==Null) && (emailMatchedContact!=Null && (emailMatchedContact.Email==smsRequest.emailAddress)) ) {
                SMSMatchedContact.SMSNumber__c=Null; 
                SMSMatchedContact.SMS_Unsubscribe_Reason__c='Invalid Email Received'; 
               SMSMatchedContact.SMSOptinStatus__c = 'N';
               SMSMatchedContact.SMSOptOutDate__c = System.now();
                if(SMSMatchedContact.LoyaltyFlag__c==False){
                   SMSMatchedContact.LoyaltyFlag__c=True;
                   SMSMatchedContact.Loyalty_Optin_Date__c = System.now();
               }
               emailMatchedContact.SMSNumber__c=smsRequest.smsNumber;
               emailMatchedContact.SMSOptinStatus__c = 'Y';
               emailMatchedContact.SMSOptInDate__c = System.now();
             if(emailMatchedContact.LoyaltyFlag__c==False){ 
               emailMatchedContact.LoyaltyFlag__c=True;
               emailMatchedContact.Loyalty_Optin_Date__c=System.now();
                 }
             existingUpdatedContact=SMSMatchedContact;
              if(existingUpdatedContact!=Null){
                  update existingUpdatedContact;
              }
             toBeUpdatedContact=emailMatchedContact; 
          }
           
          //optin#7 - Existing Matching SMS #; Email Matching record NACDT-5444
                   
        if ((SMSMatchedContact!=null && SMSMatchedContact.Email!=Null && (SMSMatchedContact.Email!=smsRequest.emailAddress)) && (emailMatchedContact!=Null && (emailMatchedContact.Email==smsRequest.emailAddress))) {
               SMSMatchedContact.SMSNumber__c=Null;
               SMSMatchedContact.SMS_Unsubscribe_Reason__c='Other Email matched'; 
			   SMSMatchedContact.SMSOptinStatus__c = 'N'; 
               SMSMatchedContact.SMSOptOutDate__c = System.now();
               emailMatchedContact.SMSNumber__c=smsRequest.smsNumber;
               emailMatchedContact.SMSOptinStatus__c = 'Y';
               emailMatchedContact.SMSOptInDate__c = System.now();
             if(emailMatchedContact.LoyaltyFlag__c==False){ 
               emailMatchedContact.LoyaltyFlag__c=True;
               emailMatchedContact.Loyalty_Optin_Date__c=System.now();
                 }
             existingUpdatedContact=SMSMatchedContact;
              if(existingUpdatedContact!=Null){
                  update existingUpdatedContact;
              }
             toBeUpdatedContact=emailMatchedContact; 
          }
           
           
           
           //optin#8 - Re-Optin Scenorios 
         if (SMSMatchedContact!=null && SMSMatchedContact.Email==Null) {
               SMSMatchedContact.SMSOptinStatus__c = 'Y';
               SMSMatchedContact.SMSOptOutDate__c = System.now();
              if(SMSMatchedContact.LoyaltyFlag__c==False){
                   SMSMatchedContact.LoyaltyFlag__c=True;
                   SMSMatchedContact.Loyalty_Optin_Date__c = System.now();
               }
               SMSMatchedContact.Email=smsRequest.emailAddress;
               SMSMatchedContact.EmailOptInStatus__c='N';
               SMSMatchedContact.EmailOptOutDate__c=System.now();
             toBeUpdatedContact=SMSMatchedContact;
              /*if(toBeUpdatedContact!=Null){
                  update existingUpdatedContact;
              }*/
            
          }
           
        Contact responseContact;
         if (newContact!=null) {
                insert newContact;

                responseContact = [select Id, Latest_Source__c, Brand_Id__c, LoyaltyID__c, CountryOfCapture__c from Contact where Id = :newContact.id];
               

            }
         else if (toBeUpdatedContact!=null) {
                update toBeUpdatedContact;
                responseContact = toBeUpdatedContact;
               
            }
        if (responseContact!=null){
                
                response.statusCode = 200;
                successResponse.code = 'OK';
                successResponse.Message = 'OK';
                successResponse.ContactId = responseContact.Id;
                if (responseContact.LoyaltyID__c!=null) successResponse.LoyaltyId = responseContact.LoyaltyID__c;
                if (responseContact.CountryOfCapture__c!=null) successResponse.countryOfCapture = responseContact.CountryOfCapture__c;
                
                return successResponse;

            }
         
       }
          return successResponse;
     }
    
    
     public static Contact createNewSMSOnlyContact(SMSRequest smsRequest){
        Contact newCon = new Contact();
        newCon.createdByMethod__c = 'API';
        newCon.RecordTypeId = emailRecordTypeId;
        newCon.Status__c = 'ACTIVE';
        newCon.Source_System__c = 'SFMC';
        newCon.Latest_Source__c = 'SFMC';
        newCon.Brand_Id__c = smsRequest.brandId;
        newCon.SMSLocale__c  =smsRequest.locale;
        /* GCT-1571 */
        newCon.Keyword__c  =smsRequest.StoreOfCapture;
        newCon.FirstName = 'Unknown';
        newCon.LastName = 'Unknown';
       
        newCon.SMSNumber__c = smsRequest.smsNumber;
        newCon.SMSOptinStatus__c = 'Y';
        newCon.SMSOptInDate__c = System.now();
        newCon.PVHCreatedDate__c = System.now();

        if (String.isNotBlank(smsRequest.StoreOfCapture)) 
            newCon.StoreOfCapture__c = smsRequest.StoreOfCapture;

        if (smsRequest.loyaltyOptin) {
            newCon.LoyaltyFlag__c = true;
            newCon.Loyalty_Optin_Date__c = System.now();
        }
       return newCon;

    }



    public static Contact createNewSMSAndEmailContact(SMSRequest smsRequest){
        Contact newCon = createNewSMSOnlyContact(smsRequest);
        newCon.Email = smsRequest.emailAddress;
        newCon.EmailOptInStatus__c = 'N';
        newCon.EmailOptOutDate__c=system.now();
        newCon.HasOptedOutOfEmail=True;
        return newCon;

    }
    
}