unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Brand_Setting__mdt/Brand_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/ebotdata__Bot_Chat_Log__c.object-meta.xml
<CustomObject>
    <description>Track each chat log record and any relevant information thru a backend process</description>
    <label>Bot Chat Log</label>
    <nameField>
        <displayFormat>BLG-{00000}</displayFormat>
        <label>Bot Chat Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Chat Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Bot_Session__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Bot_Session__c</fullName>
    <description>Bot Chat Session</description>
    <inlineHelpText>Einstein Bot Chat Session</inlineHelpText>
    <label>Bot Chat Session</label>
    <referenceTo>ebotdata__Bot_Session__c</referenceTo>
    <relationshipLabel>Bot Chat Logs</relationshipLabel>
    <relationshipName>Bot_Chat_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Current_Utterance__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Current_Utterance__c</fullName>
    <label>Current Utterance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Intent_Name__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Intent_Name__c</fullName>
    <description>Intent Name</description>
    <inlineHelpText>Intent Name</inlineHelpText>
    <label>Intent Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Chat_Log__c/fields/ebotdata__Live_Agent_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Agent_Session_Id__c</fullName>
    <description>This maps to the ChatKey column in LiveChatTranscirpt object</description>
    <inlineHelpText>This maps to the ChatKey column in LiveChatTranscirpt object</inlineHelpText>
    <label>Live Agent Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Invocation_URL__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Invocation_URL__c</fullName>
    <description>This field stores the URL of the page from which chat was initiated. It is filled via pre-chat form.</description>
    <inlineHelpText>This field stores the URL of the page from which chat was initiated.</inlineHelpText>
    <label>Invocation URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Agent_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Agent_Session_Id__c</fullName>
    <description>Live Agent Session Id</description>
    <inlineHelpText>Live Agent Session Id</inlineHelpText>
    <label>Live Agent Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Visitor_Feedback_Result__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Feedback_Result__c</fullName>
    <label>Visitor Feedback Result</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/ebotdata__Invocation_URL__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Invocation_URL__c</fullName>
    <inlineHelpText>Filled via Pre-chat form in snapin file</inlineHelpText>
    <label>Invocation URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_UtilTest.cls
/**
 *
*/

@IsTest
public with sharing class NF_UtilTest {
    public static String createLiveChatTranscript(){
        LiveChatTranscript t1 = new LiveChatTranscript();
        LiveChatVisitor lcv = new LiveChatVisitor();
        try{
            insert lcv;
        }catch(Exception e){

        }
        t1.LiveChatVisitorId = lcv.Id;
        t1.ChatKey = 'somechatkey';
        insert t1;
        return t1.ChatKey;
    }

    public static String createLiveChatTranscript(String brand){
        LiveChatTranscript t1 = new LiveChatTranscript();
        LiveChatVisitor lcv = new LiveChatVisitor();
        try{
            insert lcv;
        }catch(Exception e){

        }
        t1.LiveChatVisitorId = lcv.Id;
        t1.ChatKey = 'somechatkey';
        t1.Brand__c = brand;
        insert t1;
        return t1.ChatKey;
    }

    public static Id createLiveChatTranscript2(){
        LiveChatTranscript t1 = new LiveChatTranscript();
        LiveChatVisitor lcv = new LiveChatVisitor();
        try{
            insert lcv;
        }catch(Exception e){

        }
        t1.LiveChatVisitorId = lcv.Id;
        t1.ChatKey = 'somechatkey';
        insert t1;
        return t1.Id;
    }

    @IsTest
    public static void test1() {
        String chatKey = NF_UtilTest.createLiveChatTranscript();
        NF_Util.insertSession(chatKey,'','Calvin Klein');
        String intent = NF_Util.getLastBusinessIntent(chatKey);
        System.assertNotEquals(NF_Util.getBotSession(chatKey),null);
    }

    @IsTest
    public static void test2() {
        RecordType rt = NF_Util.getRecordType();
        //System.assertNotEquals(rt,null);
    }

    @IsTest
    public static void test3() {
        Brand_Setting__mdt mdt = NF_Util.getBrandName('https://calvinklein.com');
        System.assertNotEquals(mdt.Brand_Id__c,null);
        System.assertNotEquals(NF_Util.getDomainName('https://calvinklein.com'),null);

    }

    @IsTest
    public static void test4() {
        List<String> names = NF_Util.splitFullNameIntoFirstAndLast('test user');
        System.assertNotEquals(names.size(),0);

    }
    @IsTest
    public static void test5() {
        Account test = NF_Util.createCustomer('test', 'user', 'test@gmail.com');
        System.assertNotEquals(test,null);
        Account account = NF_Util.getContact('test@gmail.com');
        System.assertNotEquals(account,null);


        Contact cc = NF_Util.createContact('test','user', 'test@gmail.com', '1');
        System.assertNotEquals(cc,null);

        Contact c = NF_Util.getContact('test@gmail.com', '', 'Tommy Hilfiger');
        System.assertNotEquals(c,null);
    }
    
    
    
    public static ebotdata__Bot_Session__c insertBotSession(String chatKey){
        ebotdata__Bot_Session__c session = new ebotdata__Bot_Session__c();
        session.ebotdata__Live_Agent_Session_Id__c = chatKey;
        insert session;
        return session;
    }

    public static ebotdata__Bot_Chat_Log__c insertChatLog(ebotdata__Bot_Session__c session){
        ebotdata__Bot_Chat_Log__c log = new ebotdata__Bot_Chat_Log__c();
        log.ebotdata__Bot_Session__c = session.Id;
        log.ebotdata__Intent_Name__c = 'bus_testIntent_end';
        log.ebotdata__Current_Utterance__c = 'firstUserInput';
        log.ebotdata__Live_Agent_Session_Id__c = session.ebotdata__Live_Agent_Session_Id__c;
        insert log;
        return log;
    }

    @IsTest
    static void test1GetRamdomResponse() {
        
        contact con = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456');
        insert con;
        
        getContact.getContactDetails(con.Id);
        GenericRecords__c gr = new GenericRecords__c();
        gr.recordId__c = con.Id;
        gr.Name ='privacyContact';
        insert gr;
        Case cs = NF_Util.getCaseRelatedToContact(con.Id);
        
        List<NF_CreateCase.Input> inputs = new List<NF_CreateCase.Input>();
        NF_CreateCase.Input input = new NF_CreateCase.Input();
        List<NF_CreateCase.Output> outputs;

        input.chatKey = NF_UtilTest.createLiveChatTranscript();
        input.email='testemail1@email.com';
        input.brand='Calvin Klein';
        input.firstName = 'test';
        input.lastName = 'test';
        input.agentAvailable=false;
        input.reason = 'just a test';
        inputs.add(input);
        outputs = NF_CreateCase.createCase(inputs);
        System.assertNotEquals(outputs.get(0).caseNumber,null);

    }
    @IsTest
    static void updateSessionTest1() {
        NF_UpdateSessionFollowup.Input input= new NF_UpdateSessionFollowup.Input();
        input.chatKey = NF_UtilTest.createLiveChatTranscript();
        input.isPositiveFeedback = 'true';
        NF_Util.insertSession(input.chatKey,'','Calvin Klein');
        NF_Util.associateCaseWithSession(input.chatKey,'');
        List<NF_UpdateSessionFollowup.Input> inputs = new List<NF_UpdateSessionFollowup.Input>();
        inputs.add(input);
        NF_UpdateSessionFollowup.updateSession(inputs);
        ebotdata__Bot_Session__c[] botSessions = [SELECT Id, Brand__c,Visitor_Feedback_Result__c
        FROM ebotdata__Bot_Session__c
        WHERE ebotdata__Live_Agent_Session_Id__c = :input.chatKey
        LIMIT 1];
        //return botSessions.size() > 0 ? botSessions[0] : null;
        System.assertEquals(botSessions[0].Visitor_Feedback_Result__c,'Yes');

    }


    public static LiveChatTranscript insertLiveChatTranscript(String chatKey, String pageUrl, String token){
        LiveChatVisitor v = new LiveChatVisitor();
        insert v;
        LiveChatTranscript transcript = new LiveChatTranscript();
        transcript.LiveChatVisitorId= v.Id;

        if(String.isNotEmpty(chatKey)){
            transcript.ChatKey = chatKey;
        }

        if(String.isNotEmpty(pageUrl)){
            transcript.ebotdata__Invocation_URL__c = pageUrl;
        }


        insert transcript;

        return transcript;
    }
}