unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/UnsubscribeTest.cls
@isTest
private class UnsubscribeTest {

    @TestSetup
    private static void TestData(){
        Account acct = new Account();
        acct.Name = 'Test Account';
        insert acct;
        
        list<Contact> conList = new list<Contact>();
        
        //Creating Test data, 3 contact with 2 brand with EmailOptInStatus__c = true
        //--Brand 10 - contact1@nomail.com,contact2@nomail.com
        //--Brand 1 - contact2@nomail.com
        
        for(Integer i=1;i<=3;i++) {

            Contact cont = new Contact();
            cont.FirstName = 'Contact';
            cont.LastName = 'lname ' + i;
            cont.Brand_Id__c = '10';
            cont.Email = 'contact' + i + '@nomail.com';
            cont.HasOptedOutOfEmail = false;
            cont.EmailOptInStatus__c = 'Y'; // true;
            cont.AccountId = acct.Id;
            conList.add(cont);
        }
            conList[2].Brand_Id__c = '1';
            conList[2].Email = 'contact2@nomail.com';

        insert conList;
    }
    
    @isTest static void testUnsubscribe(){
        Unsubscribe.UnSubRequest unReq = new Unsubscribe.UnSubRequest();
        String requestString = '{"Count":"2","Unsubscribes":[{"BrandId":"10","Email":"contact1@nomail.com"},{"BrandId":"10","Email":"contact2@nomail.com"}]}';
        
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/subscribers/Unsubscribe';  //Request URL
        req.httpMethod = 'POST';                            //HTTP Request Type
        req.requestBody = Blob.valueof(requestString);
        RestContext.request = req;
        RestContext.response= res;

        Unsubscribe.doUnsubscribe();
        

        
        Contact con1Updated = [SELECT Id, EmailOptInStatus__c FROM Contact WHERE Email = 'contact1@nomail.com'];
        
        System.assertEquals(con1Updated.EmailOptInStatus__c,'N');

        Contact con2Updated = [SELECT Id, EmailOptInStatus__c FROM Contact WHERE Email = 'contact2@nomail.com' AND Brand_Id__c = '10' ];
        
        System.assertEquals(con2Updated.EmailOptInStatus__c,'N');

        Contact con3Updated = [SELECT Id, EmailOptInStatus__c FROM Contact WHERE Email = 'contact2@nomail.com' AND Brand_Id__c = '1' ];
        
        System.assertEquals(con3Updated.EmailOptInStatus__c,'Y');
        
        Test.stopTest();

    }

    
}