unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LiveChatTranscript/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_CreateCaseTest.cls
/**
 * Created by apoorvrajput on 10/10/20.
 */

@IsTest
private class NF_CreateCaseTest {
    
    @testSetup
    public static void setupData() {
        List<Account> genAcc = TestDataFactory.createAccount(1);
        genAcc[0].Name = 'generic Account' + Math.random();
        insert genAcc;
        
        List<Contact> genCon = TestDataFactory.createContact(1);
        genCon[0].email = 'foo@example.com';
        genCon[0].lastName = 'generic contact ' + Math.random();
        genCon[0].AccountId = genAcc[0].id;
        genCon[0].Brand_Id__c='9';
        insert genCon;
        
        TestDataFactory.createGenericRecords(genAcc[0].Id);
        TestDataFactory.createGenericRecords(genCon[0].Id);
        
        List<Account> accLst = TestDataFactory.createAccount(1);
        insert accLst;
        
        List<Contact> conLst = TestDataFactory.createContact(1);
        conLst[0].AccountId = accLst[0].Id;
        conLst[0].email = 'test@test.com';
        conLst[0].lastName = 'generic contact ' + Math.random();
        conLst[0].Brand_Id__c = '1';
        insert conLst;
        
        List<Case> parentCaseLst = TestDataFactory.createCases(1);
        parentCaseLst[0].Type = 'Support';
        parentCaseLst[0].Status = 'New';
        parentCaseLst[0].ContactId=conLst[0].id;
        parentCaseLst[0].AccountId=accLst[0].id;
        parentCaseLst[0].Brand__c='1';
        parentCaseLst[0].SuppliedEmail='test@gmail.com';
        insert parentCaseLst;
        
        LiveChatTranscript liveChatTranscript = TestDataFactory.createLiveChatTranscript('Calvin Klein','someChatKey');
        liveChatTranscript.CaseId = parentCaseLst[0].Id;
        liveChatTranscript.ContactId = conLst[0].Id;
        liveChatTranscript.AccountId = accLst[0].Id;
        insert liveChatTranscript;
        
        
        
    }
    
    public static List<NF_CreateCase.Input> createInput() {
        List<NF_CreateCase.Input> inputs = new List<NF_CreateCase.Input>();
        NF_CreateCase.Input input = new NF_CreateCase.Input();
       
        input.chatKey = 'someChatKey';
        input.email='testemail1@email.com';
        input.brand='Calvin Klein';
        input.firstName = 'test';
        input.lastName = 'test';
        input.agentAvailable=false;
        input.reason = 'just a test';
        input.existingCase = true;
        inputs.add(input);
        return inputs;
    }

    @IsTest
    static void test1GetRamdomResponse() {
        List<NF_CreateCase.Output> outputs = NF_CreateCase.createCase(NF_CreateCaseTest.createInput());
        System.assertEquals(false,outputs[0].newCase);
    }
    
    @isTest
    public static void testNewCaseCreate() {
         List<NF_CreateCase.Input> createCaseInput = NF_CreateCaseTest.createInput();
         createCaseInput[0].existingCase = null;
         createCaseInput[0].orderNumber = 'We know it';
         List<NF_CreateCase.Output> outputs = NF_CreateCase.createCase(createCaseInput);
         System.assertEquals(true,outputs[0].newCase);
    }
}