unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CalvinKlein.us</fullName>
                <label>Online - CalvinKlein.com</label>
            </value>
            <value>
                <fullName>Calvin Klein Retail</fullName>
                <label>Calvin Klein Store</label>
            </value>
            <value>
                <fullName>Tommy.com</fullName>
                <label>Online - Tommy.com</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger Retail</fullName>
                <label>Tommy Hilfiger Store</label>
            </value>
            <value>
                <fullName>SpeedoUSA.com</fullName>
                <label>Online - speedo.com</label>
            </value>
            <value>
                <fullName>VanHeusen.com</fullName>
                <label>Online - vanheusen.com</label>
            </value>
            <value>
                <fullName>Izod.com</fullName>
                <label>Online - Izod.com</label>
            </value>
            <value>
                <fullName>styleBureau.com</fullName>
                <label>Online - styleBureau.com</label>
            </value>
            <value>
                <fullName>trueandco.com</fullName>
                <label>Online -True&amp;co.com</label>
            </value>
            <value>
                <fullName>CalvinKlein.ca</fullName>
                <label>Online-CalvinKlein Canada</label>
            </value>
            <value>
                <fullName>Speedo.com</fullName>
            </value>
            <value>
                <fullName>Warner.com</fullName>
                <label>Online-Warner&#39;s</label>
            </value>
            <value>
                <fullName>Van Heusen | IZOD Company Store</fullName>
            </value>
            <value>
                <fullName>Amazon.com</fullName>
            </value>
            <value>
                <fullName>Nordstrom</fullName>
            </value>
            <value>
                <fullName>Other Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Details__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Details__c</fullName>
    <label>Reason Code Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted Forms of Payment</fullName>
            </value>
            <value>
                <fullName>Account Information (Member ID)</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Issue (Godzilla, Dummy Account)</fullName>
            </value>
            <value>
                <fullName>Account Issue (Loyalty Flag)</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Registration Error</fullName>
            </value>
            <value>
                <fullName>Adaptive</fullName>
            </value>
            <value>
                <fullName>Address Error</fullName>
            </value>
            <value>
                <fullName>Associate Discount</fullName>
            </value>
            <value>
                <fullName>Authorization Hold</fullName>
            </value>
            <value>
                <fullName>Balance Confirmation (Points/Rewards)</fullName>
            </value>
            <value>
                <fullName>BBB Complaint</fullName>
            </value>
            <value>
                <fullName>Black Friday Complaint</fullName>
            </value>
            <value>
                <fullName>Brand Protection</fullName>
            </value>
            <value>
                <fullName>Bulk Buyer Warning</fullName>
            </value>
            <value>
                <fullName>Business Solicitation</fullName>
            </value>
            <value>
                <fullName>Call/Chat Disconnect</fullName>
            </value>
            <value>
                <fullName>Cancelled Item</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order Request</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Check Complaint</fullName>
            </value>
            <value>
                <fullName>Check Inventory/Restock Inquiry</fullName>
            </value>
            <value>
                <fullName>Check-out Error (Non-Fraud/Payment)</fullName>
            </value>
            <value>
                <fullName>Claim Status</fullName>
            </value>
            <value>
                <fullName>Contest/Sweepstakes</fullName>
            </value>
            <value>
                <fullName>Corporate Outfitters Request</fullName>
            </value>
            <value>
                <fullName>Corporate Responsibility</fullName>
            </value>
            <value>
                <fullName>Corp Social Responsibility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_First_Name__c</fullName>
    <description>Supplied First Name</description>
    <label>Supplied First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>Used for either the order tracking number or return tracking number</description>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/Webform_Brands__mdt.object-meta.xml
<CustomObject>
    <label>Brand Form - Brand</label>
    <pluralLabel>Brand Form - Brands</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Brand_Code__c.field-meta.xml
<CustomField>
    <fullName>Brand_Code__c</fullName>
    <description>Brand code mapped to Brand__c field api name</description>
    <label>Brand Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <description>Stores the name of the brands</description>
    <label>Brand_Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tommy Hilfiger</fullName>
                <default>true</default>
                <label>Tommy Hilfiger</label>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>True&amp;Co.</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
            <value>
                <fullName>Calvin Klein - CA</fullName>
            </value>
            <value>
                <fullName>Warner&#39;s</fullName>
                <isActive>false</isActive>
                <label>Warner&#39;s</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Case_Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Case_Success_Message__c</fullName>
    <label>Case Success Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Check_Order_Status_At__c.field-meta.xml
<CustomField>
    <fullName>Check_Order_Status_At__c</fullName>
    <description>Brand specific link to check order status</description>
    <label>Check Order Status At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>The BrandFormHeader static resource contains the logos for various brands. Provide relative URL of logos from this static resource.</description>
    <inlineHelpText>Provide relative URL of logos from BrandFormHeader static resource.</inlineHelpText>
    <label>Logo URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Password_Reset_At__c.field-meta.xml
<CustomField>
    <fullName>Password_Reset_At__c</fullName>
    <description>Brand specific link to reset password</description>
    <label>Password Reset At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Show_Logo__c.field-meta.xml
<CustomField>
    <fullName>Show_Logo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To show/hide logo in the brand form.</description>
    <label>Show Logo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Track_Order_At__c.field-meta.xml
<CustomField>
    <fullName>Track_Order_At__c</fullName>
    <description>Link to track order</description>
    <label>Track Order At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Use_Single_Brand_Channel__c.field-meta.xml
<CustomField>
    <fullName>Use_Single_Brand_Channel__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By checking this box, you are acknowledging that there&#39;s only a single Brand Channel needed for this brand. This also means, for this Brand, you cannot use multiple Additional Details as you are not using multiple Brand Channels.</inlineHelpText>
    <label>Use Single Brand Channel</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_BrandFormControllerTest.cls
/**
 * @description       : Test class for NF_BrandFormController
 * @author            :
 * @last modified on  : 08-05-2021
 * @last modified by  : chayan.batabyal@neuraflash.com
**/
@isTest
public class NF_BrandFormControllerTest {

    public static Webform_Brands__mdt getDefault(){
        Webform_Brands__mdt bnm = new Webform_Brands__mdt();
        bnm.Brand_Name__c = 'NF Test Brand';
        bnm.Brand_Code__c = 2.0;
        bnm.Case_Success_Message__c = 'Thank you. Your case number is CASENUMBER.';
        bnm.Track_Order_At__c = 'https://track.order.com';
        bnm.Logo_URL__c = 'https://logo.com';
        bnm.Password_Reset_At__c = 'https://password.reset.com';
        bnm.Check_Order_Status_At__c = 'https://status.order.com';
        bnm.Show_Logo__c = true;
        bnm.Use_Single_Brand_Channel__c = false;
        return bnm;
    }

    @isTest
    private static void testWrapperClass(){
        NF_BrandFormController.FieldObject fob = new NF_BrandFormController.FieldObject('Name','Name__c',false,'STRING');

        Webform_Brands__mdt bnm = getDefault();

        NF_BrandFormController.BrandObject bo = new NF_BrandFormController.BrandObject(bnm);
        System.assertEquals(bo.brandCode,2);

        NF_BrandFormController.PicklistObject pob = new NF_BrandFormController.PicklistObject();
        pob.label = 'In Progress';
        pob.value = 'inProgress';
        pob.parent = 'Default';
        pob.order = 2;
        pob.information = 'The work is in progress';
        pob.show = true;

        NF_BrandFormController.FormConfig fo = new NF_BrandFormController.FormConfig();

        System.assertEquals('',NF_BrandFormController.selectOption().value);

        NF_BrandFormController.CaseAttachmentObject cob = new NF_BrandFormController.CaseAttachmentObject();
        cob.parentId = 'someRandomCaseId';
        cob.filesToLink = new List<NF_BrandFormController.FileObject>{new NF_BrandFormController.FileObject()};
            cob.filesToDelete = new List<NF_BrandFormController.FileObject>{new NF_BrandFormController.FileObject()};
                System.assertEquals('someRandomCaseId',cob.parentId);
    }

    @isTest
    private static void testCaseCreationLoyalty(){
        String caseString = '{"filesToRelate": [],"filesToDelete": [],"Brand__c": 1,"Supplied_First_Name__c": "Amit","Supplied_Last_Name__c": "Gayal","SuppliedEmail": "amitgl259@gmail.com","SuppliedPhone": "+919899902749",';
        caseString += '"Channel__c": "Tommy.com","Reason_Code__c": "Loyalty","Reason_Code_Details__c": "Edit Account Information","Tracking_Number__c": "T0021321",';
        caseString += '"Order_Number__c": "O0021321","Description": "I cannot track my order. Please help me.\\n\\n", "Type": "Privacy"}';

        String caseId = NF_BrandFormController.createCase(caseString);
        System.assertNotEquals(NULL,caseId);
    }

    @isTest
    private static void testCaseCreationProduct(){
        String caseString = '{"filesToRelate": [],"filesToDelete": [],"Brand__c": 1,"Supplied_First_Name__c": "Amit","Supplied_Last_Name__c": "Gayal","SuppliedEmail": "amitgl259@gmail.com","SuppliedPhone": "+919899902749",';
        caseString += '"Channel__c": "Tommy.com","Reason_Code__c": "Product","Reason_Code_Details__c": "Defective Merchandise","Tracking_Number__c": "T0021321",';
        caseString += '"Order_Number__c": "O0021321","Description": "I cannot track my order. Please help me.\\n\\n", "Type": "Privacy"}';

        String caseId = NF_BrandFormController.createCase(caseString);
        System.assertNotEquals(NULL,caseId);
    }

    @isTest
    static void testDocumentUpdate()
    {
        ContentVersion contentVersionInsert = new ContentVersion(
            Title = 'Test Insert',
            PathOnClient = 'Test Insert.jpg',
            VersionData = Blob.valueOf('Test Content Data to insert'),
            IsMajorVersion = true
        );
        ContentVersion contentVersionDelete = new ContentVersion(
            Title = 'Test Delete',
            PathOnClient = 'Test Delete.jpg',
            VersionData = Blob.valueOf('Test Content Data to delete'),
            IsMajorVersion = true
        );

        insert new List<ContentVersion>{contentVersionInsert,contentVersionDelete};
        list<ContentVersion> docList = [Select id,ContentDocumentId  From ContentVersion where  Title = 'Test Insert' limit 1];
        /* ContentVersion contentVersionSelect = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id IN : new List<Id>{contentVersionInsert.Id,contentVersionDelete.Id}]; */
        NF_BrandFormController.FileObject rec = new NF_BrandFormController.FileObject();
        rec.name = 'Test Insert';
        rec.documentId = docList[0].ContentDocumentId;
        String result = NF_BrandFormController.updateFileDescription(JSON.serialize(new List<NF_BrandFormController.FileObject>{rec}));
        System.assertEquals('File update completed.', result);
        System.assert(NF_BrandFormController.updateFileDescription(null).equalsIgnoreCase('No related files found.'));
    }

    @isTest
    private static void testGetFormConfig(){
        String brandName = 'Tommy Hilfiger';
        NF_BrandFormController.FormConfig fg = NF_BrandFormController.getFormConfig(brandName);
        System.assertEquals(brandName,fg.brand.brandName);

        System.assertNotEquals(NULL, NF_BrandFormController.getAllBrands());
    }
}