unpackaged/main/default/objects/Account/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Accounts for Brands</description>
    <label>Brand</label>
</RecordType>

unpackaged/main/default/objects/Brand_Setting__mdt/Brand_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Privacy_Auto_Response_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Auto_Response_Email_Template__c</fullName>
    <label>Privacy Auto Response Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>This field is used to show Country in Personal Data Request Form</description>
    <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States of America (USA)</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Data_Owner__c.field-meta.xml
<CustomField>
    <fullName>Data_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Data Owner&#39;s Contact Record</description>
    <label>Data Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Privacy Requests</relationshipLabel>
    <relationshipName>PrivacyRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/emailToAddress__c.field-meta.xml
<CustomField>
    <fullName>emailToAddress__c</fullName>
    <label>emailToAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Perfect_Match_Found__c.field-meta.xml
<CustomField>
    <fullName>Perfect_Match_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether a Perfect Match was found for the privacy request</description>
    <label>Perfect Match Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Rejected Request</fullName>
            </value>
            <value>
                <fullName>No Response to follow-up</fullName>
            </value>
            <value>
                <fullName>Data Not Found</fullName>
            </value>
            <value>
                <fullName>User Data Provided</fullName>
            </value>
            <value>
                <fullName>User Data Deleted</fullName>
            </value>
            <value>
                <fullName>User Data Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Additional_Email_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_1__c</fullName>
    <description>The first additional email to send data owner requests to</description>
    <label>Additional Email 1</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_2__c</fullName>
    <description>The second additional email to send data owner requests to</description>
    <label>Additional Email 2</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_3__c</fullName>
    <description>The third additional email to send data owner requests to</description>
    <label>Additional Email 3</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_4__c</fullName>
    <description>The fourth additional email to send data owner requests to</description>
    <label>Additional Email 4</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/System_Type__c.field-meta.xml
<CustomField>
    <fullName>System_Type__c</fullName>
    <description>The type of system for which the Data Owner is Responsible</description>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>External - Managed By PVH</fullName>
            </value>
            <value>
                <fullName>Supplemental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PrivacyCaseTriggerHandler.cls
/**
* @author       : NeuraFlash, LLC
* @date       : 04/11/2021
* @description   : This class is needed because the privacy logic can only execute once due to its sending emails, 
*           which the CaseTriggerHandler interface does not allow 
*===========================================================
* Ver    Date            Author      Modification
*===========================================================
* 1.0    00/00/0000      -----      Initial Version (Unknown Creation Date)
* 1.1    04/28/2021    Luis Rocha    Adding the missing comparison statement for Marketing and removed system debugs
* 1.2    04/28/2021    Luis Rocha    Added bypassrun for test classes on each method to use, By putting the check at the top of the action we can ensure that bypass behavior is not dependent on external settings or configuration.
*/
public class PrivacyCaseTriggerHandler {
    
    public static Boolean isFirstRun = True;
    @testVisible static Boolean bypassRun = false;
    
    private static Id supportId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(System.Label.Support_Case).getRecordTypeId();
   
    public static void sendEmailsIfNecessary() {
        if(bypassRun) { return; }
        List<Case> privacyCases = new List<Case>();
        List<Id> newCaseIds = new List<Id>();
        List<Id> parentIds = new List<Id>();
        List<Id> dataOwnerIds = new List<Id>();
        List<Case> unsubCases = new List<Case>();
        List<Case> newEmailPrivacyCases = new List<Case>();
        for (sObject sobjCase : Trigger.new) {
            Case cse = (Case)sobjCase;
            if (
            ( cse.Type == Constants.privacyCaseType || cse.Type == System.Label.Marketing) &&
            cse.Sub_Type__c == Constants.unsubscribeRequestSubType
            ){
                unsubCases.add(cse);
            }
            
            if ((cse.RecordTypeId == Constants.dataOwnerCaseRecordTypeId ||  cse.RecordTypeId == Constants.privacyRecordTypeId || cse.RecordTypeId == supportId) && cse.Sub_Type__c !='Rectify My Data') {
                privacyCases.add(cse);
            } else {
                if ( cse.Type == Constants.privacyCaseType && cse.Sub_Type__c == Constants.unsubscribeRequestSubType) {
                    unsubCases.add(cse);
                }
                if (cse.Type == Constants.privacyCaseType && cse.Sub_Type__c == Constants.privacyEmailSubType && cse.Status == Constants.newPrivacyStatus && Trigger.isUpdate ) {
                    Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                    if (String.isNotBlank(cse.emailToAddress__c) && String.isBlank(oldCase.emailToAddress__c)) {
                        newEmailPrivacyCases.add(cse);
                    }
                }
                continue;
            }
            if (cse.Sub_Type__c == Constants.dataOwnerRequestSubType) {
                if (!parentIds.contains(cse.ParentId)) {
                    parentIds.add(cse.ParentId);
                }
                if (!dataOwnerIds.contains(cse.Data_Owner__c)) {
                    dataOwnerIds.add(cse.Data_Owner__c);
                }
            } else {
                if (Trigger.isInsert) {
                    newCaseIds.add(cse.Id);
                }
            }
        }
        if (privacyCases.size() > 0) {
            if (newCaseIds.size() > 0) {
                ContactFuture.processNewPrivacyCases(newCaseIds);
            }
            sendPrivacyEmailsIfNeeded(privacyCases, parentIds, dataOwnerIds);
            if (Trigger.isUpdate) {
                createChildCasesIfNeeded(privacyCases);
            }
        }
        if (unsubCases.size() > 0) {
            processUnsubCases(unsubCases);
        }
        if (newEmailPrivacyCases.size() > 0) {
            processNewEmailPrivacyCases(newEmailPrivacyCases);
        }
    }

    private static void processNewEmailPrivacyCases(List<Case> newUnsubCases) {
        if(bypassRun) { return; }
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : newUnsubCases) {
            List<Brand_Setting__mdt> brandSetting = [Select Privacy_Auto_Response_Email_Template__c From Brand_Setting__mdt Where Brand_Id__c = :cse.Brand__c];
            if (brandSetting.size() == 0) {
                continue;
            }
            
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, brandSetting[0].Privacy_Auto_Response_Email_Template__c, cse.SuppliedEmail);
            if (email == null) {
                continue;
            }
            emailsToSend.add(email);
        }
        emailHandler.sendEmails(emailsToSend);
    }
    private static void processUnsubCases(List<Case> unsubCases) {
        if(bypassRun) { return; }
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : unsubCases) {
            if (Trigger.isInsert && cse.Status == Constants.newPrivacyStatus) {
                Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U1UnsubscribeEmail, cse.SuppliedEmail);
                if (email == null) {
                    continue;
                }
                emailsToSend.add(email);
            } else if (cse.Status == Constants.resolved && Trigger.isUpdate) {
                Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                if (oldCase.status != Constants.resolved) {
                    if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                        Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U3UnsubscribeEmail, cse.SuppliedEmail);
                        if (email == null) {
                            continue;
                        }
                        emailsToSend.add(email);
                    } else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                        Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U2UnsubscribeEmail, cse.SuppliedEmail);
                        if (email == null) {
                            continue;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        emailHandler.sendEmails(emailsToSend);
    }
    private static void createChildCasesIfNeeded(List<Case> cases) {
        if(bypassRun) { return; }
        List<Case> casesNeedingUpdate = new List<Case>();
        List<Account> accountsWithSupplementalDataOwners = [Select Name From Account Where Id In (Select AccountId From Contact Where RecordTypeId = :Constants.dataOwnerContactRecordTypeId And System_Type__c = :Constants.dataOwnerSupplemental)];
        List<String> accountNamesWithSupplemental = new List<String>();
        Map<String,String> brandValueMap = new Map<String,String>();
        List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
        for (Schema.Picklistentry ple: fieldResult) {
            brandValueMap.put(ple.getValue(), ple.getLabel());
        }
        for (Account a : accountsWithSupplementalDataOwners) {
            if (!accountNamesWithSupplemental.contains(a.Name)) {
                accountNamesWithSupplemental.add(a.Name);
            }
        }
        for(Case cse : cases) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (
                cse.Type == Constants.privacyCaseType && 
                (cse.Sub_Type__c == Constants.accessRequestSubType || cse.Sub_Type__c == Constants.deletionRequestSubType ||cse.Sub_Type__c == Constants.rectifyRequestSubType) && 
                cse.Status == Constants.dataOwnersContacted &&
                oldCase.Status != Constants.dataOwnersContacted
            ) {
                if (cse.Perfect_Match_Found__c) {
                    if (cse.Sub_Type__c == Constants.accessRequestSubType && !accountNamesWithSupplemental.contains(brandValueMap.get(cse.Brand__c))) {
                        //CSR has all data for the brand already
                        Case newCase = new Case(Id=cse.Id);
                        newCase.Status = Constants.reviewResponseStatus;
                        casesNeedingUpdate.add(newCase);
                    } else {
                        //Need to contact data owners for deletion/additional info
                        ChildPrivacyCaseActionsHandler.createChildDataOwnerCases(cse.Id);
                    }
                } else {
                    if (!Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        // No Match and no NA, resolve the case.
                        Case newCase = new Case(Id=cse.Id);
                        newCase.Status = Constants.resolved;
                        newCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        casesNeedingUpdate.add(newCase);
                    } else {
                        if (accountNamesWithSupplemental.contains(brandValueMap.get(cse.Brand__c))) {
                            // In NA without a match, but need to see if supplemental owners have data on consumer
                            ChildPrivacyCaseActionsHandler.createChildDataOwnerCases(cse.Id);
                        } else {
                            // In NA, but no supplemental data owners to contact. resolve it.
                            Case newCase = new Case(Id=cse.Id);
                            newCase.Status = Constants.resolved;
                            newCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                            casesNeedingUpdate.add(newCase);
                        }
                    }
                }
            }
        }
        if (casesNeedingUpdate.size() > 0) {
            update casesNeedingUpdate;
        }
    }
    private static void sendPrivacyEmailsIfNeeded(List<Case> cases, List<Id> parentIds, List<Id> dataOwnerIds) {
        if(bypassRun) { return; }
        Map<Id, String> dataOwnerEmailMap = new Map<Id, String>();
        Map<Id, Case> parentCasesMap = new Map<Id, Case>();
        Map<Id, List<String>> dataOwnerAddtionalEmailsMap = new Map<Id, List<String>>();
        if (parentIds.size() > 0) {
            List <Case> parentCases = [Select Id, Sub_Type__c From Case Where Id In :parentIds];
            for (Case parentCase : parentCases) {
                parentCasesMap.put(parentCase.Id, parentCase);
            }
        }
        if (dataOwnerIds.size() > 0) {
            List<Contact> dataOwners= [Select Id, Email, Additional_Email_1__c, Additional_Email_2__c, Additional_Email_3__c, Additional_Email_4__c From Contact Where Id In :dataOwnerIds];
            for (Contact dataOwner : dataOwners) {
                List<String> additionalEmails = new List<String>();
                if (String.isNotBlank(dataOwner.Additional_Email_1__c)) additionalEmails.add(dataOwner.Additional_Email_1__c);
                if (String.isNotBlank(dataOwner.Additional_Email_2__c)) additionalEmails.add(dataOwner.Additional_Email_2__c);
                if (String.isNotBlank(dataOwner.Additional_Email_3__c)) additionalEmails.add(dataOwner.Additional_Email_3__c);
                if (String.isNotBlank(dataOwner.Additional_Email_4__c)) additionalEmails.add(dataOwner.Additional_Email_4__c);
                dataOwnerAddtionalEmailsMap.put(dataOwner.Id, additionalEmails);
                dataOwnerEmailMap.put(dataOwner.Id, dataOwner.Email);
            }
        }
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : cases) {
            if (cse.Type != Constants.privacyCaseType ) {
                continue;
            }
            if (cse.Sub_Type__c == Constants.accessRequestSubType) {
                emailsToSend = processAccessCases(cse, emailsToSend, emailHandler);
            }
            if (cse.Sub_Type__c == Constants.dataOwnerRequestSubType && String.isNotBlank(cse.Id)) {
                emailsToSend = processDataOwnerCases(cse, emailsToSend, emailHandler, parentCasesMap, dataOwnerAddtionalEmailsMap, dataOwnerEmailMap);
            }
            if (cse.Sub_Type__c == Constants.deletionRequestSubType ) {
                emailsToSend = processDeletionCase(cse, emailsToSend, emailHandler);
            }
            if (cse.Sub_Type__c == Constants.rectifyRequestSubType) {
                emailsToSend = processUpdationCase(cse, emailsToSend, emailHandler);
            }
			if (cse.Sub_Type__c == Constants.doNotSellorShare) { // added as part of GCT-772
				emailsToSend = processdoNotSellShareCase(cse, emailsToSend, emailHandler);
			}
            
        }
        if (emailsToSend.size() > 0) {
            emailHandler.sendEmails(emailsToSend);
        }
    }
    private static List<Messaging.SingleEmailMessage> processAccessCases(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if(bypassRun) { return new List<Messaging.SingleEmailMessage>(); }
        if (Trigger.isInsert) {
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.A1RequestEmail);
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);
        } else if (Trigger.isUpdate) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataProvided) {
                    // NO AUTOMATED EMAIL, CSR MANUALLY SENDS
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                    email = emailHandler.createEmail(cse, Constants.A2RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                    email = emailHandler.createEmail(cse, Constants.A3RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedStalled) {
                    email = emailHandler.createEmail(cse, Constants.A10RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.A7RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    } else {
                        email = emailHandler.createEmail(cse, Constants.A8RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
        
    }
    private static List<Messaging.SingleEmailMessage> processDeletionCase(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if(bypassRun) { return new List<Messaging.SingleEmailMessage>(); }
        if (Trigger.isInsert) {
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.D1RequestEmail);
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);
        } else if (Trigger.isUpdate) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataDeleted) {
                    email = emailHandler.createEmail(cse, Constants.D4RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                }else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                    email = emailHandler.createEmail(cse, Constants.D7RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                    email = emailHandler.createEmail(cse, Constants.D8RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedStalled) {
                    email = emailHandler.createEmail(cse, Constants.D10RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.D5RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    } else {
                        email = emailHandler.createEmail(cse, Constants.D9RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
    }
    
    private static List<Messaging.SingleEmailMessage> processUpdationCase(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if(bypassRun) { return new List<Messaging.SingleEmailMessage>(); }
        if (Trigger.isInsert) {
        //    Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U1RequestEmail);
      /*  Messaging.SingleEmailMessage email = emailHandler.createEmail(cse,'R2RIdentityVerification');
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);*/
        } else if (Trigger.isUpdate) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataUpdated) {
                    email = emailHandler.createEmail(cse, Constants.U4RequestEmail);//data updated
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                }else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.U5RequestEmail);//CSR alerts consumer that there is not record to be updated'
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }else {
                        email = emailHandler.createEmail(cse, Constants.D9RequestEmail);//No Match -> Non EU/NA Consumer -> CSR alerts non NA/EU consumer';
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
    }
	// added as part of GCT-772
	private static List<Messaging.SingleEmailMessage> processdoNotSellShareCase(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if(bypassRun) { return new List<Messaging.SingleEmailMessage>(); }
        if (Trigger.isInsert) {
        //    Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U1RequestEmail);
      /*  Messaging.SingleEmailMessage email = emailHandler.createEmail(cse,'R2RIdentityVerification');
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);*/
        } else if (Trigger.isUpdate) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataUpdated) {
                    email = emailHandler.createEmail(cse, Constants.S4RequestEmail);//data updated
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                }else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.S5RequestEmail);//CSR alerts consumer that there is not record to be updated'
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    } else {
                        email = emailHandler.createEmail(cse, Constants.D9RequestEmail);//No Match -> Non EU/NA Consumer -> CSR alerts non NA/EU consumer';
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
    }
    
    private static List<Messaging.SingleEmailMessage> processDataOwnerCases(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler, Map<Id, Case> parentCasesMap, Map<Id, List<String>> dataOwnerAddtionalEmailsMap, Map<Id, String> dataOwnerEmailMap) {
        if(bypassRun) { return new List<Messaging.SingleEmailMessage>(); }
        Case parentCase = parentCasesMap.get(cse.ParentId);
        if (Trigger.isInsert) {
            String emailTemplate;
            if (parentCase.Sub_Type__c == Constants.accessRequestSubType) {
                emailTemplate = Constants.A5RequestEmail;
            }else if(parentCase.Sub_Type__c == Constants.deletionRequestSubType){
                emailTemplate = Constants.D3RequestEmail;
            }else if(parentCase.Sub_Type__c == Constants.rectifyRequestSubType){
                emailTemplate = Constants.U3RequestEmail;
            }else if(parentCase.Sub_Type__c == Constants.doNotSellorShare){
                emailTemplate = Constants.S3RequestEmail;
            }
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, emailTemplate, dataOwnerEmailMap.get(cse.Data_Owner__c));
            if (email == null) {
                return emailsToSend;
            }
            List<String> additionalEmailAddresses = dataOwnerAddtionalEmailsMap.get(cse.Data_Owner__c);
            if (additionalEmailAddresses.size() > 0) {
                email.setCcAddresses(additionalEmailAddresses);
                    
            }
            emailsToSend.add(email);
        }
        if (Trigger.isUpdate) {
            if(Constants.privacyCaseCompletedStatuses.contains(cse.Status)) {
                Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                if (!Constants.privacyCaseCompletedStatuses.contains(oldCase.Status)) {
                    system.debug('>>>>>>>>>inside method>>>>>>');
                    ChildPrivacyCaseActionsHandler.handleChildCaseResolved(cse.Id, cse.parentId);
                }
            }
        }
        return emailsToSend;
    }
}