unpackaged/main/default/objects/Case/fields/Additional_Privacy_Request_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Privacy_Request_Information__c</fullName>
    <description>This field will contain additional information to send to the Data Owners to process data owner requests</description>
    <inlineHelpText>This field will contain additional information to send to the Data Owners to process data owner requests</inlineHelpText>
    <label>Additional Privacy Request Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>This field is used to show Country in Personal Data Request Form</description>
    <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States of America (USA)</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Loyalty_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Account_Number__c</fullName>
    <label>Loyalty Account Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Perfect_Match_Found__c.field-meta.xml
<CustomField>
    <fullName>Perfect_Match_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether a Perfect Match was found for the privacy request</description>
    <label>Perfect Match Found</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rectified_Data__c.field-meta.xml
<CustomField>
    <fullName>Rectified_Data__c</fullName>
    <label>Rectified Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/State_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence__c</fullName>
    <description>This Field is used to Show States in Personal Data Form</description>
    <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
    <label>State of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_of_Residence__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Country_ds__c.field-meta.xml
<CustomField>
    <fullName>Country_ds__c</fullName>
    <description>To Capture the country values for CK brand</description>
    <label>Country DS</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DataOwner_Subtype__c.field-meta.xml
<CustomField>
    <fullName>DataOwner_Subtype__c</fullName>
    <description>Track customer privacy request type ex: unsubscribe,Delete My Data..etc</description>
    <label>Sub Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
            <value>
                <fullName>Advertising/Sharing Opt-Out</fullName>
                <isActive>false</isActive>
                <label>Advertising/Sharing Opt-Out</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/System_Type__c.field-meta.xml
<CustomField>
    <fullName>System_Type__c</fullName>
    <description>The type of system for which the Data Owner is Responsible</description>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>External - Managed By PVH</fullName>
            </value>
            <value>
                <fullName>Supplemental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ChildPrivacyCaseActionsHandler.cls
public class ChildPrivacyCaseActionsHandler {

    @future
    public static void createChildDataOwnerCases(Id caseId) {
        Case cse = [Select Id, Type, OwnerId, AccountId, Brand__c, ContactId,Contact.Country_ds__c, SuppliedEmail, SuppliedName, SuppliedPhone, Origin, Country_of_Residence__c,Rectified_Data__c, State_of_Residence__c, Sub_Type__c, Additional_Privacy_Request_Information__c, Perfect_Match_Found__c, Due_Date__c, Loyalty_Account_Number__c From Case Where Id = :caseId];
        Map<String,String> brandValueMap = new Map<String,String>();
        Group dssQueue = [Select Id, Name from group where name = 'Advertising Opt-Out Request' limit 1];
        Group r2rQueue = [Select Id, Name from group where name = 'RTR Request' limit 1];
        List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
        for (Schema.Picklistentry ple: fieldResult) {
            brandValueMap.put(ple.getValue(), ple.getLabel());
        }
        String brandName = brandValueMap.get(cse.Brand__c);
        system.debug(brandName);
       //if((!string.isblank(cse.Country_of_Residence__c) && cse.Country_of_Residence__c=='Canada') || (!string.isBlank(cse.Contact.Country_ds__c) && cse.Contact.Country_ds__c=='CA'))
        if(((!string.isblank(cse.Country_of_Residence__c) && cse.Country_of_Residence__c=='Canada') || (!string.isBlank(cse.Contact.Country_ds__c) && cse.Contact.Country_ds__c=='CA')) && brandName=='Calvin Klein'){
             brandName=brandName+' '+'Canada';
        }
        List<Contact> dataOwners;
        //system.debug(brandName);
        //system.debug(cse.Sub_Type__c+' '+cse.Perfect_Match_Found__c+' '+Constants.dataOwnerContactRecordTypeId+' '+Constants.dataOwnerSupplemental);

        if (cse.Sub_Type__c == Constants.accessRequestSubType) {
            dataOwners = [Select Id, Email,DataOwner_Subtype__c From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and System_Type__c = :Constants.dataOwnerSupplemental and RecordTypeId = :Constants.dataOwnerContactRecordTypeId];
        } else {
            if (cse.Perfect_Match_Found__c) {
                dataOwners = [Select Id, Email,DataOwner_Subtype__c From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and RecordTypeId = :Constants.dataOwnerContactRecordTypeId];
            } else {
                dataOwners = [Select Id, Email,DataOwner_Subtype__c From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and RecordTypeId = :Constants.dataOwnerContactRecordTypeId and System_Type__c = :Constants.dataOwnerSupplemental ];
            }
             
        }
        //system.debug(dataOwners);
        List<Case> newCases = new List<Case>();
        for (Contact dataOwner : dataOwners) {
            if(!string.isBlank(dataOwner.DataOwner_Subtype__c) && dataOwner.DataOwner_Subtype__c.contains(cse.Sub_Type__c)){
                Case newCase = cse.clone();
                newCase.Sub_Type__c = Constants.dataOwnerRequestSubType;
                newCase.Status = Constants.waitingForResponse;
                newCase.Data_Owner__c = dataOwner.Id;
                newCase.ParentId = cse.Id;
                newCase.RecordTypeId = Constants.dataOwnerCaseRecordTypeId;
                newCase.Description = cse.Rectified_Data__c;
                if(cse.Sub_Type__c == 'Do Not Sell/Share'){
                    newCase.ownerId = dssQueue.Id;
                }
                if(cse.Sub_Type__c == 'Rectify My Data'){
                    newCase.ownerId = r2rQueue.Id;
                }
                Log.push('===newcase '+ newCase);
                newCases.add(newCase);
           }
        }   
        insert newCases;
    }

    @future
    public static void handleChildCaseResolved(Id caseId, Id parentId) {
        addAttachmentsToParent(caseId, parentId);
        updateParentCaseIfAllChildrenClosed(parentId);
    }

    public static void addAttachmentsToParent(Id caseId, Id parentId) {
        List<EmailMessage> messagesWithAttachments = [Select Id From EmailMessage Where ParentId = :caseId And Incoming=True And HasAttachment=True];
        if (messagesWithAttachments.size() > 0) {
            List<Id> messageIds = new List<Id>();
            for (EmailMessage message : messagesWithAttachments) {
                messageIds.add(message.Id);
            }
            List<ContentDocumentLink> oldLinks = [Select Id, ContentDocumentId, LinkedEntityId, ShareType, Visibility From ContentDocumentLink Where LinkedEntityId In :messageIds];
            List<ContentDocumentLink> newLinks = new List<ContentDocumentLink>();
            for (ContentDocumentLink oldLink :oldLinks) {
                ContentDocumentLink newLink = oldLink.clone();
                newLink.LinkedEntityId = parentId;
                newLinks.add(newLink);
            }
            Log.push('===new links' + newLinks);
            Logger.logDebug();
            insert newLinks;
        }
    }

    public static void updateParentCaseIfAllChildrenClosed(Id caseId) {
        List<Case> omniCases = new List<Case>();

        Integer openChildren = [Select Count() From Case Where ParentId = :caseId And Status Not In :Constants.privacyCaseCompletedStatuses];
        Log.push('open children' + openChildren);
        if (openChildren == 0) {
            Case parentCase = [Select Id, Sub_Type__c, Status, Perfect_Match_Found__c, Originating_Queue_Id__c, State_of_Residence__c, RecordTypeId From Case Where Id = :caseId];
            if (parentCase.Status != Constants.resolved && !Constants.privacyCaseCompletedStatuses.contains(parentCase.Status)) {
                Log.push('===status good' + parentCase);
                parentCase.Status = Constants.resolved;
                if (parentCase.Sub_Type__c == Constants.deletionRequestSubType || parentCase.Sub_Type__c == Constants.doNotSellorShare){//added as part of GCT-772
                    if (parentCase.Perfect_Match_Found__c) {
                        parentCase.Resolution_Code__c = Constants.privacyResolvedDataDeleted;
                    } else {
                        Integer childDeletionsCount = [Select Count() From Case Where ParentId = :caseId And Resolution_Code__c = :Constants.privacyResolvedDataDeleted];
                        if ( childDeletionsCount == 0) {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        } else {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedDataDeleted;
                        }
                    }
                    
                }else if (parentCase.Sub_Type__c == Constants.rectifyRequestSubType) {
                    if (parentCase.Perfect_Match_Found__c) {
                        parentCase.Resolution_Code__c = Constants.privacyResolvedDataUpdated;
                    } else {
                        Integer childUpdatedCount = [Select Count() From Case Where ParentId = :caseId And Resolution_Code__c = :Constants.privacyResolvedDataUpdated];
                        if ( childUpdatedCount == 0) {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        } else {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedDataUpdated;
                        }
                    }
                    
                }else if (parentCase.Sub_Type__c == Constants.accessRequestSubType) {
                    if (parentCase.Perfect_Match_Found__c) {
                        parentCase.Status = Constants.reviewResponseStatus;
                        omniCases.add(parentCase);
                    } else {
                        Integer childProvidedCount = [Select Count() From Case Where ParentId = :caseId And Resolution_Code__c = :Constants.privacyResolvedDataProvided];
                        if ( childProvidedCount == 0) {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        } else {
                            parentCase.Status = Constants.reviewResponseStatus;
                            omniCases.add(parentCase);
                        }
                    }
                }
              If (UserInfo.getName()!='MuleSoft APIUser'){ 
                if (omniCases.size() > 0) {
                    PrivacyCaseQueueHandler.sendCasesToOmni(omniCases);
                    update omniCases;
                } else {
                    update parentCase;
                }
            }
          
            }
        }
        Logger.logDebug();
    }

}