unpackaged/main/default/objects/Case/fields/B2C_Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Locked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</description>
    <inlineHelpText>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</inlineHelpText>
    <label>Ecomm Customer Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the current B2C Commerce Customer Profile is locked-out and being prevented from logging into the storefront.</description>
    <inlineHelpText>... describes if the current B2C Commerce Customer Profile is locked-out and being prevented from logging into the storefront.</inlineHelpText>
    <label>B2C Is Locked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactCheck.cls
//Description: 
public without sharing class ContactCheck {
    @AuraEnabled
    public static String getContactId(Id CaseId){
        list<Case> conId = [select ContactId,Brand__c from Case where Id =:CaseId];
        
        if (conId[0].ContactId != NULL){
            Contact con = [select Id,B2C_Is_Enabled__c,B2C_Is_Locked__c,Brand_Id__c from Contact where Id=:conId[0].ContactId];
            if (con.B2C_Is_Enabled__c==false){
                Return SYSTEM.LABEL.This_Customer_Account_is_Disabled_you_cannot_place_an_Order;
            }
            else{
                if (con.B2C_Is_Locked__c == true){
                    Return SYSTEM.LABEL.This_Customer_Account_is_Locked_please_unlock_before_placing_an_Order;
                }
                else{
                    if(con.Brand_Id__c != conId[0].Brand__c){
                        Return 'Brand of Case is not same as the Contact';
                    }
                    else{
                    	Return conId[0].ContactId;            
                    }
            		
                }
            }
        }
        else {
            Return SYSTEM.LABEL.STOP_You_must_create_a_contact_record_or_associate_contact_record_with_an_exist;
        }
    }
    
	@AuraEnabled
    public static Boolean eCommConnectedFlag(Id contactId){
        list<Contact> con = [select Ecomm_Connected__c from Contact where Id =:contactId and Ecomm_Connected__c =:true and B2C_Customer_No__c !=:''];
        if (con.isEmpty() == True){
            Return true;
        }
        else {
        	Return false;    
        }
        
    }
    
    @AuraEnabled
    public static Contact eCommOtherCont(Id contactId){
        list<Contact> conList = [select Email,FirstName,LastName,LoyaltyID__c from Contact where Id =:contactId];
        if (conList[0].Email != ''){
        	String mail = conList[0].Email;
            Contact conEcomm = [select Id,FirstName,LastName,Email,Ecomm_Connected__c,LoyaltyID__c,Brand__c from Contact where Ecomm_Connected__c =true and B2C_Customer_No__c !=:''
                                and Email = :mail and FirstName =:conList[0].FirstName and LastName=:conList[0].LastName
                                and LoyaltyID__c =:conList[0].LoyaltyID__c limit 1];
            if (conEcomm.Id == NULL)
            {
            	return NULL;    
            }
            else {
                return conEcomm;
            }
        }
        else{
            return NULL;
        }
    }
    
    @AuraEnabled
    public static Id linkContact(Id CaseId, List<Contact> Cont){
        list<Case> cs = [select Id,ContactId from Case where Id =:CaseId];
        if (cs[0].ContactId != NULL && Cont[0].Id !=NULL){
        	cs[0].ContactId = Cont[0].Id;    
        }
        update cs[0];
        return Cont[0].Id;
    }
    
}