unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZdTnCUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C User Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EmailMessageTriggerHandlerTest.cls
/**
* @author Magnet360
*
* @date 2019
*
* @description Test Clas for EmailMessageTriggerHandler
*
* @see EmailMessageTriggerHandler
*/
@isTest
public class EmailMessageTriggerHandlerTest {

    @testSetup
    static void setupData() {
        Account acc = new Account(Name='Test Account ABC');
        insert acc;

        Entitlement testEntitlement = new entitlement(name='Test Entilement',accountid=acc.id,type='Gateway Support', StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)));
        insert testEntitlement;

        Entitlement testEntitlement1 = new entitlement(name='Test Entilement',accountid=acc.id,type='Gateway Support', StartDate=Date.valueof(System.now().addDays(-2)), EndDate=Date.valueof(System.now().addYears(2)));
        insert testEntitlement1;

        /*DML operation cannot be performed on SLAProcess Object (i.e. Entitlement Process).
        Need to rely on organization data. Retrieve the entry from organization and associate it to Entitlement.*/
        List<SlaProcess> lstEntitlementProcess = [SELECT Id, Name FROM SlaProcess WHERE Name='1 Day (24 Hour Reply)' and IsActive = true LIMIT 1];
        if (lstEntitlementProcess.size()>0)
        {
            testEntitlement.SlaProcessId = lstEntitlementProcess[0].id;
            update testEntitlement;
        }


        //List<SlaProcess> lstEntitlementProcess1 = [SELECT Id, Name FROM SlaProcess WHERE Name='2 Day (48 Hour Reply)' and IsActive = true LIMIT 1];
        // if (lstEntitlementProcess1.size()>0)//
        {
            //  testEntitlement1.SlaProcessId = lstEntitlementProcess1[0].id;
            //  update testEntitlement1;
        }//

        contact con =new contact(LastName='TestName',Email='abc@gmail.com',Brand_Id__c='1');
        insert con;

        Case testCase = new Case(EntitlementId=testEntitlement.Id, SlaStartDate = System.now().addDays(-1), Subject='Test Milestome completion', Origin = 'Email' , suppliedEmail = 'testCase1@gmail.com' , ZdTnCUserId__c = '230000',ZdTnCTicketId__c = '3333999',Brand__c='1');
        insert testCase;

        Case testCase1 = new Case(EntitlementId=testEntitlement.Id, SlaStartDate = System.now().addDays(-1), Subject='Test Milestome completion', Origin = 'Email' , suppliedEmail = 'testCase2@gmail.com' ,parentid=testcase.id,Brand__c='1');
        insert testCase1;
    }


    private static testMethod void testCompleteMilestone()
    {

        Case testCase = [Select Id from Case where SuppliedEmail = 'testCase1@gmail.com'];
        Case testCase1 = [Select Id from Case where SuppliedEmail = 'testCase2@gmail.com'];


        //CaseMilestone testCaseMilestone = new CaseMilestone(CaseId = testCase.Id);
        //insert testCaseMilestone;mwec v

        //Insert emailmessage for case
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = false;
        email.ToAddress= 'abc@gmail.com';
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
        email.ParentId = testCase.Id;
        insert email;



        //For Child Case
        EmailMessage email1 = new EmailMessage();
        email1.FromAddress = 'abc@gmail.com';
        email1.Incoming = true;
        email1.ToAddress= 'test@abc.org';
        email1.Subject = 'Test email';
        email1.HtmlBody = 'Test email body';
        email1.ParentId = testCase1.Id;
        insert email1;


    }
    private static testMethod void testUpdateEmail()
    {

        Case testCase = [Select Id from Case where SuppliedEmail = 'testCase1@gmail.com'];


        //CaseMilestone testCaseMilestone = new CaseMilestone(CaseId = testCase.Id);
        //insert testCaseMilestone;mwec v

        //Insert emailmessage for case
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = false;
        email.ToAddress= 'abc@gmail.com';
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
        email.ParentId = testCase.Id;
        email.status = '0';
        insert email;

        email.subject = 'Update Email';
        email.status = '3';
        update email;




    }
    private static testMethod void testIncomingEmail()
    {

        Case testCase = [Select Id from Case where SuppliedEmail = 'testCase1@gmail.com'];


        //CaseMilestone testCaseMilestone = new CaseMilestone(CaseId = testCase.Id);
        //insert testCaseMilestone;mwec v

        //Insert emailmessage for case
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = false;
        email.ToAddress= 'abc@gmail.com';
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
        email.ParentId = testCase.Id;
        email.Incoming = true;
        email.status = '0';
        insert email;

        email.status = '3';
        update email;




    }
}