unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Originating_Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Originating_Queue_Id__c</fullName>
    <label>Originating Queue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/State_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence__c</fullName>
    <description>This Field is used to Show States in Personal Data Form</description>
    <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
    <label>State of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_of_Residence__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PrivacyCaseQueueHandler.cls
/**
 * @author Magnet360
 * @date 2019
 *
 * @group Case
 * @group-content ../../ApexDocContent/Case.htm
 *
 * @description Class responsible for adding Privacy cases to their respective queues.
 * Extracted to a class so it could also be called from Process Builder.
 */
public class PrivacyCaseQueueHandler{
    /***********************************************************************************************
     * @description Invocable Method to Add Privacy Cases to their Omni Queues
     * @param cases List of cases to process
     */
    @InvocableMethod(label = 'Assign Privacy Case To Omni Queue')
    public static void invocablePrivacyQueueAssignment(List<Case> cases){
        Log.push('===calling invocable ' + cases);
        if (cases.size() > 0){
            cases = sendCasesToOmni(cases);
            update cases;
        }
        Logger.logDebug();
    }

    /***********************************************************************************************
     * @description Updates OwnerId of Privacy Cases to their respective omni queues
     * @param cases List of cases to update
     * @return The list of cases with ownerId updated (not saved yet)
     */
    public static List<Case> sendCasesToOmni(List<Case> cases){
        Log.push('===sending to omni ' + cases);
        Map<String, Id> queueNameMap = new Map<String, Id>();
        List<Group> possibleQueues = [Select Id, DeveloperName
                                      from Group
                                      where Type =: SYSTEM.LABEL.Queue And DeveloperName In:Constants.privacyCaseQueueNames];
        for (Group q : possibleQueues){
            queueNameMap.put(q.DeveloperName, q.Id);
        }
        Log.push('===queueNameMap ' + queueNameMap);
        for (Case cse : cases){
            if ((cse.RecordTypeId == Constants.dataOwnerCaseRecordTypeId && (String.isNotBlank(cse.ParentId) || cse.ParentId!=Null)) || (cse.RecordTypeId == Constants.supportCaseRecordTypeId && cse.Sub_Type__c != Constants.unsubscribeRequestSubType && cse.Sub_Type__c=='')){
                Log.push('continue@@@');
                 system.debug('continue@@@');
                continue;
            }
            if (String.isNotBlank(cse.Originating_Queue_Id__c)){
                Log.push('Setting Originating Queue from PrivacyCaseQueueHandler');
                  system.debug('Setting Originating Queue from PrivacyCaseQueueHandler');
                cse.OwnerId = cse.Originating_Queue_Id__c;
            } else{
                if ((cse.Sub_Type__c == Constants.unsubscribeRequestSubType && (!Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))||
                    (cse.Sub_Type__c == Constants.accessRequestSubType && (!Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))||
                    (cse.Sub_Type__c == Constants.deletionRequestSubType && (!Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))
                   ){
                    Log.push('unsubscribeCase to lowPriorityPrivacyCaseQueue@@@');
                     system.debug('unsubscribeCase to lowPriorityPrivacyCaseQueue@@@');
                    cse.OwnerId = queueNameMap.get(Constants.lowPriorityPrivacyCaseQueue);
                } else if (
                    (cse.Sub_Type__c == Constants.unsubscribeRequestSubType && (Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))||
                    (cse.Sub_Type__c == Constants.accessRequestSubType && (Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))||
                    (cse.Sub_Type__c == Constants.deletionRequestSubType && (Constants.privacyHighPriorityStates.contains(cse.State_of_Residence__c)))
                   ){
                    Log.push('highPriorityPrivacyCaseQueue@@@');
                     system.debug('highPriorityPrivacyCaseQueue@@@');
                    cse.OwnerId = queueNameMap.get(Constants.highPriorityPrivacyCaseQueue);
                } else if (cse.Sub_Type__c == Constants.privacyEmailSubType){
                    Log.push('unassignedPrivacyQueue@@@');
                     system.debug('unassignedPrivacyQueue@@@');
                    cse.OwnerId = queueNameMap.get(Constants.unassignedPrivacyQueue);
                } else if((cse.Sub_Type__c ==Null && cse.Sub_Type__c =='') && (cse.Type ==Null && cse.Type =='')&& (cse.Brand__c==Null && cse.Brand__c=='')){
                    cse.OwnerId =queueNameMap.get(Constants.spamQueue);
                }
                /*else if(cse.OwnerId==Null){
                    Log.push('Default_Case_Queue@@@');
                     system.debug('Default_Case_Queue@@@');
                    cse.OwnerId =queueNameMap.get(Constants.defaultQueue);
                }*/
            }
            Log.push('===OwnerId ' + cse.OwnerId);
                                system.debug('===OwnerId ' + cse.OwnerId);
        }
        Logger.logDebug();
        return cases;
    }

}