unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>Controlled By Account - This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Data_Owner__c.field-meta.xml
<CustomField>
    <fullName>Data_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Data Owner&#39;s Contact Record</description>
    <label>Data Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Privacy Requests</relationshipLabel>
    <relationshipName>PrivacyRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Hours_Since_Creation__c.field-meta.xml
<CustomField>
    <fullName>Hours_Since_Creation__c</fullName>
    <formula>FLOOR(NOW() - CreatedDate ) * 24</formula>
    <label>Hours Since Creation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Escalation_Email__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Escalation_Email__c</fullName>
    <description>Controlled by Account - The email address to use when data owner cases need to be escalated</description>
    <label>Privacy Escalation Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_1__c</fullName>
    <description>The first additional email to send data owner requests to</description>
    <label>Additional Email 1</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_2__c</fullName>
    <description>The second additional email to send data owner requests to</description>
    <label>Additional Email 2</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_3__c</fullName>
    <description>The third additional email to send data owner requests to</description>
    <label>Additional Email 3</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Additional_Email_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email_4__c</fullName>
    <description>The fourth additional email to send data owner requests to</description>
    <label>Additional Email 4</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/Privacy_Intervals__c/Privacy_Intervals__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Intervals to send privacy emails in hours</description>
    <label>Privacy Intervals</label>
</CustomObject>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/CaseEscalationHours__c.field-meta.xml
<CustomField>
    <fullName>CaseEscalationHours__c</fullName>
    <description>The Number of Hours after confirmation that can pass until the privacy case is escalated</description>
    <label>CaseEscalationTime</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/maxDataOwnerTime__c.field-meta.xml
<CustomField>
    <fullName>maxDataOwnerTime__c</fullName>
    <description>The amount of hours that the data owner has to complete their privacy task</description>
    <label>maxDataOwnerTime</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/reminderDataOwnerInterval__c.field-meta.xml
<CustomField>
    <fullName>reminderDataOwnerInterval__c</fullName>
    <description>The Number of hours interval that an email reminder is sent to data owners</description>
    <label>reminderDataOwnerInterval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Batch_PrivacyDataOwnerCaseReminders.cls
/**
* @author Magnet360
* @date 2019
*
* @group Case
* @group-content ../../ApexDocContent/Case.htm
*
* @description Batch class to send data owner reminder emails once they have
* been open longer than the time set in custom settings
* Called hourly from SchedulableBatch_PrivacyIntervalActions
*/
global class Batch_PrivacyDataOwnerCaseReminders implements Database.Batchable <sObject>{

    global List<Case> start(Database.BatchableContext bc){
        System.debug('===starting data owners?');
        Privacy_Intervals__c orgInterval;
        Integer dataOwnerReminderIntervalHours;
        List<Integer> dataOwnerReminderIntervalMatchingValues = new List<Integer>();

        orgInterval = Privacy_Intervals__c.getValues(Constants.privacyIntervalSettingName);
        dataOwnerReminderIntervalHours = Integer.valueOf(orgInterval.reminderDataOwnerInterval__c);
        Double totalReminders = Math.floor(Integer.valueOf(orgInterval.maxDataOwnerTime__c) / dataOwnerReminderIntervalHours);
        for (Integer i = 1; i <= totalReminders; i++) {
            dataOwnerReminderIntervalMatchingValues.add(dataOwnerReminderIntervalHours*i);
        }
        System.debug('===batch settings' + dataOwnerReminderIntervalMatchingValues + dataOwnerReminderIntervalMatchingValues + dataOwnerReminderIntervalHours);

        return [Select Id, Status, Brand__c, SuppliedEmail, ContactId, Data_Owner__r.Email, Data_Owner__r.Additional_Email_1__c, Data_Owner__r.Additional_Email_2__c,Data_Owner__r.Additional_Email_3__c,Data_Owner__r.Additional_Email_4__c, Hours_Since_Creation__c, Brand_Privacy_OWA_Name__c, Parent.Sub_Type__c, Privacy_Escalation_Email__c From Case Where Type = :Constants.privacyCaseType And Sub_Type__c = :Constants.dataOwnerRequestSubType And Hours_Since_Creation__c In :dataOwnerReminderIntervalMatchingValues And Status Not In :Constants.privacyCaseCompletedStatuses];
    }

    global void execute(Database.BatchableContext bc, List<Case> cases){
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        Integer escalationHours = Integer.valueOf(Privacy_Intervals__c.getValues(Constants.privacyIntervalSettingName).CaseEscalationHours__c);

        System.debug('===dataOwnerReminderCases' + cases);
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        for (Case cse : cases) {
            List<String> ccAddresses = new List<String>();
            if (String.isNotBlank(cse.Data_Owner__r.Additional_Email_1__c)) ccAddresses.add(cse.Data_Owner__r.Additional_Email_1__c);
            if (String.isNotBlank(cse.Data_Owner__r.Additional_Email_2__c)) ccAddresses.add(cse.Data_Owner__r.Additional_Email_2__c);
            if (String.isNotBlank(cse.Data_Owner__r.Additional_Email_3__c)) ccAddresses.add(cse.Data_Owner__r.Additional_Email_3__c);
            if (String.isNotBlank(cse.Data_Owner__r.Additional_Email_4__c)) ccAddresses.add(cse.Data_Owner__r.Additional_Email_4__c);
            if (cse.Hours_Since_Creation__c >= escalationHours) {
                String emailTemplate;
                if (cse.Parent.Sub_Type__c == Constants.deletionRequestSubType) {
                    emailTemplate = Constants.deletionDataOwnerEscalationEmail;
                }else if (cse.Parent.Sub_Type__c == Constants.rectifyRequestSubType) {
                    emailTemplate = Constants.updationDataOwnerEscalationEmail;
                }else if (cse.Parent.Sub_Type__c == Constants.doNotSellorShare) {//added as part of GCT-772
                    emailTemplate = Constants.doNotSellorShareDataOwnerEscalationEmail;
                }else {
                    emailTemplate = Constants.accessDataOwnerEscalationEmail;
                }
                Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, emailTemplate, cse.Data_Owner__r.Email);
                if (email == null) {
                    continue;
                }
                ccAddresses.add(cse.Privacy_Escalation_Email__c);
                email.setCcAddresses(ccAddresses);
                emailsToSend.add(email);
            } else {
                String emailTemplate;
                if (cse.Parent.Sub_Type__c == Constants.deletionRequestSubType) {
                    emailTemplate = Constants.deletionDataOwnerReminderEmail;
                }else if (cse.Parent.Sub_Type__c == Constants.rectifyRequestSubType) {
                    emailTemplate = Constants.updationDataOwnerReminderEmail;
                }else if (cse.Parent.Sub_Type__c == Constants.doNotSellorShare) {//added as part of GCT-772
                    emailTemplate = Constants.doNotSellorShareDataOwnerReminderEmail;
                }else {
                    emailTemplate = Constants.accessDataOwnerReminderEmail;
                }
                Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, emailTemplate, cse.Data_Owner__r.Email);
                if (email == null) {
                    continue;
                }
                if (ccAddresses.size() > 0) {
                    email.setCcAddresses(ccAddresses);
                }
                emailsToSend.add(email);

            }
        }
        System.debug('===emails to send' + emailsToSend);
        emailHandler.sendEmails(emailsToSend);

    }

    global void finish(Database.BatchableContext BC){}

}