unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>This field is used to show Country in Personal Data Request Form</description>
    <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States of America (USA)</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/R2R_Email_UserConfirmation__c.field-meta.xml
<CustomField>
    <fullName>R2R_Email_UserConfirmation__c</fullName>
    <label>Email User Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Rectified_JSON_Data__c.field-meta.xml
<CustomField>
    <fullName>Rectified_JSON_Data__c</fullName>
    <label>Rectified JSON Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/State_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence__c</fullName>
    <description>This Field is used to Show States in Personal Data Form</description>
    <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
    <label>State of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_of_Residence__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/VerificationHash__c.field-meta.xml
<CustomField>
    <fullName>VerificationHash__c</fullName>
    <defaultValue>&#39;1234&#39;</defaultValue>
    <description>Used by clickable email responses to validate the authenticity of the response.</description>
    <label>VerificationHash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Privacy_Request.recordType-meta.xml
<RecordType>
    <fullName>Privacy_Request</fullName>
    <active>true</active>
    <businessProcess>Privacy Request</businessProcess>
    <label>Privacy Request</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/Privacy_Intervals__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Intervals to send privacy emails in hours</description>
    <label>Privacy Intervals</label>
</CustomObject>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/CaseEscalationHours__c.field-meta.xml
<CustomField>
    <fullName>CaseEscalationHours__c</fullName>
    <description>The Number of Hours after confirmation that can pass until the privacy case is escalated</description>
    <label>CaseEscalationTime</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/CSRReminderInterval__c.field-meta.xml
<CustomField>
    <fullName>CSRReminderInterval__c</fullName>
    <description>The number of hours between reminder emails sent to the CSR for privacy cases</description>
    <label>CSRReminderInterval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/hardCloseHours__c.field-meta.xml
<CustomField>
    <fullName>hardCloseHours__c</fullName>
    <description>Hours after resolving a privacy case that a case must be closed</description>
    <label>hardCloseHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/MaxAfterConfirm__c.field-meta.xml
<CustomField>
    <fullName>MaxAfterConfirm__c</fullName>
    <description>The maximum number of hours that a privacy case can be open before resolution</description>
    <label>MaxAfterConfirm</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/MaxBeforeConfirm__c.field-meta.xml
<CustomField>
    <fullName>MaxBeforeConfirm__c</fullName>
    <description>The maximum number of hours the user has to confirm their request before it is auto-closed</description>
    <label>MaxBeforeConfirm</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/maxDataOwnerTime__c.field-meta.xml
<CustomField>
    <fullName>maxDataOwnerTime__c</fullName>
    <description>The amount of hours that the data owner has to complete their privacy task</description>
    <label>maxDataOwnerTime</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/maxStalledHours__c.field-meta.xml
<CustomField>
    <fullName>maxStalledHours__c</fullName>
    <description>The Maximum Number of Hours that a case may be stalled in waiting for consumer response from CSR follow-up before automatically being closed</description>
    <label>maxStalledHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Intervals__c/fields/reminderDataOwnerInterval__c.field-meta.xml
<CustomField>
    <fullName>reminderDataOwnerInterval__c</fullName>
    <description>The Number of hours interval that an email reminder is sent to data owners</description>
    <label>reminderDataOwnerInterval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/R2RProcessResponseAPITest.cls
@isTest
private class R2RProcessResponseAPITest {
    
    @testSetup
    static void R2RProcessResponseTestData(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Contact con = new Contact();
        con.FirstName = 'TestFirst';
        con.LastName = 'TestLast';
        con.Email = UserInfo.getUserEmail();
        con.AccountId = acc.Id;
        insert con;
        GenericRecords__c genericRecords = new GenericRecords__c();
        genericRecords.Name = 'privacyContact';
        genericRecords.recordId__c = con.Id;
        insert genericRecords; 
        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        String brandName='2';
        String Country='US';
        List<Case> caseList = TestDataFactory.createCases(1);
        caseList[0].origin='Email';
        caseList[0].Country_of_Residence__c='United States of America (USA)';
        caseList[0].State_of_Residence__c='MD';
        caseList[0].Type='Unsubscribe';
        caseList[0].SuppliedEmail='mrfoobar@example.com';       
        caseList[0].SuppliedPhone='9988998899';
        caseList[0].suppliedName='test';
        caseList[0].Brand__c='2';  
        caseList[0].recordTypeId = recordTypeIdPrivacyRequest;
        caseList[0].Rectified_JSON_Data__c = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test99","newUnit":"1","newCountry":"USA","newState":"maryland","newZipCode":"20988","newPhone":"7676767671","newGender":"Male","newMonth":"12","newDate":"1"}';
        caseList[0].R2R_Email_UserConfirmation__c = 'Started';
        caseList[0].accountId = acc.Id;
        insert caseList;
    }
    
    @isTest
    static void R2RProcessOpenResponseTest(){
        Privacy_Intervals__c intervalSetting = new Privacy_Intervals__c(
            Name = Constants.privacyIntervalSettingName,
            CaseEscalationHours__c = 64,
            CSRReminderInterval__c = 32,
            MaxAfterConfirm__c = 460,
            MaxBeforeConfirm__c = 440,
            maxDataOwnerTime__c = 212,
            reminderDataOwnerInterval__c = 32,
            hardCloseHours__c = 1060,
            maxStalledHours__c = 460
        );
        insert intervalSetting;
        Case caseObj = [SELECT Id,VerificationHash__c FROM Case LIMIT 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();  
        req.requestURI = '/apexrest/services/public/v1/r2rProcesss/';
        req.addParameter('in_response','Open');
        req.addParameter('in_verificationCode',caseObj.VerificationHash__c);
        req.addParameter('in_caseid',caseObj.Id);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        R2RProcessResponseAPI.restGet();
        Test.stopTest();
    }
    
    @isTest
    static void R2RProcessResolvedResponseTest(){
        Privacy_Intervals__c intervalSetting = new Privacy_Intervals__c(
            Name = Constants.privacyIntervalSettingName,
            CaseEscalationHours__c = 64,
            CSRReminderInterval__c = 32,
            MaxAfterConfirm__c = 460,
            MaxBeforeConfirm__c = 440,
            maxDataOwnerTime__c = 212,
            reminderDataOwnerInterval__c = 32,
            hardCloseHours__c = 1060,
            maxStalledHours__c = 460
        );
        insert intervalSetting;
        Case caseObj = [SELECT Id,VerificationHash__c FROM Case LIMIT 1];
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();  
        req.requestURI = '/apexrest/services/public/v1/r2rProcesss/';
        req.addParameter('in_response','Resolved');
        req.addParameter('in_verificationCode',caseObj.VerificationHash__c);
        req.addParameter('in_caseid',caseObj.Id);
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        R2RProcessResponseAPI.restGet();
        Test.stopTest();
    }
    
}