unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Is_Existing_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Is_Existing_Purchase__c</fullName>
    <description>This field is created to keep information about the purchase is Existing or Not</description>
    <label>Is Existing Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ToggleCloseCaseTabTest.cls
/**
 * Created by bryananderson on 11/14/19.
 */

@IsTest
private class ToggleCloseCaseTabTest {
    @isTest
    static void createCaseTestPos()
    {
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        //Setting the API Name for Calvin Klein Brand
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Web';
        getCaseList[0].SuppliedEmail='abc@gmail.com';
        getCaseList[0].SuppliedPhone='9988998899';
        getCaseList[0].Is_Existing_Purchase__c='Yes';
        getCaseList[0].Type='Product';
        getCaseList[0].Description='Test Cases';
        getCaseList[0].Status='Open';
		getCaseList[0].Brand__c='1';
        Test.startTest();
        insert getCaseList;
        Boolean isDisabled = ToggleCloseCaseTab.getDisableStatus(getCaseList[0].Id);
        String ownerId = ToggleCloseCaseTab.doCaseRouting(getCaseList[0].Id);
        Test.stopTest();

        system.assertEquals(isDisabled, true);
    }

    @isTest
    static void createCaseTestNeg()
    {
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        //Setting the API Name for Calvin Klein Brand
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Web';
        getCaseList[0].SuppliedEmail='abc@gmail.com';
        getCaseList[0].SuppliedPhone='9988998899';
        getCaseList[0].Is_Existing_Purchase__c='Yes';
        getCaseList[0].Type='Product';
        getCaseList[0].Description='Test Cases';
        getCaseList[0].Status='New';
		getCaseList[0].Brand__c='1';
        Test.startTest();
        insert getCaseList;
        Boolean isDisabled = ToggleCloseCaseTab.getDisableStatus(getCaseList[0].Id);
        String ownerId = ToggleCloseCaseTab.doCaseRouting(getCaseList[0].Id);
        Test.stopTest();

        system.assertEquals(isDisabled, false);
    }
}