unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_OWA_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_OWA_Name__c</fullName>
    <description>Controlled By Account - This field is the DisplayName of the Brand&#39;s Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
    <label>Brand Privacy OWA Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PrivacyEmailHandler.cls
public class PrivacyEmailHandler {
    Map<String,String> brandValueMap = new Map<String,String>();
    Map<String, Id> templateNameToIdMap = new Map<String, Id>();
    Map<String, OrgWideEmailAddress> owaMap = new Map<String, OrgWideEmailAddress>();
    Map<Id, OrgWideEmailAddress> caseToOWAMap = new Map<Id, OrgWideEmailAddress>();
    String genericContactId;

    public PrivacyEmailHandler() {
        List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
        for (Schema.Picklistentry ple: fieldResult) {
            this.brandValueMap.put(ple.getValue(), ple.getLabel());
        }
        List<EmailTemplate> templates = [Select Id, Name from EmailTemplate limit 1000];
        for (EmailTemplate template : templates) {
            this.templateNameToIdMap.put(template.Name, template.Id);
        }
        List<OrgWideEmailAddress> owaList = [Select Id, DisplayName, Address From OrgWideEmailAddress limit 1000];
        for (OrgWideEmailAddress owa : owaList) {
            this.owaMap.put(owa.DisplayName, owa);
        }

        GenericRecords__c genericContactRecord = GenericRecords__c.getValues(Constants.privacyContactGenericRecordSettingName);
        this.genericContactId = genericContactRecord.recordId__c;

    }

    // THIS METHOD WAS BUILD ASSUMING ALL CASE EMAILS GO TO SUPPLIEDEMAIL.
    // CALL THE OTHER METHOD MOVING FORWARD AND BE EXPLICIT
    public Messaging.SingleEmailMessage createEmail(Case cse, String emailTemplateName) {
        Messaging.SingleEmailMessage mail = createEmail(cse, emailTemplateName, cse.SuppliedEmail);
        return mail;
    }

    public Messaging.SingleEmailMessage createEmail(Case cse, String emailTemplateName, String emailAddress) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        Id templateId = this.templateNameToIdMap.get(emailTemplateName);
        mail.setTemplateId(templateId);

        String brandName = this.brandValueMap.get(cse.Brand__c);
        OrgWideEmailAddress owa = this.owaMap.get(cse.Brand_Privacy_OWA_Name__c);
        if (owa == null) {
            // LOG THIS SOMEWHERE
            return null;
        }
        system.debug('>>>>>>>owa.Id>>>'+owa.Id);
        mail.setOrgWideEmailAddressId(owa.Id);
        this.caseToOWAMap.put(cse.Id, owa);
		system.debug('>>>>emailAddress>>>>>'+emailAddress);
        mail.setToAddresses(new List<String>{emailAddress});
        mail.setSaveAsActivity(false);
        if (String.isNotBlank(cse.ContactId)) {
            mail.setTargetObjectId(cse.ContactId);
        } else {
            mail.setTargetObjectId(this.genericContactId);
        }
        
        mail.setWhatId(cse.Id);
        mail.setUseSignature(false);
        mail.setTreatTargetObjectAsRecipient(false);
        system.debug('>>>>>>mail>>>>>>'+mail);
        return mail;

    }

    public void sendEmails(List<Messaging.SingleEmailMessage> emails) {
        Messaging.sendEmail(emails);
        this.logEmails(emails);
    }

    private void logEmails(List<Messaging.SingleEmailMessage> emails) {
        List<EmailMessage> emailLog = new List<EmailMessage>();
        for (Messaging.SingleEmailMessage email : emails) {
            EmailMessage emailToLog = new EmailMessage();
            String toAsString='';
            Boolean check = false;
            for (String s : email.getToAddresses()) {
                if (check) toAsString += ',';           
                toAsString += s;
                check = true;
            }
            emailToLog.ToAddress = toAsString;
            emailToLog.Subject = email.getSubject();
            emailToLog.HtmlBody = email.getHtmlBody();
            emailToLog.Incoming = false;
            emailToLog.ParentId = email.getWhatId();
            emailToLog.MessageDate = System.now();
            emailToLog.FromAddress = this.caseToOWAMap.get(email.getWhatId()).Address;
            emailLog.add(emailToLog);
        }
        insert emailLog;

    }

}