unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EcommContact_Test.cls
@isTest(isParallel=false)
public class EcommContact_Test {

    static testmethod void OOBOTest(){
        account acc = new account(name = 'DummyAccount');
        insert acc;
        
        contact con = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456');
        insert con;
        getContact.getContactDetails(con.Id);
        
        GenericRecords__c gr = new GenericRecords__c();
        gr.recordId__c = con.Id;
        gr.Name ='privacyContact';
        insert gr;
        Test.startTest();
        case cs =new case(Type='Support',Status='New',SuppliedEmail='test@gmail.com',Brand__c='1');
        insert cs;
        ecommContactCase.getContactId(cs.Id);
        cs.ContactId=con.id;
        update cs;
        ecommContactCase.getContactId(cs.Id);
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        con.Ecomm_Connected__c = true;
        con.B2C_Customer_No__c ='12345678';
        update con;
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        
        con.Ecomm_Connected__c = false;
        con.B2C_Customer_No__c = '';
        update con;
        ecommContactCase.getContactId(cs.Id);
        //ecommContactCase.eCommOtherCont(con.Id);
        
        contact cont = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456',Ecomm_Connected__c = true,B2C_Customer_No__c ='12345678');
        insert cont;
        list<contact> conList = new list<contact>();
        conList.add(cont);
        ecommContactCase.eCommOtherCont(con.Id);
        ecommContactCase.linkContact(cs.Id,conList);
        Test.stopTest();
    }
    
    static testmethod void OOBOTest1(){
        account acc = new account(name = 'DummyAccount');
        insert acc;
        
        contact con = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456');
        insert con;
        getContact.getContactDetails(con.Id);
        
        GenericRecords__c gr = new GenericRecords__c();
        gr.recordId__c = con.Id;
        gr.Name ='privacyContact';
        insert gr;
        Test.startTest();
        case cs =new case(Type='Support',Status='New',SuppliedEmail='test@gmail.com');
        insert cs;
        ecommContactCase.getContactId(cs.Id);
        cs.ContactId=con.id;
        update cs;
        ecommContactCase.getContactId(cs.Id);
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        con.Ecomm_Connected__c = true;
        con.B2C_Customer_No__c ='12345678';
        update con;
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        
        con.Ecomm_Connected__c = false;
        con.B2C_Customer_No__c = '';
        update con;
        ecommContactCase.getContactId(cs.Id);
        //ecommContactCase.eCommOtherCont(con.Id);
        
        contact cont = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456',Ecomm_Connected__c = true,B2C_Customer_No__c ='12345678');
        insert cont;
        list<contact> conList = new list<contact>();
        conList.add(cont);
        ecommContactCase.eCommOtherCont(con.Id);
        ecommContactCase.linkContact(cs.Id,conList);
        Test.stopTest();
    }
    
     static testmethod void OOBOTest2(){
        account acc = new account(name = 'DummyAccount');
        insert acc;
        
        contact con = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456',B2C_Customer_No__c='123');
        insert con;
        getContact.getContactDetails(con.Id);
        
        GenericRecords__c gr = new GenericRecords__c();
        gr.recordId__c = con.Id;
        gr.Name ='privacyContact';
        insert gr;
        Test.startTest();
        case cs =new case(Type='Support',Status='New',SuppliedEmail='test@gmail.com',Brand__c='1');
        insert cs;
        ecommContactCase.getContactId(cs.Id);
        cs.ContactId=con.id;
        update cs;
        ecommContactCase.getContactId(cs.Id);
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        con.Ecomm_Connected__c = true;
        con.B2C_Customer_No__c ='12345678';
        update con;
        ecommContactCase.eCommConnectedFlag(con.Id);
        
        
        con.Ecomm_Connected__c = false;
        con.B2C_Customer_No__c = '';
        update con;
        ecommContactCase.getContactId(cs.Id);
        //ecommContactCase.eCommOtherCont(con.Id);
        
        contact cont = new contact (lastname='Dummycontact' ,email='test@gmail.com',Brand_Id__c = '1',LoyaltyID__c='123456',Ecomm_Connected__c = true,B2C_Customer_No__c ='12345678');
        insert cont;
        list<contact> conList = new list<contact>();
        conList.add(cont);
        ecommContactCase.eCommOtherCont(con.Id);
        ecommContactCase.linkContact(cs.Id,conList);
        Test.stopTest();
    }
   
}