unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Details__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Details__c</fullName>
    <label>Reason Code Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted Forms of Payment</fullName>
            </value>
            <value>
                <fullName>Account Information (Member ID)</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Issue (Godzilla, Dummy Account)</fullName>
            </value>
            <value>
                <fullName>Account Issue (Loyalty Flag)</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Registration Error</fullName>
            </value>
            <value>
                <fullName>Adaptive</fullName>
            </value>
            <value>
                <fullName>Address Error</fullName>
            </value>
            <value>
                <fullName>Associate Discount</fullName>
            </value>
            <value>
                <fullName>Authorization Hold</fullName>
            </value>
            <value>
                <fullName>Balance Confirmation (Points/Rewards)</fullName>
            </value>
            <value>
                <fullName>BBB Complaint</fullName>
            </value>
            <value>
                <fullName>Black Friday Complaint</fullName>
            </value>
            <value>
                <fullName>Brand Protection</fullName>
            </value>
            <value>
                <fullName>Bulk Buyer Warning</fullName>
            </value>
            <value>
                <fullName>Business Solicitation</fullName>
            </value>
            <value>
                <fullName>Call/Chat Disconnect</fullName>
            </value>
            <value>
                <fullName>Cancelled Item</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order Request</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Check Complaint</fullName>
            </value>
            <value>
                <fullName>Check Inventory/Restock Inquiry</fullName>
            </value>
            <value>
                <fullName>Check-out Error (Non-Fraud/Payment)</fullName>
            </value>
            <value>
                <fullName>Claim Status</fullName>
            </value>
            <value>
                <fullName>Contest/Sweepstakes</fullName>
            </value>
            <value>
                <fullName>Corporate Outfitters Request</fullName>
            </value>
            <value>
                <fullName>Corporate Responsibility</fullName>
            </value>
            <value>
                <fullName>Corp Social Responsibility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Privacy_Request.recordType-meta.xml
<RecordType>
    <fullName>Privacy_Request</fullName>
    <active>true</active>
    <businessProcess>Privacy Request</businessProcess>
    <label>Privacy Request</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Privacy_Request_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Privacy_Request_Read_Only</fullName>
    <active>true</active>
    <businessProcess>Privacy Request</businessProcess>
    <label>Privacy Request - Read Only</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Support_Case_Read_Only</fullName>
    <active>true</active>
    <businessProcess>Support Case - Read Only</businessProcess>
    <label>Support Case - Read Only</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SchedulableBatchCloseResolvedCaseTest.cls
@isTest
private class SchedulableBatchCloseResolvedCaseTest {
    
    @testsetup
    static void setup(){
        List<Case> caselist = new List<Case>();
        List<Case> updatedcaselist = new List<Case>();
        Map<String,Schema.RecordTypeInfo> RecordTypes = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName();
        //Id PrivacyRecordId = RecordTypes.get('Privacy_Request').getRecordTypeId();
        //Id PrivacyReadOnlyRecordId = RecordTypes.get('Privacy_Request_Read_Only').getRecordTypeId();
        Id SupportRecordId = RecordTypes.get('Support_Case').getRecordTypeId();
        Id SupportReadOnlyRecordId = RecordTypes.get('Support_Case_Read_Only').getRecordTypeId();
        Integer GenericCaseClosedDays = Integer.valueOf(System.Label.GeneralCase_ClosedDays);
        //Integer PrivacyCaseClosedDays = Integer.valueOf(System.Label.PrivacyCase_ClosedDays);
        
        Account acc = new Account(name='Account Name');
        Insert acc;
        
        Contact con = new Contact(Firstname='first '+ acc.Name, Lastname='last ', Brand_Id__c = '1', Email = 'firstname.lastname@nomail.com', AccountId = acc.Id);
        Insert con;
        
        for(Integer i=0;i<10;i++){
            Case testcase = new Case();
            testcase.Origin = 'Email';
            testcase.Status = 'Resolved';
            testcase.ContactId = con.Id;
            testcase.Brand__c = '1';
            testcase.Subject = 'Test Case'+i;
            testcase.Description = 'Test Description'+i;
            testcase.SuppliedEmail = con.Email;
            testcase.SuppliedName = con.FirstName + con.LastName;
            testcase.Priority = 'Medium';
           // testcase.Reason_Code__c='Corporate';
            //testcase.Reason_Code_Details__c='Accepted Forms of Payment';
            if(math.mod(i,2)==0){
                testcase.Type = 'Product';
                testcase.RecordTypeId = SupportRecordId;   
                //testcase.Type = 'Privacy';
                //testcase.RecordTypeId = PrivacyRecordId;
            } else{
                testcase.Type = 'Product';
                testcase.RecordTypeId = SupportRecordId;               
            }
            caselist.add(testcase) ;
        }
        insert caselist;
    }
    
    
    @isTest
    static void scheduleTest(){
        //Dummy CRON expression: midnight on July 25.
        // Because this is a test, job executes
        // immediately after Test.stopTest().
        String CRON_EXP = '0 0 0 25 7 ? 2022';
        Test.startTest();
        String jobId = System.schedule('ScheduleBatchCloseResolved',  CRON_EXP, new SchedulableBatchCloseResolvedCase());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest(); 
        ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.debug('Ct times triggered.: '+ct.NextFireTime);
        System.assertEquals('2022-07-25 00:00:00', String.valueOf(ct.NextFireTime));
    }
    
}