unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>This field is used to show Country in Personal Data Request Form</description>
    <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States of America (USA)</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/R2R_Email_UserConfirmation__c.field-meta.xml
<CustomField>
    <fullName>R2R_Email_UserConfirmation__c</fullName>
    <label>Email User Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Rejected Request</fullName>
            </value>
            <value>
                <fullName>No Response to follow-up</fullName>
            </value>
            <value>
                <fullName>Data Not Found</fullName>
            </value>
            <value>
                <fullName>User Data Provided</fullName>
            </value>
            <value>
                <fullName>User Data Deleted</fullName>
            </value>
            <value>
                <fullName>User Data Corrected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/State_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>State_of_Residence__c</fullName>
    <description>This Field is used to Show States in Personal Data Form</description>
    <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
    <label>State of Residence</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_of_Residence__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Privacy_Request.recordType-meta.xml
<RecordType>
    <fullName>Privacy_Request</fullName>
    <active>true</active>
    <businessProcess>Privacy Request</businessProcess>
    <label>Privacy Request</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PersonalDataFormApexControllerTest.cls
/**
 * @class:       PersonalDataFormApexControllerTest
 * @JIRA:        NASSC-98 Privacy (CCPA) Forms
 * @description: Test Class for PersonalDataFormApexController class.
 */ 
 
@isTest
public class PersonalDataFormApexControllerTest 
{
	@isTest 
    static void getDependentMapTest() 
    {	
            String brandNames = '2';
        	String sourceCountry = 'US';
            Case caseObj = new Case();
        	PersonalDataFormApexController.getDependentMap(caseObj,'Country_of_Residence__c','State_of_Residence__c',brandNames,sourceCountry);
    }
    
    @isTest 
    static void createCaseTestWithUnsubscribe() 
    {	
        PrivacyCaseTests.makeData();
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                         'Complete',
                                         '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                                         null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        String brandName='2';
        String Country='US';
        
        
         contact con = new Contact();
        con.lastName = 'Test';
        con.Email = 'mrfoobar@example.com';
        con.Brand__c = '2';
        insert con;
        
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Web';
        getCaseList[0].Country_of_Residence__c='Canada';
        getCaseList[0].State_of_Residence__c=null;
        getCaseList[0].Type='Unsubscribe';
		getCaseList[0].SuppliedEmail='mrfoobar@example.com';       
        getCaseList[0].SuppliedPhone='9988998899';
        getCaseList[0].Brand__c='2';   
        
        PersonalDataFormApexController.createCase(getCaseList[0], 'test name' , brandName, Country);
       
    }
    
    @isTest 
    static void createCaseTestWithOther() 
    {	
        PrivacyCaseTests.makeData();

        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        String brandName='2';
        String Country='US';
        
        contact con = new Contact();
        con.lastName = 'Test';
        con.Email = 'foo@example.com';
        con.Brand__c = '2';
        insert con;
        
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Email';
        getCaseList[0].Country_of_Residence__c='Canada';
        getCaseList[0].State_of_Residence__c=null;
        getCaseList[0].suppliedName = 'test';
        getCaseList[0].Type='Access My Data';
		getCaseList[0].SuppliedEmail='foo@example.com';       
        getCaseList[0].SuppliedPhone='9988998899';
        getCaseList[0].SuppliedPhone='9988998899';
        
        
        
        PersonalDataFormApexController.createCase(getCaseList[0], 'test name' , brandName,Country);
       
    }
    
    @isTest 
    static void createCaseForRectifiedDataTest() 
    {	
        PrivacyCaseTests.makeData();

        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDataRectified(changedData, brandName,'foo@example.com' , true, jsonData);
       
    }
    
    
     @isTest 
    static void createCaseForRectifiedDataTest2() 
    {	
        PrivacyCaseTests.makeData();

        Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDataRectified(changedData, brandName,'foo@example.com' , true, jsonData);
       
    }
    
      @isTest 
    static void createCaseForRectifiedDataTest3() 
    {	
        PrivacyCaseTests.makeData();

        Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        Contact con2 = new contact();
        con2.firstname = 'test22';
        con2.lastname = 'contact';
        con2.email = 'foo@example.com';
        con2.Brand__c = 'Calvin Klein';
        con2.Ecomm_Connected__c = true;
        insert con2;
        
        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDataRectified(changedData, brandName,'foo@example.com' , true, jsonData);
       
    }
    
      @isTest 
    static void createCaseForRectifiedDataTest4() 
    {	
        PrivacyCaseTests.makeData();

        Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        Contact con2 = new contact();
        con2.firstname = 'test22';
        con2.lastname = 'contact';
        con2.email = 'foo@example.com';
        con2.Brand__c = 'Calvin Klein';
        con2.Ecomm_Connected__c = true;
        insert con2;
        
        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDataRectified(changedData, brandName,'foo@example.com' , true, jsonData);
        
        Case cse = [Select id from case limit 1];
        cse.status = 'Resolved';
        cse.Sub_Type__c = 'Rectify My Data';
        cse.Resolution_Code__c = 'User Data Provided';
        cse.R2R_Email_UserConfirmation__c = 'Confirmed';
        Test.startTest();
        update cse;
        Test.stopTest();
       
    }
    
        @isTest 
    static void createCaseForDonotSellShareTest() 
    {	
        PrivacyCaseTests.makeData();

        Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        Contact con2 = new contact();
        con2.firstname = 'test22';
        con2.lastname = 'contact';
        con2.email = 'foo@example.com';
        con2.Brand__c = 'Calvin Klein';
        con2.Ecomm_Connected__c = true;
        insert con2;
        
        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDonotSellShare(brandName,'foo@example.com',false);
       
    }
    
            @isTest 
    static void createCaseForDonotSellShareTestContactNotFound() 
    {	
        PrivacyCaseTests.makeData();

        Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        Contact con2 = new contact();
        con2.firstname = 'test22';
        con2.lastname = 'contact';
        con2.email = 'foo@example.com';
        con2.Brand__c = 'Calvin Klein';
        con2.Ecomm_Connected__c = true;
        insert con2;
        
        String brandName='2';
        
        String jsonData = '{"newEmail":"","newFirstName":"testsek","newLastName":"testbar","newAddress":"test 234","newUnit":"111","newCountry":"United States of America","newState":"Maryland","newZipCode":"20874","newPhone":"1234561234","newGender":"Male","newMonth":"5","newDate":"17"}';
        String changedData = 'First Name: testsek Last Name: testbar= Address: test 234 Apartment/Suite/Unit: 111 City: germantown State: Maryland Country: United States of America Zip Code: 20874 Phone: 1234561234 Gender: Male Birthday (Month-Day): 5-17';
        PersonalDataFormApexController.createCaseForDonotSellShare(brandName,'foo@example.comm',false);
       
    }
    
     @isTest 
    static void checkIfContactExistWithEmailIdTest() 
    {	
     	 Contact con = new contact();
        con.firstname = 'test';
        con.lastname = 'contact';
        con.email = 'foo1@example.com';
        con.Brand__c = 'Calvin Klein';
        insert con;
        
        PersonalDataFormApexController.CaseWrapper wrap =  PersonalDataFormApexController.checkIfContactExistWithEmailId('2', 'foo1@example.com');
        Test.startTest();
        System.assertEquals(true, wrap.error);
        Test.stopTest();
    }

    
}