unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Details__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Details__c</fullName>
    <label>Reason Code Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted Forms of Payment</fullName>
            </value>
            <value>
                <fullName>Account Information (Member ID)</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Issue (Godzilla, Dummy Account)</fullName>
            </value>
            <value>
                <fullName>Account Issue (Loyalty Flag)</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Registration Error</fullName>
            </value>
            <value>
                <fullName>Adaptive</fullName>
            </value>
            <value>
                <fullName>Address Error</fullName>
            </value>
            <value>
                <fullName>Associate Discount</fullName>
            </value>
            <value>
                <fullName>Authorization Hold</fullName>
            </value>
            <value>
                <fullName>Balance Confirmation (Points/Rewards)</fullName>
            </value>
            <value>
                <fullName>BBB Complaint</fullName>
            </value>
            <value>
                <fullName>Black Friday Complaint</fullName>
            </value>
            <value>
                <fullName>Brand Protection</fullName>
            </value>
            <value>
                <fullName>Bulk Buyer Warning</fullName>
            </value>
            <value>
                <fullName>Business Solicitation</fullName>
            </value>
            <value>
                <fullName>Call/Chat Disconnect</fullName>
            </value>
            <value>
                <fullName>Cancelled Item</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order Request</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Check Complaint</fullName>
            </value>
            <value>
                <fullName>Check Inventory/Restock Inquiry</fullName>
            </value>
            <value>
                <fullName>Check-out Error (Non-Fraud/Payment)</fullName>
            </value>
            <value>
                <fullName>Claim Status</fullName>
            </value>
            <value>
                <fullName>Contest/Sweepstakes</fullName>
            </value>
            <value>
                <fullName>Corporate Outfitters Request</fullName>
            </value>
            <value>
                <fullName>Corporate Responsibility</fullName>
            </value>
            <value>
                <fullName>Corp Social Responsibility</fullName>
            </value>
            <value>
                <fullName>Defective Merchandise</fullName>
            </value>
            <value>
                <fullName>Good Service</fullName>
            </value>
            <value>
                <fullName>Poor Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Product_Category__c</fullName>
    <label>Reason Code Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Activewear</fullName>
            </value>
            <value>
                <fullName>Bags/Wallets</fullName>
            </value>
            <value>
                <fullName>Bottoms</fullName>
            </value>
            <value>
                <fullName>Cosmetic Products</fullName>
            </value>
            <value>
                <fullName>Dress Shirts</fullName>
            </value>
            <value>
                <fullName>Dresses/Skirts</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Fragrances</fullName>
            </value>
            <value>
                <fullName>Home Products</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
            <value>
                <fullName>Jeans/Denim</fullName>
            </value>
            <value>
                <fullName>Luggage</fullName>
            </value>
            <value>
                <fullName>Outerwear</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Shirts/Tops/Blouses/Polos</fullName>
            </value>
            <value>
                <fullName>Suiting/Formal Wear</fullName>
            </value>
            <value>
                <fullName>Sweaters/Wovens</fullName>
            </value>
            <value>
                <fullName>Swimwear</fullName>
            </value>
            <value>
                <fullName>Tops</fullName>
            </value>
            <value>
                <fullName>Underwear</fullName>
            </value>
            <value>
                <fullName>Watches/Jewelry</fullName>
            </value>
            <value>
                <fullName>Web Form Submission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_First_Name__c</fullName>
    <description>Supplied First Name</description>
    <label>Supplied First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Supplied_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplied_Last_Name__c</fullName>
    <label>Supplied Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHStoreNumber__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHStoreNumber__c</fullName>
    <label>Store Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Privacy_Request.recordType-meta.xml
<RecordType>
    <fullName>Privacy_Request</fullName>
    <active>true</active>
    <businessProcess>Privacy Request</businessProcess>
    <label>Privacy Request</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseUtilityTest.cls
/**
* @author Magnet360
*
* @date 2019
*
* @description Test Class for CaseUtility class.
*
* @see CaseUtility
*/
@isTest
private class CaseUtilityTest {

    Static String RecordTypeSupportCaseId = Schema.SObjectType.CASE.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
    Static String RecordTypePrivacyCaseId = Schema.SObjectType.CASE.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();

    @isTest
    private static void TestMethod1(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'testuser1';
        case1.Brand__c = '1';
        case1.SuppliedPhone='4564646';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        TestDataFactory.createGenericRecords('');


        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        system.debug(createdAccount);
        List<Contact> createdContact = [SELECT Id, LastName FROM Contact];
        //    System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);

    }

    @isTest
    private static void TestMethod2(){
        //New case created for existing Contact with same brand
        List<Account> accList = TestDataFactory.createAccount(1);
        insert accList;

        List<Contact> conList = TestDataFactory.createContact(1);
        Contact con = conList[0];
        con.AccountId = accList[0].Id;
        con.Email = 'testuser1@nomail.com';
        con.LastName = 'testuser1';
        con.Brand_Id__c = '1';
        insert con;

        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'testuser1';
        case1.Brand__c = '1';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        TestDataFactory.createGenericRecords(con.id);


        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, LastName FROM Contact];
        //   System.assert(createdCase.Size() == 1);
        //   System.assert(createdAccount.Size() == 1);
        // System.assert(createdContact.Size() == 1);
        //  System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
        // System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);
        System.debug('sizeee:::'+createdCase.Size());
    }

    @isTest
    private static void TestMethod3(){
        //New case created for existing Contact with different Brand
        List<Account> accList = TestDataFactory.createAccount(1);
        insert accList;

        List<Contact> conList = TestDataFactory.createContact(1);
        Contact con = conList[0];
        con.Email = 'testuser1@nomail.com';
        con.LastName = 'testuser1';
        con.Brand_Id__c = '2';
        con.AccountId = accList[0].Id;
        con.Phone='7890789078';
        insert con;

        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'testuser1';
        case1.Brand__c = '1';
        case1.SuppliedPhone ='7890789078';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        TestDataFactory.createGenericRecords(con.id);

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, LastName FROM Contact];
        List<Contact> createdContactRelated = [SELECT Id, LastName FROM Contact WHERE Brand_Id__c = '2'];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 2);
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContactRelated[0].Id);
    }

    @isTest
    private static void TestMethod4(){
        //New case created for existing Contact with Same Phone and Brand
        List<Account> accList = TestDataFactory.createAccount(1);
        insert accList;

        List<Contact> conList = TestDataFactory.createContact(1);
        Contact con = conList[0];
        con.LastName = 'testuser1';
        con.Brand_Id__c = '2';
        con.Phone='7890789078';
        con.Source_System__c = 'SFSC';
        insert con;

        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'testuser1';
        case1.Brand__c = '2';
        case1.SuppliedPhone ='7890789078';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        TestDataFactory.createGenericRecords(con.id);

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId FROM Case];
        System.debug('>>createdCase:'+createdCase);
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, LastName FROM Contact WHERE Phone = '7890789078'];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
        //System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);
    }

    @isTest
    private static void TestMethod5(){
        PrivacyCaseTests.makeData();
        //New case created for existing Contact with Same Phone and Brand
        List<Account> accList = TestDataFactory.createAccount(10);
        insert accList;

        List<Contact> conListInsert = new List<Contact>();
        List<Contact> conList = TestDataFactory.createContact(10);
        for (Integer i=0;i<accList.size();i++){
            conList[i].Email = 'testuser'+i+'@nomail.com';
            conList[i].LastName = 'testuser'+i;
            conList[i].Brand_Id__c = '4';
            conList[i].Phone='7890789078';
            conList[i].AccountId = accList[i].Id;
            conListInsert.add(conList[i]);
        }
        insert conListInsert;

        List<Case> caseListInsert = new List<Case>();
        List<Case> caseList = TestDataFactory.createCases(10);
        for(Integer i=0;i<caseList.size();i++){
            caseList[i].SuppliedEmail = 'testuser'+i+'@nomail.com';
            caseList[i].SuppliedName = 'testuser'+i;
            caseList[i].Brand__c = '4';
            caseList[i].SuppliedPhone ='7890789078';
            caseList[i].RecordTypeId = RecordTypePrivacyCaseId;
            caseList[i].Type = Constants.privacyCaseType;
            caseList[i].Sub_Type__c = Constants.deletionRequestSubType;
            caseListInsert.add(caseList[i]);
        }

        Test.startTest();
        insert caseListInsert;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, LastName FROM Contact WHERE Email = 'testuser0@nomail.com'];
        System.assert(createdCase.Size() == 10);
    }

    @isTest
    private static void TestMethodOneName(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'First';
        case1.Brand__c = '1';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        case1.Origin = 'Email';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
//        List<Account> createdAccount = [SELECT Id, Name FROM Account];
//        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);

    }

    @isTest
    private static void TestMethodEmailToCaseSetBrand(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'First';
        case1.Brand__c = null;
        case1.RecordTypeId = RecordTypeSupportCaseId;
        case1.Origin = 'Email - 1';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, Origin, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c,Brand__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName, Brand_Id__c FROM Contact];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);
//        System.assertEquals(createdCase[0].Brand__c, createdContact[0].Brand_Id__c);
        //System.assertEquals(createdCase[0].Origin, 'Email');

    }

    @isTest
    private static void TestMethodTwoNames(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'First Second';
        case1.Brand__c = '1';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        case1.Origin = 'Email';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
//        System.assertEquals(createdCase[0].Supplied_First_Name__c,'First');
//        System.assertEquals(createdCase[0].Supplied_Last_Name__c,'Second');
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);

    }

    @isTest
    private static void TestMethodThreeNames(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(1);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'First Second Third';
        case1.Brand__c = '1';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        case1.Origin = 'Email';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        insert case1;
        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() == 1);
//        System.assert(createdAccount.Size() == 1);
//        System.assert(createdContact.Size() == 1);
//        System.assertEquals(createdCase[0].Supplied_First_Name__c,'First Second');
//        System.assertEquals(createdCase[0].Supplied_Last_Name__c,'Third');
//        System.assertEquals(createdCase[0].AccountId, createdAccount[0].Id);
//        System.assertEquals(createdCase[0].ContactId, createdContact[0].Id);
//        System.assertEquals(createdContact[0].FirstName,'First Second');
//        System.assertEquals(createdContact[0].LastName,'Third');

    }

    @isTest
    private static void TestGoodService(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(5);
        Case case1 = caseList[0];
        case1.SuppliedEmail = 'testuser1@nomail.com';
        case1.SuppliedName = 'First Second Third';
        case1.Brand__c = '1';
        case1.RecordTypeId = RecordTypeSupportCaseId;
        case1.Origin = 'Email';
        //     case1.Reason_Code_Details__c='Good Service';
        case1.ZdPVHStoreNumber__c = null;
        case1.Supplied_First_Name__c='First';
        case1.Supplied_Last_Name__c='Second';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        try {
            insert case1;
        } catch (DMLException e) {
            //expected error
        }


        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() != 0   );

    }

    @isTest
    private static void TestBadService(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(5);

        Case case2 = caseList[1];
        case2.SuppliedEmail = 'testuser1@nomail.com';
        case2.SuppliedName = 'First Second Third';
        case2.Brand__c = '1';
        case2.RecordTypeId = RecordTypeSupportCaseId;
        case2.Origin = 'Email';
        case2.Supplied_First_Name__c='First';
        case2.Supplied_Last_Name__c='Second';
        TestDataFactory.createGenericRecords('');
        //case2.Reason_Code_Details__c='Poor Service';

        Test.startTest();
        try {
            insert case2;
        } catch (DMLException e) {
            //expected error
        }

        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() != 0   );

    }

    @isTest
    private static void TestDefect(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(5);

        Case case3 = caseList[2];
        case3.SuppliedEmail = 'testuser1@nomail.com';
        case3.SuppliedName = 'First Second Third';
        case3.Brand__c = '1';
        case3.RecordTypeId = RecordTypeSupportCaseId;
        case3.Origin = 'Email';
        // case3.Reason_Code_Details__c='Defective Merchandise';
//        case3.Reason_Code_Product_Category__c = 'Swimwear';
//        case3.Reason_Code_Product_Sub_Categories_Widge__c = 'General Swimwear';
        case3.Reason_Code_Manufacturers__c = null;
        case3.Supplied_First_Name__c='First';
        case3.Supplied_Last_Name__c='Second';

        Case case4 = caseList[3];
        case4.SuppliedEmail = 'testuser1@nomail.com';
        case4.SuppliedName = 'First Second Third';
        case4.Brand__c = '1';
        case4.RecordTypeId = RecordTypeSupportCaseId;
        case4.Origin = 'Email';
        // case4.Reason_Code_Details__c='Defective Merchandise';
        case4.Reason_Code_Product_Category__c = 'Swimwear';
        case4.Reason_Code_Product_Sub_Categories_Widge__c = 'General Swimwear';
        case4.Third_Party_Vendors__c = null;
        case4.Supplied_First_Name__c='First';
        case4.Supplied_Last_Name__c='Second';
        TestDataFactory.createGenericRecords('');

        Test.startTest();
        try {
            insert case3;
        } catch (DMLException e) {
            //expected error
        }

        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() != 0   );

    }

    @isTest
    private static void TestCare(){
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                'Complete',
                '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        //New case created for Contact not existing
        List<Case> caseList = TestDataFactory.createCases(5);

        Case case4 = caseList[3];
        case4.SuppliedEmail = 'testuser1@nomail.com';
        case4.SuppliedName = 'First Second Third';
        case4.Supplied_First_Name__c='First';
        case4.Supplied_Last_Name__c='Second';
        case4.Brand__c = '1';
        case4.RecordTypeId = RecordTypeSupportCaseId;
        case4.Origin = 'Email';
        // case4.Reason_Code_Details__c='Care Instructions';
        TestDataFactory.createGenericRecords('');


        Test.startTest();
        try {
            insert case4;
        } catch (DMLException e) {
            //expected error
        }

        Test.stopTest();

        List<Case> createdCase = [SELECT Id, SuppliedName, SuppliedEmail, AccountId, ContactId, Supplied_First_Name__c, Supplied_Last_Name__c FROM Case];
        List<Account> createdAccount = [SELECT Id, Name FROM Account];
        List<Contact> createdContact = [SELECT Id, FirstName, LastName FROM Contact];
        System.assert(createdCase.Size() >= 0   );

    }

}