unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CalvinKlein.us</fullName>
                <label>Online - CalvinKlein.com</label>
            </value>
            <value>
                <fullName>Calvin Klein Retail</fullName>
                <label>Calvin Klein Store</label>
            </value>
            <value>
                <fullName>Tommy.com</fullName>
                <label>Online - Tommy.com</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger Retail</fullName>
                <label>Tommy Hilfiger Store</label>
            </value>
            <value>
                <fullName>SpeedoUSA.com</fullName>
                <label>Online - speedo.com</label>
            </value>
            <value>
                <fullName>VanHeusen.com</fullName>
                <label>Online - vanheusen.com</label>
            </value>
            <value>
                <fullName>Izod.com</fullName>
                <label>Online - Izod.com</label>
            </value>
            <value>
                <fullName>styleBureau.com</fullName>
                <label>Online - styleBureau.com</label>
            </value>
            <value>
                <fullName>trueandco.com</fullName>
                <label>Online -True&amp;co.com</label>
            </value>
            <value>
                <fullName>CalvinKlein.ca</fullName>
                <label>Online-CalvinKlein Canada</label>
            </value>
            <value>
                <fullName>Speedo.com</fullName>
            </value>
            <value>
                <fullName>Warner.com</fullName>
                <label>Online-Warner&#39;s</label>
            </value>
            <value>
                <fullName>Van Heusen | IZOD Company Store</fullName>
            </value>
            <value>
                <fullName>Amazon.com</fullName>
            </value>
            <value>
                <fullName>Nordstrom</fullName>
            </value>
            <value>
                <fullName>Other Retailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/RingCentralChannel__c.field-meta.xml
<CustomField>
    <fullName>RingCentralChannel__c</fullName>
    <description>Field to store channel value of incoming call temporarily, use this to populate case channel field later.</description>
    <label>RingCentralChannel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseCreatorController.cls
public class CaseCreatorController {
    
    private ApexPages.StandardController standardController;
    
    public CaseCreatorController(ApexPages.StandardController standardController){
                this.standardController = standardController;
    }
    
    public PageReference createSupportCase(){
        // Apex code for handling record from a Detail page goes here
        Id contactRecordId = standardController.getId();
        Log.push('Contact ID:'+contactRecordId);
        Contact[] contacts = [SELECT Id,Brand_Id__c,RingCentralChannel__c,Phone,MobilePhone,OtherPhone FROM Contact WHERE id = :contactRecordId];
       	Contact selectedContact = contacts[0];
        Log.push('selectedContact:'+selectedContact);
        String recordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('Support Case').getRecordTypeId();
        //pick first not null phone number of contact in order of priority, Phone >MobilePhone>OtherPhone
        String incomingPhoneNumber = String.isNotBlank(selectedContact.Phone)?selectedContact.Phone:selectedContact.MobilePhone;  
        if(String.isBlank(incomingPhoneNumber)){ //if still blank after checking phone and mobilePhone, default to otherPhone
            incomingPhoneNumber = selectedContact.OtherPhone;
        }
        Case c = new Case();
        c.RecordTypeId = recordTypeId;
        c.Origin = SYSTEM.LABEL.Phone;
        c.Brand__c = selectedContact.Brand_Id__c;
        c.SuppliedPhone = incomingPhoneNumber;
        if(String.isNotBlank(selectedContact.RingCentralChannel__c)){
           c.Channel__c = selectedContact.RingCentralChannel__c;
        }
        c.ContactId = contactRecordId;
        insert c;
        String urlvalue=Apexpages.currentPage().getUrl();
        Log.push('current page URL:'+urlvalue);

		ApexPages.StandardController sc = new ApexPages.StandardController(c);
        PageReference pr= sc.view();
        pr.setRedirect(true);
        Logger.logDebug();
        return pr;
    }
   
    /*
    public PageReference save() {
        Log.push('Hitting save in CaseCreator');
        PageReference detailPage = standardController.save();
        if (detailPage != null) {
            // Construct URL of edit page or whatever other page you want
            PageReference editPage = new PageReference(detailPage.getUrl() + '/e');
            return editPage;
        } else {
            return detailPage;
        }
    }*/
    
    

 /*
    public static PageReference Search(){
        // Get the caller's number
       String ani = ApexPages.CurrentPage().getParameters().get('ANI');
         
        Log.push('received ani '+ani);
        // Search for contacts with that phone number
        Contact[] contacts = [SELECT Id FROM Contact WHERE Phone = :ani];
        
        // Create a Case and automatically populate some of the fields
                //Contact[] contacts = [SELECT Id FROM Contact WHERE id = :I];

        Case c = new Case();
        //c.Subject = 'Case created for inbound call from: ' + ani;
        c.Origin = 'Phone';
         
        // If we have a single match create and link to Case. Then pop the Case in edit mode.
        If (contacts.Size() > 0) {
            c.ContactId = contacts[0].Id;
        }
        insert c;
 
        return new PageReference('/' + c.Id + '/e');
    }*/
}