unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/CreatedByMethod__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMethod__c</fullName>
    <label>Created By Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/ZdPVH.recordType-meta.xml
<RecordType>
    <fullName>ZdPVH</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk PVH</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/ZdTnC.recordType-meta.xml
<RecordType>
    <fullName>ZdTnC</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk True &amp; Co</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CreatedByMethod__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMethod__c</fullName>
    <label>Created By Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZdPVHUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH User Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZdTnCUserId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCUserId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C User Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ZdBatch_assignContactsToCasesTest.cls
@isTest
public class ZdBatch_assignContactsToCasesTest {
    private static testMethod void testUpdateContactIdAccountIdOnCaseForZendeskCaseMigration()
    {
        Id zdPVHRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdPVH').getRecordTypeId();
        Id zdTnCRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdTnC').getRecordTypeId();

        List<Account> lstAccount = new List<Account>();
        lstAccount.add(new Account(Name='Test Account ABC'));
        lstAccount.add(new Account(Name='Test Account PQR'));
        insert lstAccount;

        List<Contact> lstContact = new List<Contact>();
        lstContact.add(new Contact( ZdTnCUserId__c = '230000', AccountId = lstAccount[1].Id, LastName = 'Test Contact PQR', FirstName='jay', Brand_Id__c='1', Email='test1@mail.com'));
        lstContact.add(new Contact( ZdPVHUserId__c = '44449999', AccountId = lstAccount[0].Id, LastName = 'Test Contact ABC', FirstName='joe', Brand_Id__c='2', Email='test2@mail.com'));

        insert lstContact;



        Test.startTest();


        List<Case> lstCase = new List<Case>();
        lstCase.add(new Case(RecordTypeId = zdTnCRecordTypeId, Subject='ZdTnCTicketId__c present ', Origin = 'Email' , SuppliedEmail = 'abc@gmail.com' ,
                ZdTnCUserId__c = '230000',ZdTnCTicketId__c = '3333999', Source_System__c = 'Zendesk T&C', Status = 'Closed', CreatedByMethod__c='Data Migration',
                Brand__c='1'
        ));
        lstCase.add(new Case(RecordTypeId = zdPVHRecordTypeId, Subject='ZdPVHTicketId__c present', Origin = 'Email' , SuppliedEmail = 'abc@gmail.com' ,
                ZdPVHUserId__c = '44449999', ZdPVHTicketId__c = '44449999', Source_System__c = 'Zendesk PVH', Status = 'Closed', CreatedByMethod__c='Data Migration',
                Brand__c='1'
        ));


        insert lstCase;

       List <Case> casesBefore = [select id, ContactId, ZdTnCTicketId__c, ZdTnCUserId__c, ZdPVHTicketId__c, ZdPVHUserId__c, Contact.Id, Contact.ZdPVHUserId__c, Contact.ZdTnCUserId__c from Case];

        for (Case c: casesBefore){
            System.debug('*** case: '+ c);
        }     

        ZdBatch_assignContactsToCases thisBatch1 = new ZdBatch_assignContactsToCases();
        Database.executeBatch(thisBatch1);




        Test.stopTest();

        List <Case> casesAfter = [select id, ContactId, ZdTnCTicketId__c, ZdTnCUserId__c, ZdPVHTicketId__c, ZdPVHUserId__c, Contact.Id, Contact.ZdPVHUserId__c, Contact.ZdTnCUserId__c from Case];

        for (Case c: casesAfter){
            System.debug('*** case: '+ c);
        }

    }

}