unpackaged/main/default/objects/Case/fields/Is_Milestone_Violated__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone_Violated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone Violated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Support_Case.recordType-meta.xml
<RecordType>
    <fullName>Support_Case</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Support Case</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Support_Case_Read_Only.recordType-meta.xml
<RecordType>
    <fullName>Support_Case_Read_Only</fullName>
    <active>true</active>
    <businessProcess>Support Case - Read Only</businessProcess>
    <label>Support Case - Read Only</label>
</RecordType>

unpackaged/main/default/objects/NF_Batch_Control__mdt/NF_Batch_Control__mdt.object-meta.xml
<CustomObject>
    <label>NF Batch Control</label>
    <pluralLabel>NF Batches Control</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Batch_Control__mdt/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <description>The query to be run by the batch</description>
    <inlineHelpText>Determines the batch size to run</inlineHelpText>
    <label>Query String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BatchCaseClose.cls
/*  Class: BatchCaseClose
*  Description : Batch class to update Case with Status = Closed as per the No of Days specified
*(After 24 hours of violation of milestone case gets closed automatically)
*/

global class BatchCaseClose implements Database.Batchable <sObject>{
    
    
    Id SupportRecordId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
    Id SupportReadOnlyRecordId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case_Read_Only').getRecordTypeId();
    String QueryString = Null;
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        
        NF_Batch_Control__mdt batchMeta = NF_Batch_Control__mdt.getInstance('BatchCaseClose');
        QueryString = batchMeta.Query_String__c;
        Log.push('QueryString: '+ QueryString);
        Logger.logDebug();
        return Database.getQueryLocator(QueryString);
    }
    
    global void execute(Database.BatchableContext bc, List<Case> records){
        List<Case> caseList = new List<Case>();
        
        for(Case c: records){
            date createddate = date.valueOf(c.CreatedDate);
            date today = date.valueOf(system.now());
            integer datediff = CreatedDate.daysBetween(Today);
            
            if((c.Type == 'Support') && (c.Is_Milestone_Violated__c = True)){
                Log.push('>>>Support Record Check');
                
                
                if(datediff > 4){
                    Log.push('>>>Support child case Record Closed');
                    c.Status = 'Closed';
                    c.RecordTypeId = SupportReadOnlyRecordId;
                    caseList.add(c);
                }
            } 
            
        }
        Log.push('Caselist size: '+caseList.size());
        
        if(caseList.size()>0){
            List<Database.SaveResult> results = Database.update(caseList, false);
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()){
                    for (Database.Error err : result.getErrors()){
                        Log.push('Error: '+ err.getStatusCode() + ' ' + err.getMessage());
                    }
                }
            }
        }
        Logger.logDebug();      
    }
    global void finish(Database.BatchableContext bc){
        
    }
}