unpackaged/main/default/objects/Case/fields/NFCaseScenario__c.field-meta.xml
<CustomField>
    <fullName>NFCaseScenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to categorize the Case</description>
    <label>Case Scenario</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NF_Case_Scenario__c.NFActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NF_Case_Scenario__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Manufacturers__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Manufacturers__c</fullName>
    <label>Reason Code Manufacturers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accessory Network</fullName>
            </value>
            <value>
                <fullName>American Essentials</fullName>
            </value>
            <value>
                <fullName>Basic Resources (VH Socks)</fullName>
            </value>
            <value>
                <fullName>BCNY</fullName>
            </value>
            <value>
                <fullName>Calvin Klein Sportswear</fullName>
            </value>
            <value>
                <fullName>ClearVision Optical</fullName>
            </value>
            <value>
                <fullName>COTY</fullName>
            </value>
            <value>
                <fullName>Customer Leather</fullName>
            </value>
            <value>
                <fullName>Cutie Pie Baby (100364)</fullName>
            </value>
            <value>
                <fullName>Delta Galil</fullName>
            </value>
            <value>
                <fullName>Estee</fullName>
            </value>
            <value>
                <fullName>Fishman &amp; Tobin (477)</fullName>
            </value>
            <value>
                <fullName>Fletcher</fullName>
            </value>
            <value>
                <fullName>G-III Apparel Group (54163)</fullName>
            </value>
            <value>
                <fullName>Global Brands Group</fullName>
            </value>
            <value>
                <fullName>Harbor Footwear</fullName>
            </value>
            <value>
                <fullName>Himatsingka (33699)</fullName>
            </value>
            <value>
                <fullName>Internal Wholesale</fullName>
            </value>
            <value>
                <fullName>Jimlar</fullName>
            </value>
            <value>
                <fullName>Kayser-Roth Corp.</fullName>
            </value>
            <value>
                <fullName>Kids Headquarters</fullName>
            </value>
            <value>
                <fullName>LF Home</fullName>
            </value>
            <value>
                <fullName>Marc Fisher</fullName>
            </value>
            <value>
                <fullName>Marchon (77169)</fullName>
            </value>
            <value>
                <fullName>Marcraft</fullName>
            </value>
            <value>
                <fullName>Max Leather</fullName>
            </value>
            <value>
                <fullName>Movado</fullName>
            </value>
            <value>
                <fullName>Nourison</fullName>
            </value>
            <value>
                <fullName>Pacific Coast Feather (19648)</fullName>
            </value>
            <value>
                <fullName>Peerless</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Product_Category__c</fullName>
    <label>Reason Code Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Activewear</fullName>
            </value>
            <value>
                <fullName>Bags/Wallets</fullName>
            </value>
            <value>
                <fullName>Bottoms</fullName>
            </value>
            <value>
                <fullName>Cosmetic Products</fullName>
            </value>
            <value>
                <fullName>Dress Shirts</fullName>
            </value>
            <value>
                <fullName>Dresses/Skirts</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Fragrances</fullName>
            </value>
            <value>
                <fullName>Home Products</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
            <value>
                <fullName>Jeans/Denim</fullName>
            </value>
            <value>
                <fullName>Luggage</fullName>
            </value>
            <value>
                <fullName>Outerwear</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Shirts/Tops/Blouses/Polos</fullName>
            </value>
            <value>
                <fullName>Suiting/Formal Wear</fullName>
            </value>
            <value>
                <fullName>Sweaters/Wovens</fullName>
            </value>
            <value>
                <fullName>Swimwear</fullName>
            </value>
            <value>
                <fullName>Tops</fullName>
            </value>
            <value>
                <fullName>Underwear</fullName>
            </value>
            <value>
                <fullName>Watches/Jewelry</fullName>
            </value>
            <value>
                <fullName>Web Form Submission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Product_Sub_Categories_Widge__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Product_Sub_Categories_Widge__c</fullName>
    <label>Reason Code Product Sub-Categories</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code_Product_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bath Products</fullName>
            </value>
            <value>
                <fullName>Bedding Products</fullName>
            </value>
            <value>
                <fullName>Belts</fullName>
            </value>
            <value>
                <fullName>Coats/Jackets</fullName>
            </value>
            <value>
                <fullName>Cold Weather</fullName>
            </value>
            <value>
                <fullName>Décor/Accessories</fullName>
            </value>
            <value>
                <fullName>Dinnerware</fullName>
            </value>
            <value>
                <fullName>Eyewear</fullName>
            </value>
            <value>
                <fullName>Formal Wear</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Goggles</fullName>
            </value>
            <value>
                <fullName>Handbags</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Kids Footwear</fullName>
            </value>
            <value>
                <fullName>Mens Footwear</fullName>
            </value>
            <value>
                <fullName>Mens Suiting</fullName>
            </value>
            <value>
                <fullName>Men’s Underwear</fullName>
            </value>
            <value>
                <fullName>Overcoats</fullName>
            </value>
            <value>
                <fullName>Rugs</fullName>
            </value>
            <value>
                <fullName>Slippers</fullName>
            </value>
            <value>
                <fullName>Small Goods</fullName>
            </value>
            <value>
                <fullName>Socks/Tights</fullName>
            </value>
            <value>
                <fullName>Swim Caps</fullName>
            </value>
            <value>
                <fullName>Swim Shoes</fullName>
            </value>
            <value>
                <fullName>Elite/LZR Competition</fullName>
            </value>
            <value>
                <fullName>General Swimwear</fullName>
            </value>
            <value>
                <fullName>Tie/Neckwear</fullName>
            </value>
            <value>
                <fullName>Umbrella</fullName>
            </value>
            <value>
                <fullName>Wallets</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Sub_detail__c.field-meta.xml
<CustomField>
    <fullName>Reason_Sub_detail__c</fullName>
    <label>Reason Sub-detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code_Details__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Activewear</fullName>
            </value>
            <value>
                <fullName>Advertisement Feedback</fullName>
            </value>
            <value>
                <fullName>Associate Behavior</fullName>
            </value>
            <value>
                <fullName>Bags/Wallets</fullName>
            </value>
            <value>
                <fullName>Bottoms</fullName>
            </value>
            <value>
                <fullName>Canadian Return Policy</fullName>
            </value>
            <value>
                <fullName>Carrier Claim</fullName>
            </value>
            <value>
                <fullName>Checkout/Cart</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>Cosmetic Products</fullName>
            </value>
            <value>
                <fullName>Customer Injury</fullName>
            </value>
            <value>
                <fullName>Customer Profiling</fullName>
            </value>
            <value>
                <fullName>Damaged Package</fullName>
            </value>
            <value>
                <fullName>Dead Hyperlink</fullName>
            </value>
            <value>
                <fullName>Delivered Not Received</fullName>
            </value>
            <value>
                <fullName>Dresses/Skirts</fullName>
            </value>
            <value>
                <fullName>Dress Shirts</fullName>
            </value>
            <value>
                <fullName>Editorial Feedback</fullName>
            </value>
            <value>
                <fullName>Employment Opportunities</fullName>
            </value>
            <value>
                <fullName>Employment Verification</fullName>
            </value>
            <value>
                <fullName>Express Shipping Delays</fullName>
            </value>
            <value>
                <fullName>Fashion Event Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Final Sale Inquiry</fullName>
            </value>
            <value>
                <fullName>Fit &amp; Sizing Question</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Fragrances</fullName>
            </value>
            <value>
                <fullName>General Sponsorship</fullName>
            </value>
            <value>
                <fullName>Gift Return/Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sku_Style_Number__c.field-meta.xml
<CustomField>
    <fullName>Sku_Style_Number__c</fullName>
    <label>SKU/Style Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHDateofServiceIssue__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHDateofServiceIssue__c</fullName>
    <label>Date of Service Issue</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHDistrictNumber__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHDistrictNumber__c</fullName>
    <label>District Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHStoreNumber__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHStoreNumber__c</fullName>
    <label>Store Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHUpdateAccountInfoReason__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHUpdateAccountInfoReason__c</fullName>
    <label>Update Account Info Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_ReasonCodeController.cls
public with sharing class NF_ReasonCodeController {
   @AuraEnabled(cacheable=true)
        public static Case getCase(String recordId) {
            return [
                SELECT NFCaseScenario__c,
                Reason_Sub_detail__c,
                Reason_Code_Product_Category__c,
                Reason_Code_Product_Sub_Categories_Widge__c,
                Reason_Code_Manufacturers__c,
                Sku_Style_Number__c,
                ZdPVHStoreNumber__c,
                ZdPVHDistrictNumber__c,
                ZdPVHDateofServiceIssue__c,
                ZdPVHUpdateAccountInfoReason__c
                FROM Case
                WHERE Id =: recordId
                LIMIT 1
            ];
        }
    }