unpackaged/main/default/objects/Case/fields/PendingPointsAdjustment__c.field-meta.xml
<CustomField>
    <fullName>PendingPointsAdjustment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Points Adjustment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/IsLoyaltyApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsLoyaltyApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this brand is part of Loyalty program or not.</description>
    <label>IsLoyaltyApplicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/A1_MergeLoyaltyAccApexController.cls
/*****************************************************************************************
 * @Description: Apex Class to check if the Loyalty is applicable for Case->Contact->Brand
 * @Author      : Rounak P
 * @Date          : 25 Feb 2020
 * @JIRA          : NASSC-1472
 *
 *****************************************************************************************/
public without sharing class A1_MergeLoyaltyAccApexController{
    @AuraEnabled
    public static Boolean checkIsLoyaltyApplicable(Id recordId){
        Boolean isLoyaltyApplicable = false;
        try{
            Case getCase = [Select Id, Contact.Brand_Id__c, PendingPointsAdjustment__c
                            from Case
                            where Id = :recordId];
            List<LoyaltySettings__mdt> loyaltyData = [Select Id, IsLoyaltyApplicable__c
                                                      from LoyaltySettings__mdt
                                                      WHERE BrandId__c = :getCase.Contact.Brand_Id__c];

            if (loyaltyData.size() > 0)
                isLoyaltyApplicable = loyaltyData[0].IsLoyaltyApplicable__c;
        } catch (Exception ex){
            Logger.logException(ex);
        }

        return isLoyaltyApplicable;
    }

}