unpackaged/main/default/objects/Case/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Returns</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Details__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Details__c</fullName>
    <label>Reason Code Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accepted Forms of Payment</fullName>
            </value>
            <value>
                <fullName>Account Information (Member ID)</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Account Issue (Godzilla, Dummy Account)</fullName>
            </value>
            <value>
                <fullName>Account Issue (Loyalty Flag)</fullName>
            </value>
            <value>
                <fullName>Account Merge</fullName>
            </value>
            <value>
                <fullName>Account Registration Error</fullName>
            </value>
            <value>
                <fullName>Adaptive</fullName>
            </value>
            <value>
                <fullName>Address Error</fullName>
            </value>
            <value>
                <fullName>Associate Discount</fullName>
            </value>
            <value>
                <fullName>Authorization Hold</fullName>
            </value>
            <value>
                <fullName>Balance Confirmation (Points/Rewards)</fullName>
            </value>
            <value>
                <fullName>BBB Complaint</fullName>
            </value>
            <value>
                <fullName>Black Friday Complaint</fullName>
            </value>
            <value>
                <fullName>Brand Protection</fullName>
            </value>
            <value>
                <fullName>Bulk Buyer Warning</fullName>
            </value>
            <value>
                <fullName>Business Solicitation</fullName>
            </value>
            <value>
                <fullName>Call/Chat Disconnect</fullName>
            </value>
            <value>
                <fullName>Cancelled Item</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order Request</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Check Complaint</fullName>
            </value>
            <value>
                <fullName>Check Inventory/Restock Inquiry</fullName>
            </value>
            <value>
                <fullName>Check-out Error (Non-Fraud/Payment)</fullName>
            </value>
            <value>
                <fullName>Claim Status</fullName>
            </value>
            <value>
                <fullName>Contest/Sweepstakes</fullName>
            </value>
            <value>
                <fullName>Corporate Outfitters Request</fullName>
            </value>
            <value>
                <fullName>Corporate Responsibility</fullName>
            </value>
            <value>
                <fullName>Corp Social Responsibility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Manufacturers__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Manufacturers__c</fullName>
    <label>Reason Code Manufacturers</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accessory Network</fullName>
            </value>
            <value>
                <fullName>American Essentials</fullName>
            </value>
            <value>
                <fullName>Basic Resources (VH Socks)</fullName>
            </value>
            <value>
                <fullName>BCNY</fullName>
            </value>
            <value>
                <fullName>Calvin Klein Sportswear</fullName>
            </value>
            <value>
                <fullName>ClearVision Optical</fullName>
            </value>
            <value>
                <fullName>COTY</fullName>
            </value>
            <value>
                <fullName>Customer Leather</fullName>
            </value>
            <value>
                <fullName>Cutie Pie Baby (100364)</fullName>
            </value>
            <value>
                <fullName>Delta Galil</fullName>
            </value>
            <value>
                <fullName>Estee</fullName>
            </value>
            <value>
                <fullName>Fishman &amp; Tobin (477)</fullName>
            </value>
            <value>
                <fullName>Fletcher</fullName>
            </value>
            <value>
                <fullName>G-III Apparel Group (54163)</fullName>
            </value>
            <value>
                <fullName>Global Brands Group</fullName>
            </value>
            <value>
                <fullName>Harbor Footwear</fullName>
            </value>
            <value>
                <fullName>Himatsingka (33699)</fullName>
            </value>
            <value>
                <fullName>Internal Wholesale</fullName>
            </value>
            <value>
                <fullName>Jimlar</fullName>
            </value>
            <value>
                <fullName>Kayser-Roth Corp.</fullName>
            </value>
            <value>
                <fullName>Kids Headquarters</fullName>
            </value>
            <value>
                <fullName>LF Home</fullName>
            </value>
            <value>
                <fullName>Marc Fisher</fullName>
            </value>
            <value>
                <fullName>Marchon (77169)</fullName>
            </value>
            <value>
                <fullName>Marcraft</fullName>
            </value>
            <value>
                <fullName>Max Leather</fullName>
            </value>
            <value>
                <fullName>Movado</fullName>
            </value>
            <value>
                <fullName>Nourison</fullName>
            </value>
            <value>
                <fullName>Pacific Coast Feather (19648)</fullName>
            </value>
            <value>
                <fullName>Peerless</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Code_Product_Sub_Categories_Widge__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code_Product_Sub_Categories_Widge__c</fullName>
    <label>Reason Code Product Sub-Categories</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code_Product_Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bath Products</fullName>
            </value>
            <value>
                <fullName>Bedding Products</fullName>
            </value>
            <value>
                <fullName>Belts</fullName>
            </value>
            <value>
                <fullName>Coats/Jackets</fullName>
            </value>
            <value>
                <fullName>Cold Weather</fullName>
            </value>
            <value>
                <fullName>Décor/Accessories</fullName>
            </value>
            <value>
                <fullName>Dinnerware</fullName>
            </value>
            <value>
                <fullName>Eyewear</fullName>
            </value>
            <value>
                <fullName>Formal Wear</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Goggles</fullName>
            </value>
            <value>
                <fullName>Handbags</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Kids Footwear</fullName>
            </value>
            <value>
                <fullName>Mens Footwear</fullName>
            </value>
            <value>
                <fullName>Mens Suiting</fullName>
            </value>
            <value>
                <fullName>Men’s Underwear</fullName>
            </value>
            <value>
                <fullName>Overcoats</fullName>
            </value>
            <value>
                <fullName>Rugs</fullName>
            </value>
            <value>
                <fullName>Slippers</fullName>
            </value>
            <value>
                <fullName>Small Goods</fullName>
            </value>
            <value>
                <fullName>Socks/Tights</fullName>
            </value>
            <value>
                <fullName>Swim Caps</fullName>
            </value>
            <value>
                <fullName>Swim Shoes</fullName>
            </value>
            <value>
                <fullName>Elite/LZR Competition</fullName>
            </value>
            <value>
                <fullName>General Swimwear</fullName>
            </value>
            <value>
                <fullName>Tie/Neckwear</fullName>
            </value>
            <value>
                <fullName>Umbrella</fullName>
            </value>
            <value>
                <fullName>Wallets</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Sub_detail__c.field-meta.xml
<CustomField>
    <fullName>Reason_Sub_detail__c</fullName>
    <label>Reason Sub-detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reason_Code_Details__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Activewear</fullName>
            </value>
            <value>
                <fullName>Advertisement Feedback</fullName>
            </value>
            <value>
                <fullName>Associate Behavior</fullName>
            </value>
            <value>
                <fullName>Bags/Wallets</fullName>
            </value>
            <value>
                <fullName>Bottoms</fullName>
            </value>
            <value>
                <fullName>Canadian Return Policy</fullName>
            </value>
            <value>
                <fullName>Carrier Claim</fullName>
            </value>
            <value>
                <fullName>Checkout/Cart</fullName>
            </value>
            <value>
                <fullName>Color</fullName>
            </value>
            <value>
                <fullName>Cosmetic Products</fullName>
            </value>
            <value>
                <fullName>Customer Injury</fullName>
            </value>
            <value>
                <fullName>Customer Profiling</fullName>
            </value>
            <value>
                <fullName>Damaged Package</fullName>
            </value>
            <value>
                <fullName>Dead Hyperlink</fullName>
            </value>
            <value>
                <fullName>Delivered Not Received</fullName>
            </value>
            <value>
                <fullName>Dresses/Skirts</fullName>
            </value>
            <value>
                <fullName>Dress Shirts</fullName>
            </value>
            <value>
                <fullName>Editorial Feedback</fullName>
            </value>
            <value>
                <fullName>Employment Opportunities</fullName>
            </value>
            <value>
                <fullName>Employment Verification</fullName>
            </value>
            <value>
                <fullName>Express Shipping Delays</fullName>
            </value>
            <value>
                <fullName>Fashion Event Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Final Sale Inquiry</fullName>
            </value>
            <value>
                <fullName>Fit &amp; Sizing Question</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Fragrances</fullName>
            </value>
            <value>
                <fullName>General Sponsorship</fullName>
            </value>
            <value>
                <fullName>Gift Return/Exchange</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHDateofServiceIssue__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHDateofServiceIssue__c</fullName>
    <label>Date of Service Issue</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHDistrictNumber__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHDistrictNumber__c</fullName>
    <label>District Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHStoreNumber__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHStoreNumber__c</fullName>
    <label>Store Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHUpdateAccountInfoReason__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHUpdateAccountInfoReason__c</fullName>
    <label>Update Account Info Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ReasonCodeButtonController.cls
public class ReasonCodeButtonController {
    @AuraEnabled 
    public static Map<String, List<String>> getDependentPicklist(sObject objDetail,string contrfieldApiName,string depfieldApiName ) {
        String controllingField = contrfieldApiName.toLowerCase();
        String dependentField = depfieldApiName.toLowerCase();
       
        
        Map<String,List<String>> objResults = new Map<String,List<String>>();
        Schema.sObjectType objType = objDetail.getSObjectType();
        if (objType==null){
            return objResults;
        }
        
       Map<String, Schema.SObjectField> objFieldMap = objType.getDescribe().fields.getMap();
      
        
        
        if (!objFieldMap.containsKey(controllingField) || !objFieldMap.containsKey(dependentField)){
            return objResults;     
        }
        
        Schema.SObjectField theField = objFieldMap.get(dependentField);
        Schema.SObjectField ctrlField = objFieldMap.get(controllingField);
        
        List<Schema.PicklistEntry> contrEntries = ctrlField.getDescribe().getPicklistValues();
        List<PicklistEntryWrapper> depEntries = wrapPicklistEntries(theField.getDescribe().getPicklistValues());
        List<String> controllingValues = new List<String>();
        
        for (Schema.PicklistEntry ple : contrEntries) {
            String label = ple.getLabel();
            objResults.put(label, new List<String>());
            controllingValues.add(label);
        }
        
        for (PicklistEntryWrapper plew : depEntries) {
            String label = plew.label;
            String validForBits = base64ToBits(plew.validFor);
            for (Integer i = 0; i < validForBits.length(); i++) {
                String bit = validForBits.mid(i, 1);
                if (bit == '1') {
                    objResults.get(controllingValues.get(i)).add(label);
                }
            }
        }
        return objResults;
    }
    
    public static String decimalToBinary(Integer val) {
        String bits = '';
        while (val > 0) {
            Integer remainder = Math.mod(val, 2);
            val = Integer.valueOf(Math.floor(val / 2));
            bits = String.valueOf(remainder) + bits;
        }
        return bits;
    }
    
    public static String base64ToBits(String validFor) {
        if (String.isEmpty(validFor)) return '';
        
        String validForBits = '';
        
        for (Integer i = 0; i < validFor.length(); i++) {
            String thisChar = validFor.mid(i, 1);
            Integer val = base64Chars.indexOf(thisChar);
            String bits = decimalToBinary(val).leftPad(6, '0');
            validForBits += bits;
        }
        
        return validForBits;
    }
    
    private static final String base64Chars = '' +
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '0123456789+/';
    
    
    private static List<PicklistEntryWrapper> wrapPicklistEntries(List<Schema.PicklistEntry> PLEs) {
        return (List<PicklistEntryWrapper>)
            JSON.deserialize(JSON.serialize(PLEs), List<PicklistEntryWrapper>.class);
    }
    
    
     @AuraEnabled
        public static List<String> getselectOptions(sObject objObject, string fld) {
                  system.debug('objObject --->' + objObject);
                  system.debug('fld --->' + fld);
                  List<String> allOpts = new list<String> ();
                  // Get the object type of the SObject.
                  Schema.sObjectType objType = objObject.getSObjectType();
                 
                  // Describe the SObject using its object type.
                  Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
                 
                  // Get a map of fields for the SObject
                  map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
                 
                  // Get the list of picklist values for this field.
                  list<Schema.PicklistEntry> values =fieldMap.get(fld).getDescribe().getPickListValues();
                 
                  // Add these values to the selectoption list.
                  for (Schema.PicklistEntry a: values) {
                   allOpts.add(a.getValue());
                  }
                  system.debug('allOpts ---->' + allOpts);
                  allOpts.sort();
                  return allOpts;
       }
    public class PicklistEntryWrapper{
        public String active {get;set;}
        public String defaultValue {get;set;}
        public String label {get;set;}
        public String value {get;set;}
        public String validFor {get;set;}
        public PicklistEntryWrapper(){            
        }
        
    }
    /*  @AuraEnabled get Case Manufaturer Picklist Values 
   public static List<String> getManufacturers(){
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Case.Reason_Code_Manufacturers__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
            System.debug('Values in Manufacturers are: '+pickListValuesList);
        }     
        return pickListValuesList;
    }*/
     
    
    @AuraEnabled
    public static List<Case> updateCase (String recordId ,String grandParent,String productSubCategory, String parentField,String childField ,date dateofServiceIssue, String storeNumber , String districtNumber, String updateAccountInfoReason , String manufacturer,String productCategory, string skuNumber,string thirdPartyVendor){
        list<Case> caseList = new list<Case>();
        list<Case> updatedCaseList = new list<Case>();
        caseList = [select Id,ZdPVHDateofServiceIssue__c, ZdPVHStoreNumber__c ,Reason_Code_Product_Sub_Categories_Widge__c,ZdPVHDistrictNumber__c,ZdPVHUpdateAccountInfoReason__c, Reason_Code__c, Reason_Code_Details__c,Reason_Sub_detail__c,Reason_Code_Manufacturers__c,Reason_Code_Product_Category__c,Sku_Style_Number__c,Third_Party_Vendors__c from case where Id =: recordId];
      
      for(Case cse : caseList){
          cse.Reason_Code__c = grandParent ;
          cse.Reason_Code_Details__c=parentField;
          cse.Reason_Sub_detail__c = childField ;
          cse.ZdPVHDateofServiceIssue__c=dateofServiceIssue;
          cse.ZdPVHStoreNumber__c = storeNumber ;
          cse.ZdPVHDistrictNumber__c=districtNumber;
          cse.ZdPVHUpdateAccountInfoReason__c=updateAccountInfoReason;
          cse.Reason_Code_Manufacturers__c=manufacturer;
          cse.Reason_Code_Product_Category__c=productCategory;
          cse.Sku_Style_Number__c=skuNumber;
          cse.Third_Party_Vendors__c=thirdPartyVendor;
          cse.Reason_Code_Product_Sub_Categories_Widge__c=productSubCategory;
          //todo: replace reason code and details
          if(cse.Reason_Code__c!=Null || cse.Reason_Code_Details__c!=Null || cse.Reason_Sub_detail__c!=Null ||
             cse.ZdPVHDateofServiceIssue__c!=Null || cse.ZdPVHStoreNumber__c!=Null || cse.ZdPVHDistrictNumber__c!=Null || cse.ZdPVHUpdateAccountInfoReason__c!=Null || cse.Reason_Code_Manufacturers__c!=Null || cse.Reason_Code_Product_Category__c!=Null||
             cse.Sku_Style_Number__c!=Null || cse.Third_Party_Vendors__c!=Null ||
             cse.Reason_Code_Product_Sub_Categories_Widge__c!=Null
            ){ 
                          updatedCaseList.add(cse);
                }
          
          }
       
        
        if(updatedCaseList.size()>0){
            
             update updatedCaseList;            
           }
      
          return updatedCaseList;
 }
    @AuraEnabled
    public static List<Case> trueNcoUpdateCase (String recordId ,String grandParent,String parentField,String childField,String skuNumber,string channel,String placeOfPurchase){
       list<Case> caseList = new list<Case>();
       list<Case> updatedTrNcoCaseList = new list<Case>(); 
       caseList = [select Id,Brand__c,Channel__c,Place_of_Purchase__c,Reason_Code__c,Reason_Code_Details__c,Reason_Sub_detail__c,TrueAndCo_ReasonCodes__c, TrueAndCo_ReasonCodeDetails__c ,TrueAndCo_ReasonSubDetail__c,Sku_Style_Number__c from case where Id =: recordId AND Brand__c='11'];
       system.debug(caseList+'**caseList**');
        
        string chan;
        if(channel=='Online - trueandco.com'){
            chan='trueandco.com';
        }
        else{
           chan=channel; 
        }
        
       for(Case cse : caseList){
         cse.Reason_Code__c = grandParent ;
         cse.Reason_Code_Details__c=parentField;
         cse.Reason_Sub_detail__c = childField ;
         cse.TrueAndCo_ReasonCodes__c = grandParent ;
         cse.TrueAndCo_ReasonCodeDetails__c=parentField;
         cse.TrueAndCo_ReasonSubDetail__c = childField ;   
         cse.Sku_Style_Number__c=skuNumber;
         cse.Channel__c=chan;
         cse.Place_of_Purchase__c=placeOfPurchase;
           if(cse.Reason_Code__c !=Null || cse.Reason_Code_Details__c !=Null || cse.Reason_Sub_detail__c !=Null || cse.Sku_Style_Number__c !=Null
              || cse.TrueAndCo_ReasonCodes__c !=Null || cse.TrueAndCo_ReasonCodeDetails__c !=Null ||  cse.TrueAndCo_ReasonSubDetail__c !=Null ||
             cse.Place_of_Purchase__c!= Null
             ){
              updatedTrNcoCaseList.add(cse);
           } 
        /*  cse.TrueAndCo_ReasonCodes__c = grandParent ;
         cse.TrueAndCo_ReasonCodeDetails__c=parentField;
         cse.TrueAndCo_ReasonSubDetail__c = childField ;  
           if(cse.TrueAndCo_ReasonCodes__c!=Null || cse.TrueAndCo_ReasonCodeDetails__c!=Null || cse.TrueAndCo_ReasonSubDetail__c!=Null){
              updatedCaseList.add(cse);
           } */
        
       }
        
      if(updatedTrNcoCaseList.size()>0){
        update updatedTrNcoCaseList;            
      }
        
       return updatedTrNcoCaseList;  
    }
    
}