unpackaged/main/default/objects/Case/fields/ZdParentTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdParentTicketId__c</fullName>
    <externalId>true</externalId>
    <label>ZdParentTicketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdPVHTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ZdBatch_relateParentCases.cls
global class ZdBatch_relateParentCases implements Database.Batchable <sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, ZdPVHTicketId__c, ZdParentTicketId__c  FROM Case WHERE ZdPVHTicketId__c != null AND ZdParentTicketId__c != null AND ParentId = null ORDER BY ZdParentTicketId__c');
    }
    global void execute(Database.BatchableContext bc, List<Case> scope){


        Set<String> PVHParentIds = new Set<String>();

        Map<String,Id> PVHParentIdToParentCaseIdMap = new Map<String,Id>();

        List<Case> childCasesforUpdate = new List<Case>();

        for(Case curCase : scope){

            PVHParentIds.add(curCase.ZdParentTicketId__c);

        }

        for(Case parCase : [SELECT Id, ZdPVHTicketId__c FROM Case WHERE ZdPVHTicketId__c =: PVHParentIds]){
       		PVHParentIdToParentCaseIdMap.put(parCase.ZdPVHTicketId__c, parCase.id);
        }
        for(Case curCase : scope){
            if (PVHParentIdToParentCaseIdMap.containsKey(curCase.ZdParentTicketId__c)) {
                curCase.ParentId = PVHParentIdToParentCaseIdMap.get(curCase.ZdParentTicketId__c);
                childCasesforUpdate.add(curCase);
            }
        }

        if (childCasesforUpdate.size()>0) update childCasesforUpdate;
    }
    global void finish(Database.BatchableContext bc){}
}