unpackaged/main/default/objects/Case/fields/ZdPVHTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/ZdPVH.recordType-meta.xml
<RecordType>
    <fullName>ZdPVH</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk PVH</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/ZdTnC.recordType-meta.xml
<RecordType>
    <fullName>ZdTnC</fullName>
    <active>true</active>
    <businessProcess>Support Case</businessProcess>
    <label>Zendesk True &amp; Co</label>
</RecordType>

unpackaged/main/default/objects/ZdTicketComment__c/ZdTicketComment__c.object-meta.xml
<CustomObject>
    <label>Zendesk Ticket Comments</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zendesk Ticket Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ZdTicketComment__c/fields/CommentBody__c.field-meta.xml
<CustomField>
    <fullName>CommentBody__c</fullName>
    <label>CommentBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/created_at__c.field-meta.xml
<CustomField>
    <fullName>created_at__c</fullName>
    <label>created_at</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdPVHCommentId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHCommentId__c</fullName>
    <externalId>true</externalId>
    <label>ZdPVHCommentId</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdPVHParentTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHParentTicketId__c</fullName>
    <externalId>true</externalId>
    <label>ZdPVHParentTicketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdTnCCommentId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCCommentId__c</fullName>
    <externalId>true</externalId>
    <label>ZdTnCCommentId</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdTnCParentTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCParentTicketId__c</fullName>
    <externalId>true</externalId>
    <label>ZdTnCParentTicketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ZdTicketCommentsTriggerTest.cls
@isTest
public class ZdTicketCommentsTriggerTest {

    @isTest
    static void testPVHComment(){

        Id zdPVHRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdPVH').getRecordTypeId();
        Id zdTnCRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ZdTnC').getRecordTypeId();

        Case c1 = new Case();
        c1.ZdPVHTicketId__c = 'PVHTicket111';
        c1.RecordTypeId = zdPVHRecordTypeId;
        insert c1;

        Case c2 = new Case();
        c2.ZdTnCTicketId__c = 'TnCTicket111';

        c2.RecordTypeId = zdTnCRecordTypeId;
        insert c2;

        List<ZdTicketComment__c> tcList = new List<ZdTicketComment__c>();
        Test.startTest();
        ZdTicketComment__c tc2 = new ZdTicketComment__c();
        tc2.ZdTnCParentTicketId__c = 'TnCTicket111';
        tc2.CommentBody__c = 'some body text';
        tc2.ZdTnCCommentId__c = 'for TnCTicket111';
        tc2.created_at__c = System.now();
        tcList.add(tc2);

        ZdTicketComment__c tc1 = new ZdTicketComment__c();
        tc1.ZdPVHParentTicketId__c = 'PVHTicket111';
        tc1.CommentBody__c = 'some body text';
        tc1.ZdPVHCommentId__c = 'for PVHTicket111';
        tc1.created_at__c = System.now();
        tcList.add(tc1);
        insert tcList;
        Test.stopTest();
        List<CaseComment> CaseCommentList = [select id, ParentId from CaseComment];
        System.assertEquals(c2.id, CaseCommentList[0].ParentId);

        System.assertEquals(c1.id, CaseCommentList[1].ParentId);


    }


}