unpackaged/main/default/objects/Case/fields/ZdPVHTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk PVH Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZdTnCTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCTicketId__c</fullName>
    <externalId>true</externalId>
    <label>Zendesk T&amp;C Ticket Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/ZdTicketComment__c.object-meta.xml
<CustomObject>
    <label>Zendesk Ticket Comments</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zendesk Ticket Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ZdTicketComment__c/fields/CommentBody__c.field-meta.xml
<CustomField>
    <fullName>CommentBody__c</fullName>
    <label>CommentBody</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/created_at__c.field-meta.xml
<CustomField>
    <fullName>created_at__c</fullName>
    <label>created_at</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdPVHParentTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdPVHParentTicketId__c</fullName>
    <externalId>true</externalId>
    <label>ZdPVHParentTicketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZdTicketComment__c/fields/ZdTnCParentTicketId__c.field-meta.xml
<CustomField>
    <fullName>ZdTnCParentTicketId__c</fullName>
    <externalId>true</externalId>
    <label>ZdTnCParentTicketId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_ZdTicketCommentsTriggerHelper.cls
public class NF_ZdTicketCommentsTriggerHelper {
    public static void handleBeforeInsert(List<ZdTicketComment__c> newList){
        List <String> PVHTicketIds = new List<String>();
        List <String> TnCTicketIds = new List<String>();
        List <Case> PVHParentCases = new List<Case>();   
        List <Case> TnCParentCases = new List<Case>();
        Map <string,Id> PVHCaseIdMap = new Map<string,Id>();
        Map <string,Id> TnCCaseIdMap = new Map<string,Id>();
        List <CaseComment> CaseCommentList = new List<CaseComment>();
        for (ZdTicketComment__c tc: newList){
            if (tc.ZdPVHParentTicketId__c!=null) PVHTicketIds.add(tc.ZdPVHParentTicketId__c);
            else if (tc.ZdTnCParentTicketId__c!=null) TnCTicketIds.add(tc.ZdTnCParentTicketId__c);
        }
        PVHParentCases = [select id, ZdPVHTicketId__c, ZdTnCTicketId__c  from Case where ZdPVHTicketId__c in :PVHTicketIds or ZdTnCTicketId__c in :TnCTicketIds];
        for(Case c: PVHParentCases){
            if (c.ZdPVHTicketId__c!=null) PVHCaseIdMap.put(c.ZdPVHTicketId__c, c.id);
            else if (c.ZdTnCTicketId__c!=null) TnCCaseIdMap.put(c.ZdTnCTicketId__c, c.id);
        }   
        for (ZdTicketComment__c tc: newList){
            CaseComment newCaseComment = new CaseComment();
            newCaseComment.CommentBody = tc.CommentBody__c;
            newCaseComment.isPublished = true;
            newCaseComment.CreatedDate = tc.created_at__c;
            if (tc.ZdPVHParentTicketId__c!=null) newCaseComment.ParentId = PVHCaseIdMap.get(tc.ZdPVHParentTicketId__c);
            else if (tc.ZdTnCParentTicketId__c!=null) newCaseComment.ParentId = TnCCaseIdMap.get(tc.ZdTnCParentTicketId__c);
            if (newCaseComment.ParentId!=null) CaseCommentList.add(newCaseComment);
        }
        if (CaseCommentList.size()>0) insert CaseCommentList;
        
    }
}