unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/ExpireDate__c.field-meta.xml
<CustomField>
    <fullName>ExpireDate__c</fullName>
    <label>ExpireDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Reward_Number__c.field-meta.xml
<CustomField>
    <fullName>Reward_Number__c</fullName>
    <formula>LEFT(SequenceNumber__c,(LEN(SequenceNumber__c) - (LEN(SequenceNumber__c) - FIND(LoyaltyId__c, SequenceNumber__c)+1)))</formula>
    <label>Reward Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardType__c.field-meta.xml
<CustomField>
    <fullName>RewardType__c</fullName>
    <label>RewardType</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/sfscToSfccactiveRewards.cls
@RestResource(urlMapping='/Fetching/ActiveRewards1')
global class sfscToSfccactiveRewards {
    global class ActiveRewards {
        public String LoyaltyId;
        public String RewardType;
        public String RewardId;
        public String ActiveFlag;
        public String IssuanceDate;
        public String ExpireDate;
        public String TransactionId;
    }
    global class SubResponse {
        public String Code;
        public String Count;
        public List<ActiveRewards> ActiveRewards;
    }
    @httpGet
    global static void doFetch(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        Map<String, String> paramsMap = RestContext.request.params;
        String loyaltyId = paramsMap.get('BrandId');
        String brandId = paramsMap.get('LoyaltyId');
         List<Reward__c> lstRew=[Select Id,LoyaltyId__c, Reward_Number__c, RewardId__c, RewardType__c, Status__c,ExpireDate__c
                                      From Reward__c
                                      Where LoyaltyId__c=:loyaltyId AND Status__c='Active'limit 1];
        //if(lstRew.size()>0){
            res.statusCode = 200;
            SubResponse successres = new SubResponse();
            successres.code='Ok';
            successres.Count=string.valueof(lstRew.size());
        List<ActiveRewards> lstActRew=new List<ActiveRewards>();
        ActiveRewards objRew=new ActiveRewards();
        objRew.TransactionId=loyaltyId;
        objRew.IssuanceDate=brandId;
        lstActRew.add(objRew);
        successres.ActiveRewards=lstActRew;
            res.responseBody = Blob.valueOf(JSON.serialize(successres));
            return;
       // }
    }
    
}