unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SFCCActiveRewardsTest.cls
@isTest
public class SFCCActiveRewardsTest {
    public static testmethod void testdoFetch(){
        test.startTest();
        Reward__c objRew=new Reward__c();
        objRew.LoyaltyId__c='E04005339606';
        objRew.Status__c='Active';
        objRew.RewardId__c='E04005339606';
        insert objRew;
        RestResponse res = new RestResponse();
        string url='E04005339606';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('LoyaltyId','E04005339606');
        RestContext.request.params.put('BrandId', '2');
        RestContext.response= res;
        SFCCActiveRewards.doFetch();
        test.stopTest();
        Assert.areEqual(res.statusCode, 200);
    }
    public static testmethod void testdoFetch1(){
        test.startTest();        
        RestResponse res = new RestResponse();
        string url='E04005339606';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('LoyaltyId','E04005339605');
        RestContext.request.params.put('BrandId', '2');
        RestContext.response= res;
        SFCCActiveRewards.doFetch();
        test.stopTest();
        Assert.areEqual(res.statusCode, 200);
    }
    public static testmethod void testdoFetch2(){
        test.startTest();        
        RestResponse res = new RestResponse();
        string url='E04005339606';
        RestContext.request = new RestRequest();
        RestContext.request.params.put('LoyaltyId','');
        RestContext.request.params.put('BrandId', 'E04005339606');
        RestContext.response= res;
        SFCCActiveRewards.doFetch();
        test.stopTest();
        Assert.areEqual(res.statusCode, 400);
    }
    
}