unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SFCCRewardUpdateTest.cls
@isTest
public class SFCCRewardUpdateTest {
    public static testmethod void testdoFetch(){
        String jsonStr = '{'+
            '  \"BrandId\": \"2\",'+
            '  \"LoyaltyId\": \"C0000000001\",'+
            '  \"Status\": \"Active\",'+
            '  \"RewardId\":[\"1621080000000C000000000117\",\"1621080000000C000000000118\",\"1621080000000C000000000119\" '+
            '  ],'+
            '  \"OperationType\": \"Cancelled\",'+
            '  \"OrderId\": \"\"'+
            '}';
        test.startTest();
        Reward__c objRew=new Reward__c();
        objRew.LoyaltyId__c='C0000000001';
        objRew.Status__c='Pending Redeemed';
        objRew.RewardId__c='1621080000000C000000000117';
        insert objRew;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='/services/apexrest/SFCCRewards/Update/';
        request.httpMethod = 'POST';
        request.requestBody=Blob.valueof(JSOnStr);
        RestContext.request = request;
        RestContext.response= res;
        SFCCRewardUpdate.doUpdate();
        test.stopTest();
    }
    public static testmethod void testErrorInvalidBrand(){
        String jsonStr = '{'+
            '  \"BrandId\": \"3\",'+
            '  \"LoyaltyId\": \"C0000000001\",'+
            '  \"Status\": \"Active\",'+
            '  \"RewardId\":[\"1621080000000C000000000117\",\"1621080000000C000000000118\",\"1621080000000C000000000119\" '+
            '  ],'+
            '  \"OperationType\": \"Cancelled\",'+
            '  \"OrderId\": \"\"'+
            '}';
        test.startTest();
        Reward__c objRew=new Reward__c();
        objRew.LoyaltyId__c='C0000000001';
        objRew.Status__c='Pending Redeemed';
        objRew.RewardId__c='1621080000000C000000000117';
        insert objRew;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='/services/apexrest/SFCCRewards/Update/';
        request.httpMethod = 'POST';
        request.requestBody=Blob.valueof(JSOnStr);
        RestContext.request = request;
        RestContext.response= res;
        SFCCRewardUpdate.doUpdate();
        test.stopTest();
    }
    public static testmethod void testErrorEmptyValues(){
        String jsonStr = '{'+
            '  \"BrandId\": \"2\",'+
            '  \"LoyaltyId\": \"\",'+
            '  \"Status\": \"Active\",'+
            '  \"RewardId\":[\"1621080000000C000000000117\",\"1621080000000C000000000118\",\"1621080000000C000000000119\" '+
            '  ],'+
            '  \"OperationType\": \"Cancelled\",'+
            '  \"OrderId\": \"\"'+
            '}';
        test.startTest();
        Reward__c objRew=new Reward__c();
        objRew.LoyaltyId__c='C0000000001';
        objRew.Status__c='Pending Redeemed';
        objRew.RewardId__c='1621080000000C000000000117';
        insert objRew;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='/services/apexrest/SFCCRewards/Update/';
        request.httpMethod = 'POST';
        request.requestBody=Blob.valueof(JSOnStr);
        RestContext.request = request;
        RestContext.response= res;
        SFCCRewardUpdate.doUpdate();
        test.stopTest();
    }
}