unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/NF_Nice_InContact_API_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations(endpoint, request type, timeout, header, etc) to be used in callouts to the Nice InContact API.</description>
    <label>Nice InContact API Config</label>
    <pluralLabel>Nice InContact API Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/fields/Delete_Obsolete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Obsolete_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Keep this checked if you need to delete the records created by this API sync.</inlineHelpText>
    <label>Delete Obsolete Records</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/fields/Object_to_Create__c.field-meta.xml
<CustomField>
    <fullName>Object_to_Create__c</fullName>
    <inlineHelpText>The object type that needs to be created. If &quot;Create Records&quot; is checked, this value is mandatory.</inlineHelpText>
    <label>Object to Create</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NF_Agents_Performance__c</fullName>
                <label>Agent Performance</label>
            </value>
            <value>
                <fullName>NF_Skills_SLA_Summary__c</fullName>
                <label>Skills SLA Summary</label>
            </value>
            <value>
                <fullName>NF_Skills_Summary__c</fullName>
                <label>Skills Summary</label>
            </value>
            <value>
                <fullName>NF_Teams_Performance_Total__c</fullName>
                <label>Teams Performance Total</label>
            </value>
            <value>
                <fullName>NF_Contacts_Completed__c</fullName>
                <label>Contacts Completed</label>
            </value>
            <value>
                <fullName>NF_Agent_State_History__c</fullName>
                <label>Agent State History</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NF_DeleteOldRingCentralDataSchBatch.cls
/**
 * @description       : Batch class to delete old/obsolete Ring Central data
 * @author            : chayan.batabyal@neuraflash.com
 * @last modified on  : 09-10-2021
 * @last modified by  : chayan.batabyal@neuraflash.com
**/
global class NF_DeleteOldRingCentralDataSchBatch implements Database.Batchable<SObject>, Schedulable{

    @TestVisible private String objectName = '';
    @TestVisible private Integer index = 0;
    @TestVisible private List<String> objectsToDelete = new List<String>();

    @TestVisible private Final Integer BATCH_SIZE = 2000;
    @TestVisible private Final String FIELD_TO_CONSIDER = LABEL.NF_RC_FIELD_TO_CONSIDER_FOR_DELETION;
    @TestVisible private Final DateTime CUT_OFF_DATE = Date.today().addMonths(
        -1 * Integer.valueOf(LABEL.NF_RC_CUTOFF_MONTHS_FOR_DATA_DELETION)
    );

    /**
    * @description Override execute method of schedulable interface
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    * @param SC
    **/
    global void execute(SchedulableContext SC) {
        for(
            NF_Nice_InContact_API_Config__mdt eachMetaRecord :
            NF_Nice_InContact_API_Config__mdt.getAll().values()
        ){
            if(
                eachMetaRecord.Delete_Obsolete_Records__c &&
                String.isNotBlank(eachMetaRecord.Object_to_Create__c)
            ){
                objectsToDelete.add(eachMetaRecord.Object_to_Create__c);
            }
        }

        Log.push('objectsToDelete :: ' + objectsToDelete);
        Logger.logDebug();
        if(!objectsToDelete.isEmpty()){
            NF_DeleteOldRingCentralDataSchBatch batchable =
                new NF_DeleteOldRingCentralDataSchBatch(objectsToDelete, index);
            Database.executeBatch(batchable, BATCH_SIZE);
        }
    }

    /**
    * @description Default Constructor
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    **/
    public NF_DeleteOldRingCentralDataSchBatch(){}

    /**
    * @description Custom Constructor for setting class variables
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    * @param objectAPINames
    * @param indexToSet
    **/
    public NF_DeleteOldRingCentralDataSchBatch(List<String> objectAPINames, Integer indexToSet){
        objectsToDelete = objectAPINames;
        index = indexToSet;
        objectName = objectsToDelete[index];
    }

    /**
    * @description Override start method of batchable interface
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    * @param ctx
    * @return Database.QueryLocator
    **/
    public Database.QueryLocator start(Database.BatchableContext ctx) {
        DateTime futureDate = Date.today().addYears(1);
        String query = String.isNotBlank(objectName) ?
            ('SELECT Id FROM ' + objectName + ' WHERE ' + FIELD_TO_CONSIDER + ' <: CUT_OFF_DATE') :
            'SELECT Id FROM Account WHERE CreatedDate >: futureDate AND IsDeleted = true';
        return Database.getQueryLocator(query);
    }

    /**
    * @description Override execute method of batchable interface
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    * @param BC
    * @param recordsToDelete
    **/
    public void execute(Database.BatchableContext ctx, List<SObject> recordsToDelete){
        Integer deleteSize = recordsToDelete != null && !recordsToDelete.isEmpty() ? recordsToDelete.size() : 0;
        Log.push(
            'Deleting ' + deleteSize + ' records of ' + objectName +
            ' object whose ' + FIELD_TO_CONSIDER + ' < ' + CUT_OFF_DATE
        );
        Logger.logDebug();
        Database.delete(recordsToDelete);
    }

    /**
    * @description Override finish method of batchable interface
    * @author chayan.batabyal@neuraflash.com | 09-08-2021
    * @param BC
    **/
    public void finish(Database.BatchableContext ctx){
        if(++index < objectsToDelete.size()){
            NF_DeleteOldRingCentralDataSchBatch batchable =
                new NF_DeleteOldRingCentralDataSchBatch(objectsToDelete, index);
            if(!Test.isRunningTest()){
                Database.executeBatch(batchable, BATCH_SIZE);
            }
        }
    }
}