unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/NF_Nice_InContact_API_Config__mdt.object-meta.xml
<CustomObject>
    <description>Configurations(endpoint, request type, timeout, header, etc) to be used in callouts to the Nice InContact API.</description>
    <label>Nice InContact API Config</label>
    <pluralLabel>Nice InContact API Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/fields/Delete_Obsolete_Records__c.field-meta.xml
<CustomField>
    <fullName>Delete_Obsolete_Records__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Keep this checked if you need to delete the records created by this API sync.</inlineHelpText>
    <label>Delete Obsolete Records</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NF_Nice_InContact_API_Config__mdt/fields/Object_to_Create__c.field-meta.xml
<CustomField>
    <fullName>Object_to_Create__c</fullName>
    <inlineHelpText>The object type that needs to be created. If &quot;Create Records&quot; is checked, this value is mandatory.</inlineHelpText>
    <label>Object to Create</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NF_Agents_Performance__c</fullName>
                <label>Agent Performance</label>
            </value>
            <value>
                <fullName>NF_Skills_SLA_Summary__c</fullName>
                <label>Skills SLA Summary</label>
            </value>
            <value>
                <fullName>NF_Skills_Summary__c</fullName>
                <label>Skills Summary</label>
            </value>
            <value>
                <fullName>NF_Teams_Performance_Total__c</fullName>
                <label>Teams Performance Total</label>
            </value>
            <value>
                <fullName>NF_Contacts_Completed__c</fullName>
                <label>Contacts Completed</label>
            </value>
            <value>
                <fullName>NF_Agent_State_History__c</fullName>
                <label>Agent State History</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NF_DeleteOldRingCentralDataSchBatchTest.cls
/**
 * @description       : Test class for NF_DeleteOldRingCentralDataSchBatch
 * @author            : chayan.batabyal@neuraflash.com
 * @last modified on  : 09-10-2021
 * @last modified by  : chayan.batabyal@neuraflash.com
**/
@isTest(seeAllData = false)
public class NF_DeleteOldRingCentralDataSchBatchTest {
    /**
    * @description Inserts data for testing deletion
    * @author chayan.batabyal@neuraflash.com | 09-09-2021
    **/
    @TestSetup
    static void setupData(){
        List<String> objectsToCreate = new List<String>();
        for(
            NF_Nice_InContact_API_Config__mdt eachMetaRecord :
            NF_Nice_InContact_API_Config__mdt.getAll().values()
        ){
            if(
                eachMetaRecord.Delete_Obsolete_Records__c &&
                String.isNotBlank(eachMetaRecord.Object_to_Create__c)
            ){
                objectsToCreate.add(eachMetaRecord.Object_to_Create__c);
            }
        }

        if(!objectsToCreate.isEmpty()){
            DateTime dt = Date.today().addMonths(
                -1 * (Integer.valueOf(LABEL.NF_RC_CUTOFF_MONTHS_FOR_DATA_DELETION) + 1)
            );
            List<SObject> recordsToInsert = new List<SObject>();
            for(String eachSObjectAPIName : objectsToCreate){
                Schema.SObjectType targetType = Schema.getGlobalDescribe().get(eachSObjectAPIName);
                SObject newSObject = targetType.newSObject();
                newSobject.put('Start_Date__c', dt);
                newSobject.put('End_Date__c', dt);
                recordsToInsert.add(newSobject);
            }
            insert recordsToInsert;

            for(SObject eachRecord : recordsToInsert){
                Test.setCreatedDate(Id.valueOf(String.valueOf(eachRecord.get('Id'))), dt);
            }
        }
    }

    /**
    * @description Tests scheduling of batch class and immediate execution of it too.
    * @author chayan.batabyal@neuraflash.com | 09-09-2021
    * @return testMethod
    **/
    public static testMethod void testDeletion(){
        List<String> objectNames = new List<String>();
        List<SObject> insertedRecords = new List<SObject>();
        List<SObject> recordsInDB = new List<SObject>();

        for(
            NF_Nice_InContact_API_Config__mdt eachMetaRecord :
            NF_Nice_InContact_API_Config__mdt.getAll().values()
        ){
            if(
                eachMetaRecord.Delete_Obsolete_Records__c &&
                String.isNotBlank(eachMetaRecord.Object_to_Create__c)
            ){
                objectNames.add(eachMetaRecord.Object_to_Create__c);
                insertedRecords.addAll(Database.query('SELECT Id FROM ' + eachMetaRecord.Object_to_Create__c));
            }
        }
        if(!objectNames.isEmpty()){
            NF_DeleteOldRingCentralDataSchBatch schedulable = new NF_DeleteOldRingCentralDataSchBatch();
            String cronExp = '0 30 0 1 * ?';

            Test.startTest();
            String jobId = System.schedule('testDeletion', cronExp, schedulable);
            CronTrigger ct = [SELECT TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(0, ct.TimesTriggered);
            System.assertEquals(30, ct.NextFireTime.minute());
            Database.executeBatch(new NF_DeleteOldRingCentralDataSchBatch(objectNames, 0));
            Test.stopTest();

            for(String eachObjectName : objectNames){
                recordsInDB.addAll(Database.query('SELECT Id FROM ' + eachObjectName));
            }

            System.assert(recordsInDB.size() < insertedRecords.size());
        }
    }
}