unpackaged/main/default/objects/pcify__Log__c/pcify__Log__c.object-meta.xml
<CustomObject>
    <description>Dev Logging</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__Category__c.field-meta.xml
<CustomField>
    <fullName>pcify__Category__c</fullName>
    <description>What is the classification for the log</description>
    <inlineHelpText>What is the classification for the log</inlineHelpText>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__CreditCardDetected__c.field-meta.xml
<CustomField>
    <fullName>pcify__CreditCardDetected__c</fullName>
    <description>TRUE if a credit card number was detected.</description>
    <formula>pcify__LuhnValid__c</formula>
    <inlineHelpText>TRUE if a credit card number was detected.</inlineHelpText>
    <label>Credit Card Detected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__Object__c.field-meta.xml
<CustomField>
    <fullName>pcify__Object__c</fullName>
    <description>Object type where log is originating from</description>
    <inlineHelpText>Object type where log is originating from</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__RecordId__c.field-meta.xml
<CustomField>
    <fullName>pcify__RecordId__c</fullName>
    <description>Id of the record</description>
    <inlineHelpText>Id of the record</inlineHelpText>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DeleteContentDocumentBatch.cls
/**
 * Created by bryananderson on 10/7/19.
 */

global class DeleteContentDocumentBatch implements
                Database.Batchable<sObject>, Database.Stateful {

    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT pcify__RecordId__c FROM pcify__Log__c WHERE (pcify__CreditCardDetected__c = TRUE OR pcify__Category__c = \'Record Deleted\') AND pcify__Object__c = \'ContentVersion\' ORDER BY CreatedDate DESC');
    }

    global void execute(Database.BatchableContext bc, List<pcify__Log__c> scope) {
        Set<Id> contentVersionIds = new Set<Id>();

        for (pcify__Log__c log : scope) {
            contentVersionIds.add(log.pcify__RecordId__c);
        }

        Log.push('contentVersionIds'+contentVersionIds);

        Set<ContentVersion> cvSet = new Set<ContentVersion>([SELECT ContentDocumentId FROM ContentVersion WHERE Id IN :contentVersionIds]);

        Log.push('cvSet=== ' + cvSet);

        Set<Id> cdSet = new Set<Id>();

        for (ContentVersion cv: cvSet) {
            cdSet.add(cv.ContentDocumentId);
        }

        List<ContentDocument> cdList = Database.Query('SELECT Id FROM ContentDocument WHERE Id IN :cdSet AND IsDeleted = false');

        Log.push('cdList=== ' + cdList);

        for (ContentDocument cd : cdList) {
            recordsProcessed = recordsProcessed + 1;
        }
        Logger.logDebug();
        delete cdList;
    }
    global void finish(Database.BatchableContext bc) {
        Log.push(recordsProcessed + ' records processed.');
        Logger.logDebug();
        System.scheduleBatch(new DeleteContentDocumentBatch(), 'Delete ContentDocument containing Credit Card ' + DateTime.now() + ' - ' + Math.random(), 5);
    }
}