unpackaged/main/default/objects/pcify__Log__c/pcify__Log__c.object-meta.xml
<CustomObject>
    <description>Dev Logging</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__CreditCardDetected__c.field-meta.xml
<CustomField>
    <fullName>pcify__CreditCardDetected__c</fullName>
    <description>TRUE if a credit card number was detected.</description>
    <formula>pcify__LuhnValid__c</formula>
    <inlineHelpText>TRUE if a credit card number was detected.</inlineHelpText>
    <label>Credit Card Detected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__Object__c.field-meta.xml
<CustomField>
    <fullName>pcify__Object__c</fullName>
    <description>Object type where log is originating from</description>
    <inlineHelpText>Object type where log is originating from</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pcify__Log__c/fields/pcify__RecordId__c.field-meta.xml
<CustomField>
    <fullName>pcify__RecordId__c</fullName>
    <description>Id of the record</description>
    <inlineHelpText>Id of the record</inlineHelpText>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DeleteContentDocumentBatchTest.cls
/**
 * Created by bryananderson on 10/7/19.
 */

/*@isTest
private class DeleteContentDocumentBatchTest {
    /*static testmethod void test() {
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.txt';
        cv.VersionData = Blob.valueOf('Test Content');
        //cv.IsMajorVersion = true;
        //cv.FirstPublishLocationId = UserInfo.getUserId();
        //cv.ContentLocation='S';

        Test.startTest();
        Insert cv;
        Test.stopTest();
    }*/

  /*  private static void TestData()
    {
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.txt';
        cv.VersionData = Blob.valueOf('Test Content');
        insert cv;
    }

    private static testmethod void Batchtest()
    {
        //calling Test Data Method
        TestData();
        test.startTest();
        id BatchId = Database.executeBatch(new DeleteContentDocumentBatch());
        test.stopTest();

    }
}*/

//edited testClass 
@isTest
public class DeleteContentDocumentBatchTest 
{
	@testsetup
    static void setup()
    {
      list<pcify__log__c> l=[SELECT pcify__RecordId__c FROM pcify__Log__c WHERE pcify__CreditCardDetected__c = TRUE AND pcify__Object__c ='ContentVersion' ORDER BY CreatedDate DESC limit 10];
    	insert l;
        list<ContentVersion> CVl=[SELECT ContentDocumentId FROM ContentVersion limit 10];
        insert CVl;
        //list<ContentDocument> CDl=[SELECT FileType,SharingOption FROM ContentDocument];
        //insert CDl;
    }
    
    @isTest
    static void test()
    {
        Test.startTest();
        DeleteContentDocumentBatch dcbc=new DeleteContentDocumentBatch();
        Id batchId=Database.executeBatch(dcbc);
        Test.stopTest();  
    }
    
    @isTest
    static void test2()
    {
        //String sch='20 30 8 10 2 ?';
        Test.startTest();
        String jobid=System.scheduleBatch(new DeleteContentDocumentBatch(),'Schedule',5);
        Test.stopTest();
    }
}