unpackaged/main/default/objects/A1_C360API_creds__mdt/A1_C360API_creds__mdt.object-meta.xml
<CustomObject>
    <description>Purpose of this MDT is to store the brand specific 360 API credentials specific to the environment.</description>
    <label>A1 C360API creds</label>
    <pluralLabel>A1 C360API creds</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_C360API_creds__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/A1_TrackerAPI_creds__mdt.object-meta.xml
<CustomObject>
    <description>Holds credentials for Agil1&#39;s tracker API.</description>
    <label>A1 TrackerAPI creds</label>
    <pluralLabel>A1 TrackerAPI creds</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/CustomMetadataCallbackTest.cls
@isTest
public class CustomMetadataCallbackTest {
    static testMethod void testCreateMetaDataA1c360APIToken() {
        // Create test data
        A1_C360API_creds__mdt credRec = new A1_C360API_creds__mdt();
        credRec.BrandId__c = 'TestBrand';
        Scheduler_A1C360APITokens.responseClass resp = new Scheduler_A1C360APITokens.responseClass();
        resp.access_token = 'TestAccessToken';
        resp.expires_in = 3600;
        Map<A1_C360API_creds__mdt, Scheduler_A1C360APITokens.responseClass> responseValAndMetdataMap = new Map<A1_C360API_creds__mdt, Scheduler_A1C360APITokens.responseClass>();
        responseValAndMetdataMap.put(credRec, resp);

        // Call method to test
        CustomMetadataCallback.createMetaDataA1c360APIToken(responseValAndMetdataMap);

    }

    static testMethod void testCreateTrackerAPITokenMetaData() {
        A1_TrackerAPI_creds__mdt trackerCredRec = new A1_TrackerAPI_creds__mdt();
        trackerCredRec.BrandId__c = 'TestBrand';
        Scheduler_A1TrackerAPITokens.responseClass resp = new Scheduler_A1TrackerAPITokens.responseClass();
        resp.access_token = 'TestAccessToken';
        resp.expires_in = 3600; 
        Map<A1_TrackerAPI_creds__mdt, Scheduler_A1TrackerAPITokens.responseClass> responseValAndMetdataMap = new Map<A1_TrackerAPI_creds__mdt, Scheduler_A1TrackerAPITokens.responseClass>();
        responseValAndMetdataMap.put(trackerCredRec, resp);
        // Call method to test
        CustomMetadataCallback.createTrackerAPITokenMetaData(responseValAndMetdataMap);
    }
}