unpackaged/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>ErrorLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ErrorLog__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>FileName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Its used to store Error Log Message</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>Its used to store Error Log Source System</description>
    <label>SourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Its used to store Error Log StackTrace</description>
    <label>StackTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/ExpireDate__c.field-meta.xml
<CustomField>
    <fullName>ExpireDate__c</fullName>
    <label>ExpireDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/IssuanceDate__c.field-meta.xml
<CustomField>
    <fullName>IssuanceDate__c</fullName>
    <label>IssuanceDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/OriginalExpireDate__c.field-meta.xml
<CustomField>
    <fullName>OriginalExpireDate__c</fullName>
    <label>Original Expiry Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RedeemedDate__c.field-meta.xml
<CustomField>
    <fullName>RedeemedDate__c</fullName>
    <label>Redeemed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardType__c.field-meta.xml
<CustomField>
    <fullName>RewardType__c</fullName>
    <label>RewardType</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/SequenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SequenceNumber__c</fullName>
    <description>Sequence Number and CouponId from Loyalty system</description>
    <externalId>true</externalId>
    <label>SequenceNumber</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/RewardsTest.cls
/*******************************************************************************************
* @Description: Test Class for class - Rewards
* @Author     : 
* @Date       : April 28
* @JIRA       : NASSC-1710 [NASSC-1712]
*
********************************************************************************************/ 

@isTest
public class RewardsTest {
    static Map<String, String> responseHeaders = new Map<String, String>();
  
    //method: fake response
    //@isTest(SeeAllData=true) 
    public static void setMockResponse(){
        
        responseHeaders.put('Content-Type','application/json');
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                               'Complete',
                                                               '{ }',
                                                               responseHeaders);
        
        System.debug('*** fake response = '+fakeResponse);
        Test.setMock(HttpCalloutMock.class, fakeResponse);        
        
    }
    
    //method: data setup
    @testSetup
    static void dataSetup() {
        List<Reward__c> listRewards = new List<Reward__c>();
        Reward__c rewardObject = new Reward__c(
            LoyaltyId__c = 'C04000218657',
            RewardId__c = '134275624',
            RewardType__c = '16',
            SequenceNumber__c = 'S101',
            Status__c = 'Active',
            ExpireDate__c = System.now(),
            OriginalExpireDate__c = System.now(),
            IssuanceDate__c = System.now()
        );
        listRewards.add(rewardObject);
        insert listRewards;
    }
    
    //method:
    @isTest
    public static void invocablePostRewardsToA1Test(){
        setMockResponse();
        List<Rewards.RewardsData> ListData = new List<Rewards.RewardsData>();
        Rewards.RewardsData obj = new Rewards.RewardsData();
        obj.loyaltyId = 'C04000218657';
        obj.loyaltyFlag = true;
        obj.brandId = '2';
        obj.email = 'lallan@gmail.com';
        obj.rewardId = '134275624';
        ListData.add(obj);
        Rewards.invocablePostRewardsToA1(ListData);
        
    }
    
     //method: data setup
     
     static void dataSetup1() {
        List<Reward__c> listRewards = new List<Reward__c>();
        Reward__c rewardObject = new Reward__c(
            LoyaltyId__c = 'C04000218658',
            RewardId__c = '134275625',
            RewardType__c = '17',
            //SequenceNumber__c = 'S101',
            Status__c = 'Redeemed',
            ExpireDate__c = System.now(),
            OriginalExpireDate__c = System.now(),
            IssuanceDate__c = System.now(),
            RedeemedDate__c=System.now()
        );
        listRewards.add(rewardObject);
        insert listRewards;
    }
    //method:
    @isTest
    public static void invocablePostRewardsToA1Test1(){
        setMockResponse();
        List<Rewards.RewardsData> ListData = new List<Rewards.RewardsData>();
        Rewards.RewardsData obj = new Rewards.RewardsData();
        obj.loyaltyId = 'C04000218658';
        obj.loyaltyFlag = true;
        obj.brandId = '2';
        obj.email = 'test@gmail.com';
        obj.rewardId = '134275625';
        ListData.add(obj);
        Rewards.invocablePostRewardsToA1(ListData);
        
    }
    @isTest
    public static void createErrorLogTest(){
        List<ErrorLog__c> insertErrorLog=new List<ErrorLog__c>();
        String reqEndPoint='Testing';
        String reqBody='test1';
        String resStatusCode='test2';
        String resBody='test3';
        ErrorLog__c logObject = new ErrorLog__c();
        logObject.SourceSystem__c = 'SFSC to AgileOne';
        logObject.FileName__c = 'Posting Rewards to AgileOne';
        logObject.Message__c = 'Response status code: ';
        logObject.StackTrace__c = 'Testing';
        insertErrorLog.add(logObject);
        
        if(insertErrorLog.size()>0){
            insert insertErrorLog;
        }
        
        Rewards.createErrorLogs(reqEndPoint,reqBody,resStatusCode,resBody);
        
    }
     
}