unpackaged/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BatchProcess__c/BatchProcess__c.object-meta.xml
<CustomObject>
    <label>BatchProcess</label>
    <nameField>
        <displayFormat>BP-{000000000}</displayFormat>
        <label>BatchProcess Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchProcess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BatchProcess__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>Input File Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BatchProcess__c/fields/OutputFileName__c.field-meta.xml
<CustomField>
    <fullName>OutputFileName__c</fullName>
    <label>OutputFileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</description>
    <inlineHelpText>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</inlineHelpText>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <description>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <inlineHelpText>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</inlineHelpText>
    <label>B2C Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>B2C_Integration_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</description>
    <inlineHelpText>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</inlineHelpText>
    <label>Ecomm Customer Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Bulk_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Buyer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fraud</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/Contact_Staging__c/Contact_Staging__c.object-meta.xml
<CustomObject>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <label>B2C CustomerList</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <label>B2C Integration Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/b2ccrm_syncStatus__c.field-meta.xml
<CustomField>
    <fullName>b2ccrm_syncStatus__c</fullName>
    <label>b2ccrm_syncStatus</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Brand_ID__c.field-meta.xml
<CustomField>
    <fullName>Brand_ID__c</fullName>
    <label>Brand ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerNumber__c</fullName>
    <label>Customer Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/isLoyaltyVerified__c.field-meta.xml
<CustomField>
    <fullName>isLoyaltyVerified__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isLoyaltyVerified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Loyalty_Flag__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Loyalty_ID__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_ID__c</fullName>
    <label>Loyalty ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/SFSCAccountId__c.field-meta.xml
<CustomField>
    <fullName>SFSCAccountId__c</fullName>
    <label>SFSC Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Subscriber_Key__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>WCS Subscriber Key</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/ContactStaging2__c.object-meta.xml
<CustomObject>
    <label>Contact Staging 2</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Contact Staging 2 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ContactStaging2__c/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <label>B2C Customer No</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Bulk_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Buyer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Email_Optin_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Optin_Status__c</fullName>
    <label>Email Optin Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fraud</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/isLoyaltyVerified__c.field-meta.xml
<CustomField>
    <fullName>isLoyaltyVerified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isLoyaltyVerified</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/SFSC_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>SFSC_Contact_Id__c</fullName>
    <label>SFSC Contact Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Subscriber_Key__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Key__c</fullName>
    <label>WCS Subscriber Key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Welcome_source__c.field-meta.xml
<CustomField>
    <fullName>Welcome_source__c</fullName>
    <label>Welcome source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/B2C_Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronizing</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronized</fullName>
    </customValue>
    <customValue>
        <fullName>exported</fullName>
    </customValue>
    <description>... describes the integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <masterLabel>B2C Integration Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactUpdationProcess1.cls
global class ContactUpdationProcess1 implements Database.Batchable <sObject>, Database.stateful {
global List<Contact> finalConList = new List<Contact>();
    Private String fileName;
    Private Id batchProcessId;
    Private String OutputFileName;
    Private String exceptionMessage;
    Private List<Contact> conListToExportToFile = new List<Contact>();
    
    global ContactUpdationProcess1(){
        List<BatchProcess__c> nextBP = [SELECT Id, IsProcessed__c, FileName__c FROM BatchProcess__c WHERE IsProcessed__c = false LIMIT 1];
        if(nextBP.size() > 0){
            fileName = nextBP[0].FileName__c;
            System.debug('fileName: '+fileName);
            batchProcessId = nextBP[0].Id;
            System.debug('batchProcessId: '+batchProcessId);
            //OutputFileName = nextBP[0].OutputFileName__c;
        }
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //modify the query to pick the first unporcessed file
        return Database.getQueryLocator( [SELECT Id, B2C_CustomerList_ID__c, B2C_CustomerList__c, B2C_Disable_Integration__c, 
                                          B2C_Integration_Status__c, B2C_Is_Enabled__c, Brand_ID__c, FileName__c, Point_Balance__c, SFSC_Contact_Id__c, 
                                          B2C_Customer_No__c 
                                          FROM ContactStaging2__c WHERE FileName__c =: fileName LIMIT 100]); //0032C00000eOODoQAO   (Subscriber_Key__c != null OR Email__c != null)
    }
    global void execute(Database.BatchableContext bc, List<ContactStaging2__c> conStgList) {

        List<Contact> conListToUpdate = new List<Contact>();
        for(ContactStaging2__c cs2: conStgList ){
            Contact con = new Contact();
            con.Id = cs2.SFSC_Contact_Id__c;
            con.B2C_CustomerList_ID__c = cs2.B2C_CustomerList_ID__c;
            con.B2C_CustomerList__c = cs2.B2C_CustomerList__c;
            con.B2C_Disable_Integration__c = cs2.B2C_Disable_Integration__c;
            con.B2C_Integration_Status__c = cs2.B2C_Integration_Status__c;
            con.B2C_Is_Enabled__c = cs2.B2C_Is_Enabled__c;
            con.Point_Balance__c = cs2.Point_Balance__c;
            con.B2C_Customer_No__c = cs2.B2C_Customer_No__c;
            conListToUpdate.add(con);
            conListToExportToFile.add(con);
        }
        try{
            Update conListToUpdate;
        }
        catch(DmlException e){
            exceptionMessage = e.getMessage();
        }
        
        
        }
    global void finish(Database.BatchableContext BC){
        
        string header = 'Sub_Key,B2C_CustomerList_ID__c,B2C_CustomerList__c,B2C_Disable_Integration__c,B2C_Integration_Status__c,B2C_Is_Enabled__c,Point_Balance__c,B2C_Customer_No__c,exceptionMessage\n';
        string finalstr = header;
        for(Contact c: conListToExportToFile){
            string recordString = c.id+','+c.B2C_CustomerList_ID__c+','+c.B2C_CustomerList__c+','+c.B2C_Disable_Integration__c+','+c.B2C_Integration_Status__c+','+c.B2C_Is_Enabled__c+','+c.Point_Balance__c+','+c.B2C_Customer_No__c+exceptionMessage+'\n';            
            finalstr = finalstr +recordString;
        }
        /*Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalstr);
        string csvname= fileName+'.csv';
        String email1 = 'balav@stabilistech.com';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {email1};
            String subject ='Contact CSV';
        email.setSubject(subject);SELECT CustomerNumber__c, Id, Subscriber_Key__c, Loyalty_ID__c, Loyalty_Flag__c, Email_Optin_Status__c, Welcome_source__c, Brand_ID__c, Email__c, Latest_Source__c, IsProcessed__c, SFSC_Contact_Id__c, Point_Balance__c, Loyalty_Optin_Date__c, Bulk_Buyer__c, Deceased__c, Fraud__c, SFSCAccountId__c, b2ccrm_syncStatus__c, isLoyaltyVerified__c  FROM Contact_Staging__c where FileName__c = 'loyalty-2022-08-11-001.xml' AND IsProcessed__c = true
        email.setToAddresses( toAddresses );
        email.setPlainTextBody('Contact CSV ');
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        */
        ContentVersion ContVerFile = new ContentVersion();
            ContVerFile.VersionData = Blob.valueOf(finalstr);
            ContVerFile.Title = fileName; 
            ContVerFile.ContentLocation= 's';
            List<String> S = fileName.split('\\.');
            ContVerFile.PathOnClient=S[0];
        insert ContVerFile;
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:ContVerFile.Id].ContentDocumentId;
                ContentDocumentLink cDe = new ContentDocumentLink();
                cDe.ContentDocumentId = conDoc;
                cDe.LinkedEntityId = batchProcessId;
                cDe.ShareType = 'I';
                cDe.Visibility = 'AllUsers';
                insert cDe;
        //Updating the current file as processed and starting the process for next file
        
        BatchProcess__c bp = [SELECT Id, IsProcessed__c FROM BatchProcess__c WHERE FileName__c =: fileName LIMIT 1];
        bp.IsProcessed__c = true;
        Update bp;
        
        List<BatchProcess__c> nextBP = [SELECT Id, IsProcessed__c, FileName__c FROM BatchProcess__c WHERE IsProcessed__c = false LIMIT 1];
        if(nextBP.size() > 0){
            ContactUpdationProcess1 cup = new ContactUpdationProcess1();
            Id batchId = database.executeBatch(cup);
            System.debug('batchId : '+batchId);
        }
        
    } 
}