unpackaged/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/B2CCRMSyncDefaults__mdt.object-meta.xml
<CustomObject>
    <description>Storing B2C CRM Sync static data in this metadata to populate in contact staging and contacts</description>
    <label>B2C Sync Default</label>
    <pluralLabel>B2C Sync Defaults</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <label>CustomerList</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <label>B2C CustomerList ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <label>B2C Instance</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <label>B2C Integration Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</description>
    <inlineHelpText>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</inlineHelpText>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <description>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <inlineHelpText>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</inlineHelpText>
    <label>B2C Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>B2C_Integration_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</description>
    <inlineHelpText>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</inlineHelpText>
    <label>Ecomm Customer Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Bulk_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Buyer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Bulk_Buyer_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer_Update_Date__c</fullName>
    <label>Bulk Buyer Update Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fraud</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/Contact_Staging__c/Contact_Staging__c.object-meta.xml
<CustomObject>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <label>B2C CustomerList</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <label>B2C Integration Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Brand_ID__c.field-meta.xml
<CustomField>
    <fullName>Brand_ID__c</fullName>
    <label>Brand ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/CustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerNumber__c</fullName>
    <label>Customer Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Subscriber_Key__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>WCS Subscriber Key</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/UpdatePointBalance__c.field-meta.xml
<CustomField>
    <fullName>UpdatePointBalance__c</fullName>
    <label>UpdatePointBalance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/B2C_Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronizing</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronized</fullName>
    </customValue>
    <customValue>
        <fullName>exported</fullName>
    </customValue>
    <description>... describes the integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <masterLabel>B2C Integration Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/contactDataUpdation.cls
global class contactDataUpdation implements Database.Batchable<sObject>, Database.Stateful {
    
    Private String fileName;
    
    global contactDataUpdation(String fileName1){
        fileName = fileName1;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT id,Email__c, Subscriber_Key__c, UpdatePointBalance__c, CustomerNumber__c, SFSC_Contact_Id__c     
                                          FROM Contact_Staging__c WHERE FileName__c =:fileName AND IsProcessed__c = true]); 
    }
    
    global void execute(Database.BatchableContext bc, List<Contact_Staging__c> conStgList) {
        set<Id> conIdSet = new set<Id>();
        Set<String> conStgEmailSet = new Set<String>();
        Map<String, String> subKeyCustomerListMap = new Map<String, String>();
        map<string,contact> mapContactId=new map<string,contact>();
        map<string,Contact_Staging__c> mapConStag=new map<string,Contact_Staging__c>();
        for(Contact_Staging__c contStaging:conStgList){
            //Log.push('contStaging.Subscriber_Key__c'+contStaging.Subscriber_Key__c);
            //conIdSet.add(contStaging.Subscriber_Key__c);//SFSC_Contact_Id__c
            Log.push('contStaging.SFSC_Contact_Id__c'+contStaging.SFSC_Contact_Id__c);
            conIdSet.add(contStaging.SFSC_Contact_Id__c);//SFSC_Contact_Id__c
            String emailAndId = contStaging.Email__c+contStaging.SFSC_Contact_Id__c;
            Log.push('emailAndId : '+emailAndId);
            mapConStag.put(emailAndId,contStaging);
            Log.push('conIdSet>>>'+conIdSet);
        }
        B2CCRMSyncDefaults__mdt b2cSyncDefaults = [SELECT B2C_CustomerList_ID__c, B2C_CustomerList__c, B2C_Disable_Integration__c, B2C_Instance__c, B2C_Is_Enabled__c, B2C_Integration_Status__c 
                                                   FROM B2CCRMSyncDefaults__mdt WHERE DeveloperName =  'B2CSyncData'];
        List<Contact> conListToUpdate = new List<Contact>();
        
        for(contact objCont:[SELECT id,Email,Brand_Id__c,Point_Balance__c,Deceased__c,Bulk_Buyer__c,Bulk_Buyer_Update_Date__c, Fraud__c,WelcomeSource__c,Loyalty_Optin_Date__c,LoyaltyFlag__c,LoyaltyID__c,EmailOptInStatus__c, EmailOptInDate__c, EmailOptOutDate__c, Latest_Source__c 
                             FROM contact WHERE ID IN :conIdSet]){
            List<Contact> contactListForEmailOptin = new List<Contact>();
            List<Contact> conListToAdd = new List<Contact>();
            Contact conToAdd = new Contact();
            //get the B2C data form custom metadata
            //Assigning the B2C values and point balence to contact object
            conToAdd.Id = objCont.Id;
			String emailAndId = objCont.Email+objCont.Id;
			Log.push('emailAndId : '+emailAndId);
            Log.push('mapConStag.get(emailAndId).CustomerNumber__c : '+mapConStag.get(emailAndId).CustomerNumber__c);
			conToAdd.B2C_Customer_No__c = mapConStag.get(emailAndId).CustomerNumber__c;
            conToAdd.B2C_CustomerList_ID__c = b2cSyncDefaults.B2C_CustomerList_ID__c;
			conToAdd.B2C_CustomerList__c = b2cSyncDefaults.B2C_CustomerList__c;
			conToAdd.B2C_Disable_Integration__c = b2cSyncDefaults.B2C_Disable_Integration__c;
			conToAdd.B2C_Is_Enabled__c = b2cSyncDefaults.B2C_Is_Enabled__c;
			conToAdd.B2C_Integration_Status__c = b2cSyncDefaults.B2C_Integration_Status__c;
            //conToAdd.Point_Balance__c = mapConStag.get(objCont.Email).UpdatePointBalance__c;
            conListToUpdate.add(conToAdd);
            Log.push('conListToUpdate'+conListToUpdate);
        }
        if(conListToUpdate.size()>0){
            update conListToUpdate;
        }
        Logger.logDebug();
    }
    global void finish(Database.BatchableContext BC){} 
}