unpackaged/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/B2CCRMSyncDefaults__mdt.object-meta.xml
<CustomObject>
    <description>Storing B2C CRM Sync static data in this metadata to populate in contact staging and contacts</description>
    <label>B2C Sync Default</label>
    <pluralLabel>B2C Sync Defaults</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <label>CustomerList</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <label>B2C CustomerList ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <label>B2C Instance</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <label>B2C Integration Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/B2CCRMSyncDefaults__mdt/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</description>
    <inlineHelpText>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</inlineHelpText>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <description>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <inlineHelpText>... describes the last successful integration status for a given B2C Commerce customer profile represented as a Contact.</inlineHelpText>
    <label>B2C Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>B2C_Integration_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</description>
    <inlineHelpText>... describes if a given B2C Commerce customer profile is active and enabled to interact with storefronts.</inlineHelpText>
    <label>Ecomm Customer Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Bulk_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bulk Buyer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Bulk_Buyer_Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Buyer_Update_Date__c</fullName>
    <label>Bulk Buyer Update Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Fraud__c.field-meta.xml
<CustomField>
    <fullName>Fraud__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fraud</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/Contact_Staging__c/Contact_Staging__c.object-meta.xml
<CustomObject>
    <label>Contact Staging</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contact Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <label>B2C CustomerList</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>B2C_Integration_Status__c</fullName>
    <label>B2C Integration Status</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/B2C_Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>B2C_Is_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>B2C Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/b2ccrm_syncStatus__c.field-meta.xml
<CustomField>
    <fullName>b2ccrm_syncStatus__c</fullName>
    <label>b2ccrm_syncStatus</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Brand_ID__c.field-meta.xml
<CustomField>
    <fullName>Brand_ID__c</fullName>
    <label>Brand ID</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Loyalty_Flag__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Loyalty_ID__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_ID__c</fullName>
    <label>Loyalty ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/SFSCAccountId__c.field-meta.xml
<CustomField>
    <fullName>SFSCAccountId__c</fullName>
    <label>SFSC Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact_Staging__c/fields/Subscriber_Key__c.field-meta.xml
<CustomField>
    <fullName>Subscriber_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>WCS Subscriber Key</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/B2C_Integration_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronizing</fullName>
    </customValue>
    <customValue>
        <fullName>Synchronized</fullName>
    </customValue>
    <customValue>
        <fullName>exported</fullName>
    </customValue>
    <description>... describes the integration status for a given B2C Commerce customer profile represented as a Contact.</description>
    <masterLabel>B2C Integration Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactDataExtraction.cls
global class ContactDataExtraction implements Database.Batchable <sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator( [select id,Brand_ID__c,IsProcessed__c,Subscriber_Key__c, Email__c 
                                          from Contact_Staging__c where IsProcessed__c=false AND (Subscriber_Key__c != null OR Email__c != null) limit 50000]); 
    }
    global void execute(Database.BatchableContext bc, List<Contact_Staging__c> conStgList) {
        set<Id> conStgIdSet = new set<Id>();
        set<string> conStgEmailSetFromInput = new set<string>();
        set<string> conStgEmailSet = new set<string>();
        map<string,contact> mapContactId=new map<string,contact>();
        map<string,contact> mapContactEmail=new map<string,contact>();
        map<string,Contact_Staging__c> mapConStag=new map<string,Contact_Staging__c>();
        //map<string,contact> mapContact=new map<string,contact>();
        map<string,contact>mapMasterCont=new  map<string,contact>();
        List<Contact_Staging__c> lstContStg=new List<Contact_Staging__c>();
        List<Contact_Staging__c> lstContStgNoSubKey=new List<Contact_Staging__c>();
        //looping to add Staging contact Id
        //system.debug('conStgList>>'+conStgList);
        Map<String,Boolean> emailNoSubKey = new Map<String,Boolean>();
        Map<String,Id> emailCSId = new Map<String,Id>();
        Map<String,Id> emailCSIdForDuplicate = new Map<String,Id>();
        for(Contact_Staging__c cont:conStgList){
            emailCSId.put(cont.Email__c,cont.Id);
            if(cont.Subscriber_Key__c != null){
                conStgIdSet.add(cont.Subscriber_Key__c);
                emailNoSubKey.put(cont.Email__c,false);
                //system.debug('conStgIdSet>>>'+conStgIdSet);
                system.debug('emailNoSubKey>>>'+emailNoSubKey);
            }
            else{
                conStgEmailSetFromInput.add(cont.Email__c);
                emailNoSubKey.put(cont.Email__c,true);
                //system.debug('conStgEmailSetFromInput>>>'+conStgEmailSetFromInput);
                system.debug('emailNoSubKey>>>'+emailNoSubKey);
            }
		}
        //Fetching the unique email and adding the master contact records
        for(contact objCont:[SELECT id,Email,Brand_Id__c,Point_Balance__c,Deceased__c,Bulk_Buyer__c,Bulk_Buyer_Update_Date__c, Fraud__c,WelcomeSource__c,Loyalty_Optin_Date__c,LoyaltyFlag__c,LoyaltyID__c,EmailOptInStatus__c, EmailOptInDate__c, EmailOptOutDate__c, Latest_Source__c, AccountId 
                             FROM contact WHERE Id IN :conStgIdSet AND Brand_Id__c='2' ORDER BY lastmodifieddate DESC]){
            conStgEmailSet.add(objCont.Email);
            if(!mapContactId.containskey(objCont.id)){
                
                mapContactId.put(objCont.Id,objCont);
            } 
            system.debug('mapContactId>>>'+mapContactId);
        }
        for(contact objCont:[SELECT id,Email,Brand_Id__c,Point_Balance__c,Deceased__c,Bulk_Buyer__c,Bulk_Buyer_Update_Date__c, Fraud__c,WelcomeSource__c,Loyalty_Optin_Date__c,LoyaltyFlag__c,LoyaltyID__c,EmailOptInStatus__c, EmailOptInDate__c, EmailOptOutDate__c, Latest_Source__c, AccountId 
                             FROM contact WHERE Email IN :conStgEmailSetFromInput AND Brand_Id__c='2' ORDER BY lastmodifieddate DESC]){
            conStgEmailSet.add(objCont.Email);
            if(!mapContactId.containskey(objCont.id)){
                
                mapContactId.put(objCont.Id,objCont);
            } 
            system.debug('mapContactId>>>'+mapContactId);
        }
        B2CCRMSyncDefaults__mdt b2cSyncDefaults = [SELECT B2C_CustomerList_ID__c, B2C_CustomerList__c, B2C_Disable_Integration__c, B2C_Instance__c, B2C_Is_Enabled__c, B2C_Integration_Status__c 
                                                   FROM B2CCRMSyncDefaults__mdt WHERE DeveloperName =  'B2CSyncData'];
        Map<String,Boolean> emailDeceasedMap = new Map<String,Boolean>();
        Map<String,Boolean> emailFraudMap = new Map<String,Boolean>();
        Map<String,Boolean> emailBulkBuyerMap = new Map<String,Boolean>();
        Map<String,String> emailOptinStatus = new Map<String,String>();
        Map<String,DateTime> emailOptinDate = new Map<String,DateTime>();
        Map<String,DateTime> emailOptoutDate = new Map<String,DateTime>();
        List<Contact> allContacts = [SELECT id,Email,Brand_Id__c,Point_Balance__c,Deceased__c,Bulk_Buyer__c,
                                     Bulk_Buyer_Update_Date__c, Fraud__c,Loyalty_Optin_Date__c,WelcomeSource__c,
                                     LoyaltyFlag__c,LoyaltyID__c,EmailOptInStatus__c, EmailOptInDate__c, EmailOptOutDate__c, 
                                     Latest_Source__c 
                                     FROM contact 
                                     WHERE EMAIL IN :conStgEmailSet AND Brand_Id__c='2' 
                                     ORDER BY lastmodifieddate DESC];
        //Fetching the latest contacts based on the  email and filtering the contacts based on Staging contactid if no match found then adding the contact key as email
        System.debug('allContacts size '+allContacts.size());
        List<Contact> allContactsToCheck = new List<Contact>();
        allContactsToCheck.addAll(allContacts);
        System.debug('allContactsToCheck size '+allContactsToCheck.size());
        for(contact objCont: allContactsToCheck){//[SELECT id,Email,Brand_Id__c,Point_Balance__c,Deceased__c,Bulk_Buyer__c,Bulk_Buyer_Update_Date__c, Fraud__c,Loyalty_Optin_Date__c,WelcomeSource__c,LoyaltyFlag__c,LoyaltyID__c,EmailOptInStatus__c, EmailOptInDate__c, EmailOptOutDate__c, Latest_Source__c, AccountId FROM contact WHERE EMAIL IN :conStgEmailSet AND Brand_Id__c='2' ORDER BY lastmodifieddate DESC]
            emailDeceasedMap.put(objCont.Email,false);
            emailFraudMap.put(objCont.Email,false);
            emailBulkBuyerMap.put(objCont.Email,false);
            List<Contact> contactListForEmailOptin = new List<Contact>();
            List<Contact> conListToAdd = new List<Contact>();
            Contact conToAdd = new Contact();
            //added this logic to get the Deceased, Fraud and Bulk buyer
            for(String email: conStgEmailSet){
                for(Contact con: allContacts){
                    if(email == objCont.Email){
                        conListToAdd.add(con);
                        if(con.Deceased__c == true && emailDeceasedMap.get(objCont.Email) != true){
                			emailDeceasedMap.put(objCont.Email,true);
                		}
                		if(con.Fraud__c == true && emailFraudMap.get(objCont.Email) != true){
                			emailFraudMap.put(objCont.Email,true);
                		}
                        /*if(con.Bulk_Buyer__c == true && con.Bulk_Buyer_Update_Date__c != null){
                            system.debug('objCont.Email : '+objCont.Email+'con.Bulk_Buyer__c : '+con.Bulk_Buyer__c);
                			emailBulkBuyerMap.put(objCont.Email,con.Bulk_Buyer__c);
                		}*/
                	}
                }
                //added this logic to get leatest email optin/optout status
                Map<DateTime, String> emailOptinMap = new Map<DateTime, String>();
                Map<DateTime, String> emailOptoutMap = new Map<DateTime, String>();
                List<DateTime> emailOptinDates = new List<DateTime>();
                List<DateTime> emailOptoutDates = new List<DateTime>();
                DateTime maxEmailOptinDate;
				DateTime maxEmailOptoutDate;
                for(Contact con: conListToAdd){
                    emailOptinDates.add(con.EmailOptInDate__c);
                    emailOptoutDates.add(con.EmailOptOutDate__c);
                    emailOptinMap.put(con.EmailOptInDate__c, con.EmailOptInStatus__c);
                    emailOptoutMap.put(con.EmailOptOutDate__c, con.EmailOptInStatus__c);
                }
                if(emailOptinDates.size()>0){
                    emailOptinDates.sort();
                    maxEmailOptinDate = emailOptinDates[emailOptinDates.size() - 1];
                }
                if(emailOptoutDates.size()>0){
                    emailOptoutDates.sort();
                    maxEmailOptoutDate = emailOptoutDates[emailOptoutDates.size() - 1];
                }
                emailOptinDate.put(objCont.Email, maxEmailOptinDate);
                emailOptoutDate.put(objCont.Email, maxEmailOptoutDate);
                if(maxEmailOptinDate != null && maxEmailOptoutDate != null){
                    if(maxEmailOptinDate > maxEmailOptoutDate){
                    
                    emailOptinStatus.put(objCont.Email,emailOptinMap.get(maxEmailOptinDate));
                }
                else{
                    emailOptinStatus.put(objCont.Email,emailOptoutMap.get(maxEmailOptoutDate));
                	}
                }
                
            }
            system.debug('objCont>>>'+objCont);
            if(!mapContactEmail.containskey(objCont.Email)){
            	mapContactEmail.put(objCont.Email,objCont);
            }
            system.debug('mapContactEmail>>>'+mapContactEmail);
        }
                
        for(contact objCont:mapContactId.values()){
            Contact_Staging__c objConStg=new Contact_Staging__c();
            system.debug('mapContactEmail>>>'+mapContactEmail);
            if(mapContactEmail.containskey(objCont.Email)){
                
                objConStg.Subscriber_Key__c=objCont.id;
                objConStg.SFSC_Contact_Id__c=mapContactEmail.get(objCont.Email).id;
                objConStg.Welcome_source__c=objCont.WelcomeSource__c;
                objConStg.Loyalty_Flag__c=objCont.LoyaltyFlag__c;
                objConStg.Loyalty_ID__c=objCont.LoyaltyID__c;
                objConStg.Point_Balance__c=objCont.Point_Balance__c;
                objConStg.Loyalty_Optin_Date__c=objCont.Loyalty_Optin_Date__c;
                if(objCont.Loyalty_Optin_Date__c != null){
                    String dateFormat = 'yyyy-MM-dd\'T\'HH:mm:ss\'.\'SSS';
                    String dateString = objCont.Loyalty_Optin_Date__c.format(dateFormat)+'-0000';
                    System.debug(dateString); 
                    objConStg.LoyaltyOptInDate__c = dateString;
                }
                /*if(emailBulkBuyerMap.get(objCont.Email) == true){
                    objConStg.Bulk_Buyer__c = emailBulkBuyerMap.get(objCont.Email);
                }
                else{
                    objConStg.Bulk_Buyer__c= mapContactEmail.get(objCont.Email).Bulk_Buyer__c;
                }*/
                objConStg.Bulk_Buyer__c= mapContactEmail.get(objCont.Email).Bulk_Buyer__c;
                objConStg.Fraud__c= emailFraudMap.get(objCont.Email);
                objConStg.Deceased__c= emailDeceasedMap.get(objCont.Email);
                if(emailOptinStatus.get(objCont.Email) != null){
                    objConStg.Email_Optin_Status__c = emailOptinStatus.get(objCont.Email);
                }
                else{
                    objConStg.Email_Optin_Status__c=objCont.EmailOptInStatus__c;
                }
                
                objConStg.Email__c=objCont.Email;
                objConStg.Latest_Source__c=objCont.Latest_Source__c;
                objConStg.SFSCAccountId__c=objCont.AccountId;
                //objConStg.B2C_CustomerList_ID__c  = b2cSyncDefaults.B2C_CustomerList_ID__c;
                //objConStg.B2C_CustomerList__c = b2cSyncDefaults.B2C_CustomerList__c;
                //objConStg.B2C_Disable_Integration__c = b2cSyncDefaults.B2C_Disable_Integration__c;
                //objConStg.B2C_Is_Enabled__c = b2cSyncDefaults.B2C_Is_Enabled__c;
                //objConStg.B2C_Integration_Status__c = b2cSyncDefaults.B2C_Integration_Status__c;
                objConStg.b2ccrm_syncStatus__c = 'exported';
				objConStg.IsProcessed__c=true;
                if(emailNoSubKey.get(objCont.Email) == false || objCont.Id == emailCSId.get(objCont.Email) ){
                	lstContStg.add(objConStg);
                }
                else if(emailNoSubKey.get(objCont.Email) == true || objCont.Id != emailCSId.get(objCont.Email)){
                    lstContStgNoSubKey.add(objConStg);
                    System.debug('lstContStgNoSubKey'+lstContStgNoSubKey);
                }
                system.debug('lstContStg>>>'+lstContStg);
                for(Contact_Staging__c cs:lstContStg){
                    System.debug('email, Id and Subscriber_Key__c : '+cs.Email_Optin_Status__c+' '+cs.Subscriber_Key__c+' '+cs.Email__c+' '+cs.Id);
                }
            }
        }
        System.debug('lstContStg.size() '+lstContStg.size());
        if(lstContStg.size()>0){
            //Update lstContStg;
            upsert lstContStg Subscriber_Key__c;
        }
        System.debug('lstContStgNoSubKey.size() '+lstContStgNoSubKey.size());
        List<Contact_Staging__c> listCSNoSubKeyToUpdate = new List<Contact_Staging__c>();
        Map<String, String> checkDuplicateIds = new Map<String, String>();
        if(lstContStgNoSubKey.size()>0){
            for(Contact_Staging__c cs1: lstContStgNoSubKey){
                if(!checkDuplicateIds.containsKey(cs1.Email__c)){
                	cs1.Id = emailCSId.get(cs1.Email__c);
                	System.debug('cs1 '+cs1);
                	listCSNoSubKeyToUpdate.add(cs1);
                    checkDuplicateIds.put(cs1.Email__c,cs1.Id);
                }
            }
            System.debug('listCSNoSubKeyToUpdate '+listCSNoSubKeyToUpdate.size());
            if(listCSNoSubKeyToUpdate.size() >0){
                for(Contact_Staging__c cs2: listCSNoSubKeyToUpdate){
                    System.debug('cs2 Id: '+cs2.Id);
                }
                database.update(listCSNoSubKeyToUpdate , false);
            }
        }
    }
    global void finish(Database.BatchableContext BC){} 
}