unpackaged/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Point_Balance__c.field-meta.xml
<CustomField>
    <fullName>Point_Balance__c</fullName>
    <label>Point Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/A1CustomerPointBalanceUpdate.cls
/*
* @Author: PVH
*
* Purpose: REST Resource to sync Contact informaiton
*
* JIRA NO		UPDATE DATE		UPDATED BY		UPDATE DESCRIPTION
* -------		-----------		----------		------------------
* GDC-352							Divya		New Class created
*/

@RestResource(urlMapping='/A1subscribers/pointBalance')
global with sharing class A1CustomerPointBalanceUpdate {
    global class SubRequest{
        public String code;
        public String Count;
        public Set<String> LoyaltyId;
    }
    
    global class SubResponse {
        public String code;
        public string message;
    }
    
    @HttpPost
    global static void doUpdate() {
        RestRequest req = RestContext.request;
        RestResponse response = RestContext.response;
        Blob body = req.requestBody;
        String requestString = body.toString(); // retrieve request string
        
        System.Debug('requestString' + requestString);
        
        requestWrapper rw = (requestWrapper)JSON.deserialize(requestString,requestWrapper.class); // deserialize request payload
        System.Debug('rw' + rw);
        
        Set<String> LoyaltyIds = new Set<String>();
        Map<String,requestwrapper.subscriber_class> subscribermap = new Map<String,requestwrapper.subscriber_class>();
        
        for(requestwrapper.subscriber_class scs : rw.Subscribers) { // loop through subscriber_class from request
            System.Debug('String.isBlank(scs.LoyaltyId)' + String.isBlank(scs.LoyaltyId) + 'String.isBlank(scs.BrandId)' + String.isBlank(scs.BrandId));

            if(String.isNotBlank(scs.LoyaltyId) && String.isNotBlank(scs.BrandId)) { // check if both LoyaltyId and BrandId are not blank
                subscribermap.put(scs.LoyaltyId, scs);
            }
            else { // return missing LoyaltyId in response
                system.debug('It is in else loop');
                response.statusCode = 400;
                SubResponse fres = new SubResponse();
                fres.code = 'INVALID_QUERY';
                fres.message = 'Missing required parameters LoyaltyId ';
                response.responseBody = Blob.valueOf(JSON.serialize(fres));
                return ;
            }   
        } 
        
        // query contacts with matching LoyaltyId
        List<Contact> contactlist = new List<Contact>([Select Id,Point_Balance__c,Brand_Id__c,LoyaltyID__c from Contact where B2C_Customer_No__c != null And Ecomm_Connected__c= true And LoyaltyID__c in :subscribermap.KeySet()]);
        List<Contact> updateconlist = new List<Contact>();
        
        if (contactlist.size() > 0) {
            for(Contact cons: contactlist) { // update Contacts LoyaltyId and BrandId
                cons.Point_Balance__c = Decimal.valueOf(subscribermap.get(cons.LoyaltyID__c).balancepoints);
                cons.Brand_Id__c = subscribermap.get(cons.LoyaltyID__c).BrandId;
                updateconlist.add(cons);
            }
        }

        try {
            Database.update(updateconlist); // update contacts
            response.statusCode = 200;
            SubRequest successres = new SubRequest();
            successres.code = 'OK';
            successres.Count = String.Valueof(updateconlist.size());
            successres.LoyaltyId = subscribermap.KeySet();
            response.responseBody = Blob.valueOf(JSON.serialize(successres));
            system.debug('response.responseBody'+response.responseBody);
            return;
        }
        catch (Exception e) { // exception
            System.Debug('Update failed due to' + e.getMessage());
        }
    }
}