unpackaged/main/default/objects/Contact/fields/B2C_UserName__c.field-meta.xml
<CustomField>
    <fullName>B2C_UserName__c</fullName>
    <description>... represents the B2C Commerce customer profile username mapped to a given Service Cloud Contact.</description>
    <inlineHelpText>... represents the B2C Commerce customer profile username mapped to a given Service Cloud Contact.</inlineHelpText>
    <label>B2C UserName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_Address_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_Address_Reason_Code__c</fullName>
    <label>Email Address Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Verification Success : Email Update</fullName>
            </value>
            <value>
                <fullName>Verification Success : Unable to Update in SC</fullName>
            </value>
            <value>
                <fullName>Verification Declined : No Email Update</fullName>
            </value>
            <value>
                <fullName>Verification Failure : No Customer&#39;s response</fullName>
            </value>
            <value>
                <fullName>Verfication Success: login email is already in use</fullName>
            </value>
            <value>
                <fullName>Verification Success : R2R update</fullName>
            </value>
            <value>
                <fullName>Verification Declined: No personal data update</fullName>
            </value>
            <value>
                <fullName>Verification Failure: No customer response</fullName>
            </value>
            <value>
                <fullName>Verification Success: Do Not Sell/ Share Approved</fullName>
            </value>
            <value>
                <fullName>Verification Declined: No Advertising Opt Out</fullName>
            </value>
            <value>
                <fullName>Tealium Request: Advertise OptIn</fullName>
            </value>
            <value>
                <fullName>Tealium Request: Advertise OptOut</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Email_Updated_by_CSR__c.field-meta.xml
<CustomField>
    <fullName>Email_Updated_by_CSR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Updated by CSR</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/OldEmail__c.field-meta.xml
<CustomField>
    <fullName>OldEmail__c</fullName>
    <label>OldEmail</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/classes/UpdateContactEmailBack.cls
public class UpdateContactEmailBack{
    @InvocableMethod(Label = 'B2C : update to old Email'Description = 'When there is an error because of Email change. It will update back to Old Emaill')
    public static void updateEmail(List<String> B2CHistId){
        Log.push('B2CHistid = ' + B2CHistId);
        B2C_Contact_Integration_History__c C = [select Contact__c, Integration_JSON__c
                                                from B2C_Contact_Integration_History__c
                                                where Id = :B2CHistId[0]];
        Object result = JSON.deserializeUntyped(C.Integration_JSON__c);
        Map<String, Object> resultMap = (Map<String, Object>)result;
        //Log.push('fault :' + resultMap);
        //Log.push('fault :' + resultMap.get('fault'));
        Map<String, Object> faultMap = (Map<String, Object>)resultMap.get('fault');

        //Log.push('Message to Display: '+faultMap.get('message') );

        if (faultMap != null && faultMap.containsKey('type') && faultMap.get('type') == SYSTEM.LABEL.LoginAlreadyInUseException){
            Contact con = [select Id, Email, OldEmail__c, B2C_UserName__c, Email_Updated_by_CSR__c
                           from Contact
                           where Id = :C.Contact__c];
            Log.push('Contact Id: ' + con.Id);
            Log.push('Contact Email:' + con.Email);
            Log.push('Contact OldEmail:' + con.OldEmail__c);
            con.Email = con.OldEmail__c;
            con.B2C_UserName__c = con.OldEmail__c;
            con.Email_Updated_by_CSR__c = false;
            con.Email_Address_Reason_Code__c = SYSTEM.LABEL.Verfication_Success_login_email_is_already_in_use;
            update con;
            Logger.logDebug();
        }
    }

}