unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltyID_Sequence__c/LoyaltyID_Sequence__c.object-meta.xml
<CustomObject>
    <label>LoyaltyID Sequence</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LoyaltyID Sequence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/IsLoyaltyApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsLoyaltyApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this brand is part of Loyalty program or not.</description>
    <label>IsLoyaltyApplicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/LoyaltyPrefix__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyPrefix__c</fullName>
    <label>LoyaltyPrefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LoyaltyIdGeneration.cls
/******************************************************************************
* @Description: Generate Loyalty ID for  TH/CK/HE customers which has null value 
* @Date       : Jan 2021
* @JIRA       : NASSC-2694
*
******************************************************************************/

public class LoyaltyIdGeneration
{
    public static Boolean runFlag= true;
    private static Map<String,LoyaltySettings__mdt> loyaltySettingMap=new Map<String,LoyaltySettings__mdt>();
   
    public static void loyaltyIdGenHandler (Map<Id,Contact> conId,set<String> brandSet) 
    {  
        
         system.debug('inside loyaltyidGeneration');
        List<Contact> updateContacts = new List<Contact>();
        Map<Contact,LoyaltyID_Sequence__c> nonLoyaltyContacts = new Map<Contact,LoyaltyID_Sequence__c>();
        Map<String,String> parentContacts = new Map<String,String>();
        Map<String,Contact> childContacts = new Map<String,Contact>();
        
        Id emailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
        
        
        for(LoyaltySettings__mdt meta: [Select Id,BrandId__c,IsLoyaltyApplicable__c,Parent_Brand__c,LoyaltyPrefix__c from LoyaltySettings__mdt where BrandId__c IN:brandSet AND IsLoyaltyApplicable__c = true])
        {
            loyaltySettingMap.put(meta.BrandId__c,meta);
        }        
        
        for(Contact con:conId.values())
        {   
            //MetaData brand has match with contact
            if(loyaltySettingMap.containsKey(con.Brand_Id__c))
            {
                //Parent brand is empty in MetaDataType for this contact brand. 
                if(String.isEmpty(loyaltySettingMap.get(con.Brand_Id__c).Parent_Brand__c))
                {                                                   
                    LoyaltyID_Sequence__c lSeq = new LoyaltyID_Sequence__c();
                    nonLoyaltyContacts.put(con,lSeq);
                } 
                //Parent brand is not empty in MetaDataType for this contact brand. 
                else if(String.isNotEmpty(loyaltySettingMap.get(con.Brand_Id__c).Parent_Brand__c))
                {
                    parentContacts.put(con.Email,loyaltySettingMap.get(con.Brand_Id__c).Parent_Brand__c);
                    childContacts.put(con.Email,con);
                    system.debug('childContacts****'+childContacts);
                }
            }
        }
        
        //Creating LoyaltyID_Sequence__c for Contacts iff Parent brand is empty in MetaDataType .
        if(nonLoyaltyContacts.size() > 0)
        {   
            updateContacts.addAll(populateContactsWithLoyaltyIds(nonLoyaltyContacts));
            //populateContactsWithLoyaltyIds(nonLoyaltyContacts);
        }
        
        /* If Parent brand is not empty in MetaDataType*/        
        if(parentContacts.size()>0)
        {
            
            List<Contact> parentContactList = [SELECT ID, Brand_Id__c, Email, LoyaltyID__c, LoyaltyFlag__c, Loyalty_Optin_Date__c
                                               FROM Contact 
                                               WHERE RecordTypeId = :emailRecordTypeId AND Brand_Id__c IN :parentContacts.values() AND Email!=Null AND Email IN :parentContacts.keySet() ];
            
            if(parentContactList.size()>0)
            {
                Map<Contact,LoyaltyID_Sequence__c>  nonParentLoyaltyContacts = new Map<Contact,LoyaltyID_Sequence__c>();
                
                for(Contact parentContact : parentContactList)
                {
                    contact childContact = childContacts.get(parentContact.Email);
                    
                    /* If Parent contact has loyaltyId - then use that to populate in child contact.*/
                    if (parentContact.LoyaltyID__c != null) 
                    {
                        Contact origContactUpdate = new Contact(Id=childContact.Id);
                        origContactUpdate.LoyaltyID__c = parentContact.LoyaltyID__c;
                        if (parentContact.LoyaltyFlag__c != null) origContactUpdate.LoyaltyFlag__c = parentContact.LoyaltyFlag__c;
                        if (parentContact.Loyalty_Optin_Date__c != null) origContactUpdate.Loyalty_Optin_Date__c = parentContact.Loyalty_Optin_Date__c;
                        updateContacts.add(origContactUpdate);
                        system.debug('updateContacts***'+updateContacts);
                    }                    
                    else
                    {
                        LoyaltyID_Sequence__c lSeq = new LoyaltyID_Sequence__c();
                        nonParentLoyaltyContacts.put(parentContact,lSeq);
                    }                    
                }
                /* Check Parent contact has no loyalityId - Creating LoyaltyID_Sequence__c and populate the same in Parent & Child */
                for(Contact parentContact : populateContactsWithLoyaltyIds(nonParentLoyaltyContacts))
                {
                    contact childContact = childContacts.get(parentContact.Email);
                    Contact origContactUpdate = new Contact(Id=childContact.Id);
                    origContactUpdate.LoyaltyID__c= parentContact.LoyaltyID__c;
                    updateContacts.add(parentContact);
                    updateContacts.add(origContactUpdate);
                    system.debug('updateContacts***'+updateContacts);
                }
            }
            
        }
        /* Update all Contacts at once */
        if(updateContacts.size()>0)
        {
            Update updateContacts;
        }
    }
    private static List<Contact> populateContactsWithLoyaltyIds(Map<Contact,LoyaltyID_Sequence__c> nonLoyaltyContacts)
    {
        List<Contact> returnConList = new List<Contact>();
        insert nonLoyaltyContacts.values();
        Set<id> newLoyaltyIds = new Set<id>();
        
        for(SObject sobj: nonLoyaltyContacts.values())
        { 
            newLoyaltyIds.add(sobj.Id);
        }    
        List<LoyaltyID_Sequence__c> loyaltylList =  [Select Id, Name from LoyaltyID_Sequence__c WHERE Id in :newLoyaltyIds];
        Integer index=0;
        for(Contact con: nonLoyaltyContacts.keyset())
        {
            if(String.isNotEmpty(loyaltySettingMap.get(con.Brand_Id__c).LoyaltyPrefix__c))
            {
                Contact origContactUpdate = new Contact(Id=con.Id, LoyaltyID__c = loyaltySettingMap.get(con.Brand_Id__c).LoyaltyPrefix__c + loyaltylList[index].Name);
                returnConList.add(origContactUpdate);
            }
            index++;             
        }
        return returnConList;
    }
    
    public static void hasOptedOutOfEmailUpdated(List<Contact> conList) {
        List<Contact> updatedList=new  List<Contact> ();
       
        for(Contact con:conList){
            if(con.HasOptedOutOfEmail==True && con.EmailOptInStatus__c!='N'){
                con.EmailOptInStatus__c='N';
                con.EmailOptOutDate__c=system.now();
               
            }
            else if (con.HasOptedOutOfEmail==False && con.EmailOptInStatus__c!='Y'){
                con.EmailOptInStatus__c='Y';
                con.EmailOptInDate__c=system.now();
              
            }else if (con.EmailOptInStatus__c=='Y' && con.HasOptedOutOfEmail!=False ){
                con.HasOptedOutOfEmail=False;
                
              
            }else if (con.EmailOptInStatus__c=='N' && con.HasOptedOutOfEmail!=True){
                con.HasOptedOutOfEmail=True;
               
              
            }
           
            
                }
   }
}