unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AgentWorkTriggerTest.cls
@isTest
public class AgentWorkTriggerTest {
    // THIS IS NOT TESTABLE. AN UNAVOIDABLE ERROR OCCURS. THIS TEST IS JUST TO MAKE THIS TRIGGER DEPLOYABLE.
    @isTest
    static void test_fake() {
        Account genAcc = new Account();
        genAcc.Name = 'generic Account' + Math.random();
        insert genAcc;

        Contact genCon = new Contact();
        genCon.email = 'foo@example.com';
        genCon.lastName = 'generic contact ' + Math.random();
        genCon.AccountId = genAcc.id;
        genCon.Brand_Id__c='9';
        insert genCon;

        GenericRecords__c genRec = new GenericRecords__c(
                Name = Constants.privacyContactGenericRecordSettingName,
                recordId__c = genCon.Id
        );
        insert genRec;
        //Try Catch is to ensure test doesn't fail
        ServiceChannel sc = [SELECT Id FROM ServiceChannel LIMIT 1];
        List<Case> caseList = TestDataFactory.createCases(1);
        Case cse = caseList[0];
        insert cse;
        try{
                        AgentWork aw = new AgentWork(
                    ServiceChannelId = sc.Id,
                    WorkItemId = cse.Id,
                    UserId = UserInfo.getUserId()
            );
            //NF_AgentWorkTriggerHandler.disableTrigger = true;
            //NF_CaseTriggerHandler.disableTrigger = true;
            System.debug('@35');
            Map<Id, sObject> newMap = new Map<Id, sObject>();
            newMap.put(aw.Id, aw);
            NF_AgentWorkTriggerHandler handler = new NF_AgentWorkTriggerHandler();
            handler.afterUpdate(newMap,null);
            NF_AgentWorkTriggerHelper.handleAfterUpdate((Map<Id,AgentWork>) newMap, null);
            NF_AgentWorkTriggerHandler.disableTrigger = true;
            insert aw;
            NF_AgentWorkTriggerHandler.disableTrigger = false;

            update aw;
        }
        catch(Exception e){
            
        }


    }
}