unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>ErrorLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ErrorLog__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>FileName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Its used to store Error Log Message</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>Its used to store Error Log Source System</description>
    <label>SourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Its used to store Error Log StackTrace</description>
    <label>StackTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Its used to store Error Log Type</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltyID_Sequence__c/LoyaltyID_Sequence__c.object-meta.xml
<CustomObject>
    <label>LoyaltyID Sequence</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LoyaltyID Sequence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/IsLoyaltyApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsLoyaltyApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this brand is part of Loyalty program or not.</description>
    <label>IsLoyaltyApplicable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/LoyaltyPrefix__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyPrefix__c</fullName>
    <label>LoyaltyPrefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactUtility.cls
/*
 * NASSC-1066
 NASSC-1114
 */
public class ContactUtility{
    public static void assignLoyaltyId(Map<Contact, SObject> sequenceObjMap){
        //Log.push('### sequenceObjMap ' + sequenceObjMap);
        Set<Id> seqList = new Set<Id>();

        Savepoint sp = Database.setSavepoint();
        insert sequenceObjMap.values();

        for (SObject sobj : sequenceObjMap.values()){
            seqList.add(sobj.Id);
        }

        List<LoyaltyID_Sequence__c> loyaltylList = [Select Id, Name
                                                    from LoyaltyID_Sequence__c
                                                    WHERE Id in:seqList];

        for (LoyaltyID_Sequence__c l : loyaltylList){
            for (Contact c : sequenceObjMap.keySet()){
                if (String.isEmpty(c.LoyaltyID__c)){
                    LoyaltySettings__mdt listLoyaltySetting = [Select Id, BrandId__c, IsLoyaltyApplicable__c, Parent_Brand__c, LoyaltyPrefix__c
                                                               from LoyaltySettings__mdt
                                                               where BrandId__c = :c.Brand_Id__c];
                    if (listLoyaltySetting != null){
                        c.LoyaltyID__c = (String.isNotEmpty(listLoyaltySetting.LoyaltyPrefix__c) ? listLoyaltySetting.LoyaltyPrefix__c + l.Name : l.Name);
                        break;
                    }
                }
            }
        }

        Database.rollback(sp);
    }

    public static void createErrorLogRecords(Database.SaveResult[] dmlList, String sourceSystem, String fileName){
        Log.push('***inside createErrorLogRecords');
        Log.push('***dmlList ' + dmlList);
        List<ErrorLog__c> listErrorLog = new List<ErrorLog__c>();
        String stackTrace;
        Integer maxSize = 131072;
        for (Database.SaveResult sr : dmlList){
            if (!sr.isSuccess()){
                // Operation failed, so get all errors
                for (Database.Error err : sr.getErrors()){
                    Log.push('***The following error has occurred.');
                    Log.push(err.getStatusCode() + ': ' + err.getMessage());
                    Log.push('***Fields that affected this error: ' + err.getFields());
                    ErrorLog__c logObject = new ErrorLog__c();
                    logObject.Message__c = String.valueOf(err.getStatusCode()).left(255);
                    stackTrace = err.getMessage();
                    //checking and truncating if size of stacktrace is more than 131072
                    if (stackTrace.length() > maxSize){
                        stackTrace = stackTrace.substring(0, maxSize);
                    }
                    logObject.StackTrace__c = stackTrace;
                    logObject.Type__c = SYSTEM.LABEL.Error;
                    //logObject.User__c = UserInfo.getUserId();
                    if (!String.isBlank(sourceSystem))
                        logObject.SourceSystem__c = sourceSystem;
                    if (!String.isBlank(fileName))
                        logObject.FileName__c = fileName;
                    listErrorLog.add(logObject);
                }
            }
        }
        Log.push('***listErrorLog' + listErrorLog);
        Logger.logDebug();
        insert listErrorLog;
    }

}