unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CountryOfCapture__c.field-meta.xml
<CustomField>
    <fullName>CountryOfCapture__c</fullName>
    <label>Country of Capture</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/IseCommSMS__c.field-meta.xml
<CustomField>
    <fullName>IseCommSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IseCommSMS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/isEmployee__c.field-meta.xml
<CustomField>
    <fullName>isEmployee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Employee</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <description>Captures the Keyword values from where the customer SMS opt In. Ex: TH004, Preference center , ChargeIt</description>
    <label>SMSKeyword</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/PrefCenterInterests__c.field-meta.xml
<CustomField>
    <fullName>PrefCenterInterests__c</fullName>
    <label>Email Interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Company Stores</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Tommy.com</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Anchor / Specialty Stores</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Mens</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>Womens</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Kids (TH)</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Ecom Main Site</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Ecomm - New (TH)</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>Home</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Loyalty</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Retail Store</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>One Time</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Ecom Outlet</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>CK Collection</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>CK International</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kids (HE)</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Fitness</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Performance</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Active Recreation</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>Adaptive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SelfClaimedGender__c.field-meta.xml
<CustomField>
    <fullName>SelfClaimedGender__c</fullName>
    <label>SelfClaimedGender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>GN</fullName>
            </value>
            <value>
                <fullName>PNTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMS_Unsubscribe_Reason__c.field-meta.xml
<CustomField>
    <fullName>SMS_Unsubscribe_Reason__c</fullName>
    <description>To capture the SMS unsubscribe reason once the customer opted out from SMS.</description>
    <label>SMS Unsubscribe Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptInDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptInDate__c</fullName>
    <label>SMS Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOutDate__c</fullName>
    <label>SMS Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/preferenceCenterKeyword__c.field-meta.xml
<CustomField>
    <fullName>preferenceCenterKeyword__c</fullName>
    <label>MCpreferenceCenterKeyword</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/SubscriberDataSources__mdt.object-meta.xml
<CustomObject>
    <label>SubscriberDataSource</label>
    <pluralLabel>SubscriberDataSources</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/DataSource__c.field-meta.xml
<CustomField>
    <fullName>DataSource__c</fullName>
    <label>Data Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Source System</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Welcome Source</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CustomerSMSOptinServices.cls
/*
 * Json Request
{
"brandId" : "1", "emailAddress" : "thpgguest1209@yopmail.com", "SMSNumber" : "4561234522", "Subscriberkey" : "", "SMSOptinStatus" : "P", "Locale" : "en_us"
 }  

End point url
https://pvhservicecloud--qapro.sandbox.my.salesforce.com/services/apexrest/subscriptions/customeroptin


 */


//Brand specific TH

@RestResource(urlMapping='/subscriptions/customeroptin')
global class CustomerSMSOptinServices {
	static Id emailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
    static String reqSMSNumberWithPrefix;    
    @HttpPost
    global static SFCCResponse doOptin(){
        Contact foundContact = new Contact();//SMS
        Contact foundSMSContact = new Contact();//SMS
        Contact brandAndEmailContact = new Contact();//SMS
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String requestData = req.requestBody.toString();
        SFCCRequest sfccReq = (SFCCRequest)json.deserialize(requestData, SFCCRequest.class);
        SFCCResponse sfccResponse = new SFCCResponse();
        Log.push('### sfccReq:'+sfccReq);
        System.debug('### sfccReq:'+sfccReq);
        reqSMSNumberWithPrefix=SYSTEM.LABEL.X1 + sfccReq.SMSNumber;
            //if(!String.isBlank(sfccReq.SMSNumber)){
                //Scenario -1: When Subscriber Key is blank, below logic will be executed. 
                if(String.isBlank(sfccReq.Subscriberkey)){
                    
                    res.StatusCode = 200;
                    sfccResponse.Code = 'MISSING_PARAMETERS';
                    sfccResponse.Message = 'Missing: ContactId';
                    sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                    sfccResponse.PreviousSMSOptinStatus='P'; 
                    sfccResponse.ExistingCustomer='No';
                   // return sfccResponse;
                }
                else{
                    foundContact = searchContact(sfccReq.Subscriberkey);//Subscriberkey=ContactID
                    foundSMSContact = searchSMSContact(reqSMSNumberWithPrefix);
                    system.debug('foundContact***'+foundContact);
                    system.debug('foundSMSContact***'+foundSMSContact);
                    
                    if(foundContact != null){
                        brandAndEmailContact =  SFMCUtility.searchEmailBrandContact(foundContact.Brand_Id__c,sfccReq.emailAddress);
                    }
                    //Scenario -2: When Contact is not found with Subscriber Key, below logic will be executed. 
                    if(foundContact == null){
                        
                        System.debug('***Error: Contact Not Found');
                        res.StatusCode = 200;
                        sfccResponse.Code = 'CONTACT_NOT_FOUND';
                        sfccResponse.Message = 'No matching contact found';
                        sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                        sfccResponse.PreviousSMSOptinStatus='P';
                       // return sfccResponse;
                    }
                    /*
                    //Scenario -3: When Contact is found with other contact Email address, below logic will be executed. 
                    else if(brandAndEmailContact != null && (foundContact.Email != sfccReq.emailAddress) && (foundContact.Id != brandAndEmailContact.Id)){
                        
                        res.statusCode = 200;
                        sfccResponse.code = 'CONTACT_EXISTS';
                        sfccResponse.message = 'Supplied Email address used by another contact';
                        sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                        sfccResponse.ExistingCustomer='Yes';
                        return sfccResponse;
                    }
					*/
					else if(foundSMSContact != null && (foundSMSContact.Id != sfccReq.Subscriberkey) && (foundSMSContact.SMSNumber__c == reqSMSNumberWithPrefix) && 
                            (foundSMSContact.SMSOptinStatus__c =='Y') && (foundSMSContact.Email != sfccReq.emailAddress)){
                         System.debug('This debug is at seq 01' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                         res.StatusCode = 200;
                        sfccResponse.Code = 'SMS_NUMBER_IN_USE';
                        sfccResponse.Message = 'SMS Number used by another contact';
                        sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                        sfccResponse.ExistingCustomer='Yes';
                       // return sfccResponse;
                         
                    }
                    /*Scenario -4: When Contact is found with another contact SMS number, below logic will be executed. 
                   // else if(foundSMSContact != null && ((foundContact.Id != foundSMSContact.Id) || (foundSMSContact.Id != sfccReq.Subscriberkey))){
                   else if(foundSMSContact != null && (foundContact.Id != foundSMSContact.Id) && (foundSMSContact.SMSNumber__c == reqSMSNumberWithPrefix)){
                      System.debug('This debug is at seq 02' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                        res.StatusCode = 200;
                        sfccResponse.Code = 'SMS_NUMBER_IN_USE';
                        sfccResponse.Message = 'SMS Number used by another contact';
                        sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                        sfccResponse.ExistingCustomer='Yes';
                        //return sfccResponse;
                        
                    }*/
                    //Scenario -5: When no other contact found with SMS number, below logic will be executed and SMS will get updated. 
                   else if((foundSMSContact == null && sfccReq.SMSOptinStatus != 'N' ) || (foundSMSContact != null && foundContact.Id == foundSMSContact.Id && sfccReq.SMSOptinStatus == 'P' && sfccReq.Subscriberkey == foundSMSContact.Id) ){
                   // else if(foundSMSContact != null && foundContact.Id == foundSMSContact.Id && sfccReq.SMSOptinStatus == 'P' && foundSMSContact.Id == sfccReq.Subscriberkey){ 
                   System.debug('This debug is at seq 03' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                       Contact updatedCon = updateContactOne(foundContact,sfccReq);
                        Savepoint sp;
                        try {
                            sp = Database.setSavepoint();
                            update updatedCon;
                            System.debug('***Contact Record Updated');  
                            res.StatusCode = 200;
                            sfccResponse.Code = 'Ok';
                            sfccResponse.Message = 'SUCCESS';
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            sfccResponse.PreviousSMSOptinStatus='P';
                        }
                        catch (Exception e) {
                            
                            System.debug('An exception occurred while updating Contact' + e.getMessage());
                            res.StatusCode = 500;
                            sfccResponse.Code = 'OTHER_ERROR';
                            sfccResponse.Message = e.getMessage();
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            Database.RollBack(sp);
                            
                        }
                        
                        
                        //return sfccResponse;
                        
                    }
                    
                    //Scenario -6: When SMS number is blank in the request, below logic will be executed. 
                    else if(foundContact != null && sfccReq.SMSNumber == null){
                        System.debug('This debug is at seq 04' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                        System.debug(foundContact);
                            res.StatusCode = 200;
                            sfccResponse.Code = 'MISSING_SMS';
                            sfccResponse.Message = 'SMS Number missing in the request';
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                        	sfccResponse.ExistingCustomer='Yes';
                           // return sfccResponse;
                        
                        
                      //  sfccResponse.contactId = updatedConWithOutSMS.Id;
                        
                    }
                    //Scenario -7: When Optin field is N in the request , Below Optout logic will get executed.
                    else if (foundSMSContact !=NULL && foundSMSContact.Id == sfccReq.Subscriberkey && sfccReq.SMSOptinStatus == 'N' ){
						System.debug('This debug is at seq 05' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                        String PreviousOptinStatus = foundSMSContact.SMSOptinStatus__c;
                        Contact updatedCon = updateContactOne(foundContact,sfccReq);
                        Savepoint sp;
                        try {
                            sp = Database.setSavepoint();
                            update updatedCon;
                            System.debug('***Contact Record Updated');  
                            res.StatusCode = 200;
                            sfccResponse.Code = 'Ok';
                            sfccResponse.Message = 'SUCCESS';
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            sfccResponse.PreviousSMSOptinStatus = PreviousOptinStatus;
                        }
                        catch (Exception e) {
                            System.debug('An exception occurred while updating Contact' + e.getMessage());
                            res.StatusCode = 500;
                            sfccResponse.Code = 'OTHER_ERROR';
                            sfccResponse.Message = e.getMessage();
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            Database.RollBack(sp);
                            
                        }
                        
                        
                        //return sfccResponse;
                        
                    }
                        //Scenario -8: When Optin field is Y in the request , Below Optin logic will get executed.
                    else if (foundSMSContact !=NULL && foundSMSContact.Id == sfccReq.Subscriberkey && sfccReq.SMSOptinStatus == 'Y' ){
						System.debug('This debug is at seq 06' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                        String PreviousOptinStatus = foundSMSContact.SMSOptinStatus__c;
                        Contact updatedCon = updateContactOne(foundContact,sfccReq);
                        Savepoint sp;
                        try {
                            sp = Database.setSavepoint();
                            update updatedCon;
                            System.debug('***Contact Record Updated');  
                            res.StatusCode = 200;
                            sfccResponse.Code = 'Ok';
                            sfccResponse.Message = 'SUCCESS';
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            sfccResponse.PreviousSMSOptinStatus = PreviousOptinStatus;
                        }
                        catch (Exception e) {
                            System.debug('An exception occurred while updating Contact' + e.getMessage());
                            res.StatusCode = 500;
                            sfccResponse.Code = 'OTHER_ERROR';
                            sfccResponse.Message = e.getMessage();
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            Database.RollBack(sp);
                            
                        } 
                        
                        return sfccResponse;
                        
                    }
                    else {
                        System.debug('This debug is at seq 07' + foundContact + '*****' + foundSMSContact + '********' + sfccReq);
                        System.debug(foundContact);
                        Contact updatedCon = updateContactOne(foundContact,sfccReq);
                        System.debug(updatedCon);
                        Savepoint sp;
                        try {
                            sp = Database.setSavepoint();
                            update updatedCon;
                            System.debug('***Contact Record Updated');  
                        }
                        catch (Exception e) {
                            System.debug('An exception occurred while updating Contact' + e.getMessage());
                            res.StatusCode = 500;
                            sfccResponse.Code = 'OTHER_ERROR';
                            sfccResponse.Message = e.getMessage();
                            sfccResponse.Subscriberkey=sfccReq.Subscriberkey;
                            sfccResponse.ExistingCustomer='Yes';
                            Database.RollBack(sp);
                            return sfccResponse;
                        }
                        
                        res.StatusCode = 200;
                        sfccResponse.Code = 'Ok';
                      //  sfccResponse.contactId = updatedCon.Id;
                        sfccResponse.Message='Success';
                        
                    }
                     
                }
            //}  
        
        return sfccResponse;
    } 
    /*****************/
    public static Contact searchContact(Id contactId){
        List<Contact> conList = [SELECT Id,FirstName,LastName,MailingStreet,MailingCity,MailingState,Brand_Id__c,Email,
                                 MailingCountry, MailingPostalCode, BirthDate, Phone, SMSNumber__c,SMSOptinStatus__c, SMSOptInDate__c,
                                 PrefCenterInterests__c, HomeStore__c,isEmployee__c,AccountId,SMSLocale__c,CountryOfCapture__c,SelfClaimedGender__c,
                                 Latest_Source__c,Source_System__c  
                                 FROM Contact WHERE Id =: contactId];
        if(!conList.isEmpty()){
            Logger.logDebug();
            return conList[0];
        }else{
            return null;
        }
        
        
    }
    
    public static Contact searchSMSContact(String inputSMSNumber){
        List<Contact> conList = [SELECT Id,FirstName,Email,LastName,MailingStreet,MailingCity,MailingState,
                                 MailingCountry, MailingPostalCode, BirthDate, Phone, SMSNumber__c,SMSOptinStatus__c, SMSOptInDate__c,
                                 PrefCenterInterests__c, HomeStore__c,isEmployee__c,SMSLocale__c,CountryOfCapture__c,SelfClaimedGender__c,
                                 Latest_Source__c,Source_System__c 
                                 FROM Contact 
                                 WHERE SMSNumber__c != null AND SMSNumber__c =: inputSMSNumber];
        
        if(!conList.isEmpty()){
            Logger.logDebug();
            return conList[0];
        }else{
            return null;
        }
        
    }
    
    public static Contact updateContactOne(Contact con, SFCCRequest pcReq){
         Log.push('***inside updateContact');
        System.debug('***inside updateContact');
        LoyaltySettings__mdt lsm = [Select preferenceCenterKeyword__c,BrandId__c from LoyaltySettings__mdt where BrandId__c=: con.Brand_Id__c];
        List<SubscriberDataSources__mdt> listDataSource = [SELECT Brand__c, SourceSystem__c, WelcomeSource__c, DataSource__c
                                                               FROM SubscriberDataSources__mdt
                                                               WHERE Brand__c = : con.Brand_Id__c AND SourceSystem__c ='eComm'];

            if (listDataSource.size() > 0){
                con.Source__c = listDataSource[0].DataSource__c;
            }
       
        if(String.isNotBlank(pcReq.emailAddress) && (con.Email != pcReq.emailAddress)) con.Email = pcReq.emailAddress;
        
        //Start: Setting SMS Related Fields
        if(String.isNotBlank(pcReq.SMSNumber) && pcReq.SMSOptinStatus == 'P' && String.isBlank(con.SMSNumber__c)){
            //brand new sms optin
            Log.push('***First Time Optin');
            con.SMSNumber__c = SYSTEM.LABEL.X1 + pcReq.SMSNumber;
            con.SMSOptinStatus__c = 'P';
            con.Latest_Source__c = SYSTEM.LABEL.eCommLatestSource;
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
            con.IseCommSMS__c=True;
            //con.SMSOptInDate__c = System.now();
        }
        else if((pcReq.SMSOptinStatus == 'N') && (con.SMSOptinStatus__c == null || con.SMSOptinStatus__c == 'Y' || con.SMSOptinStatus__c == 'P')){
            // sms optout
            Log.push('***Optout');
            con.SMSOptinStatus__c = 'N';
            con.SMSOptOutDate__c = System.now();
            con.Latest_Source__c = SYSTEM.LABEL.eCommLatestSource;
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
            con.IseCommSMS__c=True;
            con.SMS_Unsubscribe_Reason__c='eComm Opt-out';
        }
        else if(String.isNotBlank(pcReq.SMSNumber) && pcReq.SMSOptinStatus == 'P' && String.isNotBlank(con.SMSNumber__c) && con.SMSNumber__c == reqSMSNumberWithPrefix){
           //sms reoptin with same number
            Log.push('***Re-Optin with same number');
            con.Latest_Source__c = SYSTEM.LABEL.eCommLatestSource;
            con.SMSOptinStatus__c = 'P';
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
            con.IseCommSMS__c=True;
            //con.SMSOptInDate__c = System.now();
        }
        else if(String.isNotBlank(pcReq.SMSNumber) && pcReq.SMSOptinStatus == 'P' && String.isNotBlank(con.SMSNumber__c) && con.SMSNumber__c != reqSMSNumberWithPrefix){
            //sms optin with a different number
            Log.push('***Re-Optin with different number');
            con.Latest_Source__c = SYSTEM.LABEL.eCommLatestSource;
            con.SMSNumber__c = SYSTEM.LABEL.X1 + pcReq.SMSNumber;
            con.SMSOptinStatus__c = 'P';
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
            con.IseCommSMS__c=True;
            //con.SMSOptInDate__c = System.now();
        }
        //End: Setting SMS Related Field
        
       /* if(String.isNotBlank(pcReq.SMSNumber) && pcReq.SMSOptinStatus !='N'){
            System.debug('***First Time Optin');
            con.SMSNumber__c = pcReq.SMSNumber;
            con.SMSOptinStatus__c = 'P';
            con.SMSOptInDate__c = System.now();
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
        }
        if(String.isNotBlank(pcReq.SMSNumber) && pcReq.SMSOptinStatus == 'N'){
            con.SMSOptinStatus__c = 'N';
            con.SMSOptOutDate__c = System.now();
            con.SMS_Unsubscribe_Reason__c='eComm Opted out';
            con.SMSOptOutDate__c = System.now();
            con.Keyword__c = lsm.preferenceCenterKeyword__c;
        }*/
        
        //End: Setting SMS Related Field        
        if(String.isNotBlank(pcReq.Locale) && (con.SMSLocale__c != pcReq.Locale)) con.SMSLocale__c = pcReq.Locale;
        if(String.isBlank(con.CountryOfCapture__c) && String.isNotBlank(pcReq.Locale)){
            if(pcReq.Locale.length() == 5) con.CountryOfCapture__c = pcReq.Locale.right(2).toUpperCase();
        }
        System.debug(con);
        Logger.logDebug();
        return con;
    }
    
    /******************/
    global class SFCCRequest{
        public String brandId;
        public String emailAddress;
        public String Subscriberkey;
        public String SMSNumber;
        public String SMSOptinStatus;
        public String Locale;
    }
    global class SFCCResponse{
        public String Code;
        public String Message;
        public String Subscriberkey;
        public String PreviousSMSOptinStatus;
        public String ExistingCustomer;
    }
}