unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CustomerSMSOptinServicesTest.cls
@isTest
public class CustomerSMSOptinServicesTest {
    private static Contact createContact(){
        //Test Data for account and contact
        Account acc = new Account(Name=System.Label.PlaceHolderAccountName);
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
        insert acc;
        Contact con = new Contact();  
        con.Source_System__c = 'eComm';
        con.AccountId = acc.Id;
        con.Brand_Id__c = '1';
        con.FirstName = 'cfname';
        con.LastName = 'clname';
        con.Email = 'testemail@nomail.com';
        con.EmailOptInStatus__c = 'Y'; // true;
        con.EmailOptInDate__c = System.now();
        con.LoyaltyFlag__c=false;
        con.WelcomeSource__c = '01';
		con.StoreOfCapture__c = 'cLoc';
        con.SMSNumber__c = '9999988888';
        insert con;
        return con;
     }
    
    private static Contact createContact2(){
        //Test Data for account and contact
        Account acc = new Account(Name=System.Label.PlaceHolderAccountName);
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
        insert acc;
        Contact con = new Contact();  
        con.Source_System__c = 'eComm';
        con.AccountId = acc.Id;
        con.Brand_Id__c = '1';
        con.FirstName = 'cfname';
        con.LastName = 'clname';
        con.Email = 'testemail@nomail.com';
        con.EmailOptInStatus__c = 'N'; // true;
        con.EmailOptInDate__c = System.now();
        con.LoyaltyFlag__c=false;
        con.WelcomeSource__c = '01';
		con.StoreOfCapture__c = 'cLoc';
        con.SMSNumber__c = '8888899999';
        insert con;
        return con;
    }

    @isTest static void testdoOptinBlankSubKey(){
        //Test for Email source is not passed in the request
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.emailAddress ='abcde@def.com';
        sfccReq.SMSNumber='9999988888';
        sfccReq.SMSOptinStatus='P';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('Missing: ContactId', sfccRes.message);
        System.assertEquals('MISSING_PARAMETERS', sfccRes.code);
        Test.stopTest();
    }
    
    @isTest static void testdoOptinContactNotFound(){
        //Test for Email source is not passed in the request
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = '0032C00000hn06g';
        sfccReq.emailAddress ='abcde@def.com';
        sfccReq.SMSNumber='9999988888';
        sfccReq.SMSOptinStatus='P';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('No matching contact found', sfccRes.message);
        System.assertEquals('CONTACT_NOT_FOUND', sfccRes.code);
        Test.stopTest();
    }
    
    @isTest static void testdoOptinSMSInUse(){
        
        Contact Cont1 = createContact();
        Contact Cont2 = createContact2();
        
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = cont2.Id;
        sfccReq.emailAddress ='abcde@def.com';
        sfccReq.SMSNumber='9999988888';
        sfccReq.SMSOptinStatus='P';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('SMS Number used by another contact', sfccRes.message);
        System.assertEquals('SMS_NUMBER_IN_USE', sfccRes.code);
        Test.stopTest();
    }
 	
    @isTest static void testdoOptinValidContactUpdate(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress =Cont1.Email;
        sfccReq.SMSNumber='7777788899';
        sfccReq.SMSOptinStatus='P';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();    
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('SUCCESS', sfccRes.message);
        System.assertEquals('Ok', sfccRes.code);
        Test.stopTest();
    }
    
    @isTest static void testdoOptinException(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress ='asldfa aldsfja ';
        sfccReq.SMSNumber='ABCD 23EF$^$';
        sfccReq.SMSOptinStatus='P';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();    
        System.assertEquals(res.statusCode, 500);
        System.assertEquals('OTHER_ERROR', sfccRes.code);
        Test.stopTest();
    }
 	
    
    @isTest static void testdoOptinOptingOutSMS(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress =Cont1.Email;
        sfccReq.SMSNumber='9999988888';
        sfccReq.SMSOptinStatus='N';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('SUCCESS', sfccRes.message);
        System.assertEquals('Ok', sfccRes.code);
        Test.stopTest();
    }
 
    @isTest static void testdoOptinOptingOutException(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress ='aljfads alsdfj';
        sfccReq.SMSNumber='9999988888';
        sfccReq.SMSOptinStatus='N';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 500);
        System.assertEquals('OTHER_ERROR', sfccRes.code);
        Test.stopTest();
    }
 
        @isTest static void testdoOptinElse(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress =Cont1.Email;
        sfccReq.SMSNumber='7777788888';
        sfccReq.SMSOptinStatus='N';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 200);
        System.assertEquals('Success', sfccRes.message);
        System.assertEquals('Ok', sfccRes.code);
        Test.stopTest();
    }
    
    @isTest static void testdoOptinElseException(){
        Contact Cont1 = createContact();
        CustomerSMSOptinServices.SFCCRequest sfccReq = new CustomerSMSOptinServices.SFCCRequest();
        CustomerSMSOptinServices.SFCCResponse  sfccRes = new CustomerSMSOptinServices.SFCCResponse();
        sfccReq.brandId = '1';
        sfccReq.Subscriberkey = Cont1.Id;
        sfccReq.emailAddress ='asdfl alsfdjsdf';
        sfccReq.SMSNumber='7777788888';
        sfccReq.SMSOptinStatus='N';
        sfccReq.Locale='en_us';
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        String jsonMsg=JSON.serialize(sfccReq);
        req.requestURI = '/subscriptions/customeroptin';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(jsonMsg);
        RestContext.request = req;
        RestContext.response= res;
        sfccRes = CustomerSMSOptinServices.doOptin();
        System.assertEquals(res.statusCode, 500);
        System.assertEquals('OTHER_ERROR', sfccRes.code);
        Test.stopTest();
    }
 
}