unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CountryOfCapture__c.field-meta.xml
<CustomField>
    <fullName>CountryOfCapture__c</fullName>
    <label>Country of Capture</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSLocale__c.field-meta.xml
<CustomField>
    <fullName>SMSLocale__c</fullName>
    <label>SMSLocale</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSNumber__c.field-meta.xml
<CustomField>
    <fullName>SMSNumber__c</fullName>
    <label>SMSNumber</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptInDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptInDate__c</fullName>
    <label>SMS Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOutDate__c</fullName>
    <label>SMS Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>ErrorLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ErrorLog__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>FileName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Its used to store Error Log Message</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>Its used to store Error Log Source System</description>
    <label>SourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Its used to store Error Log StackTrace</description>
    <label>StackTrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/chargeItKeyword__c.field-meta.xml
<CustomField>
    <fullName>chargeItKeyword__c</fullName>
    <label>MCchargeItKeyword</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/MCSMSEnabled__c.field-meta.xml
<CustomField>
    <fullName>MCSMSEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SMS optin/optouts Enabled through SFMC system</description>
    <label>MC SMS Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/preferenceCenterKeyword__c.field-meta.xml
<CustomField>
    <fullName>preferenceCenterKeyword__c</fullName>
    <label>MCpreferenceCenterKeyword</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/shortCode__c.field-meta.xml
<CustomField>
    <fullName>shortCode__c</fullName>
    <label>MCshortCode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/stopKeyword__c.field-meta.xml
<CustomField>
    <fullName>stopKeyword__c</fullName>
    <label>MCstopKeyword</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/WaterfallSMSEnabled__c.field-meta.xml
<CustomField>
    <fullName>WaterfallSMSEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SMS optin/optout enabled thru Waterfall system</description>
    <label>WaterfallSMSEnabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SFMC_AccessTokens__mdt/SFMC_AccessTokens__mdt.object-meta.xml
<CustomObject>
    <label>SFMC Access Tokens</label>
    <pluralLabel>SFMC Access Tokens</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SFMC_AccessTokens__mdt/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SFMC_AccessTokens__mdt/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <label>Expires At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/WaterfallAPISettings__mdt.object-meta.xml
<CustomObject>
    <label>WaterfallAPISettings</label>
    <pluralLabel>WaterfallAPISettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/fields/AuthKey__c.field-meta.xml
<CustomField>
    <fullName>AuthKey__c</fullName>
    <label>AuthKey</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/fields/ChargeItOptinFlowId__c.field-meta.xml
<CustomField>
    <fullName>ChargeItOptinFlowId__c</fullName>
    <label>ChargeItOptinFlowId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/fields/PrefCenterOptinFlowId__c.field-meta.xml
<CustomField>
    <fullName>PrefCenterOptinFlowId__c</fullName>
    <label>PrefCenterOptinFlowId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WaterfallAPISettings__mdt/fields/WfShortCode__c.field-meta.xml
<CustomField>
    <fullName>WfShortCode__c</fullName>
    <label>WfShortCode</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SFMCUtility.cls
/*******************************************************************************************
* @Description: Utility methods for SFMC & SMS related methods for Waterfall and QueueMOAPI
* @Author     : 
* @Date       : 3 March & 20 April
* @JIRA       : NASSC-1481/NASSC-1485/NASSC-1486
*
********************************************************************************************/ 

global class SFMCUtility{
    public static integer countSFMCPostCall = 0; 
    
    //method: POST to SFMC
    @future (callout=true)
    public static void postToSFMCQueueMOAPI(String QueueMODataListAsString){
    System.debug('^^^inside postToSFMCQueueMOAPI()');
  List<QueueMOData> QueueMODataList = (List<QueueMOData>)Json.deserialize(QueueMODataListAsString,List<QueueMOData>.class);

        for (QueueMOData QMOData : QueueMODataList) {

            String KeywordType = QMOData.KeywordType;
            String BrandId = QMOData.BrandId;
            String SmsNumber = QMOData.SmsNumber;
            Id ContactId = QMOData.ContactId;
            String Email = QMOData.Email;
            String Country = QMOData.Country;
            String SMSLocale = QMOData.SMSLocale;

            String requestBody = '';
            String keyword = '';
            Integer countCalls = 0;
            String cacheControl = 'no-cache';
            String requestEndPoint = 'callout:SFMC_QueueMOAPI/';

            List<LoyaltySettings__mdt> listLoyalty = [
                    SELECT shortCode__c, chargeItKeyword__c, preferenceCenterKeyword__c, stopKeyword__c
                    FROM LoyaltySettings__mdt
                    WHERE BrandId__c = :BrandId AND shortCode__c!=null
            ];
      System.debug('***Get Loyalty Record = '+listLoyalty);
            if(listLoyalty!=null && !listLoyalty.isEmpty() && BrandId =='1')
            {
                if (KeywordType == 'chargeIt') keyword = listLoyalty[0].chargeItKeyword__c;
                if (KeywordType == 'preferenceCenter') keyword = listLoyalty[0].preferenceCenterKeyword__c;
                if (KeywordType == 'stop') keyword = listLoyalty[0].stopKeyword__c;
                
                
                if (KeywordType == 'chargeIt' || KeywordType == 'preferenceCenter') {
                    requestBody = '{"subscribers":[{ "mobilenumber": "' + SmsNumber + '", "subscriberkey": "' + ContactId + '" }],"shortCode" : "' + listLoyalty[0].shortCode__c + '","messageText" : "' + keyword + ' ' + ContactId + ' ' + Email + ' ' + BrandId + ' ' + SMSLocale + '"}';
                } else if (KeywordType == 'stop') {
                    requestBody = '{"subscribers":[{ "mobilenumber": "' + SmsNumber + '", "subscriberkey": "' + ContactId + '" }],"shortCode" : "' + listLoyalty[0].shortCode__c + '","messageText" : "' + keyword + ' ' + ContactId + '"}';
                }
                
                //getting access token
                String validAccessToken = getSFMCAccessToken();
                System.debug('*****get valid access token first time= ' + validAccessToken);
                String authorization = 'Bearer ' + validAccessToken;
                
                //SFMC Callout 1
                HttpResponse getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                
                if (getResponse.getStatusCode() == 200) System.debug('^^^Successfully POST SFMC Attempt 1');
                
                else if (getResponse.getStatusCode() == 401 || getResponse.getStatusCode() == 403) {
                    System.debug('^^^Error 401 or 403 Posting SFMC');
                    if (countSFMCPostCall == 1) {
                        System.debug('^^^getting valid access token second time');
                        validAccessToken = getSFMCAccessToken();
                        authorization = 'Bearer ' + validAccessToken;
                        //SFMC Callout 2
                        getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                        if (getResponse.getStatusCode() == 200) System.debug('*****Successfully POST SFMC Attempt 2');
                        
                        else if ((getResponse.getStatusCode() == 401 || getResponse.getStatusCode() == 403) && countSFMCPostCall == 2) {                            
                            createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                        }
                    } 
                    else {                        
                        createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                    }
                    
                }
                else {                    
                    createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                }
            }
            if(listLoyalty!=null && !listLoyalty.isEmpty() && BrandId =='2')
            {
               /* if (KeywordType == 'chargeIt') keyword = listLoyalty[0].chargeItKeyword__c;
                if (KeywordType == 'preferenceCenter') keyword = listLoyalty[0].preferenceCenterKeyword__c;*/
                if (KeywordType == 'stop') keyword = listLoyalty[0].stopKeyword__c;
                
                
                /*if (KeywordType == 'chargeIt' || KeywordType == 'preferenceCenter') {
                    requestBody = '{"subscribers":[{ "mobilenumber": "' + SmsNumber + '", "subscriberkey": "' + ContactId + '" }],"shortCode" : "' + listLoyalty[0].shortCode__c + '","messageText" : "' + keyword + ' ' + ContactId + ' ' + Email + ' ' + BrandId + ' ' + SMSLocale + '"}';
                } else */
                if (KeywordType == 'stop') {
                    requestBody = '{"subscribers":[{ "mobilenumber": "' + SmsNumber + '", "subscriberkey": "' + ContactId + '" }],"shortCode" : "' + listLoyalty[0].shortCode__c + '","messageText" : "' + keyword + ' ' + ContactId + '"}';
                }
                
                //getting access token
                String validAccessToken = CKgetSFMCAccessToken();
                System.debug('*****get valid access token first time= ' + validAccessToken);
                String authorization = 'Bearer ' + validAccessToken;
                
                //SFMC Callout 1
                HttpResponse getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                
                if (getResponse.getStatusCode() == 200) System.debug('^^^Successfully POST SFMC Attempt 1');
                
                else if (getResponse.getStatusCode() == 401 || getResponse.getStatusCode() == 403) {
                    System.debug('^^^Error 401 or 403 Posting SFMC');
                    if (countSFMCPostCall == 1) {
                        System.debug('^^^getting valid access token second time');
                        validAccessToken = CKgetSFMCAccessToken();
                        authorization = 'Bearer ' + validAccessToken;
                        //SFMC Callout 2
                        getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                        if (getResponse.getStatusCode() == 200) System.debug('*****Successfully POST SFMC Attempt 2');
                        
                        else if ((getResponse.getStatusCode() == 401 || getResponse.getStatusCode() == 403) && countSFMCPostCall == 2) {                            
                            createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                        }
                    } 
                    else {                        
                        createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                    }
                    
                }
                else {                    
                    createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to SFMC');
                }
            }
        }
    }
    
    
    //method: POST to Waterfall
    @future (callout=true)
    public static void postToWaterfallSMSAPI(String QueueMODataListAsString){
        System.debug('^^^inside postToWaterfallSMSAPI()');
        List<QueueMOData> QueueMODataList = (List<QueueMOData>)Json.deserialize(QueueMODataListAsString,List<QueueMOData>.class);
        
        for (QueueMOData QMOData : QueueMODataList) {
            
            String KeywordType = QMOData.KeywordType;
            String BrandId = QMOData.BrandId;
            String SmsNumber = QMOData.SmsNumber;
            Id ContactId = QMOData.ContactId;
            String Email = QMOData.Email;
            String Country = QMOData.Country;
            String SMSLocale = QMOData.SMSLocale;
            String requestBody = '';
            String requestEndPoint = '';
            String cacheControl = 'no-cache';
            List<WaterfallAPISettings__mdt> listWaterfallSettings = [SELECT BrandId__c, Country__c, AuthKey__c,
                                                                     ChargeItOptinFlowId__c, PrefCenterOptinFlowId__c, 
                                                                     WfShortCode__c
                                                                     FROM WaterfallAPISettings__mdt
                                                                     WHERE BrandId__c != null AND 
                                                                     BrandId__c =: BrandId AND
                                                                     Country__c != null AND
                                                                     Country__c =:Country];
            
            
            HttpResponse getResponse;
            //setting authorization
            if(listWaterfallSettings.size() > 0){
                String authorization = listWaterfallSettings[0].AuthKey__c;
                if (KeywordType == 'chargeIt') {
                    requestBody = '{"msisdns": ["'+SmsNumber+'"],"mobileFlow":"'+listWaterfallSettings[0].ChargeItOptinFlowId__c+'"}';
                    requestEndPoint = 'callout:WaterfallAPIOptin/';
                    getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                }
                else if (KeywordType == 'preferenceCenter') {
                    requestBody = '{"msisdns": ["'+SmsNumber+'"],"mobileFlow":"'+listWaterfallSettings[0].PrefCenterOptinFlowId__c+'"}';
                    requestEndPoint = 'callout:WaterfallAPIOptin/';
                    getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                }
                else if(KeywordType == 'stop'){
                    requestEndPoint = 'callout:WaterfallAPIOptout/'+SmsNumber+'?shortCode='+listWaterfallSettings[0].WfShortCode__c;
                    getResponse = doCalloutSFMC(requestEndPoint, 'POST', requestBody, authorization, cacheControl);
                }
                
                if (String.valueOf(getResponse.getStatusCode()).startsWith('2')) {
                    System.debug('^^^POST Call to Waterfall Success with StatusCode = '+getResponse.getStatusCode());
                }
                else {
                    System.debug('^^^POST Call to Waterfall Error');                 
                    createErrorLogs(requestEndPoint,requestBody,String.valueOf(getResponse.getStatusCode()),getResponse.getBody(),'SFSC to Waterfall');
                }
            }
        }
    }
    
    
    private static String getSFMCAccessToken(){
         String accessToken = null;        
        List<SFMC_AccessTokens__mdt> tokenRecord = [SELECT Access_Token__c 
                                                    FROM SFMC_AccessTokens__mdt 
                                                    WHERE DeveloperName='Token_1' AND expires_at__c > :System.now() LIMIT 1];
        if (tokenRecord.size()>0){
            accessToken = tokenRecord[0].access_token__c;
        } 
        return accessToken;
    }
     private static String CKgetSFMCAccessToken(){
         String accessToken = null;        
        List<SFMC_AccessTokens__mdt> tokenRecord = [SELECT Access_Token__c 
                                                    FROM SFMC_AccessTokens__mdt 
                                                    WHERE DeveloperName!='Token_1' AND expires_at__c > :System.now() LIMIT 1];
        if (tokenRecord.size()>0){
            accessToken = tokenRecord[0].access_token__c;
        } 
        return accessToken;
    }
    
    

    //method: POST callout to SFMC 
    private static HttpResponse doCalloutSFMC(String requestEP, String calloutMethod,String inputBody, String auth, String cacheControl){
        System.debug('^^^inside doCalloutSFMC()');
        System.debug('^^^Request Body = '+inputBody);
        System.debug('^^^auth = '+auth);
        countSFMCPostCall = countSFMCPostCall + 1;
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Authorization', auth);
        req.setHeader('Cache-Control', cacheControl);
        req.setEndpoint(requestEP);
        req.setMethod(calloutMethod);
        req.setBody(inputBody);
        Http http = new Http();
        try{
            res = http.send(req);
            System.debug('*****Status Code = '+res.getStatusCode());
            System.debug('*****Response Body = '+res.getBody());
        }catch(System.CalloutException e) {
            System.debug('Callout error: '+ e);
        }
        return res;
        
       
    }
   
    //method: create logs in ErrorLog__c object
    public static void createErrorLogs(String reqEndPoint, String reqBody, String resStatusCode, String resBody, String sourceSystem){
        ErrorLog__c logObject = new ErrorLog__c();
        logObject.SourceSystem__c = sourceSystem;
        logObject.FileName__c = 'Auth API Call from SFSC';
        logObject.Message__c = 'Response status code: '+ resStatusCode;
        logObject.StackTrace__c = 'POST '+ reqEndPoint + ' ; request payload: '+ reqBody + ' ; response body: ' + resBody;
        
        try{
            insert logObject;
        }
        catch(Exception e){
            System.debug('Exception has occurred while inserting in ErrorLog Object: ' + e.getMessage());
        }
    }
    
    //Set contact SMS preferences
    Static void setContactSMSOptin(Contact cont,Boolean smsOptInFlag){
        if (smsOptInFlag){
            cont.SMSOptinStatus__c = 'Y'; //true;
            cont.SMSOptInDate__c = System.now();
            cont.SMSOptOutDate__c = Null;
        } else {
            cont.SMSOptinStatus__c = 'N'; //false;
            cont.SMSOptInDate__c = Null;
            cont.SMSOptOutDate__c = System.now();
        }
    }


    public class QueueMOData {

        @InvocableVariable
        public String KeywordType;
        @InvocableVariable
        public String BrandId;
        @InvocableVariable
        public String SmsNumber;
        @InvocableVariable
        public Id ContactId;
        @InvocableVariable
        public String Email;
        @InvocableVariable
        public String Country;
        @InvocableVariable
        public String SMSLocale;
    }


    @InvocableMethod(label='invocable QueueMOAPI' description='pass thru method to call QueueMOAPI')
    public static void invocableTargetSMSAPI(List<QueueMOData> QueueMODataList) {
    String jsonString = json.serialize(QueueMODataList);
        List<LoyaltySettings__mdt> listLoyaltyData = [SELECT BrandId__c, MCSMSEnabled__c, WaterfallSMSEnabled__c,
                                                     shortCode__c, preferenceCenterKeyword__c, chargeItKeyword__c, 
                                                     stopKeyword__c 
                                                     FROM LoyaltySettings__mdt 
                                                     WHERE BrandId__c =: QueueMODataList[0].BrandId];
        if(listLoyaltyData[0].MCSMSEnabled__c){
             System.debug('^^^calling postToSFMCQueueMOAPI method');
            if(!Test.isRunningTest())  postToSFMCQueueMOAPI(jsonString);
        }
        if(listLoyaltyData[0].WaterfallSMSEnabled__c){
            System.debug('^^^calling postToWaterfallSMSAPI method');
            if(!Test.isRunningTest())  postToWaterfallSMSAPI(jsonString);                
            
        }

    }
    
    //method: 
    public static Contact searchSMSBrandContact(String brandId,String SMSNumber){

        List <Contact> conList = [SELECT id, Brand_Id__c, Email, SMSNumber__c, AccountId, StoreOfCapture__c, CountryOfCapture__c,
                LoyaltyID__c, LoyaltyFlag__c, SMSOptinStatus__c,SMSLocale__c,EmailOptInStatus__c, Loyalty_Optin_Date__c, SMSOptInDate__c, Source_System__c, Latest_Source__c
        FROM CONTACT
               WHERE Brand_Id__c=:brandId AND SMSNumber__c=:SMSNumber limit 1];

        if (conList.size()>0) return conList[0];
        else return null;
    }
    
    //method:
    public static Contact searchEmailBrandContact(String brandId,String EmailAddress){

        List <Contact> conList = [SELECT id, Brand_Id__c, Email, SMSNumber__c, AccountId, StoreOfCapture__c, CountryOfCapture__c,
                LoyaltyID__c, LoyaltyFlag__c, SMSOptinStatus__c,SMSLocale__c,EmailOptInStatus__c, Loyalty_Optin_Date__c, SMSOptInDate__c, Source_System__c, Latest_Source__c
               FROM CONTACT 
               WHERE Brand_Id__c=:brandId AND Email=:EmailAddress limit 1];

        if (conList.size()>0) return conList[0];
        else return null;
    }

    public static Id getSiblingAccountId(String brandId,String EmailAddress){

        List <Contact> conList = [SELECT id, AccountId
        FROM CONTACT
        WHERE Email=:EmailAddress AND Brand_Id__c!=:brandId AND AccountId!=null AND Account.Name != 'Dummy Parent Account' limit 1];

        if (conList.size()>0) return conList[0].AccountId;
        else return null;
    }

    //Email validation function
    public static Boolean validateEmail(string emailString){
        System.debug(Pattern.matches('([a-zA-Z0-9_\\-\\.]+)@(((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3}))','emailString'));
        return Pattern.matches('([a-zA-Z0-9_\\-\\.]+)@(((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3}))',emailString);
    }
   
    
}