unpackaged/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bass</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
                <label>Calvin Klein</label>
            </value>
            <value>
                <fullName>Heritage Ecom</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>IZOD.com</fullName>
            </value>
            <value>
                <fullName>Partner Brands</fullName>
                <label>Partner Brands</label>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Style Bureau</fullName>
                <label>Style Bureau</label>
            </value>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com</fullName>
                <label>Van Heusen.com</label>
            </value>
            <value>
                <fullName>Warners.com</fullName>
            </value>
            <value>
                <fullName>Speedo USA</fullName>
            </value>
            <value>
                <fullName>Van Heusen.com (VHE)</fullName>
            </value>
            <value>
                <fullName>True&amp;Co</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/CreatedByMethod__c.field-meta.xml
<CustomField>
    <fullName>CreatedByMethod__c</fullName>
    <label>Created By Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Do_Not_Sync_with_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Sync_with_SFMC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field value is true, then SFMC will not sync this record with it.</description>
    <label>Do Not Sync with SFMC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOrigSource__c.field-meta.xml
<CustomField>
    <fullName>EmailOrigSource__c</fullName>
    <label>EmailOrigSource</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Latest_Source__c.field-meta.xml
<CustomField>
    <fullName>Latest_Source__c</fullName>
    <label>Latest Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/SubscriberDataSources__mdt/SubscriberDataSources__mdt.object-meta.xml
<CustomObject>
    <label>SubscriberDataSource</label>
    <pluralLabel>SubscriberDataSources</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/DataSource__c.field-meta.xml
<CustomField>
    <fullName>DataSource__c</fullName>
    <label>Data Source</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <label>Source System</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SubscriberDataSources__mdt/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Welcome Source</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TCsignUp.cls
/*
 * Created Date :10/04/2020
 * Created By   :PVH
 * 
 * JSON Request :
 * {"brandId": "11","firstName": "John","lastName": "Doe","country":"US","emailAddress": "john@someEmail.com","emailOptIn": "true","SourceSystem": "TC","WelcomeSource": "01"}
 * URL: https://instance.salesforce.com/services/apexrest/tcsubscriber/SignUp
 * 
 */

@RestResource(urlMapping='/tcsubscriber/SignUp')
global without sharing class TCsignUp {
    static Id emailRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId(); 
    static Map<String,String> mapSubbrandParentbrand = new Map<String,String>();
    
    global class TnCoRequest{
        public String brandId;
        public String firstName; 
        public String lastName;
        public String country;
        public String emailAddress;
        public String emailOptIn;
        public String SourceSystem;
        public String WelcomeSource;
    }
    
    global class TnCoResponse{
        public String code;
        public String message;
        public String ContactId;
        public String ExistingCustomer;
        public String NewsLetterAlreadySignedUp;
       
     }
    
    @HttpPost
    global static TnCoResponse doSignup(){
        
        List<Contact> profileUpdateContacts = new List<Contact>();
        Map<Id, Contact> oldContacts = new Map<Id, Contact>();
        Boolean existingCont = false;
        List<Contact> newConList = new List<Contact>();    
        List<Contact> allContactList = new List<Contact>();
        
        List<ID> allContactID = new List<ID>();
        Contact contact = new Contact();
        Date reqBDate;  
        
        List<Contact> contacts = new List<Contact>();
        List<Contact> updatedconList = new List<Contact>();
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String requestData = req.requestBody.toString();
        TnCoRequest tNcoReq = (TnCoRequest)json.deserialize(requestData, TnCoRequest.class);
        System.debug('tNcoReq***'+tNcoReq);
        TnCoResponse tnCoResponse = new TnCoResponse();    
        
        // Brand id or email not present in request, return error message
        if(String.isEmpty(tNcoReq.brandId) || String.isEmpty(tNcoReq.emailAddress) || String.isBlank(tNcoReq.brandId) ||  String.isBlank(tNcoReq.emailAddress) ){
            res.statusCode = 400;
            tnCoResponse.code = 'INVALID_QUERY';
            tnCoResponse.message = 'Missing required parameters:  BrandId or email';
            System.debug('***tnCoResponse: ' + tnCoResponse); 
            return tnCoResponse;
        } else { //Brand id and email present in request   
            
            //Check for existing contact
            contacts = searchContacts(tNcoReq.brandId,tNcoReq.emailAddress,emailRecordTypeId);
            System.debug('contacts***' + contacts);
            if(contacts != NULL && contacts.size()>0) {
                contact = contacts[0];
            }
            If(tNcoReq.brandId=='11'){  
               //Contact not found
                if(contacts.size()<1){
                    newConList.add(createContact(tNcoReq,tNcoReq.brandId));
                   
                }
                else{
                    existingCont = true;
                    oldContacts.put(contact.Id, contact.clone());
                    profileUpdateContacts.add(updateContact(contact,tNcoReq));
                 }
            }
            
            if(profileUpdateContacts.size()>0) {
                Database.SaveResult[] srList = Database.update(profileUpdateContacts, false);
                for(Contact con : profileUpdateContacts){
                    if(con.id!=null) allContactList.add(con);
                }
            }
            if(newConList.size()>0){
                Database.SaveResult[] srList = Database.insert(newConList, false);
               for(Contact con : newConList){
                    if(con.id!=null) allContactList.add(con);
                }
                
            }
           
           
            for(Contact con: allContactList){
                allContactID.add(con.Id);
             }
                   
            
            
        }
          
           res.statusCode = 200;
           tnCoResponse = returnResponse(existingCont, allContactID, tNcoReq.brandId, oldContacts);
           System.debug('***tnCoResponse: ' + tnCoResponse);  
           return tnCoResponse;
            
      }
    
    //Search Contact record
    Static List<Contact> searchContacts(String brandId, String emails,Id emailRecordTypeId){
        
        System.debug('Contact search Brand Id***'+brandId);
        System.debug('Contact search emails***'+emails);
        System.debug('Contact search emailRecordTypeId***'+emailRecordTypeId);
        List<Contact> searchedContactList =  [SELECT Id, FirstName, LastName, Brand_Id__c, MailingStreet, MailingCity, MailingState, MailingPostalCode, 
                                              Phone, MobilePhone, MailingCountry, Email, HomePhone, Birthdate, HomeStore__c, AccountId,  
                                              Latest_Source__c, EmailOptInStatus__c, ReportsToId, Source_System__c,Do_Not_Sync_with_SFMC__c,
                                              WelcomeSource__c,StoreOfCapture__c,createdByMethod__c
                                              FROM Contact 
                                              WHERE RecordTypeId = :emailRecordTypeId AND Brand_Id__c =:brandId AND Email = :emails];
        
        return ((searchedContactList!=null)?searchedContactList:Null);
    }
    
    //Create New Contact record
    Static Contact createContact(TnCoRequest tNcoReq, String brandId){
       system.debug('tNcoReq.emailOptIn****'+tNcoReq.emailOptIn);
        Contact con = new Contact();
        con.RecordTypeId = emailRecordTypeId;
        
        if(String.isNotBlank(tNcoReq.sourceSystem)) {
            con.Source_System__c = tNcoReq.sourceSystem;
            con.Latest_Source__c = tNcoReq.sourceSystem;
        }
        else{
            con.Source_System__c = 'TC';
            con.Latest_Source__c = 'TC';
         }
        con.createdByMethod__c = 'API';
        con.Status__c = 'ACTIVE';     
        
        if(String.isNotEmpty(brandId)){
            con.Brand_Id__c = brandId;
        } else con.Brand_Id__c = tNcoReq.brandId;
        
        String searchBrand = tNcoReq.brandId;
        System.debug('createContact - searchBrand**** = '+searchBrand);
        
        if(String.isNotBlank(tNcoReq.firstName)) con.FirstName = tNcoReq.firstName;
        else if(String.isBlank(tNcoReq.firstName) || String.valueOf(tNcoReq.firstName) == '') con.firstName = 'UNKNOWN';
        if(String.isNotBlank(tNcoReq.lastName)){ con.LastName = tNcoReq.lastName; }
        else if(String.isBlank(tNcoReq.lastName) || String.valueOf(tNcoReq.lastName) == '') con.LastName = 'UNKNOWN';
        if(String.isNotBlank(tNcoReq.country)) { con.MailingCountry = tNcoReq.country; }
        else if(String.isBlank(tNcoReq.country) || String.valueOf(tNcoReq.country) == '') con.MailingCountry = 'US';
        if(String.isNotBlank(tNcoReq.emailAddress)) con.Email = tNcoReq.emailAddress;
        
         System.debug('WelcomeSource**** = '+tNcoReq.WelcomeSource);
        
        if(String.isNotBlank(tNcoReq.WelcomeSource)) con.WelcomeSource__c = tNcoReq.WelcomeSource;
        If(String.isNotBlank(tNcoReq.sourceSystem)) { con.Latest_Source__c  = tNcoReq.sourceSystem; }
        else if(String.isBlank(tNcoReq.sourceSystem) || String.valueOf(tNcoReq.sourceSystem) == '') con.Latest_Source__c = 'TC'; 
        
         List<SubscriberDataSources__mdt> listDataSource = [SELECT Brand__c, SourceSystem__c, 
                                                              WelcomeSource__c,DataSource__c
                                                              FROM SubscriberDataSources__mdt
                                                              WHERE Brand__c=:searchBrand AND
                                                              SourceSystem__c=:tNcoReq.SourceSystem AND
                                                              WelcomeSource__c =:tNcoReq.WelcomeSource];
            
            if (listDataSource.size()>0){
                con.EmailOrigSource__c = listDataSource[0].DataSource__c;
                con.Source__c = listDataSource[0].DataSource__c;
            }
        
        if(String.isNotBlank(tNcoReq.emailOptIn) && Boolean.valueOf(tNcoReq.emailOptIn) == true){ 
            con.EmailOptInStatus__c='Y';
            if(String.isNotBlank(con.EmailOptInStatus__c)){
                con.EmailOptInDate__c=system.now();
                con.EmailOptOutDate__c=Null;
                con.HasOptedOutOfEmail=false;
                con.Do_Not_Sync_with_SFMC__c=false;
            }
       }
        if(String.isNotBlank(tNcoReq.emailOptIn) && Boolean.valueOf(tNcoReq.emailOptIn) == false ){ 
            con.EmailOptInStatus__c='N';
            if(String.isNotBlank(con.EmailOptInStatus__c)){
                con.EmailOptInDate__c=Null;
                con.EmailOptOutDate__c=system.now();
                con.HasOptedOutOfEmail=true;
            }
       } 
        
        return con;
    }
    
     //Update existing Contact details
    Static Contact updateContact(Contact cont, TnCoRequest tNcoR){
       
        cont.Status__c = 'ACTIVE';
        cont.createdByMethod__c = 'API';
        String searchBrand = tNcoR.brandId;
        System.debug('***updateContact - searchBrand = '+searchBrand);
        
        If(String.isNotBlank(tNcoR.firstName) && (!tNcoR.firstName.equals(cont.FirstName))) cont.FirstName = tNcoR.firstName;
        If(String.isNotBlank(tNcoR.lastName) && (!tNcoR.lastName.equals(cont.LastName))) cont.LastName = tNcoR.lastName;
        If(String.isNotBlank(tNcoR.country) && (!tNcoR.country.equals(cont.MailingCountry))) cont.MailingCountry = tNcoR.country;
        If(String.isNotBlank(tNcoR.emailAddress) && (!tNcoR.emailAddress.equals(cont.Email))) cont.Email = tNcoR.emailAddress;
        If(String.isNotBlank(tNcoR.WelcomeSource) && (!tNcoR.WelcomeSource.equals(cont.WelcomeSource__c))) cont.WelcomeSource__c = tNcoR.WelcomeSource;
        if(String.isNotBlank(tNcoR.sourceSystem)) {
            cont.Source_System__c = tNcoR.sourceSystem;
            cont.Latest_Source__c = tNcoR.sourceSystem;
        }
        else{
            cont.Source_System__c = 'TC';
            cont.Latest_Source__c = 'TC';
         }
        
       
        List<SubscriberDataSources__mdt> listDataSource = [SELECT Brand__c, SourceSystem__c, 
                                                              WelcomeSource__c,DataSource__c
                                                              FROM SubscriberDataSources__mdt
                                                              WHERE Brand__c=:searchBrand AND
                                                              SourceSystem__c=:tNcoR.SourceSystem AND
                                                              WelcomeSource__c =:tNcoR.WelcomeSource];
            
            if (listDataSource.size()>0){
                cont.Source__c = listDataSource[0].DataSource__c;
            } 
        
        if(String.isNotBlank(tNcoR.emailOptIn) && Boolean.valueOf(tNcoR.emailOptIn) == true){ 
            System.debug('*** tNcoR.emailOptIn = '+ tNcoR.emailOptIn);
              if(cont.EmailOptInStatus__c=='Y' ){
                  System.debug('*** cont.EmailOptInStatus__c = '+ cont.EmailOptInStatus__c);
                 cont.EmailOptInStatus__c='Y';
                 //cont.EmailOptInDate__c=system.now();
                 cont.HasOptedOutOfEmail=false;
                 cont.Do_Not_Sync_with_SFMC__c=false;
              }
             else if(cont.EmailOptInStatus__c=='N' || cont.EmailOptInStatus__c==NUll){
                 System.debug('*** tNcoR.emailOptIn = '+ tNcoR.emailOptIn);
                 cont.EmailOptInStatus__c='Y';
                 cont.Do_Not_Sync_with_SFMC__c=false;
                 cont.EmailOptInDate__c=system.now();
                 cont.HasOptedOutOfEmail=false;
                
             }
         }
         else if(String.isNotBlank(tNcoR.emailOptIn) && Boolean.valueOf(tNcoR.emailOptIn) == false){  
              if(cont.EmailOptInStatus__c=='N' ){
                 cont.EmailOptInStatus__c='N';
                // cont.EmailOptOutDate__c=system.now();
                 cont.HasOptedOutOfEmail=true;
              }
             else if(cont.EmailOptInStatus__c=='Y' || cont.EmailOptInStatus__c==NUll){
                 cont.EmailOptInStatus__c='N';
                 cont.EmailOptOutDate__c=system.now();
                 cont.HasOptedOutOfEmail=true;
                 //cont.Do_Not_Sync_with_SFMC__c=false;
             }
         }
            
         return cont;
    } 
    
    Static TnCoResponse returnResponse(Boolean existingCont, List<Id> allContactID, String brandId, Map<Id, Contact> oldContacts){
        Contact contact;        
        TnCoResponse tNcoRes = new TnCoResponse();
        
        System.debug('***allContactID = '+allContactID);
        System.debug('***Brand_Id__c = '+brandId);
        if(allContactID != null && allContactID.size()>0){
            contact = [SELECT Id, LoyaltyId__c,EmailOptInStatus__c,LoyaltyFlag__c,createdByMethod__c,Do_Not_Sync_with_SFMC__c,EmailOptInDate__c FROM Contact WHERE Id IN :allContactID AND Brand_Id__c = :brandId  ];
                        
            if(existingCont){
                if(oldContacts.containsKey(contact.Id) && oldContacts.get(contact.Id).EmailOptInStatus__c == 'Y'){
                    tNcoRes.NewsLetterAlreadySignedUp = 'true';
                    oldContacts.get(contact.Id).Do_Not_Sync_with_SFMC__c=false;
                } else if(oldContacts.containsKey(contact.Id) && oldContacts.get(contact.Id).EmailOptInStatus__c == 'N' && oldContacts.get(contact.Id).createdByMethod__c!='API'){
                    tNcoRes.NewsLetterAlreadySignedUp = 'flase';
                    oldContacts.get(contact.Id).EmailOptInStatus__c = 'Y'; 
                    oldContacts.get(contact.Id).EmailOptInDate__c=system.now();
                    oldContacts.get(contact.Id).Do_Not_Sync_with_SFMC__c=false;
                }
            } else {
                tNcoRes.NewsLetterAlreadySignedUp = 'false';
                if(oldContacts.containsKey(contact.Id)){
                 oldContacts.get(contact.Id).Do_Not_Sync_with_SFMC__c=false;
                }
            }
            
            tNcoRes.ContactId = contact.Id;
               
        }        
        
        tNcoRes.code = 'OK';       
        tNcoRes.ExistingCustomer = String.valueOf(existingCont);        
        tNcoRes.message='Success';
        return tNcoRes;     
       
    }
    
    
}