unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DirectMailOptin__c.field-meta.xml
<CustomField>
    <fullName>DirectMailOptin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Mail Optin</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>U</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ZetaCustomerCaptureWrapper.cls
/* 
* Objective: Wrapper class for ZetaCustomerCapture 
*
* Date: Oct 2019
*
*/

public class ZetaCustomerCaptureWrapper {
        public String Channel;
        public String Source;
        public String TransactionDate;
        public String Prefix;
        public String FirstName;
        public String MiddleName;
        public String LastName;
        public String Gender;
        public String AddressLine1;
        public String AddressLine2;
        public String AddressLine3;
        public String City;
        public String State;
        public String PostalCode;
        public String ZIPPlus;
        public String Country;
        public Date DateOfBirth;
        public String EmailAddress;
        public String HomePhone;
        public String WorkPhone;
        public String MobilePhone;
        public Boolean DirectMailOptInFlag;
        public String HomeStore;
        public Boolean LoyaltyFlag;
        public String Buffer1;
        //EmailPreferenceCls;        
        public List<EmailPreferenceCls> EmailPreferenceList = new list<EmailPreferenceCls>();
        //objWrapSMSPreferenceCls
        public List<SMSPreferenceCls> SMSPreferenceList = new list<SMSPreferenceCls>();
        
        public String MobileOptInStoreCode;
        public String StoreCode;
        public String Language;
        //public List<SMSPreferenceList> SMSPreferenceList;
        
        public ZetaCustomerCaptureWrapper(Contact record){
            if(record.Channel__c != null) {
                Channel = record.Channel__c;    
            }
            if(record.Source__c != null) {
                Source  = record.Source__c;
            }

            if(record.Salutation__c != null) {
                Prefix  = record.Salutation__c;    
            }
            if(record.FirstName != null) {
                FirstName  = record.FirstName;
            }
            if(record.MiddleName != null) {
                MiddleName  = record.MiddleName;
            }
            if(record.LastName != null) {
                LastName  = record.LastName;
            }
            if(record.Gender__c != null) {
                Gender  = record.Gender__c;    
            }            
            //Address information
            AddressLine1  = null;
            AddressLine2  = null;
            AddressLine3  = null;
            if(record.MailingStreet != null) {
                String[] arrAddress = record.MailingStreet.split('\n');
                if(arrAddress.size() > 0)
                AddressLine1  = arrAddress[0].replace('\r', '');
                if(arrAddress.size() > 1)
                AddressLine2  = arrAddress[1].replace('\r', '');
                if(arrAddress.size() > 2)
                AddressLine3  = arrAddress[2].replace('\r', '');
            }
            if(record.MailingState != null) {
                City  = record.MailingCity;
            }
            if(record.MailingCity != null) {
                State  = record.MailingState;
            }
            if(record.MailingPostalCode != null) {
                PostalCode  = record.MailingPostalCode;
            }                        
            ZIPPlus  = null;
            if(record.MailingCountry != null) {
                Country  = record.MailingCountry;
            }
            if(record.Email != null) {
                EmailAddress  = record.Email;
            }                       
            //Phone
            if(record.HomePhone != null) {
                HomePhone  = record.HomePhone;
            }            
            WorkPhone  = null;
            if(record.MobilePhone != null) {
                MobilePhone  = record.MobilePhone;
            }
            if(record.DirectMailOptin__c != null) {
                DirectMailOptInFlag = record.DirectMailOptin__c;
            }
            if(record.HomeStore__c != null) {
                HomeStore  = record.HomeStore__c;
            }
            if(record.LoyaltyFlag__c != null) {
                LoyaltyFlag = record.LoyaltyFlag__c;
            }
            Buffer1 = record.id;
            //EmailPreference
            EmailPreferenceCls objWrapEmailPreference = new EmailPreferenceCls(record);
            EmailPreferenceList.add(objWrapEmailPreference);
            //SMSPreferences
            SMSPreferenceCls objWrapSMSPreferenceCls = new SMSPreferenceCls(record);
            SMSPreferenceList.add(objWrapSMSPreferenceCls);
            
            MobileOptInStoreCode  = null;
            if(record.StoreOfCapture__c != null) {
                StoreCode  = record.StoreOfCapture__c;
            } 
            if(record.Language__c != null) {
                Language  = record.Language__c;
            }             
            //date            
            TransactionDate = string.valueOf(record.CreatedDate.format('MM/dd/YYYY')); 
            if(record.Birthdate != null) {
                DateOfBirth     = record.Birthdate;
            }                     
        }
        
        class EmailPreferenceCls {
            public Integer BusinessUnitID;
            public Boolean EmailOptInFlag;
            public List<EmailUserPreferences> EmailUserPreferences;
            
            public EmailPreferenceCls(Contact record) {
                String optInFlag = system.label.false; 
                if(record.EmailOptInStatus__c==SYSTEM.LABEL.Y) {
                   optInFlag = system.label.true; 
                }
                BusinessUnitID = integer.valueof(record.Brand_Id__c);
                EmailOptInFlag = Boolean.valueOf(optInFlag);
                EmailUserPreferences = new List<EmailUserPreferences>();            
            }
        }        
    
        public class EmailUserPreferences {
            public EmailUserPreferences() {                            
            }
        }
        
        public class SMSPreferenceCls {
            public Integer BusinessUnitID;
            public Boolean MobileOptInFlag;
            public List<SMSPreferences> SMSPreferences;
            
            public SMSPreferenceCls(Contact record) {
                String optInFlag = system.label.false; 
                if(record.SMSOptinStatus__c==SYSTEM.LABEL.Y) {
                   optInFlag = system.label.true; 
                }
                BusinessUnitID = integer.valueof(record.Brand_Id__c);
                MobileOptInFlag = Boolean.valueOf(optInFlag);
                SMSPreferences = new List<SMSPreferences>();            
            }
            
        }
        
        public class SMSPreferences {
            public SMSPreferences () {                            
            }
        }
    }