unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInDate__c</fullName>
    <label>Email Opt-in Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt-out Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Unsubscribe.cls
/*  Json Request
 *  {"Count":"2", "Unsubscribes":[ { "BrandId":"3", "Email":"abc@123.com" }, { "BrandId":"2","Email":"xyc@123.com"}]}
 *
 *  https://instance.salesforce.com/services/apexrest/subscribers/Unsubscribe
 */
@RestResource(urlMapping = '/subscribers/Unsubscribe')
global without sharing class Unsubscribe{
    public class UnSubRequest{
        public String Count;
        public List<Unsubscribes> Unsubscribes;
        public String FileName;
    }

    public class Unsubscribes{
        public String BrandId;
        public String Email;
    }

    @HttpPost
    global static void doUnsubscribe(){
        RestRequest req = RestContext.request;

        List<Contact> conts = new List<Contact>();
        Set<String> emailSet = new Set<String>();
        List<String> brandIdSet = new List<String>();

        String requestData = req.requestBody.toString();
        Log.push('****' + requestData);

        UnSubRequest unSubReq = (UnSubRequest)JSON.deserialize(requestData, UnSubRequest.class);
        Log.push('****' + unSubReq);
        String FileName = unSubReq.FileName;
        String sourceSystem = SYSTEM.LABEL.BlueCore;
        // Create List of Email and BrandId to be used to get matching contacts
        for (Unsubscribes ubs : unSubReq.Unsubscribes){

            emailSet.add(ubs.Email);
            brandIdSet.add(ubs.BrandId);
        }
        Log.push('****' + emailSet);
        Log.push('****' + brandIdSet);

        if (emailSet.size() > 0){
            conts = [SELECT Id, Email, HasOptedOutOfEmail, EmailOptOutDate__c, EmailOptInStatus__c
                     FROM Contact
                     WHERE Email IN:emailSet AND Brand_Id__c = :brandIdSet[0] AND EmailOptInStatus__c = 'Y'];   // using brandIdSet[0] as all entries will have same brandId per call.
        }

        if (conts.size() > 0){

            for (Contact c : conts){

                c.EmailOptInStatus__c = SYSTEM.LABEL.N;
                //c.EmailOptInDate__c = null;
                c.HasOptedOutOfEmail = true;
                c.EmailOptOutDate__c = System.now();

            }

            Database.SaveResult[] results = Database.update (conts, false);
            Log.push('*****' + unSubReq.FileName);
            Logger.logDebug();
            ContactUtility.createErrorLogRecords(results, sourceSystem, FileName);
        }
    }

}