unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/SAP_Store_Codes__mdt/SAP_Store_Codes__mdt.object-meta.xml
<CustomObject>
    <label>SAP Store Codes</label>
    <pluralLabel>SAP Store Codes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SAP_Store_Codes__mdt/fields/New_StoreUniqueId__c.field-meta.xml
<CustomField>
    <fullName>New_StoreUniqueId__c</fullName>
    <label>New StoreUniqueId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Batch_SAPStoreCodeUpdate_Test.cls
/*
 * @Author: Puru
 *
 * Purpose: Test class for 'Batch_SAPStoreCodeUpdate'
 *
 * JIRA NO       UPDATE DATE     UPDATED BY      UPDATE DESCRIPTION
 * -------       -----------     ----------      ------------------
 * NGCSI-1926    Sep-29-2021     Puru            New Class created
 */
@isTest
public class Batch_SAPStoreCodeUpdate_Test{
    @TestSetup
    static void makeData(){
        Account acc = new Account(Name = 'TestAccount');
        insert acc;

        List<Contact> lstConts = new List<Contact>();
        SAP_Store_Codes__mdt TestStoreCode = new SAP_Store_Codes__mdt(MasterLabel = 'T0123', New_StoreUniqueId__c = 'T123');
        //update TestStoreCode;
        for (integer i = 0; i <= 200; i++){
            Contact cont = new Contact(FirstName = 'fName_' + i, LastName = 'lName_' + i, Email = 'testemail_' + i + '@test.com', LoyaltyID__c = 'TH4005340161_' + i, Brand_Id__c = '1', HomeStore__c = 'T0123');
            lstConts.add(cont);
        }

        upsert lstConts;
    }

    static testMethod void testData(){
        List<Contact> lstConts = [Select Id, FirstName, LastName, Email, LoyaltyID__c, Brand_Id__c, HomeStore__c
                                   FROM Contact];
        Test.startTest();
        Batch_SAPStoreCodeUpdate cb = New Batch_SAPStoreCodeUpdate();
        Database.QueryLocator ql = cb.start(null);
        cb.execute(null, lstConts);
        cb.Finish(null);
        Test.stopTest();
    }

}