unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DirectMailOptin__c.field-meta.xml
<CustomField>
    <fullName>DirectMailOptin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Mail Optin</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <formula>IF(ISPICKVAL(SelfClaimedGender__c, &quot;&quot;), 
CASE(TEXT(Account.Gender__c),
&quot;M&quot;,&quot;M&quot;,
&quot;F&quot;,&quot;F&quot;,&quot;None&quot;
),
CASE(TEXT(SelfClaimedGender__c),
&quot;GN&quot;,&quot;GN&quot;,
&quot;M&quot;,&quot;M&quot;,
&quot;PNTS&quot;,&quot;PNTS&quot;,
&quot;F&quot;,&quot;F&quot;,
&quot;NONE&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gender</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>English</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>U</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Zeta_Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>Zeta_Callout_Response__c</fullName>
    <label>Zeta Callout Response</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/ZetaGUID__c.field-meta.xml
<CustomField>
    <fullName>ZetaGUID__c</fullName>
    <label>ZetaGUID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ZetaCustomerCapture.cls
/*
* Task: NASSC-841 [Customer Capture API Callout]
* 
* Objective:  When a customer contact record is directly created in SFSC, SFSC has to make a callout to Zeta and submit the customer data.  
* Zeta will create a corresponding customer record in its system and will return response code.
*
* Date: Oct 2019
*/

global class ZetaCustomerCapture {

    @InvocableMethod(label='FetchContact' description='Inserts the contacts')
    public static void sendCustomerData(List<id> ContactIds) {
        Map<String, string> brandIdToGUID = new Map<String, string>();
        Set<String> brandIds = new Set<String>();
        List<Contact> conObjs = [SELECT Id,  Source__c, Channel__c, FirstName, LastName, Brand_Id__c, Gender__c,
                Zeta_Callout_Response__c
        FROM contact
        WHERE
                id IN :ContactIds];
        if(conObjs.size()>0) {
            for(Contact cc : conObjs) {
                brandIds.add(cc.Brand_Id__c);
            }
            if(brandIds.size()>0) {
                List<LoyaltySettings__mdt> LoyaltySettings = [SELECT BrandId__c,ZetaGUID__c
                FROM LoyaltySettings__mdt
                where BrandId__c IN :brandIds];
                for(LoyaltySettings__mdt LoyaltySetting: LoyaltySettings) {
                    if(LoyaltySetting.ZetaGUID__c != null)
                        brandIdToGUID.put(LoyaltySetting.BrandId__c,LoyaltySetting.ZetaGUID__c);
                }
                if(brandIdToGUID.size()>0) {
                    for(Contact cc : conObjs) {
                        if(brandIdToGUID.containsKey(cc.Brand_Id__c)){
                            System.enqueueJob(new ZetaCustomerCaptureQueueable(cc.id, brandIdToGUID.get(cc.Brand_Id__c)));
                            //makeCallOut(cc.id, brandIdToGUID.get(cc.Brand_Id__c));
                        }
                    }
                }
            }
        }
    }
    
    
    @future (callout=true) 
    public static void makeCallOut(Id contactId, string ZetaGUID) { 
        
        //Log.push('The contact id is::'+contactId+' and zetaguid is::'+ZetaGUID);                 
        Contact contactObj = [SELECT Channel__c, Source__c, CreatedDate, Salutation__c, Gender__c, FirstName, MiddleName,LastName,
                              MailingCity, MailingState, MailingPostalCode, MailingCountry, Birthdate, Email, 
                              HomePhone, Phone, MailingStreet,
                              MobilePhone, DirectMailOptin__c, HomeStore__c, LoyaltyFlag__c,Brand_Id__c, EmailOptInStatus__c,
                              StoreOfCapture__c, Language__c, SMSOptinStatus__c
                              from contact 
                              WHERE id = :contactId];
       
       ZetaCustomerCaptureWrapper objWrapContact = new ZetaCustomerCaptureWrapper(contactObj); 
       String jsB2 = JSON.serialize(objWrapContact);       
       Log.push('serialized string is ==>'+jsB2);
                    
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Zeta');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('iid', ZetaGUID);
        req.setMethod('POST');        
        req.setBody(jsB2);

        Http http = new Http();
        
        try {
            HttpResponse res = http.send(req);
            String returnVal = res.getBody();  
            Log.push('returnVal---->'+res.getBody());
            if(returnVal != null && returnVal != ''){                
                contactObj.Zeta_Callout_Response__c = res.getBody();
                update contactObj;
            }
            //Log.push('response---->'+res.getBody());
        } catch(System.CalloutException e) {
           Logger.logException(e);
        }
        Logger.logDebug();        
    }        
}