unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/IRE_StagingTable__c/IRE_StagingTable__c.object-meta.xml
<CustomObject>
    <label>IRE StagingTable</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRE StagingTable</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/IREDeactivationDate__c.field-meta.xml
<CustomField>
    <fullName>IREDeactivationDate__c</fullName>
    <label>IREDeactivationDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/IREReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>IREReactivationDate__c</fullName>
    <label>IREReactivationDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/MasterCustomerId__c.field-meta.xml
<CustomField>
    <fullName>MasterCustomerId__c</fullName>
    <label>MasterCustomerId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/SubscriberKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriberKey__c</fullName>
    <label>SubscriberKey</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SchedulableBatch_IREStagingTableTest.cls
@isTest(isParallel=false)
public class SchedulableBatch_IREStagingTableTest {
     @testsetup
    static void setup(){
        account acc = new account(name = 'DummyAccount');
        insert acc;
        
        contact con = new contact (lastname='Dummycontact' ,email='test@gmail.com',AccountId=acc.id,Brand_Id__c='1');
        insert con;
        
        IRE_StagingTable__c TestIRE  = new IRE_StagingTable__c(MasterCustomerId__c ='1234567',SubscriberKey__c=con.id,IREDeactivationDate__c=date.parse('01/01/2019'),  IREReactivationDate__c=date.parse('02/02/2019'));
        insert TestIRE;
        Test.setCreatedDate(TestIRE.Id, DateTime.newInstance(2019,06,06));
        
    }
    
    @isTest
    static void scheduleTest(){
        //Dummy CRON expression: midnight on July 25.
        // Because this is a test, job executes
        // immediately after Test.stopTest().
        String CRON_EXP = '0 0 0 25 9 ? 2023';
        Test.startTest();
        String jobId = System.schedule('SchedulableBatch_purgeIREStagingTable15',  CRON_EXP, new SchedulableBatch_purgeIREStagingTable());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest(); 
        ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals('2023-09-25 00:00:00', String.valueOf(ct.NextFireTime));
    }
}