unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>EventDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source from Outside Lists.</description>
    <inlineHelpText>Source from Outside Lists.</inlineHelpText>
    <label>Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LogSignupActivitiesTest.cls
/******************************************************************************
* @Description: Test Class for LogSignupActivities
* @Date		  : April 16, 2020
* @JIRA		  : NASSC-1665
*
******************************************************************************/
@isTest(isParallel=false)
public class LogSignupActivitiesTest {
    
    @isTest
    public static void LogSignUpActivityTest(){
        Contact con = new Contact(Lastname='test', Brand_Id__c='1', Source__c='WE_FOOTER',EventDate__c=System.now(), LoyaltyID__c='TH40000233', StoreOfCapture__c='testcode');
        insert con;
        
        List<LogSignupActivities.SignUpActivityData> ListData = new List<LogSignupActivities.SignUpActivityData>();
        LogSignupActivities.SignUpActivityData objSignUp = new LogSignupActivities.SignUpActivityData();
        objSignUp.ContactId = con.Id;
        objSignUp.eventDate = con.EventDate__c;
        objSignUp.dataSource = con.Source__c;
        objSignUp.BrandId = con.Brand_Id__c;
        objSignUp.loyaltyId = con.LoyaltyID__c;
        objSignUp.StoreCode = con.StoreOfCapture__c;
        ListData.add(objSignUp);
        LogSignupActivities.LogSignUpActivity(ListData);  
    }
}