unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/GenericRecords__c/GenericRecords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Generic Records</label>
</CustomObject>

unpackaged/main/default/objects/GenericRecords__c/fields/recordId__c.field-meta.xml
<CustomField>
    <fullName>recordId__c</fullName>
    <description>Id of the generic record</description>
    <label>recordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestCaseCreatorController.cls
@isTest
public class TestCaseCreatorController {
    
    @isTest
    public static void testCreateSupportCase(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Contact contact = new Contact();
        contact.FirstName = 'testFirst';
        contact.LastName = 'testLast';
        contact.Phone = '8884324322';
        contact.Email= 'test@gmail.com';
        contact.AccountId = acc.id;
        contact.Brand_Id__c='1';
		insert contact;
        GenericRecords__c gr = new GenericRecords__c();
        gr.recordId__c = contact.Id;
        gr.Name ='privacyContact';
        insert gr;
        ApexPages.StandardController sdc = new ApexPages.StandardController(contact);
        CaseCreatorController caseCreatorController = new CaseCreatorController(sdc);
        CaseCreatorController.createSupportCase();//create new case for this contact id
        Case createdCase = [select id from case where ContactId = :contact.id];
        System.assert(createdCase != null);
    }
    
    /*@isTest
    public static void testCreatePrivacyCase(){
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        Contact contact = new Contact();
        contact.FirstName = 'testFirst';
        contact.LastName = 'testLast';
        contact.Phone = '8884324322';
        contact.Email= 'test@gmail.com';
        contact.AccountId = acc.id;
		insert contact;
        ApexPages.StandardController sdc = new ApexPages.StandardController(contact);
        PrivacyCaseCreatorController caseCreatorController = new PrivacyCaseCreatorController(sdc);
        caseCreatorController.createPrivacyCase();//create new case for this contact id
        Case createdCase = [select id from case where ContactId = :contact.id];
        System.assert(createdCase != null);
    }*/

}