unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ecomm_Connected__c.field-meta.xml
<CustomField>
    <fullName>Ecomm_Connected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomm Connected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Loyalty_Optin_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Optin_Date__c</fullName>
    <label>Loyalty Optin Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyMergeDate__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyMergeDate__c</fullName>
    <label>LoyaltyMergeDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/IRE_StagingTable__c/IRE_StagingTable__c.object-meta.xml
<CustomObject>
    <label>IRE StagingTable</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRE StagingTable</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/IREDeactivationDate__c.field-meta.xml
<CustomField>
    <fullName>IREDeactivationDate__c</fullName>
    <label>IREDeactivationDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/IREReactivationDate__c.field-meta.xml
<CustomField>
    <fullName>IREReactivationDate__c</fullName>
    <label>IREReactivationDate</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/MasterCustomerId__c.field-meta.xml
<CustomField>
    <fullName>MasterCustomerId__c</fullName>
    <label>MasterCustomerId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/IRE_StagingTable__c/fields/SubscriberKey__c.field-meta.xml
<CustomField>
    <fullName>SubscriberKey__c</fullName>
    <label>SubscriberKey</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NF_IREStagingTableTriggerHelper.cls
public class NF_IREStagingTableTriggerHelper{
    public static void handleAfterInsert(List<IRE_StagingTable__c> newList){
        List<String> subscriberKeyList = new List<String>();
        Map<String, IRE_StagingTable__c> subkeyToIREMap = new Map<String, IRE_StagingTable__c>();
        List<Contact> contactToUpdateList = new List<Contact>();
        //  Map<String,List<Contact>> subscriberKeyContactMap = new Map<String,List<Contact>>();

        for (IRE_StagingTable__c ireRecord : newList){
            if (ireRecord.SubscriberKey__c != null){
                subscriberKeyList.add(ireRecord.SubscriberKey__c);
                subkeyToIREMap.put(ireRecord.SubscriberKey__c, ireRecord);

            }
        }

        List<Contact> contactList = new List<Contact>();
        if (subscriberKeyList.size() > 0){
            contactList = [SELECT Id, Email, Brand_Id__c, LoyaltyID__c, Loyalty_Optin_Date__c, Ecomm_Connected__c
                           FROM Contact
                           WHERE Id IN:subscriberKeyList];
        }
        if (contactList.size() > 0){
            for (Contact conResult : contactList){
                List<Contact> initialUpdateList = new List<Contact>();
                IRE_StagingTable__c ireRecord = subkeyToIREMap.get(conResult.Id);
                //MGDCTH-442- check if Loyalty id is same-START
                if ((ireRecord.MasterCustomerId__c != null) & (conResult.LoyaltyID__c != null)){
                    if (!(((ireRecord.MasterCustomerId__c.toUpperCase()).equals(conResult.LoyaltyID__c)) || (ireRecord.MasterCustomerId__c.equals(conResult.LoyaltyID__c)))){
                        System.debug('contact will be updated with MasterCustomerId__c');
                        initialUpdateList.add(conResult);

                        /**
                         check if the given conatct is ecomm connected.
                         If not search ecomm connected record with same Email + Brand ID
                         **/

                        if (!(conResult.Ecomm_Connected__c)){
                            List<Contact> contactListForEcomm = new List<Contact>();
                            contactListForEcomm = [SELECT Id, Email, Brand_Id__c, LoyaltyID__c, Loyalty_Optin_Date__c, Ecomm_Connected__c
                                                   FROM Contact
                                                   WHERE Email = :conResult.Email AND Brand_Id__c = :conResult.Brand_Id__c AND Ecomm_Connected__c = True];
                            if (contactListForEcomm.size() > 0){
                                for (Contact ecomContact : contactListForEcomm){

                                    initialUpdateList.add(ecomContact);
                                }

                            }
                        }
                        //MGDCTH-442- check if Loyalty id is same-END
                        for (Contact con : initialUpdateList){
                            con.LoyaltyID__c = ireRecord.MasterCustomerId__c.toUpperCase();
                            if (String.isBlank(String.valueOf(ireRecord.IREDeactivationDate__c)) && String.isNotBlank(String.valueOf(ireRecord.IREReactivationDate__c))){
                                con.LoyaltyMergeDate__c = ireRecord.IREReactivationDate__c;
                            }
                            if (String.isBlank(String.valueOf(ireRecord.IREReactivationDate__c)) && String.isNotBlank(String.valueOf(ireRecord.IREDeactivationDate__c))){
                                con.LoyaltyMergeDate__c = ireRecord.IREDeactivationDate__c;
                            }
                            if (String.isNotBlank(String.valueOf(ireRecord.IREReactivationDate__c)) && String.isNotBlank(String.valueOf(ireRecord.IREDeactivationDate__c))){
                                if (ireRecord.IREDeactivationDate__c > ireRecord.IREReactivationDate__c){
                                    con.LoyaltyMergeDate__c = ireRecord.IREDeactivationDate__c;
                                } else{
                                    con.LoyaltyMergeDate__c = ireRecord.IREReactivationDate__c;
                                }
                            }
                            contactToUpdateList.add(con);
                        }

                    }
                }
            }
        }


        System.debug('***contactToUpdateList:' + contactToUpdateList);
        if (contactToUpdateList.size() > 0){
            Database.SaveResult[] srList = Database.update (contactToUpdateList, false);
            ContactUtility.createErrorLogRecords(srList, 'IRE', newList[0].FileName__c);
        }
    }
}