unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/ExpireDate__c.field-meta.xml
<CustomField>
    <fullName>ExpireDate__c</fullName>
    <label>ExpireDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Reward_Number__c.field-meta.xml
<CustomField>
    <fullName>Reward_Number__c</fullName>
    <formula>LEFT(SequenceNumber__c,(LEN(SequenceNumber__c) - (LEN(SequenceNumber__c) - FIND(LoyaltyId__c, SequenceNumber__c)+1)))</formula>
    <label>Reward Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardType__c.field-meta.xml
<CustomField>
    <fullName>RewardType__c</fullName>
    <label>RewardType</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SFCC_ContactRewardListedResponse.cls
global class SFCC_ContactRewardListedResponse {
      
          //Wrapper class to warp the various  List<sObject> as Super wrapper
      global class supersobjectWrapper{
          List<Reward__c> Rewards=new List<Reward__c>();//A list to hold the Rewards
          List<Contact> Contacts=new List<Contact>();//A list to hold the Contacts  
     }
        
     //This method will be called as the http get request
     public static supersobjectWrapper makeResponseString(){  
         List<Reward__c>  lstRew=new List<Reward__c>();
         List<Contact> lstcontacts=new List<Contact>();
         
         lstRew=[Select Id,LoyaltyId__c, Reward_Number__c, RewardId__c, RewardType__c, 
                                      Status__c,ExpireDate__c
                                      From Reward__c];
         lstcontacts=[Select id,CreatedDate,LastModifiedDate,Isdeleted from Contact];
         
         supersobjectWrapper superWrap=new supersobjectWrapper();//Instantiating thesuperclass
         superWrap.Contacts = lstcontacts ;
         superWrap.Rewards = lstRew;
         
          return superWrap;
         }
}