unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/A1_TrackerAPI_creds__mdt.object-meta.xml
<CustomObject>
    <description>Holds credentials for Agil1&#39;s tracker API.</description>
    <label>A1 TrackerAPI creds</label>
    <pluralLabel>A1 TrackerAPI creds</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/Base64__c.field-meta.xml
<CustomField>
    <fullName>Base64__c</fullName>
    <label>Base64</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/TenantId__c.field-meta.xml
<CustomField>
    <fullName>TenantId__c</fullName>
    <label>TenantId</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/A1_TrackerAPI_creds__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AccuralPeriods__mdt/AccuralPeriods__mdt.object-meta.xml
<CustomObject>
    <label>Accural Periods</label>
    <pluralLabel>Accural Periods</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AccuralPeriods__mdt/fields/AccuralPeriod__c.field-meta.xml
<CustomField>
    <fullName>AccuralPeriod__c</fullName>
    <description>Name of accrual period. ex: &quot;20190204-20200202&quot;</description>
    <label>Accural Period</label>
    <length>17</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/AccuralPeriods__mdt/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>day before the start date of next year.</description>
    <label>EndDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/AccuralPeriods__mdt/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Start date of accrual period. 4th monday of the year.</description>
    <label>StartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/LoyaltyComments__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyComments__c</fullName>
    <label>Loyalty Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/NFCaseScenario__c.field-meta.xml
<CustomField>
    <fullName>NFCaseScenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to categorize the Case</description>
    <label>Case Scenario</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NF_Case_Scenario__c.NFActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NF_Case_Scenario__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PointsAdjustmentTimeStamp__c.field-meta.xml
<CustomField>
    <fullName>PointsAdjustmentTimeStamp__c</fullName>
    <label>Points Adjustment TimeStamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PointsGranted__c.field-meta.xml
<CustomField>
    <fullName>PointsGranted__c</fullName>
    <label>Points</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_Case_Scenario__c/NF_Case_Scenario__c.object-meta.xml
<CustomObject>
    <description>Used to categorize Cases</description>
    <label>Case Scenario</label>
    <nameField>
        <label>Case Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NF_Case_Scenario__c/fields/NF_Scenario__c.field-meta.xml
<CustomField>
    <fullName>NF_Scenario__c</fullName>
    <description>Returns the Scenario (string to the right of the colon) of a Case Scenario&#39;s name for reporting, list views, etc.</description>
    <formula>RIGHT(Name, (LEN(Name)-(FIND(&#39;: &#39;, Name))))</formula>
    <label>Scenario</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_Case_Scenario__c/fields/NFScenarioCategory__c.field-meta.xml
<CustomField>
    <fullName>NFScenarioCategory__c</fullName>
    <description>Returns the Category (string to the left of the colon) of a Case Scenario&#39;s name for reporting, list views, etc.</description>
    <formula>LEFT( Name , (FIND(&#39;:&#39;, Name)-1))</formula>
    <label>Scenario Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/A1TrackerAPIPoints.cls
/******************************************************************************
* @Description:Makes callout to posts the points data to Agil1’s trackerAPI as an event.
* @Author     : Dhiren 
* @Date       : 01:01.2020
* @JIRA       : NASSC-1182
*
******************************************************************************/ 

public class A1TrackerAPIPoints {
    
    @TestVisible
    private class Events {
        public String Type {get;set;} 
        public String Subtype {get;set;} 
        public String EventTimeStamp {get;set;} 
        public String c_pointsGranted {get;set;} 
        public String c_accrualPeriod {get;set;} 
        public String c_sfscCaseNumber {get;set;} 
        public String c_sfscComments {get;set;} 
        public String c_sfscReasonCode {get;set;} 
        public String c_sfscAgentId {get;set;} 
        public String SourceCustomerNumber {get;set;} 
        public String CustomerID {get;set;} 
        public String Cookie {get;set;} 
    }
    
    @TestVisible
    private class Customers {
        public String SourceCustomerNumber {get;set;} 
        public String c_loyaltyid {get;set;} 
        public String c_loyaltyFlag {get;set;}
        public String ID {get;set;} 
        public String Email {get;set;} 
    }
    
    
    @InvocableMethod(label='A1 Tracker Api' description='Post Tracker API Points')
    public static void invokePostTrackerAPIPoints(List<Id> CaseIds) {
        Log.push('invokePostTrackerAPIPoints called');
        Id CaseId = CaseIds[0];
        futurePostTrackerAPIEvents(CaseId);
        Logger.logDebug();
    }
    
    @future(callout=true)
    public static void futurePostTrackerAPIEvents(Id CaseId){
        Log.push('futurePostTrackerAPIEvents called');
        Map<String,String> LoyaltyMap = new Map<String,String>(); 
        List<Case> CaseList = [SELECT Id, CaseNumber, NFCaseScenario__r.NFScenarioCategory__c, NFCaseScenario__r.NF_Scenario__c, LoyaltyComments__c, PointsGranted__c, PointsAdjustmentTimeStamp__c, OwnerId, NFCaseScenario__c, Contact.Brand_Id__c, Contact.LoyaltyID__c,Contact.LoyaltyFlag__c,Contact.Email,Owner.FirstName,Owner.LastName
                               FROM Case 
                               WHERE Id=:CaseId LIMIT 1];

        Log.push('CaseList:'+CaseList);
        
        List<AccuralPeriods__mdt> accualPeriod = [SELECT Id,MasterLabel, AccuralPeriod__c, EndDate__c, StartDate__c 
                                                  FROM AccuralPeriods__mdt
                                                  WHERE StartDate__c <= :Date.today() and EndDate__c >= :Date.today()];
        Log.push('accualPeriod:'+accualPeriod);
        
        //if records brand is child, assigning brandId with its parent
        //fetching loyalty MDT
        List<LoyaltySettings__mdt> loyaltyList = [Select Id, BrandId__c, Parent_Brand__c from LoyaltySettings__mdt];
        for(LoyaltySettings__mdt loyalRecord : loyaltyList){
            if(loyalRecord.Parent_Brand__c != null){
            	LoyaltyMap.put(loyalRecord.BrandId__c,loyalRecord.Parent_Brand__c);
            }
        }
        Log.push('***Posting Loyalty Map = '+LoyaltyMap);
        String brandIdToPass = CaseList[0].Contact.Brand_Id__c;
        
        //if records brand is child, assigning brandId with its parent
        if(LoyaltyMap.containsKey(brandIdToPass)){
            Log.push('***changing brandIdToPass: subBrand to parentBrand');
            brandIdToPass = LoyaltyMap.get(brandIdToPass);
        }
        Log.push('***brandIdToPass = '+brandIdToPass);
        
        List<A1_TrackerAPI_creds__mdt> creds =[SELECT Id,MasterLabel, Base64__c, BrandId__c, Password__c, Username__c, TenantId__c 
                                               FROM A1_TrackerAPI_creds__mdt
                                               WHERE BrandId__c =: brandIdToPass];
        Log.push('creds:'+creds);
        if(!creds.isEmpty()){
            Events eve = new Events();
            eve.Type='points';
            eve.Subtype='customerServiceAdhocGrant';
       //     eve.EventTimeStamp=String.valueOf(CaseList[0].PointsAdjustmentTimeStamp__c.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.000\'Z\''));
            eve.EventTimeStamp=String.valueOf(CaseList[0].PointsAdjustmentTimeStamp__c.getTime());
            eve.c_pointsGranted=String.valueOf(CaseList[0].PointsGranted__c);
            eve.c_accrualPeriod = accualPeriod[0].AccuralPeriod__c;
            eve.c_sfscCaseNumber = CaseList[0].CaseNumber;
            eve.c_sfscComments = CaseList[0].LoyaltyComments__c;
            eve.c_sfscReasonCode = CaseList[0].NFCaseScenario__r.NFScenarioCategory__c;
            eve.c_sfscAgentId = (CaseList[0].Owner.FirstName+CaseList[0].Owner.LastName).toLowerCase();
            eve.SourceCustomerNumber = CaseList[0].Contact.LoyaltyID__c;
            eve.CustomerID = CaseList[0].Contact.LoyaltyID__c;
            eve.Cookie = '';
            Log.push('eve:'+eve);

            Customers cust = new Customers();
            cust.SourceCustomerNumber = CaseList[0].Contact.LoyaltyID__c;
            cust.c_loyaltyid = CaseList[0].Contact.LoyaltyID__c;
            cust.ID = CaseList[0].Contact.LoyaltyID__c;
            if (CaseList[0].Contact.LoyaltyFlag__c!=null && CaseList[0].Contact.LoyaltyFlag__c) cust.c_loyaltyFlag = 'Yes';
            cust.Email = CaseList[0].Contact.Email;
            Log.push('cust:'+cust);
            String body = String.valueOf('{"events" :['+JSON.serialize(eve)+'], "customers" : ['+JSON.serialize(cust)+']}');
            //String body = String.valueOf('"events" :['+JSON.serialize(eve)+'], "customers" : ['+JSON.serialize(cust)+']');
            Log.push('body:'+body);
            String trackerAccKey = AgileOne.getTrackerAPIAccesskey(creds[0]);
            Log.push('***AccessKey = '+trackerAccKey);
            //String trackerAccKey = '2a$10$QbZVzccFtgdNW49AekLpWOMQuNXw.RVQMKEkTqHiGO52UluqDjXg2';
            String reqEndPoint = 'callout:A1_TrackerAPI_DataEndPoint/'+creds[0].TenantId__c+'/dw/tracker?scheme=a1webtag&accessKey='+trackerAccKey;
            Log.push('httpCalloutMethod called');

            String responseString = Null;
            HttpRequest req = new HttpRequest();
            req.setHeader('Content-Type', 'application/json');
            req.setBody(body);
            req.setEndpoint(reqEndPoint);
            req.setMethod(SYSTEM.LABEL.POST);
            Log.push('reqEndPoint '+reqEndPoint);
            Http http = new Http();
            try{
                HttpResponse res = http.send(req);
                Log.push('***response body:'+res.getBody());
                responseString = res.getBody();

            }catch(System.CalloutException e) {
                Log.push('Callout error: '+ e);
            }
        }
        Logger.logDebug();
    }
        
}