unpackaged/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event to create Log records.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Log_Event__e/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Contains the class name</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Log_Event__e/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Contains the method name</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/StackTraceUtility.cls
/*
* @Author: Apoorv (NeuraFlash)
* @CreatedDate: May'21, 2020
* @Description: Utility class to extract class & method name from the exception stack trace. 
*/

public with sharing class StackTraceUtility {

    private static final String ORG_NAMESPACE = [SELECT NamespacePrefix FROM Organization].NamespacePrefix;
    private static final Pattern STACK_LINE = Pattern.compile('^(?:Class\\.)?([^.]+)\\.?([^\\.\\:]+)?[\\.\\:]?([^\\.\\:]*): line (\\d+), column (\\d+)$');
    
    public static void populateClassAndMethodName(Log_Event__e logEvent, String stackTraceString){
        List<String> stacktrace = stackTraceString.split('\n');

		for(String line : stacktrace) {
			Matcher matcher = STACK_LINE.matcher(line);
			if(matcher.find() && !line.startsWith('Class.System.')){
				Boolean hasNamespace = String.isNotBlank(matcher.group(3));
				if(hasNamespace) {
					logEvent.Class_Name__c = (matcher.group(1).equals(ORG_NAMESPACE)) ? matcher.group(2) : matcher.group(1) + '.' + matcher.group(2);
					logEvent.Method_Name__c = getMethodName(matcher.group(3));
				} else {
					logEvent.Class_Name__c = matcher.group(1);
					logEvent.Method_Name__c = getMethodName(matcher.group(2));
				}
				return;
			}
		}
    }

    private static String getMethodName(String method) {
		String methodName = (method == null) ? 'anonymous' : method;
		return (methodName.contains('init')) ? 'constructor' : methodName;
    }
}