unpackaged/main/default/objects/Brand_Setting__mdt/Brand_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Email__c.field-meta.xml
<CustomField>
    <fullName>Brand_Email__c</fullName>
    <label>Brand Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Setting__mdt/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand Id</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand_Privacy_Email__c.field-meta.xml
<CustomField>
    <fullName>Brand_Privacy_Email__c</fullName>
    <description>Controlled By Account - Email Address for the Brand&#39;s Privacy Email Communications</description>
    <label>Brand Privacy Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Availability Questions</fullName>
            </value>
            <value>
                <fullName>Quality Concerns</fullName>
            </value>
            <value>
                <fullName>Sizing Questions</fullName>
            </value>
            <value>
                <fullName>Care Instructions</fullName>
            </value>
            <value>
                <fullName>Product Feedback</fullName>
            </value>
            <value>
                <fullName>Problem Placing Order</fullName>
            </value>
            <value>
                <fullName>Tracking Order Shipment</fullName>
            </value>
            <value>
                <fullName>Edit Existing Order</fullName>
            </value>
            <value>
                <fullName>Cancel Order</fullName>
            </value>
            <value>
                <fullName>Missing/Damaged Product</fullName>
            </value>
            <value>
                <fullName>Return Policy</fullName>
            </value>
            <value>
                <fullName>Returning Order</fullName>
            </value>
            <value>
                <fullName>Creating Return Label</fullName>
            </value>
            <value>
                <fullName>Tracking Return</fullName>
            </value>
            <value>
                <fullName>Return Status</fullName>
            </value>
            <value>
                <fullName>Signing Up</fullName>
            </value>
            <value>
                <fullName>Program Questions</fullName>
            </value>
            <value>
                <fullName>Adding Points</fullName>
            </value>
            <value>
                <fullName>Redeeming Rewards</fullName>
            </value>
            <value>
                <fullName>Account Balance</fullName>
            </value>
            <value>
                <fullName>Password Reset</fullName>
            </value>
            <value>
                <fullName>Update Information</fullName>
            </value>
            <value>
                <fullName>Problem Receiving</fullName>
            </value>
            <value>
                <fullName>Unsubscribe</fullName>
            </value>
            <value>
                <fullName>Access My Data</fullName>
            </value>
            <value>
                <fullName>Delete My Data</fullName>
            </value>
            <value>
                <fullName>Data Owner Request</fullName>
            </value>
            <value>
                <fullName>Privacy Email</fullName>
            </value>
            <value>
                <fullName>Rectify My Data</fullName>
            </value>
            <value>
                <fullName>Do Not Sell/Share</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EmailPublisherLoader.cls
global class EmailPublisherLoader implements QuickAction.QuickActionDefaultsHandler {
    // Empty constructor
    global EmailPublisherLoader() {
    }

    // The main interface method
    global void onInitDefaults(QuickAction.QuickActionDefaults[] defaults) {
        system.debug('*** SETTING DEFAULTS ***');
        QuickAction.SendEmailQuickActionDefaults sendEmailDefaults = null;


        // Check if the quick action is the standard case feed Send Email action
        system.debug('*** DEFAULTS *** '+defaults);
        for (Integer j = 0; j < defaults.size(); j++) {
            if (defaults.get(j) instanceof QuickAction.SendEmailQuickActionDefaults &&
                    defaults.get(j).getTargetSObject().getSObjectType() ==
                            EmailMessage.sObjectType &&
                    defaults.get(j).getActionName().equals('Case.SendEmail') &&
                    defaults.get(j).getActionType().equals('SendEmail')) {
                sendEmailDefaults =
                        (QuickAction.SendEmailQuickActionDefaults)defaults.get(j);
                break;
            }
        }
        system.debug('*** DEFAULTS *** '+sendEmailDefaults);

        if (sendEmailDefaults != null) {
            system.debug('*** UPDATING DEFAULTS *** ');
            Case c = [SELECT Status, Reason, Brand__c, RecordTypeId, Type, Sub_Type__c, Brand_Privacy_Email__c FROM Case
            WHERE Id=:sendEmailDefaults.getContextId()];
            system.debug('*** CASE ID *** '+c.Id);
			If (c.RecordTypeId == Constants.privacyRecordTypeId || c.RecordTypeId == Constants.dataOwnerCaseRecordTypeId || c.Type == Constants.privacyCaseType || c.Sub_Type__c == Constants.unsubscribeRequestSubType)
			{
                EmailMessage emailMessage = (EmailMessage)sendEmailDefaults.getTargetSObject();
                emailMessage.ValidatedFromAddress = c.Brand_Privacy_Email__c;
				 //Add any logic specific to Privacy Requests here
			}
			else 
			{
				EmailMessage emailMessage = (EmailMessage)sendEmailDefaults.getTargetSObject();
				// Set BCC address to make sure each email goes for audit
				try{
					Brand_Setting__mdt bs = [Select MasterLabel, DeveloperName, Brand_Email__c  from Brand_Setting__mdt where Brand_Id__c = :c.Brand__c];
					emailMessage.ValidatedFromAddress = bs.Brand_Email__c;
				} catch(QueryException e) {
					system.debug('*** EmailPublisherLoader - Exception raised setting validated From Address *** '+c.Id);
				}
			}
        }
    }

    private Id getTemplateIdHelper(String templateApiName) {
        Id templateId = null;
        try {
            templateId = [select id, name from EmailTemplate
            where developername = : templateApiName].id;
        } catch (Exception e) {
            system.debug('Unble to locate EmailTemplate using name: ' +
                    templateApiName + ' refer to Setup | Communications Templates '
                    + templateApiName);
        }
        return templateId;
    }
    private String getBccAddress(String reason) {
        if (reason != null && reason.equals('Technical'))
        { return 'support_technical@mycompany.com'; }
        else if (reason != null && reason.equals('Billing'))
        { return 'support_billing@mycompany.com'; }
        else { return 'support@mycompany.com'; }
    }


}