unpackaged/main/default/objects/A1_RewardTypes__mdt/A1_RewardTypes__mdt.object-meta.xml
<CustomObject>
    <description>Purpose of this MDT is to store the reward type vs reward description mapping per each brand.</description>
    <label>A1_RewardTypes</label>
    <pluralLabel>A1_RewardTypes</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/A1_RewardTypes__mdt/fields/RewardType__c.field-meta.xml
<CustomField>
    <fullName>RewardType__c</fullName>
    <label>RewardType</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RewardId</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyID__c</fullName>
    <label>Loyalty ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/Parent_Brand__c.field-meta.xml
<CustomField>
    <fullName>Parent_Brand__c</fullName>
    <label>Parent Brand</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reward__c/fields/Expire_Date_form__c.field-meta.xml
<CustomField>
    <fullName>Expire_Date_form__c</fullName>
    <formula>DATEVALUE(ExpireDate__c) + 1</formula>
    <label>Expire Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/ExpireDate__c.field-meta.xml
<CustomField>
    <fullName>ExpireDate__c</fullName>
    <label>ExpireDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <externalId>true</externalId>
    <label>LoyaltyId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardId__c.field-meta.xml
<CustomField>
    <fullName>RewardId__c</fullName>
    <externalId>true</externalId>
    <label>RewardId</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/RewardType__c.field-meta.xml
<CustomField>
    <fullName>RewardType__c</fullName>
    <label>RewardType</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Redeemed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Redeemed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reward__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/A1_RewardsDataApexController.cls
/******************************************************************************
* @Description: Show Rewards Data to Case and Contact Page
* @Author	  : Rounak P
* @Date		  : 26:12.2019
* @JIRA		  : NASSC-1176,1178,1180
*
******************************************************************************/ 


public without sharing class A1_RewardsDataApexController {

    @AuraEnabled
    public static List<RewardWrapper> getLoyaltyId(Id recordIds) {
        
        Map<String,String> LoyaltyMap = new Map<String,String>();
        
        Contact conRecord;
        Case caseRecord;
        String brandId;
		List<Reward__c> listRewards = new List<Reward__c>();       
        Schema.SObjectType token = recordIds.getSObjectType();
        Schema.DescribeSObjectResult dr = token.getDescribe();
		System.debug('Name = '+dr.getName());
       
        // fetching loyalty MDT
        List<LoyaltySettings__mdt> loyaltyList = [Select Id, BrandId__c, Parent_Brand__c from LoyaltySettings__mdt];
        for(LoyaltySettings__mdt loyalRecord : loyaltyList){
            if(loyalRecord.Parent_Brand__c != null){
            	LoyaltyMap.put(loyalRecord.BrandId__c,loyalRecord.Parent_Brand__c);
            }
        }
        System.debug('Loyalty Map = '+LoyaltyMap);
        
        
        if(dr.getName().equals('Contact')){
            conRecord = [Select LoyaltyID__c,Brand_Id__c from Contact WHERE Id=:recordIds];
            brandId = conRecord.Brand_Id__c;
        }
        else if(dr.getName().equals('Case')){
            caseRecord = [Select Contact.LoyaltyID__c,Contact.Brand_Id__c from Case WHERE Id=:recordIds];
            brandId = caseRecord.Contact.Brand_Id__c;
        }       
        
        //if records brand is child, assigning brandId with its parent
        if(LoyaltyMap.containsKey(brandId)){
            brandId = LoyaltyMap.get(brandId);
        }
        
        //System.debug('Loyalty Id = '+conRecord.LoyaltyID__c);
        //System.debug('Actual BrandId = '+conRecord.Brand_Id__c);
        //System.debug('Updated BrandId = '+brandId);
        
        //System.debug('Loyalty Id = '+caseRecord.Contact.LoyaltyID__c);
        //System.debug('Brand Id = '+caseRecord.Contact.Brand_Id__c);
        
        if(conRecord!=null && conRecord.LoyaltyID__c !=null){
             listRewards = AgileOne.getRewardsData(conRecord.LoyaltyID__c);
        }
        else if(caseRecord!=null && caseRecord.Contact.LoyaltyID__c !=null){
             listRewards = AgileOne.getRewardsData(caseRecord.Contact.LoyaltyID__c);
        }
        
        Map<String,String> metadataMap = new Map<String,String>();
        Set<String> rewType = new Set<String>();
	    for(Reward__c rew : listRewards)
        {
			rewType.add(rew.RewardType__c);
        }

        List<A1_RewardTypes__mdt> rewardMetadata = [Select Description__c,RewardType__c from A1_RewardTypes__mdt WHERE BrandId__c=:brandId AND RewardType__c IN : rewType];
        for(A1_RewardTypes__mdt meta : rewardMetadata){
            metadataMap.put(meta.RewardType__c,meta.Description__c);
        }
        
        
      List<RewardWrapper> wrapperlist = new List<RewardWrapper>();
      for(Reward__c rew : listRewards){
           RewardWrapper wrapperObj = new RewardWrapper();
           wrapperObj.rewardId = rew.RewardId__c;
           wrapperObj.transactionId = rew.TransactionId__c;
           wrapperObj.status = rew.Status__c;
           wrapperObj.description = metadataMap.get(rew.RewardType__c);
           System.debug('***Get BackEnd ExpireDate__c = '+rew.ExpireDate__c);
           //Date expDate = rew.Expire_Date_form__c;
          
           String getExpireDateString = DateTime.newInstance(rew.ExpireDate__c.year(),rew.ExpireDate__c.month(),rew.ExpireDate__c.day()).format('yyyy-MM-dd');
		   System.debug('***Expire_Date_form__c AS String = '+getExpireDateString);
           wrapperObj.expireDate = getExpireDateString;
           wrapperlist.add(wrapperObj);
        }
      System.debug('***Final Data = '+wrapperlist);
      return wrapperlist;
    }
    
 public class RewardWrapper {
       	@AuraEnabled
        public String rewardId { get; set; }
        @AuraEnabled
        public String transactionId { get; set; }
        @AuraEnabled
        public String description { get; set; }
        @AuraEnabled
        public String status { get; set; }
     	@AuraEnabled
        public String expireDate { get; set; }
		}
}