unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/Community_Footer_Copyright_Area_Items__mdt.object-meta.xml
<CustomObject>
    <description>Stores the URL or text that is displayed in the copyright section of the footer area of the community, specific to each brand.</description>
    <label>Community Footer Copyright Area Items</label>
    <pluralLabel>Community Footer Copyright Area Items</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <referenceTo>Webform_Brands__mdt</referenceTo>
    <relationshipLabel>Community Footer Copyright Area Items</relationshipLabel>
    <relationshipName>Community_Footer_Copyright_Area_Items</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/fields/Item_SequenceNo__c.field-meta.xml
<CustomField>
    <fullName>Item_SequenceNo__c</fullName>
    <label>Item SequenceNo.</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/fields/Open_In_New_Tab__c.field-meta.xml
<CustomField>
    <fullName>Open_In_New_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Open_In_New_Tab</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Copyright_Area_Items__mdt/fields/Row_SequenceNo__c.field-meta.xml
<CustomField>
    <fullName>Row_SequenceNo__c</fullName>
    <label>Row SequenceNo.</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/Community_Footer_Items__mdt.object-meta.xml
<CustomObject>
    <description>Stores the URL or text that is displayed in the footer of the community, specific to each brand.</description>
    <label>Community Footer Items</label>
    <pluralLabel>Community_Footer_Items</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Stores the Name of the Brand</description>
    <label>Brand</label>
    <referenceTo>Webform_Brands__mdt</referenceTo>
    <relationshipName>Community_Footer_Data</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>Stores the column header label</description>
    <label>Header</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Header_SequenceNo__c.field-meta.xml
<CustomField>
    <fullName>Header_SequenceNo__c</fullName>
    <label>Header SequenceNo.</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Item_SequenceNo__c.field-meta.xml
<CustomField>
    <fullName>Item_SequenceNo__c</fullName>
    <label>Item SequenceNo.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Stores the label of the items in the footer</description>
    <label>Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Open_In_New_Tab__c.field-meta.xml
<CustomField>
    <fullName>Open_In_New_Tab__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether or not to open the URL in a new tab</description>
    <label>Open_In_New_Tab</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Community_Footer_Items__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Stores the value of the footer items i.e, URL, text, number, etc.</description>
    <label>Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Webform_Brands__mdt/Webform_Brands__mdt.object-meta.xml
<CustomObject>
    <label>Brand Form - Brand</label>
    <pluralLabel>Brand Form - Brands</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Webform_Brands__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <description>Stores the name of the brands</description>
    <label>Brand_Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tommy Hilfiger</fullName>
                <default>true</default>
                <label>Tommy Hilfiger</label>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>True&amp;Co.</fullName>
            </value>
            <value>
                <fullName>Warner</fullName>
            </value>
            <value>
                <fullName>Olga</fullName>
            </value>
            <value>
                <fullName>Calvin Klein - CA</fullName>
            </value>
            <value>
                <fullName>Warner&#39;s</fullName>
                <isActive>false</isActive>
                <label>Warner&#39;s</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/pvhCommunityFooterController.cls
public class pvhCommunityFooterController {

    @AuraEnabled(cacheable = true)
    public static Map<String, List<Community_Footer_Items__mdt>> getFooterData(String brandName) {
        try {
             Map<String, List<Community_Footer_Items__mdt>> mapFooterLabelToValue = new Map<String, List<Community_Footer_Items__mdt>>();
             for(Community_Footer_Items__mdt eachData : [SELECT Brand__c, Brand__r.Brand_Name__c, Name__c, Value__c,
                                                            Header__c, Item_SequenceNo__c, Open_In_New_Tab__c, Header_SequenceNo__c
                                                                FROM Community_Footer_Items__mdt 
                                                                    WHERE Brand__r.MasterLabel =: brandName
                                                                        ORDER BY Header_SequenceNo__c, Item_SequenceNo__c ASC]) {
                
                if(mapFooterLabelToValue.containsKey(eachData.Header__c)) {
                    List<Community_Footer_Items__mdt> lstTempMdt = mapFooterLabelToValue.get(eachData.Header__c);
                    lstTempMdt.add(eachData);
                    mapFooterLabelToValue.put(eachData.Header__c, lstTempMdt);
                } else {
                    mapFooterLabelToValue.put(eachData.Header__c, new List<Community_Footer_Items__mdt>{eachData});
                }
            } 
            if(!mapFooterLabelToValue.keySet().isEmpty()) return mapFooterLabelToValue; 
        } catch(Exception ex) {
            System.debug('Exception :::'+ ex.getMessage());
        }
        return null;
    }

    @AuraEnabled(cacheable = true)
    public static Map<Integer, List<Community_Footer_Copyright_Area_Items__mdt>> getFooterCopyrightAreaData(String brandName) {
        try {
            Map<Integer, List<Community_Footer_Copyright_Area_Items__mdt>> mapLabelToValue = new Map<Integer, List<Community_Footer_Copyright_Area_Items__mdt>>();
             for(Community_Footer_Copyright_Area_Items__mdt eachData : [SELECT Brand__c, Brand__r.Brand_Name__c, Name__c, Value__c,
                                                                             Open_In_New_Tab__c, Row_SequenceNo__c,Item_SequenceNo__c
                                                                                FROM Community_Footer_Copyright_Area_Items__mdt 
                                                                                    WHERE Brand__r.MasterLabel =: brandName
                                                                                        ORDER BY Row_SequenceNo__c, Item_SequenceNo__c DESC]) {
                
                if(mapLabelToValue.containsKey(Integer.valueOf(eachData.Row_SequenceNo__c))) {
                    List<Community_Footer_Copyright_Area_Items__mdt> lstTempMdt = mapLabelToValue.get(Integer.valueOf(eachData.Row_SequenceNo__c));
                    lstTempMdt.add(eachData);
                    mapLabelToValue.put(Integer.valueOf(eachData.Row_SequenceNo__c), lstTempMdt);
                } else {
                    mapLabelToValue.put(Integer.valueOf(eachData.Row_SequenceNo__c), new List<Community_Footer_Copyright_Area_Items__mdt>{eachData});
                }
            } 
            System.debug('-- checking data--'+mapLabelToValue);
            if(!mapLabelToValue.keySet().isEmpty()) return mapLabelToValue; 
        } catch(Exception ex) {
            System.debug('Exception :::'+ ex.getMessage());
        }
        return null;
    } 
}