unpackaged/main/default/objects/NF_Banner__c/NF_Banner__c.object-meta.xml
<CustomObject>
    <label>Portal Banner</label>
    <nameField>
        <label>Portal Banner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Banners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/NF_Banner__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines weather this message is active or not</description>
    <inlineHelpText>Determines weather this message is active or not</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>This is the brand id</description>
    <inlineHelpText>This is the brand id</inlineHelpText>
    <label>Brand Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/DateEnd__c.field-meta.xml
<CustomField>
    <fullName>DateEnd__c</fullName>
    <defaultValue>TODAY()+1</defaultValue>
    <description>This is the date where the message will stop being displayed.</description>
    <inlineHelpText>This is the date where the message will stop being displayed.</inlineHelpText>
    <label>Date End</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/DateStart__c.field-meta.xml
<CustomField>
    <fullName>DateStart__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>This is the date when the Message will start to appear.</description>
    <inlineHelpText>This is the date when the Message will start to appear.</inlineHelpText>
    <label>Date Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/DisplayonHomepageorTopic__c.field-meta.xml
<CustomField>
    <fullName>DisplayonHomepageorTopic__c</fullName>
    <description>What page should this be displayed:

Home -  home page of the community / portal / digital experience
Topic - Certain Topic Page along with any articles that lookup to this topic.</description>
    <inlineHelpText>What page should this be displayed:

Home -  home page of the community / portal / digital experience
Topic - Certain Topic Page along with any articles that lookup to this topic.</inlineHelpText>
    <label>Where should this go?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Topic</fullName>
            </value>
            <value>
                <fullName>Custom Page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/ImageFile__c.field-meta.xml
<CustomField>
    <fullName>ImageFile__c</fullName>
    <description>This is used to display any image.</description>
    <inlineHelpText>This is used to display any image.</inlineHelpText>
    <label>Image File</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>This is the message that will be shown in the banner.</description>
    <inlineHelpText>This is the message that will be shown in the banner.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/PageKey__c.field-meta.xml
<CustomField>
    <fullName>PageKey__c</fullName>
    <description>This is the page key when selecting the custom page.</description>
    <inlineHelpText>This is the page key when selecting the custom page.</inlineHelpText>
    <label>Page Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_Banner__c/fields/TopicId__c.field-meta.xml
<CustomField>
    <fullName>TopicId__c</fullName>
    <description>This is the topic id, this is needed if we choose the choice to display this in topic pages.</description>
    <inlineHelpText>This is the topic id, this is needed if we choose the choice to display this in topic pages.</inlineHelpText>
    <label>Topic Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_BannerSystemController.cls
/**
 * @description       : Controller to be used in the NF Banner System
 * @author            : Luis Rocha
 * @last modified on  : 06-21-2021
 * @last modified by  : Luis Rocha
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   06-21-2021   Luis Rocha   Initial Version
**/
public without sharing class NF_BannerSystemController {

    /**
    * @description retrieve all brands (Netowrks)
    * @author Luis Rocha | 06-21-2021 
    * @return List<Network> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Network> getBrandList() {
        return [SELECT Name FROM Network];
    }
    
    /**
    * @description 
    * @author Luis Rocha | 06-21-2021 
    * @return List<NF_Banner__c> a list of the custom object banner
    **/
    @AuraEnabled(cacheable=true)
    public static List<NF_Banner__c> getAllMessages(){
        try {
            List<NF_Banner__c> listOfMessages = [SELECT Message__c, 
                Brand__c,
                DateStart__c, 
                DateEnd__c, 
                Active__c,
                DisplayonHomepageorTopic__c,
                TopicId__c,
                ImageFile__c
            FROM NF_Banner__c
            WHERE Active__c = true 
            AND DateStart__c <=: System.Today()
            AND DateEnd__c >= Today
            AND Brand__c != null];
            return listOfMessages;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description 
    * @author Luis Rocha | 06-21-2021 
    * @param pageKey 
    * @return List<NF_Banner__c> a list of the custom object banner
    **/
    @AuraEnabled(cacheable=true)
    public static List<NF_Banner__c> getAllMessages(String pageKey){
        try {
            List<NF_Banner__c> listOfMessages = [SELECT Message__c, 
                Brand__c,
                DateStart__c, 
                DateEnd__c, 
                Active__c,
                DisplayonHomepageorTopic__c,
                TopicId__c,
                ImageFile__c,
                PageKey__c
            FROM NF_Banner__c
            WHERE Active__c = true 
            AND DateStart__c <=: System.Today()
            AND DateEnd__c >= Today
            AND PageKey__c =: pageKey
            AND Brand__c != null];
            return listOfMessages;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * @description 
    * @author Luis Rocha | 06-21-2021 
    * @param homeOrTopic 
    * @param recordId 
    * @param pageKey 
    * @return List<NF_Banner__c> a list of the custom object banner
    **/
    @AuraEnabled(cacheable=true)
    public static List<NF_Banner__c> getMessages(String homeOrTopic, String recordId, String pageKey){
        try {
            if(homeOrTopic == 'Home' || homeOrTopic == 'Topic'){
                return getAllMessages();
            } else if(homeOrTopic == 'custompage'){
                return getAllMessages(pageKey); 
            } else {
                List<TopicAssignment> listOfTopicAssignment = [SELECT EntityId, 
                        TopicId 
                    FROM TopicAssignment 
                    WHERE EntityId =: recordId];
                
                Set<Id> setOfTopicIds = new Set<Id>();
                for(TopicAssignment topicAssignment : listOfTopicAssignment ){
                    setOfTopicIds.add(topicAssignment.TopicId);
                }

                List<NF_Banner__c> listOfMessages = [SELECT Message__c, 
                    Brand__c,
                    DateStart__c, 
                    DateEnd__c, 
                    Active__c,
                    DisplayonHomepageorTopic__c,
                    TopicId__c,
                    ImageFile__c
                FROM NF_Banner__c
                WHERE Active__c = true 
                AND DateStart__c <=: System.Today()
                AND DateEnd__c >= Today
                AND TopicId__c in : setOfTopicIds];
                
                return listOfMessages;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description Retrieve all topics that have a network attached to it. 
    * @author Luis Rocha | 06-21-2021 
    * @return List<Topic> a list of all topics that have a brand attached to it. 
    **/
    @AuraEnabled(cacheable=true)
    public static List<Topic> getTopicList() {
        return [SELECT Name, NetworkId FROM Topic WHERE NetworkId != null];
    }

    /**
    * @description : Retrieves the Brands and Topics
    * @author Luis Rocha | 06-21-2021 
    * @return BrandAndTopicWrapper the wrapper including both the topics and brands 
    **/
    @AuraEnabled(cacheable=true)
    public static BrandAndTopicWrapper getBrandsAndTopics() {
        BrandAndTopicWrapper batw = new BrandAndTopicWrapper();
        batw.topics = getTopicList();
        batw.brands = getBrandList();
        return batw;
    }

    // wrapper class with @AuraEnabled and {get;set;} properties 
    public class BrandAndTopicWrapper{
        @AuraEnabled
        public List<Topic>  topics{get;set;}
        @AuraEnabled
        public List<Network>  brands{get;set;}
    }
}