unpackaged/main/default/objects/Brand_Bot_Announcement__c/Brand_Bot_Announcement__c.object-meta.xml
<CustomObject>
    <label>Brand Bot Announcement</label>
    <nameField>
        <label>Brand Bot Announcement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Bot Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Brand_Bot_Announcement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <description>Text to display to the end-user</description>
    <label>Announcement</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Brand_Bot_Announcement__c/fields/Announcement_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Announcement_End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The LAST day the announcement will display on.</description>
    <label>Announcement End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brand_Bot_Announcement__c/fields/Announcement_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the announcement will begin to display</description>
    <label>Announcement Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Brand_Bot_Announcement__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tommy Hilfiger</fullName>
            </value>
            <value>
                <fullName>Calvin Klein</fullName>
            </value>
            <value>
                <fullName>IZOD</fullName>
            </value>
            <value>
                <fullName>Speedo</fullName>
            </value>
            <value>
                <fullName>Van Heusen</fullName>
            </value>
            <value>
                <fullName>DEFAULT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NF_GetBrandBotAnnouncement.cls
/**
 * Created by samuel on 6/10/21.
 */
public without sharing class NF_GetBrandBotAnnouncement{
    public class Input{
        @InvocableVariable(required = true)
        public String Brand_API_Name;
    }

    public class Output{
        @InvocableVariable(required = false)
        public Boolean announcementFound = false;
        @InvocableVariable(required = false)
        public String announcement;
    }

    @InvocableMethod(label = 'NeuraFlash - Get Brand Announcement')
    public static List<Output> getAnnouncement(List<Input> inputs){
        Input input = inputs[0];
        Output out = new Output();

        Date today = Date.today();

        Brand_Bot_Announcement__c[] botAnnouncementsToDisplay = new List<Brand_Bot_Announcement__c>();

        if (test.isRunningTest()){
            if (input.Brand_API_Name == SYSTEM.LABEL.Speedo)
                today = today.addDays(1);
            else if (input.Brand_API_Name == SYSTEM.LABEL.IZOD)
                today = today.addDays(10);
            Log.push('>>> "TODAY" IS >>> ' + today);
        }
        botAnnouncementsToDisplay = [SELECT Announcement__c
                                     FROM Brand_Bot_Announcement__c
                                     WHERE Announcement_Start_Date__c <= :today AND Announcement_End_Date__c >= :today AND Brand__c = :input.Brand_API_Name
                                     ORDER BY LastModifiedDate DESC
                                     LIMIT 1];

        Log.push('botAnnouncementsToDisplay'+botAnnouncementsToDisplay);

        if (botAnnouncementsToDisplay.size() > 0){
            out.announcementFound = true;
            out.announcement = botAnnouncementsToDisplay[0].Announcement__c;
        }
        Logger.logDebug();
        return new List<Output>{ out };
    }

}