unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Live Chat Transcript</description>
    <inlineHelpText>Live Chat Transcript</inlineHelpText>
    <label>Live Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Einstein Bot Chat Session</relationshipLabel>
    <relationshipName>Einstein_Bot_Chat_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_BotSessionPopulateFieldsHelper.cls
public class NF_BotSessionPopulateFieldsHelper {
    public static void handleAfterInsert(Map<id,ebotdata__Bot_Session__c> botSessions){
        try {
            Set<Id> liveChatTranscriptIds = new Set<Id>();
            Map<Id, LiveChatTranscript> transcripts = new Map<Id, LiveChatTranscript>();
            
            List<ebotdata__Bot_Session__c> sessionList = [SELECT Id, Brand__c,ebotdata__Live_Chat_Transcript__c
                                                          FROM ebotdata__Bot_Session__c
                                                          WHERE Id IN :botSessions.keySet()];
            
            //First, get all the transcript IDs we need from the sessions
            List<ebotdata__Bot_Session__c> sessionsToUpdate = new List<ebotdata__Bot_Session__c>();
            //for (Id sessionId : botSessions.keySet()) {
            for(ebotdata__Bot_Session__c session : sessionList){
                //ebotdata__Bot_Session__c session = botSessions.get(sessionId);
                Log.push('>>NF_BotSessionPopulateFields.updateFields: session=' + session);
                liveChatTranscriptIds.add(session.ebotdata__Live_Chat_Transcript__c);
            }
            //Get all the transcripts
            transcripts = new Map<Id, LiveChatTranscript>([SELECT Id, ChatKey, Brand__c
                                                           FROM LiveChatTranscript
                                                           WHERE Id IN :liveChatTranscriptIds]);
            Log.push('>>NF_BotSessionPopulateFields.updateFields: transcripts=' + transcripts);
            
            //Go through the sessions again, and update with the corresponding transcript fields
            //for (Id sessionId : botSessions.keySet()) {
            //    ebotdata__Bot_Session__c session = botSessions.get(sessionId);
            for(ebotdata__Bot_Session__c session : sessionList){
                Log.push('>>NF_BotSessionPopulateFields.updateFields: session=' + session);
                if (session.ebotdata__Live_Chat_Transcript__c != null) {
                    LiveChatTranscript transcript = transcripts.get(session.ebotdata__Live_Chat_Transcript__c);
                    Log.push('>>NF_BotSessionPopulateFields.updateFields: retrieved transcript=' + session);
                    
                    if (session != null && transcript != null && String.isNotEmpty(transcript.Brand__c)) {
                        Log.push('>>NF_BotSessionPopulateFields.updateFields: updating Brand__c');
                        session.Brand__c = transcript.Brand__c;
                    }
                    sessionsToUpdate.add(session);
                }
            }
            
            Log.push('>>NF_BotSessionPopulateFields.updateFields: sessionsToUpdate=' + sessionsToUpdate);
            
            if (sessionsToUpdate.size() > 0) {
                
                update sessionsToUpdate;
            }
            Logger.logDebug();
        }
        catch(Exception e){
            Logger.logException(e);
        }
    }
}