unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Agent_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Agent_Session_Id__c</fullName>
    <description>Live Agent Session Id</description>
    <inlineHelpText>Live Agent Session Id</inlineHelpText>
    <label>Live Agent Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/ebotdata__Live_Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>ebotdata__Live_Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Live Chat Transcript</description>
    <inlineHelpText>Live Chat Transcript</inlineHelpText>
    <label>Live Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Einstein Bot Chat Session</relationshipLabel>
    <relationshipName>Einstein_Bot_Chat_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LiveChatTranscript/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_BotSessionPopulateFieldsTest.cls
/**
 * Created by apoorvrajput on 10/23/20.
 */

@IsTest
private class NF_BotSessionPopulateFieldsTest {
    @IsTest
    static void testBehavior() {
        Test.startTest();
        String chatKey = NF_UtilTest.createLiveChatTranscript('Calvin Klein');
		NF_BotSessionPopulateFieldsTest nf = new NF_BotSessionPopulateFieldsTest();
        List<LiveChatTranscript> listTranscripts = new List<LiveChatTranscript>();

        try {
            listTranscripts = [SELECT Id, URL__c, Brand__c
            FROM LiveChatTranscript
            WHERE ChatKey = :chatKey];
        }
        catch(Exception e){
            System.debug('Exception encountered: ' + e);
        }

        LiveChatTranscript transcript = listTranscripts.size() > 0 ? listTranscripts[0] : null;

        ebotdata__Bot_Session__c session = new ebotdata__Bot_Session__c();
        session.ebotdata__Live_Agent_Session_Id__c = chatKey;
        session.ebotdata__Live_Chat_Transcript__c = transcript.Id;
        insert session;


        ebotdata__Bot_Session__c sessionNew = NF_Util.getBotSession(chatKey);
        Test.stopTest();
        System.assertEquals(transcript.Brand__c,sessionNew.Brand__c);
    }
    
    @isTest
    static void instantiateClass(){
        NF_BotSessionPopulateFields bspf = new NF_BotSessionPopulateFields();
    }
        
}