unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Visitor_Feedback_Intent__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Feedback_Intent__c</fullName>
    <label>Visitor Feedback Intent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Visitor_Feedback_Result__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Feedback_Result__c</fullName>
    <label>Visitor Feedback Result</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_UpdateSessionFollowup.cls
public with sharing class NF_UpdateSessionFollowup {
    public class Input{
        @InvocableVariable(required=true)
        public String chatKey;

        @InvocableVariable(required=true)
        public String isPositiveFeedback;
    }

    @InvocableMethod(label='Neuraflash - Update Bot Session After Followup')
    public static void updateSession(List<Input> input){
        String chatKey = input[0].chatKey;
        Boolean isPositiveFeedback = Boolean.valueOf(input[0].isPositiveFeedback);

        try {
            String lbi = NF_Util.getLastBusinessIntent(chatKey);

            ebotdata__Bot_Session__c session = NF_Util.getBotSession(chatKey);
            session.Visitor_Feedback_Intent__c = lbi;
            session.Visitor_Feedback_Result__c = (isPositiveFeedback) ? SYSTEM.LABEL.Yes : SYSTEM.LABEL.No;

            update session;
        }catch(Exception e){
            Logger.logException(e);
        }
    }
}