unpackaged/main/default/objects/ebotdata__Bot_Session__c/ebotdata__Bot_Session__c.object-meta.xml
<CustomObject>
    <description>The Bot Session object that captures info about the session between Bot and end-user</description>
    <label>Bot Session</label>
    <nameField>
        <displayFormat>BOS-{00000}</displayFormat>
        <label>Bot Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ebotdata__Bot_Session__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NF_UpdateSessionTest.cls
/**
 * Created by apoorvrajput on 10/10/20.
 */

@IsTest
private class NF_UpdateSessionTest {
    @IsTest
    static void test1UpdateSession() {
        Test.startTest();
        List<NF_UpdateSession.Input> inputs = new List<NF_UpdateSession.Input>();
        NF_UpdateSession.Input input = new NF_UpdateSession.Input();

        input.chatKey = NF_UtilTest.createLiveChatTranscript();
        input.brandName = 'Calvin Klein';
        inputs.add(input);
        NF_Util.insertSession(input.chatKey,'','Calvin Klein');
        NF_Util.associateCaseWithSession(input.chatKey,'');
        NF_UpdateSession.updateSession(inputs);
        ebotdata__Bot_Session__c session = NF_Util.getBotSession(input.chatKey);
        Test.stopTest();
        System.assertEquals(session.Brand__c,'Calvin Klein');
    }
}