unpackaged/main/default/objects/Brand_Details_Mapping__mdt/Brand_Details_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Brand Details Mapping</label>
    <pluralLabel>Brand Details Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Brand_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Number__c</fullName>
    <label>Brand Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Email_template_donot_share_Sell__c.field-meta.xml
<CustomField>
    <fullName>Email_template_donot_share_Sell__c</fullName>
    <label>Email template donot share/Sell</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Brand_Details_Mapping__mdt/fields/Ordwide_Email__c.field-meta.xml
<CustomField>
    <fullName>Ordwide_Email__c</fullName>
    <label>Ordwide Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/R2RChangeRequestSendEmail.cls
public class R2RChangeRequestSendEmail{
    
    @InvocableMethod(label='R2RChangeRequest' description='Trigger to old email')
    public static void mailChangeRequest(List<flowInputs> flowInputsList) {    
        system.debug('flowInputsList='+flowInputsList);
        
        Map<String,String> mapOfBrands = new Map<String,String>();
		Schema.DescribeFieldResult fieldResult = Case.Brand__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			mapOfBrands.put(pickListVal.getValue(),pickListVal.getLabel());
		}     
		
        Map<String,Brand_Details_Mapping__mdt> mapOfBrandMappings = new Map<String,Brand_Details_Mapping__mdt>();
        
        List<Brand_Details_Mapping__mdt> listOfBrandMappings = [Select Id,Brand_Number__c,Brand_Name__c,Email_Template__c,Email_template_donot_share_Sell__c,Ordwide_Email__c from Brand_Details_Mapping__mdt];
        for(Brand_Details_Mapping__mdt eachMdt : listOfBrandMappings){
            mapOfBrandMappings.put(eachMdt.Brand_Number__c, eachMdt);
            
        }
        
        
        List<Messaging.SingleEmailMessage> lsem = new List<Messaging.SingleEmailMessage>();
        List<OrgwideEmailAddress> owdList = [Select Id,displayName from OrgwideEmailAddress where 
                                             displayName = :mapOfBrandMappings.get(flowInputsList[0].brandName).Ordwide_Email__c];

        system.debug('mapOfBrands'+mapOfBrands);
        OrgwideEmailAddress owdToAssign = owdList[0];
        system.debug('flowInputsList[0].brandName'+flowInputsList[0].brandName);
        List<EmailTemplate> templates; 
        if(flowInputsList[0].subType == 'Do Not Sell/Share'){
            templates = [SELECT Id,Name FROM EmailTemplate 
                                         WHERE Name = :mapOfBrandMappings.get(flowInputsList[0].brandName).Email_template_donot_share_Sell__c];
           
            system.debug('templates***'+templates);
        }else{
           templates = [SELECT Id,Name FROM EmailTemplate 
                                         WHERE Name = :mapOfBrandMappings.get(flowInputsList[0].brandName).Email_Template__c];
            system.debug('templates***'+templates);
        }
        
        Messaging.SingleEmailMessage sem = new Messaging.SingleEmailMessage();   
        sem.setTemplateId(templates[0].Id);
        sem.setSaveAsActivity(true);
        sem.setTargetObjectId(flowInputsList[0].contactId);
        sem.setWhatId(flowInputsList[0].caseId);
        sem.setUseSignature(false);
        sem.setTreatTargetObjectAsRecipient(true);
        sem.setOrgWideEmailAddressId(owdToAssign.Id);
        lsem.add(sem);
        Messaging.sendEmail(lsem);
    }
    public class flowInputs{
        @InvocableVariable
        public String emailAddress;
        @InvocableVariable
        public String caseId;
        @InvocableVariable
        public String contactId;
        @InvocableVariable
        public String brandName;
        @InvocableVariable
        public String subType;
    }
}