unpackaged/main/default/objects/BatchProcess__c/BatchProcess__c.object-meta.xml
<CustomObject>
    <label>BatchProcess</label>
    <nameField>
        <displayFormat>BP-{000000000}</displayFormat>
        <label>BatchProcess Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchProcess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BatchProcess__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>Input File Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/BatchProcess__c/fields/OutputFileName__c.field-meta.xml
<CustomField>
    <fullName>OutputFileName__c</fullName>
    <label>OutputFileName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Brand_Id__c.field-meta.xml
<CustomField>
    <fullName>Brand_Id__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand_Id</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/EmailOptInStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailOptInStatus__c</fullName>
    <label>Email Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/LoyaltyFlag__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LoyaltyFlag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/WelcomeSource__c.field-meta.xml
<CustomField>
    <fullName>WelcomeSource__c</fullName>
    <label>Latest Welcome Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>1-Overlay</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>2-Footer</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3-My Account</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4-Guest Checkout</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>CK CA Guest checkout</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6-RAF</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>CK Project Blue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

unpackaged/main/default/objects/ContactStaging2__c/ContactStaging2__c.object-meta.xml
<CustomObject>
    <label>Contact Staging 2</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Contact Staging 2 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Staging 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ContactStaging2__c/fields/HomeStore__c.field-meta.xml
<CustomField>
    <fullName>HomeStore__c</fullName>
    <label>HomeStore</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/Seuqence__c.field-meta.xml
<CustomField>
    <fullName>Seuqence__c</fullName>
    <label>Seuqence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/SMSOptinStatus__c.field-meta.xml
<CustomField>
    <fullName>SMSOptinStatus__c</fullName>
    <label>SMS Opt-in</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ContactStaging2__c/fields/StoreOfCapture__c.field-meta.xml
<CustomField>
    <fullName>StoreOfCapture__c</fullName>
    <label>Store Of Capture</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Brand_Id.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner&#39;s</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactUpdationProcess1Test.cls
@isTest(isParallel=false)
public class ContactUpdationProcess1Test {
    @TestSetup
    static void makeData(){
        Account acc = new Account(Name=System.Label.PlaceHolderAccountName);
        String recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();
        insert acc;
        List<Contact> conList = new List<Contact>();
        for(Integer i=1;i<=5;i++){
            Contact con = new Contact();
            con.RecordTypeId = recordTypeId;
            con.Source_System__c = 'eComm';
            con.AccountId = acc.Id;
            con.Brand_Id__c = '2';
            con.FirstName = 'cfname';
            con.LastName = 'clname';
            con.MailingStreet = 'c mailing scteet';
            con.MailingCity = 'ccity';
            con.MailingState = 'cstate';
            con.MailingPostalCode = 'c1234';
            con.MailingCountry = 'ccity';
            con.Email = 'testemail@nomail.com'+i;
            con.Phone = '5555555555';
            con.HomePhone = '0987654321';
            con.MobilePhone = '7777777775';
            con.Birthdate = Date.newInstance(1990, 12, 30);       
            con.HomeStore__c = 'cLoc';
            con.LoyaltyFlag__c = false;
            con.EmailOptInStatus__c = 'N'; //false;
            con.SMSOptinStatus__c = 'N'; //false;
            con.WelcomeSource__c = '01';
            con.StoreOfCapture__c = 'cLoc';
            conList.add(con);
        }
        insert conList;
        Set<String> emailIds = new Set<String>();
        integer J = 1;
        List<ContactStaging2__c> cs2List = new  List<ContactStaging2__c>();
        for(contact con: conList){
            ContactStaging2__c objContStg =new ContactStaging2__c();
            objContStg.Email__c = con.Email;
            objContStg.FileName__c = 'file' + j;
            objContStg.Seuqence__c = String.valueOf(j);
            j = j+1;
            cs2List.add(objContStg);
        }
        
        insert cs2List;
        List<BatchProcess__c> bpList = new List<BatchProcess__c>();
        for(ContactStaging2__c cs2: cs2List){
            BatchProcess__c bp = new BatchProcess__c();
            bp.FileName__c = cs2.FileName__c;
            //bp.OutputFileName__c = cs2.FileName__c;
            bp.IsProcessed__c = false;
            bpList.add(bp);
        }
        insert bpList;
    }
@isTest static void testdoSignup(){
        Test.startTest();
        ContactUpdationProcess1 c = new ContactUpdationProcess1();
        Database.executeBatch(c);
        Test.stopTest();
    }
}