unpackaged/main/default/objects/LoyaltySettings__mdt/LoyaltySettings__mdt.object-meta.xml
<CustomObject>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <label>BrandId</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/LoyaltySettings__mdt/fields/LogSignupActivity__c.field-meta.xml
<CustomField>
    <fullName>LogSignupActivity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Signup Activity</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/TrackerEvents__c.object-meta.xml
<CustomObject>
    <label>Tracker Events</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TrackerEvents__c/fields/BrandId__c.field-meta.xml
<CustomField>
    <fullName>BrandId__c</fullName>
    <description>BrandId</description>
    <label>BrandId</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <description>CustomerId</description>
    <label>CustomerId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/fields/DataSource__c.field-meta.xml
<CustomField>
    <fullName>DataSource__c</fullName>
    <label>DataSource</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/fields/LoyaltyId__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyId__c</fullName>
    <description>LoyaltyId</description>
    <label>LoyaltyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/fields/StoreCode__c.field-meta.xml
<CustomField>
    <fullName>StoreCode__c</fullName>
    <label>StoreCode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TrackerEvents__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SignUp,</fullName>
            </value>
            <value>
                <fullName>Unsubscribe,</fullName>
            </value>
            <value>
                <fullName>News-letter SignUp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LogSignupActivities.cls
/******************************************************************************
* @Description: insert record into TrackerEvents__c for SignUps
* @Date		  : April 13, 2020
* @JIRA		  : NASSC-1665
*
******************************************************************************/
public class LogSignupActivities{

    @InvocableMethod(label='invocable LogSignUpActivity' description='pass thru method to call LogSignupActivities')
    public static void LogSignUpActivity(List<SignUpActivityData> contactSignUpData) {

        String jsonString = json.serialize(contactSignUpData);
       	createSignUpActivity(jsonString);
    }
    
    @future
    public static void createSignUpActivity(String contactDataAsString){
        System.debug('***inside createSignUpActivity');
        List<TrackerEvents__c> eventList = new List<TrackerEvents__c>();
        List<SignUpActivityData> conList = (List<SignUpActivityData>)Json.deserialize(contactDataAsString,List<SignUpActivityData>.class);
        Map<String,Boolean> mapBrandLogSignUp = new Map<String,Boolean>();
        List<LoyaltySettings__mdt> listLoyalty = [Select Id, BrandId__c, LogSignupActivity__c from LoyaltySettings__mdt];
        for(LoyaltySettings__mdt loyalRecord : listLoyalty){
            mapBrandLogSignUp.put(loyalRecord.BrandId__c,loyalRecord.LogSignupActivity__c);
        }
        System.debug('^^^mapBrandLogSignUp = '+mapBrandLogSignUp);
        for(SignUpActivityData signUpData : conList){
            //check if LogSignupActivity__c is CHECKED for brand
            System.debug('^^^Status of Log = '+mapBrandLogSignUp.get(signUpData.BrandId));
            if(mapBrandLogSignUp.get(signUpData.BrandId)){
                TrackerEvents__c eventRecord = new TrackerEvents__c();
                eventRecord.Type__c = 'SignUp';
                eventRecord.DataSource__c = signUpData.dataSource;
                eventRecord.CustomerId__c = signUpData.ContactId;
                eventRecord.BrandId__c 	  = signUpData.BrandId;
                eventRecord.EventDate__c  = signUpData.eventDate;
                eventRecord.LoyaltyId__c  = signUpData.loyaltyId;
                eventRecord.StoreCode__c  = signUpData.StoreCode;
                eventList.add(eventRecord);
            }
            else{
                System.debug('^^^LogSignupActivity__c is DISABLED for this Brand');
            }
        }
        
        try {
            if(eventList.size() > 0){
                insert eventList;
                System.debug('***Records Inserted: TrackerEvents__c'); 
            }            
        }
        catch (Exception e) {
            System.debug('An exception occurred while inserting records in : TrackerEvents__c' + e.getMessage());
        }
       
    }
  
    public class SignUpActivityData {
       	@InvocableVariable
        public Id ContactId;
        @InvocableVariable
        public DateTime eventDate;
        @InvocableVariable
        public String dataSource;
        @InvocableVariable
        public String BrandId;
        @InvocableVariable
        public String loyaltyId;
        @InvocableVariable
        public String StoreCode;
       
    }
}